// apps/web/src/ui/team/AchievementRanking.svelte
<script lang="ts">
  // T-11-028 업적 랭킹 — 기록실 탭. 구단주의 시즌 업적 점수 순(같은 점수면 먼저 닿은 구단주가 앞선다). 구단주는 공개
  // 닉네임과 그 시즌 팀 이름으로만 보이고, 팀이 있으면 줄을 눌러 팀 프로필을 연다. 서버가 5분마다 새로 센다.
  import { ACH_GRADES, ACH_RANK_PER_PAGE, achGradeOf } from '@offside/contracts/owner-team';
  import { fetchAchRanking, type AchRankResponse } from '@offside/app-core/api/team';
  import { hofStart } from '@offside/app-core/state';
  import { num as n } from '@offside/app-core/teamText';
  import Laurel from '../Laurel.svelte';
  import { appState } from '../state.svelte.js';
  import AchGradeBadge from './AchGradeBadge.svelte';
  import GradeEmblem from './GradeEmblem.svelte';

  const MEDAL = ['gold', 'silver', 'bronze'];
  /** undefined = 지금 시즌(서버가 정한다). */
  let season = $state<number | undefined>(undefined);
  let page = $state(1);
  let data = $state<AchRankResponse | null>(null);
  let failed = $state(false);

  $effect(() => {
    const [se, p] = [season, page];
    failed = false;
    void fetchAchRanking(se, p).then((r) => {
      if (se !== season || p !== page) return; // 더 늦게 고른 조건의 응답만 쓴다.
      if (r.ok) data = r.data;
      else failed = true;
    });
  });

  const pages = $derived(data ? Math.max(1, Math.ceil(data.total / ACH_RANK_PER_PAGE)) : 1);
  function goPage(p: number) {
    page = p;
    window.scrollTo(0, 0);
  }
  function openTeam(id: string) {
    appState.hof = { ...hofStart(), tab: 'teams', team: id };
    window.scrollTo(0, 0);
  }
</script>

<section class="card" data-ach-ranking>
  <div class="eyebrow">Achievement ranking</div>
  <h1 style="margin-bottom:8px">업적 랭킹</h1>
  {#if data && data.seasons.length > 1}
    <div class="seg board-tabs hof-seasons" role="group" aria-label="시즌">
      {#each data.seasons as s (s.id)}
        <button class="opt" aria-pressed={data.season === s.id} data-ach-season={s.id} onclick={() => ((season = s.id), (page = 1))}>{s.name}</button>
      {/each}
    </div>
  {/if}
  {#if failed}
    <p class="empty">랭킹을 불러오지 못했습니다. 잠시 후 다시 시도해 주세요.</p>
  {:else if !data}
    <p class="empty">불러오는 중…</p>
  {:else if data.items.length}
    <p class="muted hof-source">{data.seasons.find((s) => s.id === data?.season)?.name} · 구단주 {n(data.total)}명 · 업적 점수 순</p>
    {#each data.items as r (r.rank)}
      {@const grade = achGradeOf(r.score).grade}
      {#snippet row()}
        {#if r.rank <= MEDAL.length}
          <div class="hof-rank medal {MEDAL[r.rank - 1]}"><Laurel /><span>{r.rank}</span></div>
        {:else}
          <div class="hof-rank">{r.rank}</div>
        {/if}
        <div>
          <b>{r.nickname ?? '익명 구단주'}</b>
          <div class="muted fs-xs">{r.team ? `${r.team.name} · ` : ''}업적 {n(r.done)}개 · 선수 {n(r.players)}명</div>
        </div>
        <div class="ach-rank-value">
          <GradeEmblem id={grade.id} size={34} />
          <div>
            <AchGradeBadge {grade} emblem={false} />
            <span class="num hof-value">{n(r.score)}</span>
          </div>
        </div>
      {/snippet}
      {#if r.team}
        <button class="hof-row" data-ach-rank={r.rank} onclick={() => r.team && openTeam(r.team.id)}>{@render row()}</button>
      {:else}
        <div class="hof-row" data-ach-rank={r.rank}>{@render row()}</div>
      {/if}
    {/each}
    {#if pages > 1}
      <nav class="hof-pager" aria-label="랭킹 페이지">
        <button class="icon-btn" data-ach-page="prev" disabled={page <= 1} onclick={() => goPage(page - 1)}>← 이전</button>
        <span class="num" aria-live="polite">{page} / {pages}</span>
        <button class="icon-btn" data-ach-page="next" disabled={page >= pages} onclick={() => goPage(page + 1)}>다음 →</button>
      </nav>
    {/if}
  {:else}
    <p class="empty">아직 랭킹에 오른 구단주가 없어요. 은퇴한 선수로 시즌 업적을 달성하면 여기에 올라요.</p>
  {/if}
  <details class="ach-grades">
    <summary class="muted fs-sm">등급 기준</summary>
    <ul>
      {#each ACH_GRADES as g (g.id)}
        <li><AchGradeBadge grade={g} /><span class="num muted">{n(g.min)}점부터</span></li>
      {/each}
    </ul>
  </details>
  <p class="muted fs-xs" style="margin-top:10px">시즌마다 처음부터 다시 쌓아요. 선수·팀·구단주 업적 점수의 합이고, 랭킹은 5분마다 새로 세요.</p>
</section>

// apps/mobile/src/screens/hof/team/AchievementRanking.tsx
// T-11-028 구단주 랭킹(웹 team/AchievementRanking.svelte) — 기록실 탭. 구단주의 시즌 업적 점수 순(같은 점수면 먼저 닿은 구단주가
// 앞선다). 구단주는 공개 닉네임과 그 시즌 팀 이름으로만 보이고, 팀이 있으면 줄을 눌러 팀 프로필(appState.hof.team)을 연다.
// 서버가 5분마다 새로 센다.
import { useEffect, useState } from 'react';
import { View } from 'react-native';
import { ACH_GRADES, ACH_RANK_PER_PAGE, achGradeOf } from '@offside/contracts/owner-team';
import { fetchAchRanking, type AchRankResponse } from '@offside/app-core/api/team';
import { hofStart } from '@offside/app-core/state';
import { num as n } from '@offside/app-core/teamText';
import { RowFrame } from '../../../components/HofRow';
import { appState } from '../../../store';
import { rem } from '../../../theme/type';
import { useColors } from '../../../theme/useColors';
import { Btn } from '../../../ui/Btn';
import { Card } from '../../../ui/Card';
import { Press } from '../../../ui/Press';
import { scrollTo } from '../../../ui/scroll';
import { Txt } from '../../../ui/Txt';
import { Seg, TabOpt } from '../../board/parts';
import { AchGradeBadge } from '../../owner/TeamParts';
import { GradeEmblem } from '../../../ui/GradeEmblem';

export default function AchievementRanking() {
  const c = useColors();
  /** undefined = 지금 시즌(서버가 정한다). */
  const [season, setSeason] = useState<number | undefined>(undefined);
  const [page, setPage] = useState(1);
  const [data, setData] = useState<AchRankResponse | null>(null);
  const [failed, setFailed] = useState(false);
  const [gradesOpen, setGradesOpen] = useState(false);

  useEffect(() => {
    setFailed(false);
    let live = true; // 더 늦게 고른 조건의 응답만 쓴다.
    void fetchAchRanking(season, page).then((r) => {
      if (!live) return;
      if (r.ok) setData(r.data);
      else setFailed(true);
    });
    return () => {
      live = false;
    };
  }, [season, page]);

  const pages = data ? Math.max(1, Math.ceil(data.total / ACH_RANK_PER_PAGE)) : 1;
  function goPage(p: number) {
    setPage(p);
    scrollTo(0);
  }
  function openTeam(id: string) {
    appState.hof = { ...hofStart(), tab: 'teams', team: id };
    scrollTo(0);
  }

  const empty = (text: string) => (
    <Txt tone="muted" style={{ fontSize: rem(0.875), paddingVertical: 8 }}>
      {text}
    </Txt>
  );
  return (
    <Card gap={0}>
      <View testID="ach-ranking-screen">
        <Txt v="eyebrow">Owner ranking</Txt>
        <Txt v="h1" accessibilityRole="header" style={{ marginBottom: 8 }}>
          구단주 랭킹
        </Txt>
      </View>
      {data && data.seasons.length > 1 ? (
        <Seg cols={2} label="시즌" style={{ marginTop: 4, marginBottom: 6 }}>
          {data.seasons.map((s) => (
            <TabOpt
              key={s.id}
              title={s.name}
              selected={data.season === s.id}
              testID={`ach-rank-season-${s.id}`}
              onPress={() => {
                setSeason(s.id);
                setPage(1);
              }}
            />
          ))}
        </Seg>
      ) : null}
      {failed ? (
        empty('랭킹을 불러오지 못했어요. 잠시 후 다시 시도해 주세요.')
      ) : !data ? (
        <Txt
          tone="muted"
          accessibilityLiveRegion="polite"
          style={{ fontSize: rem(0.875), paddingVertical: 8 }}
        >
          불러오는 중…
        </Txt>
      ) : data.items.length ? (
        <>
          <Txt tone="muted" style={{ fontSize: rem(0.75), marginBottom: 6 }}>
            {`${data.seasons.find((s) => s.id === data.season)?.name} · 구단주 ${n(data.total)}명 · 업적 점수 순`}
          </Txt>
          {data.items.map((r, i) => {
            const team = r.team;
            const row = (
              <RowFrame rank={r.rank - 1} first={i === 0}>
                <View style={{ flexDirection: 'row', alignItems: 'center', gap: 10 }}>
                  <View style={{ flex: 1, minWidth: 0 }}>
                    <Txt bold numberOfLines={1}>
                      {r.nickname ?? '익명 구단주'}
                    </Txt>
                    <Txt tone="muted" style={{ fontSize: rem(0.75) }}>
                      {`${team ? `${team.name} · ` : ''}업적 ${n(r.done)}개 · 선수 ${n(r.players)}명`}
                    </Txt>
                  </View>
                  <GradeEmblem id={achGradeOf(r.score).grade.id} size={34} />
                  <View style={{ alignItems: 'flex-end', gap: 2 }}>
                    <AchGradeBadge grade={achGradeOf(r.score).grade} emblem={false} />
                    <Txt
                      num
                      numberOfLines={1}
                      style={{ fontSize: rem(1.375), lineHeight: rem(1.375) * 1.2 }}
                    >
                      {n(r.score)}
                    </Txt>
                  </View>
                </View>
              </RowFrame>
            );
            return team ? (
              <Press
                key={r.rank}
                scale={0.985}
                testID={`ach-rank-${r.rank}`}
                onPress={() => openTeam(team.id)}
              >
                {row}
              </Press>
            ) : (
              <View key={r.rank} testID={`ach-rank-${r.rank}`}>
                {row}
              </View>
            );
          })}
          {pages > 1 ? (
            <View
              accessibilityLabel="랭킹 페이지"
              style={{
                flexDirection: 'row',
                alignItems: 'center',
                justifyContent: 'space-between',
                gap: 8,
                paddingTop: 12,
                borderTopWidth: 1,
                borderTopColor: c.line,
              }}
            >
              <Btn
                sm
                testID="ach-rank-page-prev"
                disabled={page <= 1}
                onPress={() => goPage(page - 1)}
              >
                ← 이전
              </Btn>
              <Txt num accessibilityLiveRegion="polite" style={{ fontWeight: '700' }}>
                {`${page} / ${pages}`}
              </Txt>
              <Btn
                sm
                testID="ach-rank-page-next"
                disabled={page >= pages}
                onPress={() => goPage(page + 1)}
              >
                다음 →
              </Btn>
            </View>
          ) : null}
        </>
      ) : (
        empty('아직 랭킹에 오른 구단주가 없어요. 은퇴한 선수로 시즌 업적을 달성하면 여기에 올라요.')
      )}
      <View testID="ach-grades" style={{ marginTop: 12 }}>
        <Press
          scale={0.99}
          onPress={() => setGradesOpen(!gradesOpen)}
          accessibilityLabel="등급 기준"
          accessibilityState={{ expanded: gradesOpen }}
          style={{ minHeight: 32, justifyContent: 'center' }}
        >
          <Txt tone="muted" v="sm">
            {`${gradesOpen ? '▾' : '▸'} 등급 기준`}
          </Txt>
        </Press>
        {gradesOpen ? (
          <View style={{ flexDirection: 'row', flexWrap: 'wrap', gap: 6, marginTop: 6 }}>
            {ACH_GRADES.map((g) => (
              <View
                key={g.id}
                style={{
                  width: '48.5%',
                  flexDirection: 'row',
                  alignItems: 'center',
                  justifyContent: 'space-between',
                  gap: 8,
                  paddingVertical: 6,
                  paddingHorizontal: 10,
                  borderRadius: 10,
                  backgroundColor: c.surface2,
                }}
              >
                <AchGradeBadge grade={g} />
                <Txt num={400} tone="muted" style={{ fontSize: rem(0.8125) }}>
                  {`${n(g.min)}점부터`}
                </Txt>
              </View>
            ))}
          </View>
        ) : null}
      </View>
      <Txt tone="muted" style={{ fontSize: rem(0.75), marginTop: 10 }}>
        시즌마다 처음부터 다시 쌓아요. 선수·팀·구단주 업적 점수의 합이고, 랭킹은 5분마다 새로 세요.
      </Txt>
    </Card>
  );
}
