// apps/mobile/src/screens/home/HomeFirsts.tsx
// 홈 타일의 서버 최초 기록 진입점(웹 firsts/HomeFirsts.svelte). 가장 최근에 세워진 기록 한 줄을 보여 주고, 누르면 전체 화면으로 간다.
import { useEffect, useState } from 'react';
import type { ServerFirst } from '@offside/contracts';
import { getFirsts } from '@offside/app-core/api/client';
import { achievedList } from '@offside/app-core/firsts';
import { go } from '../../game/nav';
import { homeText as L } from '@offside/app-core/i18n/ko/home';
import { Tile } from './Tile';

export function HomeFirsts() {
  const [latest, setLatest] = useState<ServerFirst | null>(null);
  const [count, setCount] = useState<{ done: number; total: number } | null>(null);
  useEffect(() => {
    let alive = true;
    void getFirsts().then((r) => {
      if (!alive || !r.ok) return;
      const done = achievedList(r.data.items);
      setLatest(done[0] ?? null);
      setCount({ done: done.length, total: r.data.items.length });
    });
    return () => {
      alive = false;
    };
  }, []);

  return (
    <Tile
      testID="firsts"
      eyebrow="Server firsts"
      title={latest ? latest.label : L.firstsTitle}
      sub={`${count ? L.firstsCount(count) : L.firstsEmpty} →`}
      subNum
      onPress={() => go('firsts')}
    />
  );
}

// apps/web/src/ui/firsts/HomeFirsts.svelte
<script lang="ts">
  // T-10-027 홈 타일의 서버 최초 기록 진입점. 가장 최근에 세워진 기록 한 줄을 보여 주고, 누르면 전체 화면으로 간다.
  import type { ServerFirst } from '@offside/contracts';
  import { getFirsts } from '@offside/app-core/api/client';
  import { go } from '../nav.js';
  import { achievedList } from '@offside/app-core/firsts';
  import { homeText as L } from '@offside/app-core/i18n/ko/home';

  let latest = $state<ServerFirst | null>(null);
  let count = $state<{ done: number; total: number } | null>(null);
  $effect(() => {
    void getFirsts().then((r) => {
      if (!r.ok) return;
      const done = achievedList(r.data.items);
      latest = done[0] ?? null;
      count = { done: done.length, total: r.data.items.length };
    });
  });
</script>

<button class="tile tile-link" data-act="firsts" onclick={() => go('firsts')}>
  <span class="eyebrow">Server firsts</span><b>{latest ? latest.label : L.firstsTitle}</b><span class="muted num fs-sm"
    >{count ? L.firstsCount(count) : L.firstsEmpty} →</span
  >
</button>
