// apps/mobile/src/screens/owner/TeamFriends.tsx
// T-11-098 친구 · 친선전(웹 team/TeamFriends.svelte) — 내 팀 '경기' 탭의 '친구' 칸. 친구 코드 · 받은/보낸 신청 · 친구 ·
// 최근 친선전. 친선전은 랭크와 따로 센다(레이팅·전적·업적에 들어가지 않고, 하루 한도와 친구별 상대 전적이 따로 있다).
// 친구 데이터는 이 칸을 처음 열 때만 불러온다(useFriends). 문구는 웹과 같이 고친다.
import { useRef, useState, type ReactNode } from 'react';
import { Alert, Share, View } from 'react-native';
import * as Clipboard from 'expo-clipboard';
import { normalizeFriendCode } from '@offside/contracts/owner-team';
import {
  acceptFriend,
  fetchFriends,
  playFriendly,
  removeFriend,
  requestFriend,
  type FriendPerson,
  type FriendsResponse,
} from '@offside/app-core/api/friends';
import type { TeamMatch } from '@offside/app-core/api/team';
import {
  FOUNDER_LABEL,
  PRESEASON_FRIENDLY_HINT,
  canFriendly,
  canPreseasonFriendly,
  friendCodeLabel,
  friendInviteText,
  friendRequestText,
  h2hText,
  preseasonTeamLine,
} from '@offside/app-core/friendText';
import { LoadState, type LoadStatus } from '../../components/LoadState';
import { TeamLogo } from '../../components/TeamLogo';
import { toast } from '../../game/host';
import { useColors } from '../../theme/useColors';
import { DISPLAY, rem } from '../../theme/type';
import { Btn, Card, Pill, Txt } from '../../ui';
import { TextField } from '../settings/parts';
import { MatchRow } from './TeamHistory';
import { Seg, SegBtn } from './TeamParts';

export type OppTab = 'ranked' | 'friends';

/** '경기' 탭 맨 위 두 칸 고르기. */
export function OppSwitch({ value, onPick }: { value: OppTab; onPick: (v: OppTab) => void }) {
  return (
    <Seg label="경기 종류">
      <SegBtn
        center
        selected={value === 'ranked'}
        testID="opp-tab-ranked"
        onPress={() => onPick('ranked')}
      >
        <Txt bold>랭크 경기</Txt>
      </SegBtn>
      <SegBtn
        center
        selected={value === 'friends'}
        testID="opp-tab-friends"
        onPress={() => onPick('friends')}
      >
        <Txt bold>친구</Txt>
      </SegBtn>
    </Seg>
  );
}

/** 친구 데이터 · 쓰기. 칸을 처음 열 때(ensure)만 불러오고, 쓰기 뒤에는 조용히 다시 불러온다. */
export function useFriends() {
  const [data, setData] = useState<FriendsResponse | null>(null);
  const [status, setStatus] = useState<LoadStatus>('loading');
  const [busy, setBusy] = useState(false);
  const dataRef = useRef<FriendsResponse | null>(null);
  const sequence = useRef(0);
  const loadingRef = useRef(false);
  const busyRef = useRef(false);

  function put(d: FriendsResponse | null) {
    dataRef.current = d;
    setData(d);
  }
  async function load(silent = false) {
    const seq = ++sequence.current;
    loadingRef.current = true;
    if (!silent) setStatus('loading');
    const r = await fetchFriends();
    if (seq !== sequence.current) return;
    loadingRef.current = false;
    if (!r.ok) {
      if (!silent) setStatus('error');
      return;
    }
    put(r.data);
    setStatus('ready');
  }
  /** 칸을 열 때. 이미 불러온 데이터가 있으면 다시 부르지 않는다. */
  function ensure() {
    if (!dataRef.current && !loadingRef.current) void load();
  }
  /** 쓰기 하나를 한 번에 하나씩. 성공하면 목록을 다시 불러온다. */
  async function write<T>(
    run: () => Promise<{ ok: true; data: T } | { ok: false; error: { message: string } }>,
    done?: (data: T) => void,
  ): Promise<boolean> {
    if (busyRef.current) return false;
    busyRef.current = true;
    setBusy(true);
    const r = await run();
    busyRef.current = false;
    setBusy(false);
    if (!r.ok) {
      toast(r.error.message);
      return false;
    }
    done?.(r.data);
    void load(true);
    return true;
  }
  /** preseason: T-11-113 프리시즌 팀끼리(개막 뒤) 친선전. */
  async function play(f: FriendPerson, preseason = false): Promise<TeamMatch | null> {
    if (busyRef.current) return null;
    busyRef.current = true;
    setBusy(true);
    const r = await playFriendly(f.code, preseason);
    busyRef.current = false;
    setBusy(false);
    if (!r.ok) {
      if (r.error.reason === 'FRIENDLY_DAILY_LIMIT')
        put(dataRef.current && { ...dataRef.current, matchesLeft: 0 });
      else void load(true);
      toast(r.error.message);
      return null;
    }
    const { match, h2h, matchesLeft } = r.data;
    const d = dataRef.current;
    if (d)
      put({
        ...d,
        matchesLeft,
        friends: d.friends.map((x) => (x.code === f.code ? { ...x, h2h } : x)),
        recent: [match, ...d.recent.filter((m) => m.id !== match.id)].slice(0, 10),
      });
    return match;
  }

  return {
    data,
    status,
    busy,
    reload: () => void load(),
    /** T-11-111 당겨서 새로고침 — 이미 불러온 뒤에만, 보이는 목록은 두고 조용히 다시 받는다. */
    refresh: () => (dataRef.current ? load(true) : Promise.resolve()),
    ensure,
    play,
    request: (body: Parameters<typeof requestFriend>[0]) =>
      write(
        () => requestFriend(body),
        (res) => toast(friendRequestText(res)),
      ),
    accept: (f: FriendPerson) =>
      write(
        () => acceptFriend(f.code),
        (res) => toast(friendRequestText(res)),
      ),
    remove: (f: FriendPerson) => write(() => removeFriend(f.code)),
  };
}
export type Friends = ReturnType<typeof useFriends>;

function Row({ children }: { children: ReactNode }) {
  const c = useColors();
  return (
    <View
      style={{
        gap: 8,
        paddingVertical: 10,
        borderTopWidth: 1,
        borderTopColor: c.line,
      }}
    >
      {children}
    </View>
  );
}

function Who({ f, h2h = false }: { f: FriendPerson; h2h?: boolean }) {
  const record = h2h ? h2hText(f.h2h) : null;
  const preseasonLine = h2h ? preseasonTeamLine(f) : null;
  return (
    <View style={{ flexDirection: 'row', alignItems: 'center', gap: 10 }}>
      <TeamLogo logo={f.team?.logo} name={f.team?.name ?? f.name} size={32} decorative />
      <View style={{ flex: 1, minWidth: 0, gap: 2 }}>
        <View style={{ flexDirection: 'row', alignItems: 'center', gap: 6 }}>
          <Txt bold numberOfLines={1} style={{ flexShrink: 1 }}>
            {f.name}
          </Txt>
          {f.founder ? <Pill tone="good">{FOUNDER_LABEL}</Pill> : null}
        </View>
        <Txt tone="muted" v="sm">
          {f.team ? `${f.team.name} · OVR ${f.team.ovr}` : '이번 시즌 팀이 없어요'}
        </Txt>
        {preseasonLine ? (
          <Txt tone="muted" v="sm">
            {preseasonLine}
          </Txt>
        ) : null}
        {record ? <Txt tone="muted" v="sm">{`상대 전적 ${record}`}</Txt> : null}
      </View>
    </View>
  );
}

const buttons = { flexDirection: 'row', justifyContent: 'flex-end', gap: 8 } as const;

export function TeamFriends({
  friends,
  onPlayed,
  onOpen,
  onPreseason,
}: {
  friends: Friends;
  /** 친선전을 치르면(중계 화면으로). */
  onPlayed: (match: TeamMatch) => void;
  /** 최근 친선전을 누르면(결과 화면으로). */
  onOpen: (match: TeamMatch) => void;
  /** T-11-113 '프리시즌 팀 꾸리기' — 프리시즌 팀 편성 화면으로. */
  onPreseason: () => void;
}) {
  const c = useColors();
  const { data, status, busy } = friends;
  const [input, setInput] = useState('');

  async function copyCode(code: string) {
    try {
      await Clipboard.setStringAsync(friendCodeLabel(code));
      toast('코드를 복사했어요');
    } catch {
      toast('코드를 복사하지 못했어요');
    }
  }
  async function shareInvite(code: string) {
    try {
      await Share.share({ message: friendInviteText(code) });
    } catch {
      toast('공유하지 못했어요');
    }
  }
  async function submitCode() {
    const code = normalizeFriendCode(input);
    if (!code) return toast('친구 코드 8자리를 확인해 주세요.');
    if (await friends.request({ code })) setInput('');
  }
  async function challenge(f: FriendPerson, preseason = false) {
    const m = await friends.play(f, preseason);
    if (m) onPlayed(m);
  }
  function askRemove(f: FriendPerson) {
    Alert.alert('친구 끊기', `${f.name} 님과 친구를 끊을까요? 상대 전적도 사라져요.`, [
      { text: '취소', style: 'cancel' },
      { text: '끊기', style: 'destructive', onPress: () => void friends.remove(f) },
    ]);
  }

  return (
    <LoadState status={status} failText="친구를 불러오지 못했어요." retry={friends.reload}>
      {data ? (
        <>
          <Card gap={4}>
            <Txt v="eyebrow">Friends</Txt>
            <Txt v="h1" accessibilityRole="header">
              친구
            </Txt>
            <Txt tone="muted" v="sm" testID="friendly-left">
              {`친선전은 레이팅과 전적에 들어가지 않아요. 오늘 남은 친선전 ${data.matchesLeft}/${data.matchesPerDay}`}
            </Txt>
            {data.canPlay ? null : (
              <Txt tone="muted" v="sm" testID="friendly-cant-play">
                이번 시즌 팀을 만들면 친구와 친선전을 할 수 있어요.
              </Txt>
            )}
            {data.canPlayPreseason === false ? (
              <>
                <Txt tone="muted" v="sm" testID="friendly-preseason-hint">
                  {PRESEASON_FRIENDLY_HINT}
                </Txt>
                <Btn
                  sm
                  testID="friendly-preseason-make"
                  style={{ alignSelf: 'flex-start' }}
                  onPress={onPreseason}
                >
                  프리시즌 팀 꾸리기
                </Btn>
              </>
            ) : null}
          </Card>

          <Card gap={10}>
            <Txt v="h2" accessibilityRole="header">
              내 친구 코드
            </Txt>
            <Txt
              selectable
              testID="friend-code"
              style={{
                fontFamily: DISPLAY[700],
                fontSize: rem(1.75),
                letterSpacing: 2,
                color: c.ink,
              }}
            >
              {friendCodeLabel(data.code)}
            </Txt>
            <View style={{ flexDirection: 'row', gap: 8 }}>
              <Btn
                sm
                kind="primary"
                testID="friend-share"
                onPress={() => void shareInvite(data.code)}
              >
                초대 링크 공유
              </Btn>
              <Btn sm testID="friend-copy" onPress={() => void copyCode(data.code)}>
                코드 복사
              </Btn>
            </View>
          </Card>

          <Card gap={10}>
            <Txt v="h2" accessibilityRole="header">
              친구 코드로 신청
            </Txt>
            <View style={{ flexDirection: 'row', gap: 8, alignItems: 'center' }}>
              <TextField
                style={{ flex: 1 }}
                value={input}
                onChangeText={setInput}
                placeholder="ABCD-EFGH"
                autoCapitalize="characters"
                maxLength={12}
                testID="friend-code-input"
                accessibilityLabel="친구 코드"
                onSubmitEditing={() => void submitCode()}
              />
              <Btn
                kind="primary"
                testID="friend-request"
                disabled={busy}
                onPress={() => void submitCode()}
              >
                신청
              </Btn>
            </View>
          </Card>

          {data.received.length ? (
            <Card gap={0}>
              <Txt v="h2" accessibilityRole="header" style={{ marginBottom: 6 }}>
                {`받은 신청 ${data.received.length}`}
              </Txt>
              {data.received.map((f) => (
                <Row key={f.code}>
                  <View testID={`friend-received-${f.code}`}>
                    <Who f={f} />
                  </View>
                  <View style={buttons}>
                    <Btn
                      sm
                      kind="primary"
                      disabled={busy}
                      testID="friend-accept"
                      accessibilityLabel={`${f.name} 신청 수락`}
                      onPress={() => void friends.accept(f)}
                    >
                      수락
                    </Btn>
                    <Btn
                      sm
                      disabled={busy}
                      testID="friend-decline"
                      accessibilityLabel={`${f.name} 신청 거절`}
                      onPress={() => void friends.remove(f)}
                    >
                      거절
                    </Btn>
                  </View>
                </Row>
              ))}
            </Card>
          ) : null}

          <Card gap={0}>
            <Txt v="h2" accessibilityRole="header" style={{ marginBottom: 6 }}>
              {`친구 ${data.friends.length}/${data.max}`}
            </Txt>
            {data.friends.length ? (
              data.friends.map((f) => (
                <Row key={f.code}>
                  <View testID={`friend-${f.code}`}>
                    <Who f={f} h2h />
                  </View>
                  <View style={buttons}>
                    <Btn
                      sm
                      kind="primary"
                      testID="friend-play"
                      accessibilityLabel={`${f.name} 님과 친선전`}
                      disabled={busy || !canFriendly(data, f)}
                      onPress={() => void challenge(f)}
                    >
                      친선전
                    </Btn>
                    {f.preseasonTeam ? (
                      <Btn
                        sm
                        testID="friend-play-preseason"
                        accessibilityLabel={`${f.name} 님과 프리시즌 친선전`}
                        disabled={busy || !canPreseasonFriendly(data, f)}
                        onPress={() => void challenge(f, true)}
                      >
                        프리시즌 친선전
                      </Btn>
                    ) : null}
                    <Btn
                      sm
                      kind="ghost"
                      disabled={busy}
                      testID="friend-remove"
                      accessibilityLabel={`${f.name} 님과 친구 끊기`}
                      onPress={() => askRemove(f)}
                    >
                      끊기
                    </Btn>
                  </View>
                </Row>
              ))
            ) : (
              <Txt tone="muted">아직 친구가 없어요. 신청을 수락하면 여기에 보여요.</Txt>
            )}
          </Card>

          {data.sent.length ? (
            <Card gap={0}>
              <Txt v="h2" accessibilityRole="header" style={{ marginBottom: 6 }}>
                보낸 신청
              </Txt>
              {data.sent.map((f) => (
                <Row key={f.code}>
                  <Who f={f} />
                  <View style={buttons}>
                    <Btn
                      sm
                      disabled={busy}
                      testID="friend-cancel"
                      accessibilityLabel={`${f.name} 신청 취소`}
                      onPress={() => void friends.remove(f)}
                    >
                      취소
                    </Btn>
                  </View>
                </Row>
              ))}
            </Card>
          ) : null}

          {data.recent.length ? (
            <Card gap={0}>
              <Txt v="h2" accessibilityRole="header" style={{ marginBottom: 6 }}>
                최근 친선전
              </Txt>
              {data.recent.map((m) => (
                <MatchRow key={m.id} m={m} open={onOpen} />
              ))}
            </Card>
          ) : null}
        </>
      ) : null}
    </LoadState>
  );
}

// apps/web/src/ui/team/TeamFriends.svelte
<script lang="ts">
  // T-11-098 친구 · 친선전 — 내 친구 코드(초대 링크) · 코드로 신청 · 받은/보낸 신청 · 친구 목록과 친선전 · 최근 친선전.
  // 친선전은 레이팅·전적에 들어가지 않는다. 이 쪽을 열 때만 불러온다(웹 메모 1분, 쓰기를 하면 메모가 비워진다).
  import { onMount } from 'svelte';
  import { normalizeFriendCode } from '@offside/contracts/owner-team';
  import {
    acceptFriend,
    fetchFriends,
    playFriendly,
    removeFriend,
    requestFriend,
    type FriendPerson,
    type FriendsResponse,
  } from '@offside/app-core/api/friends';
  import type { TeamMatch } from '@offside/app-core/api/team';
  import {
    canFriendly,
    canPreseasonFriendly,
    FOUNDER_LABEL,
    friendAcceptedText,
    friendCodeLabel,
    friendInviteText,
    friendInviteUrl,
    friendRequestText,
    h2hText,
    PRESEASON_FRIENDLY_HINT,
    preseasonTeamLine,
  } from '@offside/app-core/friendText';
  import { toast } from '../helpers.js';
  import { copyText } from '../inapp-open.js';
  import LoadState, { type LoadStatus } from '../LoadState.svelte';
  import { clearInvite, pendingInvite } from '../friendInvite.svelte.js';
  import TeamLogo from './TeamLogo.svelte';
  import TeamMatchRow from './TeamMatchRow.svelte';

  let {
    onplayed,
    onopen,
    onpreseason,
  }: {
    /** 친선전을 치렀다 — 결과(중계)를 연다. */
    onplayed: (m: TeamMatch, matchesLeft: number) => void;
    /** 최근 친선전 한 경기를 연다. */
    onopen: (m: TeamMatch, matchesLeft: number) => void;
    /** T-11-113 프리시즌 팀 화면으로 간다(프리시즌 팀이 없을 때). */
    onpreseason: () => void;
  } = $props();

  let status = $state<LoadStatus>('loading');
  let data = $state<FriendsResponse | null>(null);
  let busy = $state(false);
  let codeInput = $state('');
  let invite = $state<string | null>(pendingInvite());

  async function load() {
    status = 'loading';
    const r = await fetchFriends();
    if (!r.ok) {
      status = 'error';
      return;
    }
    data = r.data;
    // 내 코드로 들어온 초대 링크는 쓸 일이 없다.
    if (invite && invite === r.data.code) {
      clearInvite();
      invite = null;
    }
    status = 'ready';
  }
  onMount(() => void load());

  /** 쓰기 하나를 돌리고(겹치지 않게) 성공하면 목록을 다시 받는다. */
  async function run<T>(
    act: () => Promise<{ ok: true; data: T } | { ok: false; error: { message: string } }>,
    done?: (d: T) => void,
  ) {
    if (busy) return;
    busy = true;
    const r = await act();
    busy = false;
    if (!r.ok) return toast(r.error.message);
    done?.(r.data);
    await load();
  }

  function sendCode(raw: string, fromInvite = false) {
    const code = normalizeFriendCode(raw);
    if (!code) return toast('친구 코드 8자리를 확인해 주세요.');
    void run(
      () => requestFriend({ code }),
      (d) => {
        toast(friendRequestText(d));
        codeInput = '';
        if (fromInvite) {
          clearInvite();
          invite = null;
        }
      },
    );
  }

  function dropInvite() {
    clearInvite();
    invite = null;
  }

  const accept = (p: FriendPerson) =>
    run(() => acceptFriend(p.code), () => toast(friendAcceptedText(p.name)));
  const remove = (p: FriendPerson, ask: string | null) => {
    if (ask && !confirm(ask)) return;
    void run(() => removeFriend(p.code));
  };

  /** 친선전 한 판. preseason이면 프리시즌 팀끼리(T-11-113). */
  async function play(p: FriendPerson, preseason = false) {
    if (busy) return;
    busy = true;
    const r = await playFriendly(p.code, preseason);
    busy = false;
    if (!r.ok) {
      if (r.error.reason === 'FRIENDLY_DAILY_LIMIT' && data) data.matchesLeft = 0;
      return toast(r.error.message);
    }
    onplayed(r.data.match, r.data.matchesLeft);
  }

  async function share() {
    if (!data) return;
    if (navigator.share) {
      try {
        await navigator.share({ text: friendInviteText(data.code, window.location.origin) });
      } catch (e) {
        // 공유 시트를 닫은 것(AbortError)은 실패가 아니다.
        if ((e as Error)?.name !== 'AbortError') toast('공유하지 못했어요');
      }
      return;
    }
    const copied = await copyText(friendInviteUrl(data.code, window.location.origin));
    toast(copied ? '초대 링크를 복사했어요' : '공유하지 못했어요');
  }
  async function copyCode() {
    if (!data) return;
    toast((await copyText(friendCodeLabel(data.code))) ? '코드를 복사했어요' : '코드를 복사하지 못했어요');
  }

  const teamLine = (p: FriendPerson) => (p.team ? `${p.team.name} · OVR ${p.team.ovr}` : '이번 시즌 팀이 없어요');
</script>

<section class="card stack" style="gap:12px" data-friends>
  <div>
    <div class="eyebrow">Friends</div>
    <h1>친구</h1>
    {#if data}
      <p class="muted fs-sm">친선전은 레이팅과 전적에 들어가지 않아요. 오늘 남은 친선전 {data.matchesLeft}/{data.matchesPerDay}</p>
      {#if !data.canPlay}<p class="muted fs-sm" data-friends-hint>이번 시즌 팀을 만들면 친구와 친선전을 할 수 있어요.</p>{/if}
      {#if data.canPlayPreseason === false}
        <div class="fr-legacy" data-friends-preseason-hint>
          <p class="muted fs-sm">{PRESEASON_FRIENDLY_HINT}</p>
          <button class="btn btn-sm" onclick={onpreseason} data-act="friend-preseason-team">프리시즌 팀 꾸리기</button>
        </div>
      {/if}
    {/if}
  </div>
  <LoadState {status} failText="친구 목록을 불러오지 못했어요." retry={() => void load()}>
    {#if data}
      {#if invite}
        <div class="fr-invite" role="status" data-friend-invite>
          <p>초대 링크로 들어왔어요. 코드 <b>{friendCodeLabel(invite)}</b> 구단주에게 친구 신청할까요?</p>
          <div class="fr-row-actions">
            <button class="btn btn-primary btn-sm" disabled={busy} onclick={() => sendCode(invite!, true)} data-act="friend-invite-send">신청</button>
            <button class="btn btn-sm" onclick={dropInvite}>닫기</button>
          </div>
        </div>
      {/if}

      <div class="fr-code">
        <span class="muted fs-sm">내 친구 코드</span>
        <b class="fr-code-value" data-friend-code>{friendCodeLabel(data.code)}</b>
        <div class="fr-row-actions">
          <button class="btn btn-sm" onclick={share} data-act="friend-share">초대 링크 공유</button>
          <button class="btn btn-sm" onclick={copyCode}>코드 복사</button>
        </div>
      </div>

      <form class="fr-add" onsubmit={(e) => { e.preventDefault(); sendCode(codeInput); }}>
        <label class="fr-add-label" for="friend-code-input">친구 코드로 신청</label>
        <div class="fr-add-row">
          <input id="friend-code-input" type="text" enterkeyhint="send" bind:value={codeInput} placeholder="ABCD-EFGH" autocomplete="off" autocapitalize="characters" spellcheck="false" maxlength="12" data-friend-code-input />
          <button class="btn btn-primary" type="submit" disabled={busy || !codeInput.trim()} data-act="friend-request">신청</button>
        </div>
      </form>

      {#if data.received.length}
        <h2 class="fr-h">받은 신청 {data.received.length}</h2>
        {#each data.received as p (p.code)}
          <div class="fr-person" data-friend-received={p.code}>
            <div class="fr-info"><b>{p.name}</b><span class="muted fs-sm">{teamLine(p)}</span></div>
            <div class="fr-row-actions">
              <button class="btn btn-primary btn-sm" disabled={busy} onclick={() => void accept(p)} data-act="friend-accept">수락</button>
              <button class="btn btn-sm" disabled={busy} onclick={() => remove(p, null)}>거절</button>
            </div>
          </div>
        {/each}
      {/if}

      <h2 class="fr-h">친구 {data.friends.length}/{data.max}</h2>
      {#each data.friends as p (p.code)}
        {@const h2h = h2hText(p.h2h)}
        {@const preseasonLine = preseasonTeamLine(p)}
        <div class="fr-person" data-friend={p.code}>
          <TeamLogo logo={p.team?.logo ?? null} name={p.team?.name ?? p.name} size={32} decorative />
          <div class="fr-info">
            <b>{p.name}{#if p.founder}<span class="pill good fr-founder" data-friend-founder>{FOUNDER_LABEL}</span>{/if}</b>
            <span class="muted fs-sm">{teamLine(p)}</span>
            {#if preseasonLine}<span class="muted fs-sm" data-friend-preseason>{preseasonLine}</span>{/if}
            {#if h2h}<span class="fs-sm">상대 전적 {h2h}</span>{/if}
          </div>
          <div class="fr-row-actions">
            <button class="btn btn-primary btn-sm" disabled={busy || !canFriendly(data, p)} onclick={() => void play(p)} data-act="friend-play">친선전</button>
            {#if p.preseasonTeam}<button class="btn btn-sm" disabled={busy || !canPreseasonFriendly(data, p)} onclick={() => void play(p, true)} data-act="friend-play-preseason">프리시즌 친선전</button>{/if}
            <button class="icon-btn fs-sm" disabled={busy} onclick={() => remove(p, `${p.name} 님과 친구를 끊을까요? 상대 전적도 사라져요.`)} data-act="friend-remove">끊기</button>
          </div>
        </div>
      {:else}
        <p class="muted">아직 친구가 없어요. 신청을 수락하면 여기에 보여요.</p>
      {/each}

      {#if data.sent.length}
        <h2 class="fr-h">보낸 신청</h2>
        {#each data.sent as p (p.code)}
          <div class="fr-person" data-friend-sent={p.code}>
            <div class="fr-info"><b>{p.name}</b><span class="muted fs-sm">{teamLine(p)}</span></div>
            <button class="btn btn-sm" disabled={busy} onclick={() => remove(p, null)}>취소</button>
          </div>
        {/each}
      {/if}

      {#if data.recent.length}
        <h2 class="fr-h">최근 친선전</h2>
        {#each data.recent as m (m.id)}
          <TeamMatchRow {m} onopen={(x) => onopen(x, data!.matchesLeft)} />
        {/each}
      {/if}
    {/if}
  </LoadState>
</section>

<style>
  .fr-h {
    margin: 6px 0 0;
    font-size: 0.9375rem;
  }
  .fr-invite {
    display: flex;
    flex-direction: column;
    gap: 8px;
    padding: 12px;
    border: 1.5px solid var(--accent-text);
    border-radius: 12px;
  }
  .fr-invite p {
    margin: 0;
    font-size: 0.875rem;
  }
  .fr-code {
    display: flex;
    flex-direction: column;
    gap: 6px;
  }
  .fr-code-value {
    font-family: var(--display);
    font-size: 1.5rem;
    letter-spacing: 0.06em;
  }
  .fr-add {
    display: flex;
    flex-direction: column;
    gap: 6px;
  }
  .fr-add-label {
    font-size: 0.875rem;
    color: var(--muted);
  }
  .fr-add-row {
    display: flex;
    gap: 8px;
  }
  .fr-add-row input {
    flex: 1;
    min-width: 0;
    text-transform: uppercase;
  }
  .fr-row-actions {
    display: flex;
    flex-wrap: wrap;
    gap: 6px;
    flex: none;
  }
  .fr-person {
    display: flex;
    align-items: center;
    gap: 10px;
    padding: 10px 0;
    border-top: 1px solid var(--line);
  }
  .fr-legacy {
    display: flex;
    flex-wrap: wrap;
    align-items: center;
    gap: 8px;
    margin-top: 6px;
  }
  .fr-legacy p {
    margin: 0;
    flex: 1 1 200px;
  }
  .fr-founder {
    margin-left: 6px;
    vertical-align: middle;
  }
  .fr-info {
    display: flex;
    flex-direction: column;
    gap: 2px;
    flex: 1;
    min-width: 0;
    overflow-wrap: anywhere;
  }
</style>
