// apps/mobile/src/screens/owner/TeamAchievements.tsx
// 시즌 업적 탭(웹 team/Team.svelte 의 [data-club-achievements]) — 맨 위 시즌 등급 · 점수 · 업적 랭킹 · 다음 등급 막대, 다음 목표,
// 분류(선수·팀·구단주·감독) 탭, 고른 분류의 단계별 묶음은 접었다 펴고(다 채우지 못한 첫 단계만 펼쳐 둔다), 감독 분류는
// 잠금 카드로 예고한다. T-11-028 업적마다 점수가 있고 점수 합이 등급이 된다.
import { useEffect, useState } from 'react';
import { View } from 'react-native';
import type { AchCategory } from '@offside/contracts/owner-team';
import type { ClubAchievementsResponse } from '@offside/app-core/api/team';
import { hofStart } from '@offside/app-core/state';
import {
  achDone,
  achGradeView,
  achNear,
  achOpenGroup,
  achPoints,
  achRankText,
  achSections,
  achState,
  achTotal,
} from '@offside/app-core/teamOwner';
import { num } from '@offside/app-core/teamText';
import { LoadState, type LoadStatus } from '../../components/LoadState';
import { go } from '../../game/nav';
import { appState } from '../../store';
import { mix } from '../../theme/colors';
import { useColors } from '../../theme/useColors';
import { DISPLAY, rem } from '../../theme/type';
import { Card, Press, Txt } from '../../ui';
import { SelectField } from '../settings/parts';
import { AchGradeBadge, TmTitle } from './TeamParts';

function Stage({ children }: { children: string }) {
  const c = useColors();
  return (
    <View
      style={{
        paddingVertical: 2,
        paddingHorizontal: 6,
        borderRadius: 6,
        backgroundColor: c.surface2,
      }}
    >
      <Txt tone="accent" style={{ fontSize: rem(0.6875), fontWeight: '700' }}>
        {children}
      </Txt>
    </View>
  );
}

/** 진행 막대(웹 .tm-bar). sm은 다음 목표 줄 아래 전체 폭(웹 .tm-bar.sm). */
function Bar({ ratio, sm, label }: { ratio: number; sm?: boolean; label?: string }) {
  const c = useColors();
  const pct = Math.round(ratio * 100);
  return (
    <View
      {...(label
        ? {
            accessible: true,
            accessibilityRole: 'progressbar' as const,
            accessibilityLabel: label,
            accessibilityValue: { min: 0, max: 100, now: pct },
          }
        : { importantForAccessibility: 'no-hide-descendants' as const })}
      style={{
        height: sm ? 6 : 8,
        borderRadius: 99,
        overflow: 'hidden',
        backgroundColor: sm ? c.line : c.surface2,
      }}
    >
      <View
        style={{
          width: `${pct}%`,
          height: '100%',
          borderRadius: 99,
          backgroundColor: c.accent,
        }}
      />
    </View>
  );
}

/** 업적 점수(웹 .tm-pts) — 얻은 점수(또는 다음 목표)는 accent, 아직이면 muted. */
function Pts({ children, got }: { children: string; got: boolean }) {
  return (
    <Txt
      tone={got ? 'accent' : 'muted'}
      style={{
        flexShrink: 0,
        fontFamily: DISPLAY[700],
        fontSize: rem(0.8125),
        fontVariant: ['tabular-nums'],
      }}
    >
      {children}
    </Txt>
  );
}

function Group({
  g,
  initialOpen,
  newIds,
}: {
  g: ClubAchievementsResponse['groups'][number];
  initialOpen: boolean;
  newIds: ReadonlySet<string>;
}) {
  const c = useColors();
  const [open, setOpen] = useState(initialOpen);
  return (
    <View
      testID={`ach-group-${g.id}`}
      style={{ borderWidth: 1, borderColor: c.line, borderRadius: 12, backgroundColor: c.surface }}
    >
      <Press
        scale={0.99}
        onPress={() => setOpen(!open)}
        accessibilityLabel={`${g.stage} ${g.title} ${achDone(g.items)}/${g.items.length} 달성`}
        accessibilityState={{ expanded: open }}
        style={{
          flexDirection: 'row',
          alignItems: 'center',
          gap: 8,
          minHeight: 48,
          paddingVertical: 8,
          paddingHorizontal: 12,
        }}
      >
        <Stage>{g.stage}</Stage>
        <Txt bold style={{ flex: 1, minWidth: 0 }}>
          {g.title}
        </Txt>
        <Txt tone="accent" style={{ fontFamily: DISPLAY[700] }}>
          {`${achDone(g.items)}/${g.items.length}`}
        </Txt>
      </Press>
      {open ? (
        <View style={{ gap: 6, paddingHorizontal: 12, paddingBottom: 10 }}>
          {g.items.map((i) => (
            <View
              key={i.id}
              style={{
                flexDirection: 'row',
                justifyContent: 'space-between',
                alignItems: 'center',
                gap: 10,
                paddingVertical: 8,
                paddingHorizontal: 10,
                borderRadius: 10,
                backgroundColor: c.surface2,
              }}
            >
              <View style={{ flex: 1, minWidth: 0, gap: 2 }}>
                <View style={{ flexDirection: 'row', alignItems: 'center', gap: 6 }}>
                  <Txt style={{ flexShrink: 1 }}>{i.label}</Txt>
                  {newIds.has(i.id) ? <NewChip /> : null}
                </View>
                <Txt
                  tone={i.done ? 'accent' : 'muted'}
                  style={{ fontSize: rem(0.75), fontWeight: i.done ? '700' : '400' }}
                >
                  {achState(i)}
                </Txt>
              </View>
              <Pts got={i.points > 0}>{achPoints(i)}</Pts>
            </View>
          ))}
        </View>
      ) : null}
    </View>
  );
}

/** T-11-034 지난번 업적 탭을 본 뒤 새로 오른 업적 표시(웹 .tm-ach-new). */
function NewChip() {
  const c = useColors();
  return (
    <View
      testID="ach-new"
      style={{ paddingHorizontal: 5, paddingVertical: 1, borderRadius: 4, backgroundColor: c.bad }}
    >
      <Txt
        style={{
          color: '#fff',
          fontSize: rem(0.625),
          lineHeight: rem(0.625) * 1.3,
          fontWeight: '800',
          letterSpacing: 0.04 * rem(0.625),
        }}
      >
        NEW
      </Txt>
    </View>
  );
}

/** 아직 열리지 않은 감독 분류 예고 카드(웹 .tm-ach-locked.tm-ach-soon). */
function ManagerSoon() {
  const c = useColors();
  return (
    <View
      testID="ach-group-manager"
      accessible
      accessibilityLabel="감독 커리어 업적, 곧 열려요. 감독 시뮬레이션이 열리면 감독으로 거둔 성적도 업적이 돼요."
      style={{
        gap: 6,
        padding: 12,
        borderWidth: 1,
        borderStyle: 'dashed',
        borderColor: c.line,
        borderRadius: 12,
        backgroundColor: c.surface2,
      }}
    >
      <View style={{ flexDirection: 'row', alignItems: 'center', gap: 8 }}>
        <Stage>SOON</Stage>
        <Txt bold style={{ flex: 1 }}>
          감독 커리어
        </Txt>
      </View>
      <Txt tone="muted" v="sm">
        감독 시뮬레이션이 열리면 감독으로 거둔 성적도 업적이 돼요. 선수·팀·구단주 업적처럼 시즌마다
        새로 쌓여요.
      </Txt>
    </View>
  );
}

export function TeamAchievements({
  ach,
  status,
  newIds,
  load,
}: {
  ach: ClubAchievementsResponse | null;
  status: LoadStatus;
  /** T-11-034 새로 오른 업적(NEW) — 그 분류·단계를 먼저 펼친다. */
  newIds: ReadonlySet<string>;
  load: (season?: number) => void;
}) {
  const c = useColors();
  const [cat, setCat] = useState<AchCategory>('player');
  useEffect(() => {
    const first = ach?.groups.find((g) => g.items.some((i) => newIds.has(i.id)));
    if (first) setCat(first.category);
  }, [ach, newIds]);
  const seasonName = ach?.seasons.find((o) => o.id === ach.season)?.name ?? '';
  const tot = ach ? achTotal(ach.groups) : null;
  const gv = ach ? achGradeView(ach.score) : null;
  const sections = ach ? achSections(ach.groups) : [];
  const sec = sections.find((x) => x.id === cat) ?? sections[0];
  const near = ach ? achNear(ach.groups) : [];
  const openId = sec
    ? (sec.groups.find((g) => g.items.some((i) => newIds.has(i.id)))?.id ??
      achOpenGroup(sec.groups))
    : null;
  /** 기록실 업적 랭킹 탭을 연다. */
  function openAchRanking() {
    appState.hof = { ...hofStart(), tab: 'ach' };
    go('hof');
  }
  return (
    <Card gap={12}>
      <TmTitle
        eyebrow="Season achievements"
        title="시즌 업적"
        right={
          ach && ach.seasons.length > 1 ? (
            <SelectField
              label="시즌"
              testID="ach-season"
              value={ach.season}
              options={ach.seasons.map((o) => ({ value: o.id, label: o.name }))}
              onChange={(v) => load(v)}
              style={{ maxWidth: '45%', minHeight: 40 }}
            />
          ) : null
        }
      />
      <LoadState
        status={status}
        failText="업적을 불러오지 못했어요."
        retry={() => load(ach?.season)}
      >
        {ach && tot && gv && sec ? (
          <>
            <View style={{ gap: 8 }} testID="ach-summary">
              <View style={{ flexDirection: 'row', alignItems: 'center', gap: 10 }}>
                <AchGradeBadge grade={gv.grade} large />
                <View
                  style={{
                    flex: 1,
                    minWidth: 0,
                    flexDirection: 'row',
                    alignItems: 'baseline',
                    gap: 4,
                  }}
                  accessible
                  accessibilityLabel={`시즌 업적 점수 ${num(ach.score)}점`}
                >
                  <Txt
                    numberOfLines={1}
                    tone="accent"
                    style={{ fontFamily: DISPLAY[700], fontSize: rem(2), lineHeight: rem(2) * 1.1 }}
                  >
                    {num(ach.score)}
                  </Txt>
                  <Txt tone="muted">점</Txt>
                </View>
                <Press
                  scale={0.97}
                  testID="ach-ranking"
                  onPress={openAchRanking}
                  accessibilityLabel={`업적 랭킹 ${achRankText(ach.rank, ach.ranked)}`}
                  style={{
                    maxWidth: '50%',
                    minHeight: 44,
                    alignItems: 'flex-end',
                    justifyContent: 'center',
                    gap: 1,
                    paddingVertical: 4,
                    paddingHorizontal: 10,
                    borderWidth: 1,
                    borderColor: c.line,
                    borderRadius: 10,
                    backgroundColor: c.surface,
                  }}
                >
                  <Txt tone="muted" style={{ fontSize: rem(0.6875), fontWeight: '600' }}>
                    업적 랭킹
                  </Txt>
                  <Txt style={{ fontSize: rem(0.8125), fontWeight: '700', textAlign: 'right' }}>
                    {achRankText(ach.rank, ach.ranked)}
                  </Txt>
                </Press>
              </View>
              <Bar ratio={gv.ratio} label="다음 등급까지" />
              <Txt tone="muted" v="sm">
                {`${gv.next ? `${gv.next.name}까지 ${num(gv.toNext)}점` : '최고 등급이에요'} · 업적 ${tot.done}/${tot.total} 달성`}
              </Txt>
              <Txt
                tone="muted"
                v="xs"
              >{`${seasonName}에 처음 뛰어 은퇴한 내 선수 ${ach.players}명과 이 시즌 팀·구단 활동으로 채워요. 시즌마다 처음부터 다시 쌓아요.`}</Txt>
            </View>
            {near.length ? (
              <View style={{ gap: 6 }} testID="ach-near">
                <Txt v="eyebrow">다음 목표</Txt>
                {near.map((n) => (
                  <View
                    key={n.item.id}
                    style={{
                      gap: 6,
                      paddingVertical: 8,
                      paddingHorizontal: 10,
                      borderRadius: 10,
                      backgroundColor: c.surface2,
                    }}
                  >
                    <View style={{ flexDirection: 'row', alignItems: 'flex-start', gap: 10 }}>
                      <View style={{ flex: 1, minWidth: 0, gap: 2 }}>
                        <Txt bold>{n.item.label}</Txt>
                        <Txt tone="muted" style={{ fontSize: rem(0.75) }}>
                          {`${n.group} · ${achState(n.item)}`}
                        </Txt>
                      </View>
                      <Pts got>{`+${num(n.item.worth)}점`}</Pts>
                    </View>
                    <Bar ratio={n.ratio} sm />
                  </View>
                ))}
              </View>
            ) : null}
            <View
              accessibilityRole="tablist"
              accessibilityLabel="업적 분류"
              style={{ flexDirection: 'row', gap: 6 }}
            >
              {sections.map((x) => {
                const on = sec.id === x.id;
                return (
                  <Press
                    key={x.id}
                    scale={0.97}
                    testID={`ach-cat-${x.id}`}
                    onPress={() => setCat(x.id)}
                    accessibilityRole="tab"
                    accessibilityLabel={`${x.name} ${x.locked ? '잠김' : `${num(x.score)}점`}`}
                    accessibilityState={{ selected: on }}
                    style={{
                      flex: 1,
                      minWidth: 0,
                      minHeight: 48,
                      alignItems: 'center',
                      justifyContent: 'center',
                      gap: 1,
                      paddingVertical: 6,
                      paddingHorizontal: 4,
                      borderWidth: 1,
                      borderColor: on ? c.accent : c.line,
                      borderRadius: 10,
                      backgroundColor: on ? mix(c.accent, c.surface, 0.12) : c.surface,
                    }}
                  >
                    <Txt
                      numberOfLines={1}
                      adjustsFontSizeToFit
                      minimumFontScale={0.85}
                      style={{ fontSize: rem(0.875), fontWeight: '700' }}
                    >
                      {x.name.replace(' 업적', '')}
                    </Txt>
                    <Txt num={400} tone={on ? 'accent' : 'muted'} style={{ fontSize: rem(0.75) }}>
                      {x.locked ? '🔒︎' : num(x.score)}
                    </Txt>
                  </Press>
                );
              })}
            </View>
            {sec.locked ? (
              <ManagerSoon />
            ) : (
              sec.groups.map((g) => (
                <Group
                  key={`${ach.season}-${g.id}`}
                  g={g}
                  initialOpen={g.id === openId}
                  newIds={newIds}
                />
              ))
            )}
          </>
        ) : null}
      </LoadState>
    </Card>
  );
}

// apps/web/src/ui/team/TeamAchievements.svelte
<script lang="ts">
  // T-11-028 시즌 업적 화면 — 점수·등급, 다음 목표, 분류별 업적. 불러오기는 Team.svelte가 맡는다.
  import type { AchCategory } from '@offside/contracts/owner-team';
  import type { ClubAchievementsResponse } from '@offside/app-core/api/team';
  import { num } from '@offside/app-core/teamText';
  import {
    achDone, achGradeView, achNear, achOpenGroup, achPoints, achRankText, achSections, achState, achTotal,
  } from '@offside/app-core/teamOwner';
  import LoadState, { type LoadStatus } from '../LoadState.svelte';
  import AchGradeBadge from './AchGradeBadge.svelte';

  let {
    ach,
    status,
    newIds,
    cat = $bindable(),
    load,
    onrank,
  }: {
    ach: ClubAchievementsResponse | null;
    status: LoadStatus;
    /** 지난번 업적 탭을 본 뒤 새로 오른 업적(NEW). */
    newIds: ReadonlySet<string>;
    /** 보고 있는 분류(선수·팀·구단주·감독). */
    cat: AchCategory;
    /** 시즌을 지정해 다시 불러온다(없으면 보고 있는 시즌). */
    load: (season?: number) => void;
    /** 기록실 업적 랭킹을 연다. */
    onrank: () => void;
  } = $props();
</script>

<section class="card stack" style="gap:12px" data-club-achievements>
  <div class="tm-title">
    <div>
      <div class="eyebrow">Season achievements</div>
      <h1>시즌 업적</h1>
    </div>
    {#if ach && ach.seasons.length > 1}
      <select class="tm-season" aria-label="시즌" value={ach.season} onchange={(e) => load(Number(e.currentTarget.value))}>
        {#each ach.seasons as o (o.id)}
          <option value={o.id}>{o.name}</option>
        {/each}
      </select>
    {/if}
  </div>
  <LoadState {status} failText="업적을 불러오지 못했어요." retry={() => load(ach?.season)}>
    {#if ach}
      {@const tot = achTotal(ach.groups)}
      {@const gv = achGradeView(ach.score)}
      {@const sections = achSections(ach.groups)}
      {@const sec = sections.find((x) => x.id === cat) ?? sections[0]!}
      {@const near = achNear(ach.groups)}
      {@const openId = sec.groups.find((g) => g.items.some((i) => newIds.has(i.id)))?.id ?? achOpenGroup(sec.groups)}
      <div class="tm-ach-sum" data-ach-summary>
        <div class="tm-ach-head">
          <AchGradeBadge grade={gv.grade} large />
          <div class="tm-ach-total"><b>{num(ach.score)}</b><span class="muted">점</span></div>
          <button class="tm-ach-rank" data-act="ach-ranking" onclick={onrank}>
            <small class="muted">업적 랭킹</small><span>{achRankText(ach.rank, ach.ranked)}</span>
          </button>
        </div>
        <div class="tm-bar" role="progressbar" aria-label="다음 등급까지" aria-valuemin={0} aria-valuemax={100} aria-valuenow={Math.round(gv.ratio * 100)}>
          <span style:width="{gv.ratio * 100}%"></span>
        </div>
        <p class="muted fs-sm" data-ach-next>
          {gv.next ? `${gv.next.name}까지 ${num(gv.toNext)}점` : '최고 등급이에요'} · 업적 {tot.done}/{tot.total} 달성
        </p>
        <p class="muted fs-xs">{ach.seasons.find((o) => o.id === ach?.season)?.name ?? ''}에 처음 뛰어 은퇴한 내 선수 {ach.players}명과 이 시즌 팀·구단 활동으로 채워요. 시즌마다 처음부터 다시 쌓아요.</p>
      </div>
      {#if near.length}
        <div class="tm-near" data-ach-near>
          <div class="eyebrow">다음 목표</div>
          <ul>
            {#each near as n (n.item.id)}
              <li>
                <span class="tm-near-txt"><b>{n.item.label}</b><small class="muted">{n.group} · {achState(n.item)}</small></span>
                <span class="tm-pts">+{num(n.item.worth)}점</span>
                <span class="tm-bar sm" aria-hidden="true"><span style:width="{n.ratio * 100}%"></span></span>
              </li>
            {/each}
          </ul>
        </div>
      {/if}
      <div class="tm-ach-cats" role="tablist" aria-label="업적 분류" style:grid-template-columns="repeat({sections.length}, minmax(0, 1fr))">
        {#each sections as x (x.id)}
          <button role="tab" aria-selected={sec.id === x.id} data-ach-cat={x.id} onclick={() => (cat = x.id)}>
            <span>{x.name.replace(' 업적', '')}</span>
            <small class="num">{x.locked ? '🔒︎' : num(x.score)}</small>
          </button>
        {/each}
      </div>
      {#if sec.locked}
        <div class="tm-ach tm-ach-locked tm-ach-soon" data-ach-group="manager">
          <div class="tm-ach-head"><span class="tm-ach-stage">SOON</span><b>감독 커리어</b></div>
          <small class="muted">감독 시뮬레이션이 열리면 감독으로 거둔 성적도 업적이 돼요. 선수·팀·구단주 업적처럼 시즌마다 새로 쌓여요.</small>
        </div>
      {:else}
        {#each sec.groups as g (`${ach.season}-${g.id}`)}
          <details class="tm-ach" data-ach-group={g.id} open={g.id === openId}>
            <summary>
              <span class="tm-ach-stage">{g.stage}</span>
              <b>{g.title}</b>
              <span class="tm-ach-count">{achDone(g.items)}/{g.items.length}</span>
            </summary>
            <ul>
              {#each g.items as i (i.id)}
                <li class:done={i.done}>
                  <span class="tm-ach-txt"><span>{i.label}{#if newIds.has(i.id)}<em class="tm-ach-new">NEW</em>{/if}</span><small>{achState(i)}</small></span>
                  <span class="tm-pts" class:got={i.points > 0}>{achPoints(i)}</span>
                </li>
              {/each}
            </ul>
          </details>
        {/each}
      {/if}
    {/if}
  </LoadState>
</section>

<style>
  .tm-title {
    display: flex;
    justify-content: space-between;
    align-items: flex-start;
    gap: 12px;
  }
  .tm-title h1 {
    overflow-wrap: anywhere;
  }
  .tm-ach-sum {
    display: flex;
    flex-direction: column;
    gap: 8px;
  }
  .tm-ach-sum p {
    margin: 0;
  }
  .tm-ach-head {
    display: flex;
    align-items: center;
    gap: 10px;
  }
  .tm-ach-total {
    display: flex;
    align-items: baseline;
    gap: 4px;
    flex: 1;
    min-width: 0;
  }
  .tm-ach-rank {
    display: flex;
    flex-direction: column;
    align-items: flex-end;
    gap: 1px;
    min-height: 44px;
    justify-content: center;
    padding: 4px 10px;
    border: 1px solid var(--line);
    border-radius: 10px;
    background: var(--surface);
    color: var(--ink);
    font: inherit;
    font-size: 0.8125rem;
    font-weight: 700;
    cursor: pointer;
  }
  .tm-ach-rank small {
    font-size: 0.6875rem;
    font-weight: 600;
  }
  .tm-ach-cats {
    display: grid;
    gap: 6px;
  }
  .tm-ach-cats button {
    display: flex;
    flex-direction: column;
    align-items: center;
    gap: 1px;
    min-height: 48px;
    padding: 6px 4px;
    border: 1px solid var(--line);
    border-radius: 10px;
    background: var(--surface);
    color: var(--ink);
    font: inherit;
    font-size: 0.875rem;
    font-weight: 700;
    cursor: pointer;
  }
  .tm-ach-cats button small {
    font-size: 0.75rem;
    color: var(--muted);
  }
  .tm-ach-cats button[aria-selected='true'] {
    border-color: var(--accent);
    background: color-mix(in srgb, var(--accent) 12%, var(--surface));
  }
  .tm-ach-cats button[aria-selected='true'] small {
    color: var(--accent-text);
  }
  .tm-ach-txt {
    display: flex;
    flex-direction: column;
    gap: 2px;
    flex: 1;
    min-width: 0;
  }
  .tm-ach-new {
    margin-left: 6px;
    padding: 1px 5px;
    border-radius: 4px;
    background: var(--bad, #e5484d);
    color: #fff;
    font-style: normal;
    font-size: 0.625rem;
    font-weight: 800;
    letter-spacing: 0.04em;
    vertical-align: 1px;
  }
  .tm-ach-txt small {
    color: var(--muted);
    font-size: 0.75rem;
  }
  .tm-pts {
    flex: none;
    font-family: var(--display);
    font-size: 0.8125rem;
    font-weight: 700;
    color: var(--muted);
    font-variant-numeric: tabular-nums;
  }
  .tm-pts.got,
  .tm-near .tm-pts {
    color: var(--accent-text);
  }
  .tm-ach-total b {
    font-family: var(--display);
    font-size: 2rem;
    line-height: 1;
    color: var(--accent-text);
  }
  .tm-bar {
    display: block;
    height: 8px;
    border-radius: 99px;
    background: var(--surface-2);
    overflow: hidden;
  }
  .tm-bar.sm {
    grid-column: 1 / -1;
    height: 6px;
    background: var(--line);
  }
  .tm-bar > span {
    display: block;
    height: 100%;
    border-radius: inherit;
    background: var(--accent);
  }
  .tm-near ul {
    list-style: none;
    margin: 6px 0 0;
    padding: 0;
    display: flex;
    flex-direction: column;
    gap: 6px;
  }
  .tm-near li {
    display: grid;
    grid-template-columns: minmax(0, 1fr) auto;
    align-items: start;
    gap: 6px 10px;
    padding: 8px 10px;
    border-radius: 10px;
    background: var(--surface-2);
  }
  .tm-near-txt {
    display: flex;
    flex-direction: column;
    gap: 2px;
    flex: 1;
    min-width: 0;
  }
  .tm-season {
    flex: none;
    max-width: 45%;
    min-height: 40px;
    padding: 0 8px;
    border: 1px solid var(--line);
    border-radius: 10px;
    background: var(--surface);
    color: var(--ink);
    font: inherit;
  }
  .tm-ach {
    border: 1px solid var(--line);
    border-radius: 12px;
    background: var(--surface);
  }
  .tm-ach summary {
    display: flex;
    align-items: center;
    gap: 8px;
    min-height: 48px;
    padding: 8px 12px;
    cursor: pointer;
  }
  .tm-ach-stage {
    flex: none;
    padding: 2px 6px;
    border-radius: 6px;
    font-size: 0.6875rem;
    font-weight: 700;
    background: var(--surface-2);
    color: var(--accent-text);
  }
  .tm-ach summary b {
    flex: 1;
    min-width: 0;
  }
  .tm-ach-count {
    flex: none;
    font-family: var(--display);
    font-weight: 700;
    color: var(--accent-text);
  }
  .tm-ach ul {
    list-style: none;
    margin: 0;
    padding: 0 12px 10px;
    display: flex;
    flex-direction: column;
    gap: 6px;
  }
  .tm-ach li {
    display: flex;
    justify-content: space-between;
    align-items: center;
    gap: 10px;
    padding: 8px 10px;
    border-radius: 10px;
    background: var(--surface-2);
  }
  .tm-ach li.done .tm-ach-txt small {
    color: var(--accent-text);
    font-weight: 700;
  }
  .tm-ach-locked {
    display: flex;
    align-items: center;
    gap: 8px;
    min-height: 48px;
    padding: 8px 12px;
    border-style: dashed;
    background: var(--surface-2);
    color: var(--muted);
  }
  .tm-ach-locked b {
    flex: 1;
  }
  .tm-ach-soon {
    flex-direction: column;
    align-items: stretch;
    gap: 6px;
    padding: 12px;
  }
  .tm-ach-soon b {
    color: var(--ink);
  }
</style>
