// apps/mobile/src/components/TeamPitch.tsx
// T-10-092 팀 선발 그라운드(웹 team/TeamPitch.svelte · TeamLines.svelte). 공격이 위. 내 팀 편성(자리를 눌러 선수 고르기)과
// 팀 프로필(보기만)이 함께 쓴다. TeamLines는 팀의 공격·중원·수비·골문 힘.
import { useState } from 'react';
import { View } from 'react-native';
import {
  DETAIL_LABEL,
  FORMATION_ROWS,
  FORMATIONS,
  type FormationId,
} from '@offside/contracts/owner-team';
import type { TeamLines as Lines } from '@offside/app-core/api/team';
import { alpha } from '../theme/colors';
import { DISPLAY, rem } from '../theme/type';
import { useColors } from '../theme/useColors';
import { useShadow } from '../ui/Card';
import { Press } from '../ui/Press';
import { Txt } from '../ui/Txt';

export type PitchCell = { rating: number; name: string; youth: boolean };

function Slot({
  code,
  cell,
  index,
  onpick,
}: {
  code: string;
  cell: PitchCell;
  index: number;
  onpick?: ((i: number) => void) | undefined;
}) {
  const c = useColors();
  const label = `${DETAIL_LABEL[code as keyof typeof DETAIL_LABEL]} · ${cell.name} · ${cell.rating}`;
  const style = {
    flex: 1,
    flexBasis: 0,
    maxWidth: 76,
    minWidth: 0,
    minHeight: 64,
    alignItems: 'center',
    gap: 1,
    paddingVertical: 6,
    paddingHorizontal: 2,
    borderWidth: 1,
    borderStyle: cell.youth ? 'dashed' : 'solid',
    borderColor: alpha(c.onPitch, 0.35),
    borderRadius: 12,
    backgroundColor: cell.youth ? 'transparent' : 'rgba(0,0,0,0.22)',
  } as const;
  const inner = (
    <>
      <Txt
        style={{
          fontFamily: DISPLAY[400],
          fontSize: rem(0.6875),
          lineHeight: rem(0.6875) * 1.4,
          letterSpacing: 0.08 * rem(0.6875),
          color: c.onPitch,
        }}
      >
        {code}
      </Txt>
      <Txt
        style={{
          fontFamily: DISPLAY[700],
          fontVariant: ['tabular-nums'],
          fontSize: rem(1.25),
          lineHeight: rem(1.25),
          color: cell.youth ? c.onPitch : c.pitchAccent,
        }}
      >
        {cell.rating}
      </Txt>
      <Txt
        numberOfLines={1}
        style={{
          maxWidth: '100%',
          fontSize: rem(0.6875),
          lineHeight: rem(0.6875) * 1.4,
          color: c.onPitch,
        }}
      >
        {cell.name}
      </Txt>
    </>
  );
  return onpick ? (
    <Press
      testID={`slot-${index}`}
      accessibilityLabel={label}
      onPress={() => onpick(index)}
      style={style}
    >
      {inner}
    </Press>
  ) : (
    <View
      testID={`slot-${index}`}
      accessible
      accessibilityRole="none"
      accessibilityLabel={label}
      style={style}
    >
      {inner}
    </View>
  );
}

export function TeamPitch({
  formation,
  cells,
  onpick,
}: {
  formation: FormationId;
  cells: readonly PitchCell[];
  onpick?: ((i: number) => void) | undefined;
}) {
  const c = useColors();
  const shadow = useShadow();
  const [h, setH] = useState(0);
  const codes = FORMATIONS[formation];
  /** 그라운드 줄(공격이 위). 각 줄은 자리 인덱스 목록. */
  const rows = (() => {
    let at = 0;
    return FORMATION_ROWS[formation]
      .map((n) => {
        const row = Array.from({ length: n }, (_, k) => at + k);
        at += n;
        return row;
      })
      .reverse();
  })();
  const filled = cells.filter((x) => !x.youth).length;
  return (
    <View
      accessibilityLabel={`선발 ${filled}명 · 나머지 유스 선수`}
      style={[{ borderRadius: 16, backgroundColor: c.pitch }, shadow]}
    >
      <View
        onLayout={(e) => setH(e.nativeEvent.layout.height)}
        style={{
          borderRadius: 16,
          overflow: 'hidden',
          gap: 10,
          paddingVertical: 14,
          paddingHorizontal: 6,
        }}
      >
        {/* 잔디 줄무늬(44px씩 번갈아)와 하프라인. */}
        {Array.from({ length: Math.ceil(h / 88) }, (_, k) => (
          <View
            key={k}
            pointerEvents="none"
            style={{
              position: 'absolute',
              left: 0,
              right: 0,
              top: k * 88 + 44,
              height: 44,
              backgroundColor: c.pitch2,
            }}
          />
        ))}
        <View
          pointerEvents="none"
          style={{
            position: 'absolute',
            left: 0,
            right: 0,
            top: Math.floor(h / 2),
            height: 1,
            backgroundColor: c.chalk,
          }}
        />
        {rows.map((row, r) => (
          <View key={r} style={{ flexDirection: 'row', justifyContent: 'space-around', gap: 4 }}>
            {row.map((i) => {
              const cell = cells[i];
              return cell ? (
                <Slot key={i} code={codes[i]!} cell={cell} index={i} onpick={onpick} />
              ) : null;
            })}
          </View>
        ))}
      </View>
    </View>
  );
}

/** 팀의 공격·중원·수비·골문 힘(내 팀 편성 · 팀 프로필). */
const CELLS = [
  ['atk', '공격'],
  ['mid', '중원'],
  ['def', '수비'],
  ['gk', '골문'],
] as const;

export function TeamLines({ lines }: { lines: Lines }) {
  const c = useColors();
  return (
    <View testID="team-lines" style={{ flexDirection: 'row', gap: 6 }}>
      {CELLS.map(([k, label]) => (
        <View
          key={k}
          accessible
          accessibilityLabel={`${label} ${Math.round(lines[k])}`}
          style={{
            flex: 1,
            alignItems: 'center',
            paddingVertical: 6,
            borderRadius: 10,
            backgroundColor: c.surface2,
          }}
        >
          <Txt tone="muted" style={{ fontSize: rem(0.75), lineHeight: rem(0.75) * 1.5 }}>
            {label}
          </Txt>
          <Txt num style={{ fontSize: rem(1.25), lineHeight: rem(1.25) * 1.3, fontWeight: '700' }}>
            {Math.round(lines[k])}
          </Txt>
        </View>
      ))}
    </View>
  );
}

// apps/web/src/ui/team/TeamPitch.svelte
<script lang="ts">
  // T-10-092 팀 선발 그라운드(공격이 위). 내 팀 편성(자리를 눌러 선수 고르기)과 팀 프로필(보기만)이 함께 쓴다.
  import { DETAIL_LABEL, FORMATION_ROWS, FORMATIONS, type FormationId } from '@offside/contracts/owner-team';

  type Cell = { rating: number; name: string; youth: boolean };
  let {
    formation,
    cells,
    onpick,
  }: { formation: FormationId; cells: readonly Cell[]; onpick?: ((i: number) => void) | undefined } = $props();

  const codes = $derived(FORMATIONS[formation]);
  /** 그라운드 줄(공격이 위). 각 줄은 자리 인덱스 목록. */
  const rows = $derived.by(() => {
    let at = 0;
    return FORMATION_ROWS[formation]
      .map((n) => {
        const row = Array.from({ length: n }, (_, k) => at + k);
        at += n;
        return row;
      })
      .reverse();
  });
  const filled = $derived(cells.filter((c) => !c.youth).length);
</script>

{#snippet inner(i: number, c: Cell)}
  <span class="tm-code">{codes[i]}</span>
  <b>{c.rating}</b>
  <span class="tm-name">{c.name}</span>
{/snippet}

<section class="tm-pitch" aria-label="선발 {filled}명 · 나머지 유스 선수">
  {#each rows as row, r (r)}
    <div class="tm-row">
      {#each row as i (i)}
        {@const c = cells[i]}
        {#if c && onpick}
          <button class="tm-slot" class:youth={c.youth} data-slot={i} onclick={() => onpick(i)} aria-label="{DETAIL_LABEL[codes[i]!]} · {c.name} · {c.rating}">
            {@render inner(i, c)}
          </button>
        {:else if c}
          <div class="tm-slot" class:youth={c.youth} data-slot={i} role="group" aria-label="{DETAIL_LABEL[codes[i]!]} · {c.name} · {c.rating}">
            {@render inner(i, c)}
          </div>
        {/if}
      {/each}
    </div>
  {/each}
</section>

<style>
  .tm-pitch {
    display: flex;
    flex-direction: column;
    gap: 10px;
    padding: 14px 6px;
    border-radius: 16px;
    background:
      linear-gradient(var(--chalk), var(--chalk)) center / 100% 1px no-repeat,
      repeating-linear-gradient(180deg, var(--pitch) 0 44px, var(--pitch-2) 44px 88px);
    box-shadow: var(--shadow);
  }
  .tm-row {
    display: flex;
    justify-content: space-around;
    gap: 4px;
  }
  .tm-slot {
    flex: 1 1 0;
    max-width: 76px;
    min-width: 0;
    min-height: 64px;
    display: flex;
    flex-direction: column;
    align-items: center;
    gap: 1px;
    padding: 6px 2px;
    border: 1px solid color-mix(in srgb, var(--on-pitch) 35%, transparent);
    border-radius: 12px;
    background: color-mix(in srgb, #000 22%, transparent);
    color: var(--on-pitch);
    font: inherit;
  }
  button.tm-slot {
    cursor: pointer;
  }
  .tm-slot.youth {
    border-style: dashed;
    background: transparent;
  }
  .tm-slot b {
    font-family: var(--display);
    font-size: 1.25rem;
    line-height: 1;
    color: var(--pitch-accent);
  }
  .tm-slot.youth b {
    color: var(--on-pitch);
  }
  .tm-code {
    font-family: var(--display);
    font-size: 0.6875rem;
    letter-spacing: 0.08em;
  }
  .tm-name {
    max-width: 100%;
    font-size: 0.6875rem;
    white-space: nowrap;
    overflow: hidden;
    text-overflow: ellipsis;
  }
</style>
