// apps/mobile/src/ui/CupTrophy.tsx
// T-11-145 컵 트로피 — 모양은 app-core/cupTrophy(웹과 같다), 효과는 등급 엠블럼(GradeEmblem)처럼 후광·광택, 우승은 반짝임까지.
// 받침대에는 name(구단주 이름)을 새기고, 넘치면 선수 카드 이름처럼 흘려 보낸다. 움직임 줄이기를 켰거나 앱이 뒤로 가면 멈춘다.
import { useEffect, useId, useRef, useState } from 'react';
import {
  Animated as RNAnimated,
  AppState,
  Easing as RNEasing,
  StyleSheet,
  Text as RNText,
  View,
} from 'react-native';
import Animated, {
  cancelAnimation,
  Easing,
  interpolate,
  useAnimatedStyle,
  useSharedValue,
  withRepeat,
  withTiming,
} from 'react-native-reanimated';
import Svg, {
  Circle,
  Defs,
  LinearGradient,
  Path,
  RadialGradient,
  Rect,
  Stop,
} from 'react-native-svg';
import { useSnapshot } from 'valtio';
import {
  cupTrophy,
  TROPHY_CUP_VIEWBOX,
  TROPHY_PLATE as P,
  TROPHY_PLATE_MIN,
  TROPHY_VIEWBOX,
  type TrophyStage,
} from '@offside/app-core/cupTrophy';
import { prefs } from '../store';

const CYCLE: Record<TrophyStage, number> = { champion: 8500, runnerup: 8000, sf: 9500 };
const STAR = 'M8 0L10 6L16 8L10 10L8 16L6 10L0 8L6 6Z';

/** 받침대에 새긴 이름. 자리보다 길면 2초 쉬고 끝까지 흘렀다가 처음으로 돌아온다(PlayerCard CardName과 같은 리듬). */
function PlateName({
  name,
  size,
  color,
  moving,
}: {
  name: string;
  size: number;
  color: string;
  moving: boolean;
}) {
  const [textWidth, setTextWidth] = useState(0);
  const offset = useRef(new RNAnimated.Value(0)).current;
  const width = (size * P.w) / 64;
  const distance = textWidth - width;
  useEffect(() => {
    offset.setValue(0);
    if (distance <= 1 || !moving) return;
    const loop = RNAnimated.loop(
      RNAnimated.sequence([
        RNAnimated.delay(2000),
        RNAnimated.timing(offset, {
          toValue: -distance,
          duration: Math.max(4000, distance * 160),
          easing: RNEasing.linear,
          useNativeDriver: true,
        }),
        RNAnimated.delay(2000),
        RNAnimated.timing(offset, { toValue: 0, duration: 0, useNativeDriver: true }),
      ]),
    );
    loop.start();
    return () => loop.stop();
  }, [distance, moving, offset]);
  const style = {
    fontSize: (size * P.font) / 64,
    fontWeight: '800' as const,
    color,
    includeFontPadding: false,
    letterSpacing: 0.2,
  };
  const scroll = moving && distance > 1;
  return (
    <View
      style={{
        position: 'absolute',
        left: (size * P.x) / 64,
        top: (size * P.y) / 64,
        width,
        height: (size * P.h) / 64,
        overflow: 'hidden',
        justifyContent: 'center',
      }}
    >
      <RNText
        allowFontScaling={false}
        onTextLayout={(e) => setTextWidth(e.nativeEvent.lines[0]?.width ?? 0)}
        style={[style, { position: 'absolute', width: 1000, opacity: 0 }]}
      >
        {name}
      </RNText>
      <RNAnimated.Text
        allowFontScaling={false}
        numberOfLines={1}
        ellipsizeMode="tail"
        style={[
          style,
          {
            width: scroll ? textWidth : width,
            textAlign: scroll ? 'left' : 'center',
            transform: [{ translateX: offset }],
          },
        ]}
      >
        {name}
      </RNAnimated.Text>
    </View>
  );
}

export function CupTrophy({
  stage,
  name,
  size = 40,
  bare = false,
}: {
  stage: TrophyStage;
  /** 받침대에 새길 이름(구단주). 없으면 비워 둔다. */
  name?: string;
  size?: number;
  /** 받침대 없이 컵만(홈 배너). 작게 그리면(TROPHY_PLATE_MIN 미만) 늘 컵만. */
  bare?: boolean;
}) {
  const trophy = cupTrophy(stage);
  const { palette } = trophy;
  const cupOnly = bare || size < TROPHY_PLATE_MIN;
  const layers = cupOnly ? trophy.layers.filter((l) => !l.plinth) : trophy.layers;
  const { motionOK } = useSnapshot(prefs);
  const [active, setActive] = useState(AppState.currentState === 'active');
  const uid = useId().replace(/[^a-zA-Z0-9]/g, '');
  const phase = useSharedValue(0);
  const champion = stage === 'champion';

  useEffect(() => {
    const sub = AppState.addEventListener('change', (state) => setActive(state === 'active'));
    return () => sub.remove();
  }, []);
  useEffect(() => {
    phase.value = 0;
    if (motionOK && active)
      phase.value = withRepeat(
        withTiming(1, { duration: CYCLE[stage], easing: Easing.linear }),
        -1,
      );
    return () => cancelAnimation(phase);
  }, [motionOK, active, stage, phase]);

  const haloStyle = useAnimatedStyle(() => ({
    opacity: champion && motionOK ? interpolate(phase.value, [0, 0.5, 1], [0.5, 0.95, 0.5]) : 0.7,
  }));
  const polishStyle = useAnimatedStyle(() => ({
    opacity: interpolate(phase.value, [0, 0.62, 0.68, 0.82, 0.87, 1], [0, 0, 0.75, 0.75, 0, 0]),
    transform: [
      {
        translateX: interpolate(
          phase.value,
          [0, 0.62, 0.82, 1],
          [-size * 1.2, -size * 1.2, size * 1.2, size * 1.2],
        ),
      },
    ],
  }));
  const sparkStyle = useAnimatedStyle(() => ({
    opacity: motionOK
      ? interpolate(phase.value, [0, 0.55, 0.68, 0.82, 1], [0.15, 0.15, 0.95, 0.2, 0.15])
      : 0.4,
    transform: [{ scale: motionOK ? interpolate(phase.value, [0, 0.68, 1], [0.7, 1.1, 0.7]) : 1 }],
  }));
  const spark = size * 0.16;
  return (
    <View
      testID={`cup-trophy-${stage}`}
      pointerEvents="none"
      accessibilityElementsHidden
      importantForAccessibility="no-hide-descendants"
      style={{ width: size, height: size, flexShrink: 0 }}
    >
      <Animated.View
        style={[{ position: 'absolute', top: -size / 10, left: -size / 10 }, haloStyle]}
      >
        <Svg width={size * 1.2} height={size * 1.2} viewBox="0 0 80 80">
          <Defs>
            <RadialGradient id={`${uid}halo`} cx="50%" cy="42%" r="50%">
              <Stop offset="0" stopColor={palette.base} stopOpacity={0.26} />
              <Stop offset="0.62" stopColor={palette.base} stopOpacity={0.08} />
              <Stop offset="1" stopColor={palette.base} stopOpacity={0} />
            </RadialGradient>
          </Defs>
          <Circle cx={40} cy={34} r={34} fill={`url(#${uid}halo)`} />
        </Svg>
      </Animated.View>
      <Svg width={size} height={size} viewBox={cupOnly ? TROPHY_CUP_VIEWBOX : TROPHY_VIEWBOX}>
        {layers.map((layer, index) => (
          <Path key={index} d={layer.d} fill={palette[layer.tone]} />
        ))}
      </Svg>
      {name && !cupOnly ? (
        <PlateName name={name} size={size} color={palette.engrave} moving={motionOK && active} />
      ) : null}
      {motionOK ? (
        <View
          style={{
            position: 'absolute',
            top: size * (cupOnly ? 0.18 : 0.06),
            left: size * 0.18,
            right: size * 0.18,
            bottom: size * (cupOnly ? 0.22 : 0.32),
            overflow: 'hidden',
          }}
        >
          <Animated.View style={[StyleSheet.absoluteFill, polishStyle]}>
            <Svg width="100%" height="100%" viewBox="0 0 64 64" preserveAspectRatio="none">
              <Defs>
                <LinearGradient id={`${uid}shine`} x1="0%" y1="0%" x2="100%" y2="30%">
                  <Stop offset="0.36" stopColor={palette.mark} stopOpacity={0} />
                  <Stop offset="0.48" stopColor={palette.mark} stopOpacity={0.6} />
                  <Stop offset="0.62" stopColor={palette.mark} stopOpacity={0} />
                </LinearGradient>
              </Defs>
              <Rect width={64} height={64} fill={`url(#${uid}shine)`} />
            </Svg>
          </Animated.View>
        </View>
      ) : null}
      {champion ? (
        <Animated.View style={[StyleSheet.absoluteFill, sparkStyle]}>
          <Svg
            width={spark}
            height={spark}
            viewBox="0 0 16 16"
            style={{ position: 'absolute', top: 0, right: size * 0.02 }}
          >
            <Path d={STAR} fill={palette.light} />
          </Svg>
          <Svg
            width={spark * 0.75}
            height={spark * 0.75}
            viewBox="0 0 16 16"
            style={{ position: 'absolute', top: size * 0.3, left: 0 }}
          >
            <Path d={STAR} fill={palette.light} />
          </Svg>
        </Animated.View>
      ) : null}
    </View>
  );
}

// apps/web/src/ui/cup/CupTrophy.svelte
<script lang="ts">
  // T-11-145 컵 트로피 — 모양은 app-core/cupTrophy가 정하고, 여기서는 등급 엠블럼(GradeEmblem)처럼 은은한 후광·광택을 얹는다.
  // 우승 트로피만 반짝임이 둘 더 붙는다. 받침대에는 name(구단주 이름)을 새기고, 넘치면 선수 카드 이름처럼 흘려 보낸다.
  // 화면 밖에서는 움직임을 멈춘다. 작게 그리거나(TROPHY_PLATE_MIN 미만) bare면 받침대 없이 컵만 그린다(배지·홈 배너).
  import { cupTrophy, TROPHY_CUP_VIEWBOX, TROPHY_PLATE as P, TROPHY_PLATE_MIN, TROPHY_VIEWBOX, type TrophyStage } from '@offside/app-core/cupTrophy';

  const { stage, name, size = 40, bare = false }: { stage: TrophyStage; name?: string | undefined; size?: number; bare?: boolean } = $props();
  const trophy = $derived(cupTrophy(stage));
  const palette = $derived(trophy.palette);
  const cupOnly = $derived(bare || size < TROPHY_PLATE_MIN);
  const layers = $derived(cupOnly ? trophy.layers.filter((l) => !l.plinth) : trophy.layers);
  const engraved = $derived(!!name && !cupOnly);
  const pct = (n: number) => `${(n / 64) * 100}%`;
  let visible = $state(false);
  let plateWidth = $state(0);
  let nameWidth = $state(0);
  const overflow = $derived(Math.max(0, nameWidth - plateWidth));

  function observe(node: HTMLElement) {
    const observer = new IntersectionObserver(([entry]) => {
      visible = entry?.isIntersecting ?? false;
    });
    observer.observe(node);
    return { destroy: () => observer.disconnect() };
  }
</script>

<span class="cup-trophy" class:cup-only={cupOnly} data-trophy={stage} data-visible={visible} style={`--t-size:${size}px;--t-base:${palette.base};--t-light:${palette.light};--t-mark:${palette.mark}`} aria-hidden="true" use:observe>
  <span class="t-halo"></span>
  <svg viewBox={cupOnly ? TROPHY_CUP_VIEWBOX : TROPHY_VIEWBOX} width={size} height={size} aria-hidden="true" focusable="false">
    {#each layers as layer, index (index)}
      <path d={layer.d} fill={palette[layer.tone]} />
    {/each}
  </svg>
  {#if engraved}
    <span class="t-plate" class:scrolling={overflow > 1} data-trophy-name={name} bind:clientWidth={plateWidth}
      style:left={pct(P.x)} style:top={pct(P.y)} style:width={pct(P.w)} style:height={pct(P.h)}
      style:font-size="{(size * P.font) / 64}px" style:color={palette.engrave}
      style:--name-offset="-{overflow}px" style:--name-duration="{Math.max(6, overflow / 6 + 4)}s">
      <span class="t-name" bind:offsetWidth={nameWidth}>{name}</span>
    </span>
  {/if}
  <span class="t-shine"></span>
  {#if stage === 'champion'}
    <span class="t-spark spark-one"></span>
    <span class="t-spark spark-two"></span>
  {/if}
</span>

<style>
  .cup-trophy {
    position: relative;
    isolation: isolate;
    display: grid;
    place-items: center;
    flex: none;
    width: var(--t-size);
    height: var(--t-size);
    pointer-events: none;
  }
  svg {
    position: relative;
    z-index: 2;
    font-family: var(--font-display, inherit);
    filter: drop-shadow(0 1px 2px color-mix(in srgb, var(--t-base) 35%, transparent));
  }
  /* 컵만: 잔이 가운데로 내려오니 광택 자리도 따라 내린다. */
  .cup-only .t-shine {
    inset: 18% 18% 22%;
  }
  .t-plate {
    position: absolute;
    z-index: 3;
    display: flex;
    align-items: center;
    justify-content: center;
    overflow: hidden;
    font-weight: 800;
    line-height: 1;
    letter-spacing: 0.02em;
    white-space: nowrap;
  }
  .t-plate.scrolling {
    justify-content: flex-start;
  }
  .t-name {
    display: inline-block;
    width: max-content;
  }
  .t-plate.scrolling .t-name {
    animation: t-name-scroll var(--name-duration) linear infinite;
  }
  .cup-trophy[data-visible='false'] .t-name {
    animation-play-state: paused;
  }
  @keyframes t-name-scroll {
    0%,
    15% {
      transform: translateX(0);
    }
    85%,
    100% {
      transform: translateX(var(--name-offset));
    }
  }
  .t-halo {
    position: absolute;
    inset: -10% -10% 20%;
    border-radius: 50%;
    background: radial-gradient(
      circle,
      color-mix(in srgb, var(--t-base) 26%, transparent),
      color-mix(in srgb, var(--t-base) 8%, transparent) 62%,
      transparent 76%
    );
    opacity: 0.7;
  }
  [data-trophy='champion'] .t-halo {
    animation: t-breathe 6s ease-in-out infinite;
  }
  /* 광택은 잔(위쪽 70%)에만 지나간다. */
  .t-shine {
    position: absolute;
    z-index: 3;
    inset: 6% 18% 32%;
    overflow: hidden;
    clip-path: polygon(0 0, 100% 0, 88% 100%, 12% 100%);
  }
  .t-shine::after {
    content: '';
    position: absolute;
    inset: 0;
    background: linear-gradient(110deg, transparent 36%, color-mix(in srgb, var(--t-mark) 60%, transparent) 48%, transparent 62%);
    opacity: 0;
    transform: translateX(-120%);
    animation: t-polish 8.5s ease-in-out infinite;
  }
  [data-trophy='runnerup'] .t-shine::after {
    animation-delay: -3s;
  }
  [data-trophy='sf'] .t-shine::after {
    animation-duration: 9.5s;
    animation-delay: -6s;
  }
  .t-spark {
    position: absolute;
    z-index: 4;
    width: 16%;
    height: 16%;
    background: var(--t-light);
    clip-path: polygon(50% 0, 62% 38%, 100% 50%, 62% 62%, 50% 100%, 38% 62%, 0 50%, 38% 38%);
    opacity: 0.2;
    animation: t-spark 7s ease-in-out infinite;
  }
  .spark-one {
    top: 0;
    right: 2%;
  }
  .spark-two {
    top: 30%;
    left: 0;
    width: 12%;
    height: 12%;
    animation-delay: -3.5s;
  }
  .cup-trophy[data-visible='false'] .t-halo,
  .cup-trophy[data-visible='false'] .t-shine::after,
  .cup-trophy[data-visible='false'] .t-spark {
    animation-play-state: paused;
  }
  @keyframes t-polish {
    0%,
    62% {
      opacity: 0;
      transform: translateX(-120%);
    }
    68% {
      opacity: 0.75;
    }
    82% {
      opacity: 0.75;
      transform: translateX(120%);
    }
    87%,
    100% {
      opacity: 0;
      transform: translateX(120%);
    }
  }
  @keyframes t-breathe {
    0%,
    100% {
      opacity: 0.5;
      transform: scale(0.92);
    }
    50% {
      opacity: 0.95;
      transform: scale(1);
    }
  }
  @keyframes t-spark {
    0%,
    55%,
    100% {
      opacity: 0.15;
      transform: scale(0.7);
    }
    68% {
      opacity: 0.95;
      transform: scale(1.1);
    }
    82% {
      opacity: 0.2;
      transform: scale(0.8);
    }
  }
  @media (prefers-reduced-motion: reduce) {
    .t-halo,
    .t-shine::after,
    .t-spark {
      animation: none;
    }
    .t-shine {
      display: none;
    }
    .t-plate.scrolling .t-name {
      animation: none;
    }
    .t-plate.scrolling {
      text-overflow: ellipsis;
    }
    .t-spark {
      opacity: 0.4;
    }
  }
</style>
