// apps/mobile/src/components/TitleBadge.tsx
// T-11-150 대표 칭호 알약(웹 cup/TitleBadge.svelte) — 컵 트로피와 '제3회 챔피언'. 금·은·동 색은 트로피 팔레트를 따른다.
// 보통(md), 댓글 · 채팅 닉네임 옆은 작게(sm), 줄이 좁은 랭킹은 트로피만(icon — 이름은 접근성 글자로). 목록에 여러 개 그려지는
// sm · icon은 움직이지 않는 그림(TrophyArt)을 쓴다.
import Svg, { Path } from 'react-native-svg';
import { useColors } from '../theme/useColors';
import { View } from 'react-native';
import { cupTrophy } from '@offside/app-core/cupTrophy';
import {
  parseTitle,
  titleLabel,
  titleIconPath,
  titleGradeColor,
  titleGradeLabel,
  permanentTitleOf,
} from '@offside/app-core/ownerTitle';
import { ownerProfileText as L } from '@offside/app-core/i18n/ko/ownerProfile';
import { alpha } from '../theme/colors';
import { rem } from '../theme/type';
import { CupTrophy, TrophyArt } from '../ui/CupTrophy';
import { Txt } from '../ui/Txt';

export function TitleBadge({ title, size = 'md' }: { title: string; size?: 'md' | 'sm' | 'icon' }) {
  const c = useColors();
  const t = parseTitle(title);
  const grade = permanentTitleOf(title)?.grade;
  const label = titleLabel(title);
  if (!label) return null;
  const palette = t
    ? cupTrophy(t.stage).palette
    : { base: titleGradeColor(title), light: titleGradeColor(title) };
  const icon = size === 'icon';
  return (
    <View
      testID={`title-badge-${title}`}
      accessible
      accessibilityRole="image"
      accessibilityLabel={L.titleAria({
        title: grade ? `${titleGradeLabel(grade)} · ${label}` : label,
      })}
      style={{
        flexDirection: 'row',
        alignItems: 'center',
        gap: size === 'md' ? 4 : 2,
        ...(icon
          ? {}
          : {
              paddingVertical: size === 'md' ? 2 : 0,
              paddingLeft: size === 'md' ? 4 : 2,
              paddingRight: size === 'md' ? 10 : 7,
              borderRadius: 999,
              borderWidth: 1,
              borderColor: palette.base,
              backgroundColor: alpha(palette.light, 0.3),
            }),
      }}
    >
      {!t ? (
        <Svg width={size === 'md' ? 22 : 16} height={size === 'md' ? 22 : 16} viewBox="0 0 16 16">
          <Path d={titleIconPath(title)} fill={c.ink} />
        </Svg>
      ) : size === 'md' ? (
        <CupTrophy stage={t.stage} size={22} />
      ) : (
        <TrophyArt stage={t.stage} size={16} />
      )}
      {icon ? null : (
        <Txt bold numberOfLines={1} style={{ fontSize: rem(size === 'md' ? 0.75 : 0.75) }}>
          {label}
        </Txt>
      )}
    </View>
  );
}

// apps/web/src/ui/cup/TitleBadge.svelte
<script lang="ts">
  // T-11-150 대표 칭호 알약 — 컵 트로피와 '제3회 챔피언'. 금·은·동 색은 트로피 팔레트를 따른다. 팀 프로필 · 구단주 프로필은
  // 보통(md), 댓글 · 채팅 닉네임 옆은 작게(sm), 줄이 좁은 랭킹은 트로피만(icon — 이름은 툴팁 · 스크린 리더로).
  // 목록에 여러 개 그려지는 sm · icon은 움직이지 않는 그림(TrophyArt)만.
  import { cupTrophy } from '@offside/app-core/cupTrophy';
  import { parseTitle, titleLabel, titleIconPath, titleGradeColor, titleGradeLabel, permanentTitleOf } from '@offside/app-core/ownerTitle';
  import { ownerProfileText as L } from '@offside/app-core/i18n/ko/ownerProfile';
  import CupTrophy from './CupTrophy.svelte';
  import TrophyArt from './TrophyArt.svelte';

  const { title, size = 'md' }: { title: string; size?: 'md' | 'sm' | 'icon' } = $props();
  const t = $derived(parseTitle(title));
  const grade = $derived(permanentTitleOf(title)?.grade);
  const label = $derived(titleLabel(title));
</script>

{#if label}
  {@const palette = t ? cupTrophy(t.stage).palette : { base: titleGradeColor(title), light: titleGradeColor(title) }}
  <span class="title-badge" class:small={size === 'sm'} class:icon={size === 'icon'} data-title={title} role="img" aria-label={L.titleAria({ title: grade ? `${titleGradeLabel(grade)} · ${label}` : label })} title={label} style={`--tb-base:${palette.base};--tb-light:${palette.light}`}>
    {#if !t}<svg width={size === 'md' ? 22 : 16} height={size === 'md' ? 22 : 16} viewBox="0 0 16 16" fill="currentColor" shape-rendering="crispEdges" aria-hidden="true"><path d={titleIconPath(title)} /></svg>{:else if size === 'md'}<CupTrophy stage={t.stage} size={22} />{:else}<TrophyArt stage={t.stage} size={16} />{/if}
    {#if size !== 'icon'}<span aria-hidden="true">{label}</span>{/if}
  </span>
{/if}

<style>
  .title-badge {
    display: inline-flex;
    align-items: center;
    gap: 4px;
    padding: 2px 10px 2px 4px;
    border-radius: 999px;
    font-size: var(--fs-xs, 12px);
    font-weight: 800;
    color: var(--ink);
    white-space: nowrap;
    background: color-mix(in srgb, var(--tb-light) 30%, var(--surface-2));
    box-shadow: inset 0 0 0 1px color-mix(in srgb, var(--tb-base) 55%, transparent);
    vertical-align: middle;
  }
  .title-badge :global(svg) {
    flex: none;
    font-family: var(--font-display, inherit);
  }
  .title-badge.small {
    gap: 2px;
    padding: 0 7px 0 2px;
    font-size: 12px;
  }
  .title-badge.icon {
    padding: 0;
    background: none;
    box-shadow: none;
    flex: none;
  }
</style>
