// apps/web/src/ui/admin/AdminCupPredictions.svelte
<script lang="ts">
  import { onMount } from 'svelte';
  import { createCupAdmin, emptyCupAdmin } from '@offside/app-core/admin/cupPredictions';
  import { cupText as L } from '@offside/app-core/i18n/ko/cup';
  import { kstDateTime as kst } from '@offside/app-core/boardText';
  import { predictionPercentages } from '@offside/app-core/cupPredictions';
  import { roundLabel } from '../cup/cupView';
  import { toast } from '../helpers';
  let { cups }: {cups: import('@offside/app-core/api/admin').AdminCup[]}=$props();
  let s=$state(emptyCupAdmin());
  const model=createCupAdmin(v=>s=v);
  let reason=$state('');
  const seasons=$derived([...new Set(s.cups.map(x=>x.cup.season))]);
  const active=$derived(s.report?.items.find(x=>x.match.id===s.matchId));
  onMount(()=>{void model.load(cups); return ()=>model.dispose();});
  async function recover(){
    if(!confirm(L.adminRecoverConfirm))return;
    if(await model.recover(reason)){reason='';toast(L.adminRecovered);}
  }
</script>
<section class="pred-admin stack" data-admin="cup-predictions">
  <h2>{L.adminPredictionTitle}</h2>
  <p class="muted fs-sm">{L.adminPredictionNote}</p>
  <div class="filters">
    <label>{L.adminSeason}<select value={s.season} disabled={s.busy} onchange={e=>model.season(Number(e.currentTarget.value))}>{#each seasons as n (n)}<option value={n}>{n}</option>{/each}</select></label>
    <label>{L.adminCompetition}<select value={s.cupId} disabled={s.busy} onchange={e=>model.select(e.currentTarget.value)}>{#each s.cups.filter(x=>x.cup.season===s.season) as x (x.cup.id)}<option value={x.cup.id}>{L.edition({n:x.cup.edition})}</option>{/each}</select></label>
    <button class="btn" disabled={s.loading||s.busy} onclick={()=>model.refresh()}>{L.adminRefresh}</button>
  </div>
  {#if s.error}<p role="alert">{s.error}</p>{/if}
  {#if s.loading}<p role="status">{L.loading}</p>
  {:else if s.report}
    <div class="summary"><span>{L.adminPeople} <b>{s.report.participants}</b></span>{#each [['total',L.adminTotal],['hits',L.adminHits],['granted',L.adminGranted]] as [key,label] (key)}<span>{label} <b>{s.report.items.reduce((n,x)=>n+x[key as 'total'|'hits'|'granted'],0)}</b></span>{/each}</div>
    {#each s.report.items as x (x.match.id)}
      {@const m=x.match}
      {@const pct=predictionPercentages({...x,matchId:m.id})}
      <article class="match" data-admin-match={m.id}>
        <div class="row"><span class="muted fs-xs">{roundLabel(m.round)} {m.group?L.groupName({no:m.group}):''} · {kst(m.at)}</span></div>
        <div class="admin-score-row"><b>{x.homeName||L.tbd}</b><div class="admin-score-center"><span class="pill" class:good={m.played} class:cup-upcoming={!m.played && m.at > new Date().toISOString()} class:warn={!m.played && m.at <= new Date().toISOString()}>{m.played?L.matchFinished:m.at<=new Date().toISOString()?L.matchProcessing:L.matchScheduled}</span><b>{m.played?`${m.homeGoals} : ${m.awayGoals}`:'vs'}</b></div><b>{x.awayName||L.tbd}</b></div>
        <div class="shares"><span>{L.predictionHome} {pct.home}%</span>{#if m.round.startsWith('g')}<span>{L.predictionDraw} {pct.draw}%</span>{/if}<span>{L.predictionAway} {pct.away}%</span></div>
        <p class="muted fs-xs">{L.adminTotal} {x.total} · {L.adminHits} {x.hits} · {L.adminGranted} {x.granted}{#if m.played} · {L.adminPending} {x.pending} · {L.adminUnpaid} {x.unpaid}{/if}</p>
        <button class="btn" disabled={s.busy} onclick={()=>{reason='';void model.details(m.id);}}>{L.adminDetails}</button>
        {#if s.matchId===m.id}
          <div class="detail" data-admin-prediction-detail>
            <button class="btn" disabled={s.busy} onclick={model.close}>{L.adminClose}</button>
            {#if s.detailLoading}<p role="status">{L.loading}</p>{/if}
            {#if s.rows && !s.rows.items.length}<p class="muted">{L.predictionEmpty}</p>{/if}
            {#each s.rows?.items??[] as r (r.profileId)}
              <div class="person"><b>{r.nickname}</b><small>{r.profileId}</small><span>{r.pick==='home'?L.predictionHome:r.pick==='away'?L.predictionAway:L.predictionDraw} · {r.correct===null?(m.played?L.adminPending:L.predictionSelected):r.correct?L.predictionHit:L.predictionMiss}{r.rewardedAt?` · ${L.predictionRewarded}`:r.correct?` · ${L.adminUnpaid}`:''}</span><small class="muted">{kst(r.updatedAt)}</small></div>
            {/each}
            {#if s.rows?.next}<button class="btn" disabled={s.detailLoading||s.busy} onclick={()=>model.details(m.id,true)}>{L.adminMore}</button>{/if}
            {#if active?.match.played}
              <label>{L.adminReason}<textarea maxlength="200" bind:value={reason} disabled={s.busy}></textarea></label>
              <button class="btn" disabled={s.busy||reason.trim().length<5||!(x.pending+x.unpaid)} onclick={recover}>{s.busy?L.loading:L.adminRecover}</button>
            {/if}
          </div>
        {/if}
      </article>
    {/each}
  {:else}<p>{L.adminNoCups}</p>{/if}
</section>
<style>
  .admin-score-row{display:grid;grid-template-columns:minmax(0,1fr) auto minmax(0,1fr);gap:8px;align-items:center}.admin-score-row>b:first-child{text-align:right}.admin-score-row>b{overflow-wrap:anywhere}.admin-score-center{display:flex;flex-direction:column;align-items:center;gap:4px}.admin-score-center .pill{white-space:nowrap}
  h2,p{margin:0}.pred-admin{gap:12px;margin-top:20px;min-width:0}.filters{display:flex;flex-wrap:wrap;align-items:end;gap:8px}.filters label{flex:1;min-width:100px}label{display:flex;flex-direction:column;gap:6px;font-size:13px}select,textarea{min-height:44px;width:100%;min-width:0}textarea{resize:vertical}.summary,.shares{display:flex;flex-wrap:wrap;gap:8px 16px}.summary{padding:12px;border:1px solid var(--line);border-radius:12px}.match{display:flex;flex-direction:column;gap:10px;border-top:1px solid var(--line);padding:14px 0;min-width:0}.match>.row{flex-wrap:wrap}.person{overflow-wrap:anywhere}.detail{display:flex;flex-direction:column;gap:12px;border-left:2px solid var(--accent);padding-left:12px}.person{display:flex;flex-direction:column;gap:4px;padding:8px 0;border-bottom:1px solid var(--line)}.btn{min-height:44px}
</style>

// apps/mobile/src/screens/settings/admin/AdminCupPredictions.tsx
import CupMatchStatus from '../../owner/CupMatchStatus';
import { useEffect, useMemo, useState } from 'react';
import { View } from 'react-native';
import { createCupAdmin, emptyCupAdmin } from '@offside/app-core/admin/cupPredictions';
import { cupText as L } from '@offside/app-core/i18n/ko/cup';
import { kstDateTime as kst } from '@offside/app-core/boardText';
import { predictionPercentages } from '@offside/app-core/cupPredictions';
import { roundLabel } from '../../owner/cupText';
import { Btn } from '../../../ui/Btn';
import { Txt } from '../../../ui/Txt';
import { useColors } from '../../../theme/useColors';
import { TextBox, confirmAsync } from '../../board/parts';

export default function AdminCupPredictions() {
  const [s, setS] = useState(emptyCupAdmin);
  const [reason, setReason] = useState('');
  const model = useMemo(() => createCupAdmin(setS), []);
  const c = useColors();
  useEffect(() => {
    void model.load();
    return model.dispose;
  }, [model]);
  const seasons = [...new Set(s.cups.map((x) => x.cup.season))];
  async function recover() {
    if (!(await confirmAsync(L.adminRecover, L.adminRecoverConfirm))) return;
    if (await model.recover(reason)) setReason('');
  }
  return (
    <View style={{ gap: 12 }}>
      <Txt v="h2">{L.adminPredictionTitle}</Txt>
      <Txt v="sm" tone="muted">
        {L.adminPredictionNote}
      </Txt>
      <Txt>{L.adminSeason}</Txt>
      <View style={{ flexDirection: 'row', flexWrap: 'wrap', gap: 8 }}>
        {seasons.map((n) => (
          <Btn
            key={n}
            disabled={s.busy}
            kind={s.season === n ? 'accent' : 'default'}
            onPress={() => void model.season(n)}
          >
            {n}
          </Btn>
        ))}
      </View>
      <Txt>{L.adminCompetition}</Txt>
      <View style={{ flexDirection: 'row', flexWrap: 'wrap', gap: 8 }}>
        {s.cups
          .filter((x) => x.cup.season === s.season)
          .map((x) => (
            <Btn
              key={x.cup.id}
              disabled={s.busy}
              kind={s.cupId === x.cup.id ? 'accent' : 'default'}
              onPress={() => void model.select(x.cup.id)}
            >
              {L.edition({ n: x.cup.edition })}
            </Btn>
          ))}
      </View>
      <Btn disabled={s.loading || s.busy} onPress={() => void model.refresh()}>
        {L.adminRefresh}
      </Btn>
      {s.error ? <Txt accessibilityRole="alert">{s.error}</Txt> : null}
      {s.loading ? (
        <Txt>{L.loading}</Txt>
      ) : s.report ? (
        <>
          <Txt>
            {L.adminPeople} {s.report.participants} · {L.adminTotal}{' '}
            {s.report.items.reduce((n, x) => n + x.total, 0)}
          </Txt>
          {s.report.items.map((x) => {
            const m = x.match;
            const pct = predictionPercentages({ ...x, matchId: m.id });
            return (
              <View
                key={m.id}
                style={{ gap: 10, borderTopWidth: 1, borderColor: c.line, paddingVertical: 14 }}
              >
                <Txt v="xs" tone="muted">
                  {roundLabel(m.round)} {m.group ? L.groupName({ no: m.group }) : ''} · {kst(m.at)}
                </Txt>
                <View style={{ flexDirection: 'row', alignItems: 'center', gap: 8 }}>
                  <Txt bold style={{ flex: 1, textAlign: 'right' }}>
                    {x.homeName || L.tbd}
                  </Txt>
                  <View style={{ alignItems: 'center', gap: 4 }}>
                    <CupMatchStatus m={m} />
                    <Txt bold>{m.played ? `${m.homeGoals} : ${m.awayGoals}` : 'vs'}</Txt>
                  </View>
                  <Txt bold style={{ flex: 1 }}>
                    {x.awayName || L.tbd}
                  </Txt>
                </View>
                <Txt v="sm">
                  {L.predictionHome} {pct.home}% ·{' '}
                  {m.round.startsWith('g') ? `${L.predictionDraw} ${pct.draw}% · ` : ''}
                  {L.predictionAway} {pct.away}%
                </Txt>
                <Txt v="xs" tone="muted">
                  {L.adminTotal} {x.total} · {L.adminHits} {x.hits} · {L.adminGranted} {x.granted}
                  {m.played
                    ? ` · ${L.adminPending} ${x.pending} · ${L.adminUnpaid} ${x.unpaid}`
                    : ''}
                </Txt>
                <Btn
                  disabled={s.busy}
                  onPress={() => {
                    setReason('');
                    void model.details(m.id);
                  }}
                >
                  {L.adminDetails}
                </Btn>
                {s.matchId === m.id ? (
                  <View
                    style={{ gap: 12, borderLeftWidth: 2, borderColor: c.accent, paddingLeft: 12 }}
                  >
                    <Btn disabled={s.busy} onPress={model.close}>
                      {L.adminClose}
                    </Btn>
                    {s.detailLoading ? <Txt>{L.loading}</Txt> : null}
                    {(s.rows?.items ?? []).map((r) => (
                      <View key={r.profileId} style={{ gap: 4 }}>
                        <Txt bold>{r.nickname}</Txt>
                        <Txt v="xs">{r.profileId}</Txt>
                        <Txt v="sm">
                          {r.pick === 'home'
                            ? L.predictionHome
                            : r.pick === 'away'
                              ? L.predictionAway
                              : L.predictionDraw}{' '}
                          ·{' '}
                          {r.correct === null
                            ? m.played
                              ? L.adminPending
                              : L.predictionSelected
                            : r.correct
                              ? L.predictionHit
                              : L.predictionMiss}
                          {r.rewardedAt
                            ? ` · ${L.predictionRewarded}`
                            : r.correct
                              ? ` · ${L.adminUnpaid}`
                              : ''}
                        </Txt>
                        <Txt v="xs" tone="muted">
                          {kst(r.updatedAt)}
                        </Txt>
                      </View>
                    ))}
                    {s.rows?.next ? (
                      <Btn
                        disabled={s.detailLoading || s.busy}
                        onPress={() => void model.details(m.id, true)}
                      >
                        {L.adminMore}
                      </Btn>
                    ) : null}
                    {m.played ? (
                      <>
                        <Txt v="sm">{L.adminReason}</Txt>
                        <TextBox
                          accessibilityLabel={L.adminReason}
                          value={reason}
                          onChangeText={setReason}
                          maxLength={200}
                          editable={!s.busy}
                        />
                        <Btn
                          disabled={s.busy || reason.trim().length < 5 || !(x.pending + x.unpaid)}
                          onPress={() => void recover()}
                        >
                          {s.busy ? L.loading : L.adminRecover}
                        </Btn>
                      </>
                    ) : null}
                  </View>
                ) : null}
              </View>
            );
          })}
        </>
      ) : (
        <Txt>{L.adminNoCups}</Txt>
      )}
    </View>
  );
}
