// apps/mobile/src/screens/game/LeagueTable.tsx
// 선수가 뛰는 리그의 순위표(웹 tabs/LeagueTable.svelte, T-10-024). 기본은 상위 3팀 + 내 팀 앞뒤 2팀 + 꼴찌만 접어서 보여
// 주고, '전체 순위'로 모두 펼친다. 접힌 구간은 '⋯' 줄 하나로 표시한다. T-11-024 시즌 탭의 시즌 현황 카드 안에 들어가는
// 한 묶음이라 카드 테두리 없이 작은 제목을 단다. 칸은 순위·팀·경기·승점만(승·무·패는 리포트·시즌 누적 줄에 있다).
import { useState } from 'react';
import { View } from 'react-native';
import { leagueOf, leagueTable } from '@offside/game/engine';
import type { GameState } from '@offside/game/types';
import { alpha } from '../../theme/colors';
import { useColors } from '../../theme/useColors';
import { DISPLAY, rem } from '../../theme/type';
import { Btn } from '../../ui/Btn';
import { ClubBadge } from '../../ui/ClubBadge';
import { Txt } from '../../ui/Txt';

type Row = ReturnType<typeof leagueTable>[number];
type Shown = { gap: true; key: string } | { gap: false; key: string; rank: number; r: Row };

const COL = 32;

export function LeagueTable({ s }: { s: GameState }) {
  const c = useColors();
  const [full, setFull] = useState(false);
  const rows = leagueTable(s);
  const myRank = rows.findIndex((r) => r.me) + 1;
  const keep = (rank: number) => rank <= 3 || Math.abs(rank - myRank) <= 2 || rank === rows.length;
  const shown: Shown[] = [];
  rows.forEach((r, i) => {
    const rank = i + 1;
    // 구단 이름은 유저가 겹치게 바꿀 수 있다(T-10-034) — 키는 순위로 잡는다.
    if (full || keep(rank)) shown.push({ gap: false, key: `row-${rank}`, rank, r });
    else if (!shown.at(-1)?.gap) shown.push({ gap: true, key: `gap-${rank}` });
  });
  const folded = shown.some((x) => x.gap);

  const head = (t: string, team = false) => (
    <Txt
      key={t}
      tone="muted"
      style={[
        { fontSize: rem(0.6875), fontWeight: '600', textAlign: team ? 'left' : 'center' },
        team ? { flex: 1, paddingLeft: 6 } : { width: COL },
      ]}
    >
      {t}
    </Txt>
  );
  return (
    <View testID="league-table" style={{ gap: 10 }}>
      <View
        style={{ flexDirection: 'row', justifyContent: 'space-between', alignItems: 'baseline' }}
      >
        <SubTitle>{`${leagueOf(s.leagueId).name} 순위`}</SubTitle>
        {s.season.played && (folded || full) ? (
          <Btn
            sm
            testID="table-toggle"
            accessibilityLabel={full ? '순위표 접기' : '전체 순위 보기'}
            onPress={() => setFull(!full)}
          >
            {full ? '접기' : '전체 순위'}
          </Btn>
        ) : null}
      </View>
      {s.season.played ? (
        <View>
          <View
            style={{
              flexDirection: 'row',
              alignItems: 'center',
              paddingVertical: 4,
              paddingHorizontal: 2,
              borderBottomWidth: 1,
              borderBottomColor: c.line,
            }}
          >
            {head('#')}
            {head('팀', true)}
            {['경기', '승점'].map((t) => head(t))}
          </View>
          {shown.map((x) =>
            x.gap ? (
              <View
                key={x.key}
                accessibilityElementsHidden
                importantForAccessibility="no-hide-descendants"
                style={{
                  padding: 2,
                  alignItems: 'center',
                  borderBottomWidth: 1,
                  borderBottomColor: c.line,
                }}
              >
                <Txt tone="muted" style={{ lineHeight: rem(1) }}>
                  ⋯
                </Txt>
              </View>
            ) : (
              <View
                key={x.key}
                accessible
                accessibilityLabel={`${x.rank}위 ${x.r.name} ${x.r.p}경기 ${x.r.w}승 ${x.r.d}무 ${x.r.l}패 승점 ${x.r.pts}${x.r.me ? ', 내 팀' : ''}`}
                style={[
                  {
                    flexDirection: 'row',
                    alignItems: 'center',
                    paddingVertical: 7,
                    paddingHorizontal: 2,
                    borderBottomWidth: 1,
                    borderBottomColor: c.line,
                  },
                  x.r.me && {
                    backgroundColor: alpha(c.pitch, 0.1),
                    borderLeftWidth: 3,
                    borderLeftColor: c.accent,
                  },
                ]}
              >
                <Cell bold={x.r.me || x.rank === 1} color={x.rank === 1 ? c.accentText : undefined}>
                  {x.rank}
                </Cell>
                <View
                  style={{
                    flex: 1,
                    minWidth: 0,
                    flexDirection: 'row',
                    alignItems: 'center',
                    gap: 4,
                    paddingLeft: 6,
                  }}
                >
                  {x.r.id ? <ClubBadge club={{ id: x.r.id, name: x.r.name }} size={16} /> : null}
                  <Txt
                    numberOfLines={1}
                    style={{
                      flex: 1,
                      fontSize: rem(0.8125),
                      fontWeight: x.r.me ? '700' : '400',
                    }}
                  >
                    {x.r.name}
                  </Txt>
                </View>
                <Cell bold={x.r.me}>{x.r.p}</Cell>
                <Cell bold={x.r.me}>{x.r.w}</Cell>
                <Cell bold={x.r.me}>{x.r.d}</Cell>
                <Cell bold={x.r.me}>{x.r.l}</Cell>
                <Cell bold>{x.r.pts}</Cell>
              </View>
            ),
          )}
        </View>
      ) : (
        <Txt tone="muted" style={{ fontSize: rem(0.8125) }}>
          {`개막하면 ${rows.length}개 팀 순위표가 채워져요.`}
        </Txt>
      )}
    </View>
  );
}

/** 카드 안 작은 묶음 제목(웹 .sub-title). */
export function SubTitle({ children }: { children: string }) {
  return (
    <Txt accessibilityRole="header" style={{ fontSize: rem(0.9375), fontWeight: '700' }}>
      {children}
    </Txt>
  );
}

/** 표 숫자 칸(웹 td.num — 숫자 서체 0.9375rem, 가운데 정렬. 굵기는 행이 정한다). */
function Cell({
  children,
  bold,
  color,
}: {
  children: number;
  bold?: boolean | undefined;
  color?: string | undefined;
}) {
  return (
    <Txt
      style={[
        {
          width: COL,
          textAlign: 'center',
          fontFamily: bold ? DISPLAY[700] : DISPLAY[400],
          fontSize: rem(0.9375),
          fontVariant: ['tabular-nums'],
        },
        color ? { color } : null,
      ]}
    >
      {children}
    </Txt>
  );
}

// apps/web/src/ui/tabs/LeagueTable.svelte
<script lang="ts">
  // T-10-024: 선수가 뛰는 리그의 순위표. 기본은 상위 3팀 + 내 팀 앞뒤 2팀 + 꼴찌만 접어서 보여 주고,
  // '전체 순위'로 모두 펼친다. T-11-024 시즌 탭의 시즌 현황 카드 안에 들어가는 한 묶음이라 카드 테두리 없이 작은 제목을 단다. 칸은 순위·팀·경기·승점만(승·무·패는 리포트·시즌 누적 줄에 있다).
  import { leagueOf, leagueTable } from '@offside/game/engine';
  import type { GameState } from '@offside/game/types';
  import ClubBadge from '../ClubBadge.svelte';

  const { s }: { s: GameState } = $props();
  let full = $state(false);

  const rows = $derived(leagueTable(s));
  const myRank = $derived(rows.findIndex((r) => r.me) + 1);
  const keep = (rank: number) => rank <= 3 || Math.abs(rank - myRank) <= 2 || rank === rows.length;
  // 접힌 구간은 '⋯' 줄 하나로 표시한다.
  const shown = $derived.by(() => {
    const out: ({ gap: true; key: string } | { gap: false; key: string; rank: number; r: (typeof rows)[number] })[] = [];
    rows.forEach((r, i) => {
      const rank = i + 1;
      if (full || keep(rank)) out.push({ gap: false, key: `row-${rank}`, rank, r }); // 구단 이름은 유저가 겹치게 바꿀 수 있다(T-10-034).
      else if (!out.at(-1)?.gap) out.push({ gap: true, key: `gap-${rank}` });
    });
    return out;
  });
  const folded = $derived(shown.some((x) => x.gap));
</script>

<div class="league-table" data-league-table>
  <div class="row" style="justify-content:space-between;align-items:baseline">
    <h3 class="sub-title">{leagueOf(s.leagueId).name} 순위</h3>
    {#if s.season.played && (folded || full)}
      <button class="icon-btn" data-act="table-toggle" aria-expanded={full} onclick={() => (full = !full)}>{full ? '접기' : '전체 순위'}</button>
    {/if}
  </div>
  {#if s.season.played}
    <table>
      <thead>
        <tr><th scope="col">#</th><th scope="col" class="lt-team">팀</th><th scope="col">경기</th><th scope="col">승점</th></tr>
      </thead>
      <tbody>
        {#each shown as x (x.key)}
          {#if x.gap}
            <tr class="lt-gap" aria-hidden="true"><td colspan="4">⋯</td></tr>
          {:else}
            <tr class:me={x.r.me} class:top={x.rank === 1} aria-current={x.r.me ? 'true' : undefined}>
              <td class="num">{x.rank}</td>
              <td class="lt-team">{#if x.r.id}<ClubBadge club={{ id: x.r.id, name: x.r.name }} size={16} /> {/if}{x.r.name}</td>
              <td class="num">{x.r.p}</td>
              <td class="num lt-pts">{x.r.pts}</td>
            </tr>
          {/if}
        {/each}
      </tbody>
    </table>
  {:else}
    <p class="muted fs-sm">개막하면 {rows.length}개 팀 순위표가 채워져요.</p>
  {/if}
</div>
