// apps/mobile/src/screens/settings/Admin.tsx
// T-10-016 운영 도구(관리자 전용, 웹 Admin.svelte). 관리자 여부는 서버가 요청마다 다시 확인한다 — 여기서는 화면만 가린다.
import { useEffect, useState } from 'react';
import { View } from 'react-native';
import { fetchBoardViewer } from '@offside/app-core/api/boards';
import { appState } from '../../store';
import { BackBar } from '../../ui/ActionBar';
import { Card } from '../../ui/Card';
import { Screen } from '../../ui/Screen';
import { Topbar } from '../../ui/Topbar';
import { Txt } from '../../ui/Txt';
import { Seg, TabOpt } from '../board/parts';
import AdminAutomation from './admin/AdminAutomation';
import AdminBalance from './admin/AdminBalance';
import AdminComments from './admin/AdminComments';
import AdminChatReports from './admin/AdminChatReports';
import AdminNameReports from './admin/AdminNameReports';
import AdminDashboard from './admin/AdminDashboard';

const TABS = [
  { id: 'dashboard', label: '대시보드' },
  { id: 'comments', label: '신고·댓글' },
  { id: 'balance', label: '밸런스' },
  { id: 'automation', label: '자동 플레이' },
] as const;

export default function Admin() {
  const [tab, setTab] = useState<(typeof TABS)[number]['id']>('dashboard');
  const [admin, setAdmin] = useState<boolean | null>(null);

  useEffect(() => {
    let live = true;
    void fetchBoardViewer().then((r) => live && setAdmin(r.ok && r.data.admin));
    return () => {
      live = false;
    };
  }, []);

  return (
    <Screen footer={<BackBar testID="owner" fallback={() => (appState.screen = 'owner')} />}>
      <Topbar />
      <Card gap={14}>
        <View>
          <Txt v="eyebrow">Admin</Txt>
          <Txt v="h1" accessibilityRole="header">
            운영 도구
          </Txt>
        </View>
        {admin === null ? (
          <Txt tone="muted" accessibilityLiveRegion="polite">
            확인하는 중…
          </Txt>
        ) : !admin ? (
          <Txt tone="muted">운영자 계정으로 로그인해야 볼 수 있어요.</Txt>
        ) : (
          <>
            <Seg cols={TABS.length} label="운영 도구">
              {TABS.map((t) => (
                <TabOpt
                  key={t.id}
                  tight
                  title={t.label}
                  selected={tab === t.id}
                  testID={`admin-tab-${t.id}`}
                  onPress={() => setTab(t.id)}
                />
              ))}
            </Seg>
            {tab === 'dashboard' ? (
              <AdminDashboard />
            ) : tab === 'comments' ? (
              <>
                <AdminChatReports />
                <AdminNameReports />
                <AdminComments />
              </>
            ) : tab === 'automation' ? (
              <AdminAutomation />
            ) : (
              <AdminBalance />
            )}
          </>
        )}
      </Card>
    </Screen>
  );
}

// apps/web/src/ui/Admin.svelte
<script lang="ts">
  // T-10-016 운영 도구(관리자 전용). 게임과 무관해 메인 번들과 떼어 처음 열 때 불러온다.
  // 관리자 여부는 서버가 요청마다 다시 확인한다 — 여기서는 화면만 가린다.
  import { onMount } from 'svelte';
  import { fetchBoardViewer } from '@offside/app-core/api/boards';
  import { appState } from './state.svelte.js';
  import BackBar from './BackBar.svelte';
  import Topbar from './Topbar.svelte';
  import AdminBalance from './admin/AdminBalance.svelte';
  import AdminComments from './admin/AdminComments.svelte';
  import AdminNameReports from './admin/AdminNameReports.svelte';
  import AdminChatReports from './admin/AdminChatReports.svelte';
  import AdminDashboard from './admin/AdminDashboard.svelte';
  import AdminAutomation from './admin/AdminAutomation.svelte';

  const TABS = [
    { id: 'dashboard', label: '대시보드' },
    { id: 'comments', label: '신고·댓글' },
    { id: 'balance', label: '밸런스' },
    { id: 'automation', label: '자동 플레이' },
  ] as const;
  let tab = $state<(typeof TABS)[number]['id']>('dashboard');
  let admin = $state<boolean | null>(null);

  onMount(() => {
    void fetchBoardViewer().then((r) => (admin = r.ok && r.data.admin));
  });
</script>

<div class="wrap">
  <Topbar />
  <section class="card stack" style="gap:14px">
    <div>
      <div class="eyebrow">Admin</div>
      <h1>운영 도구</h1>
    </div>
    {#if admin === null}
      <p class="muted" aria-live="polite">확인하는 중…</p>
    {:else if !admin}
      <p class="muted">운영자 계정으로 로그인해야 볼 수 있어요.</p>
    {:else}
      <div class="seg admin-tabs" style="grid-template-columns:repeat({TABS.length},1fr)" role="group" aria-label="운영 도구">
        {#each TABS as t (t.id)}
          <button class="opt" aria-pressed={tab === t.id} data-admin-tab={t.id} onclick={() => (tab = t.id)}>{t.label}</button>
        {/each}
      </div>
      {#if tab === 'dashboard'}<AdminDashboard />
      {:else if tab === 'comments'}<AdminChatReports /><AdminNameReports /><AdminComments />
      {:else if tab === 'automation'}<AdminAutomation />
      {:else}<AdminBalance />{/if}
    {/if}
  </section>
  <BackBar act="owner" fallback={() => (appState.screen = 'owner')} />
</div>
