// apps/mobile/src/screens/owner/FundsHistory.tsx
// 구단 자금 내역(웹 FundsHistory.svelte) — 구단주 화면의 '구단 자금' 칸으로 연다. 지금 자금, 들어온·나간 자금 합(출처별),
// 그리고 방출·판매·영입·구단 자금 사용을 한국 시각 날짜로 묶어 최근 순으로 보여 준다(30줄씩 더 보기).
import { useEffect, useMemo, useState } from 'react';
import { View } from 'react-native';
import type { FundsHistoryEntry, FundsHistoryResponse } from '@offside/contracts';
import {
  fetchFundsHistory,
  fundsHistoryDays,
  fundsHistoryTotals,
} from '@offside/app-core/fundsHistory';
import { fundsText } from '@offside/app-core/market';
import { fundsHistoryText as H } from '@offside/app-core/i18n/ko/fundsHistory';
import { localCareerNames } from '@offside/game/hof-store';
import { go } from '../../game/nav';
import { DISPLAY, rem } from '../../theme/type';
import { useColors } from '../../theme/useColors';
import { BackBar, Btn, Card, Screen, Topbar, Txt } from '../../ui';
import { useRefresh } from '../../ui/refresh';

type Totals = ReturnType<typeof fundsHistoryTotals>['income'];

/** 들어온·나간 자금 칸(웹 .fh-totals div). */
function TotalBox({
  label,
  t,
  plus,
  testID,
}: {
  label: string;
  t: Totals;
  plus?: boolean;
  testID: string;
}) {
  const c = useColors();
  return (
    <View
      testID={testID}
      style={{
        flex: 1,
        minWidth: 0,
        gap: 2,
        paddingVertical: 10,
        paddingHorizontal: 12,
        borderRadius: 12,
        backgroundColor: c.surface2,
      }}
    >
      <Txt tone="muted" style={{ fontSize: rem(0.75) }}>
        {label}
      </Txt>
      <Txt
        tone={plus ? 'good' : 'ink'}
        style={{ fontFamily: DISPLAY[700], fontSize: rem(1.125), fontVariant: ['tabular-nums'] }}
      >
        {t.total}
      </Txt>
      {t.lines.map((l) => (
        <Txt key={l.label} tone="muted" style={{ fontSize: rem(0.8125) }}>
          {`${l.label} ${l.value}`}
        </Txt>
      ))}
    </View>
  );
}

export default function FundsHistory() {
  const c = useColors();
  const local = useMemo(() => localCareerNames(), []);
  const [res, setRes] = useState<FundsHistoryResponse | null>(null);
  const [items, setItems] = useState<FundsHistoryEntry[]>([]);
  const [page, setPage] = useState(0);
  const [failed, setFailed] = useState(false);
  const [loading, setLoading] = useState(false);
  const [retryN, setRetryN] = useState(0);
  const { tick, track } = useRefresh();

  async function load(next: number) {
    setLoading(true);
    setFailed(false);
    const r = await track(fetchFundsHistory(next));
    setLoading(false);
    if (!r.ok) return setFailed(true);
    setRes(r.data);
    setItems((prev) => (next === 0 ? r.data.items : [...prev, ...r.data.items]));
    setPage(next);
  }

  useEffect(() => {
    void load(0);
  }, [tick, retryN]);

  const days = useMemo(() => fundsHistoryDays(items, local), [items, local]);
  const totals = res ? fundsHistoryTotals(res.totals) : null;
  const badge = (kind: FundsHistoryEntry['kind']) =>
    kind === 'sold' ? c.accentText : kind === 'released' ? c.bad : c.ink;
  const small = { fontSize: rem(0.875) } as const;

  return (
    <Screen footer={<BackBar testID="funds-back" fallback={() => go('owner')} />}>
      <Topbar />
      <View style={{ gap: 2, paddingHorizontal: 4 }}>
        <Txt v="eyebrow">{H.eyebrow}</Txt>
        <Txt v="h1" accessibilityRole="header">
          {H.title}
        </Txt>
      </View>

      {failed && !res ? (
        <Card gap={10}>
          <Txt tone="muted">{H.loadFail}</Txt>
          <Btn sm onPress={() => setRetryN((n) => n + 1)}>
            {H.retry}
          </Btn>
        </Card>
      ) : !res || !totals ? (
        <Card>
          <Txt tone="muted">…</Txt>
        </Card>
      ) : (
        <>
          <Card gap={12} testID="funds-summary">
            <View style={{ gap: 2 }}>
              <Txt tone="muted" style={{ fontSize: rem(0.8125) }}>
                {H.balance}
              </Txt>
              <Txt
                testID="funds-balance"
                style={{
                  fontFamily: DISPLAY[700],
                  fontSize: rem(1.75),
                  color: c.accentText,
                  fontVariant: ['tabular-nums'],
                }}
              >
                {fundsText(res.balance)}
              </Txt>
            </View>
            <View style={{ flexDirection: 'row', gap: 8 }}>
              <TotalBox label={H.income} t={totals.income} plus testID="funds-income" />
              <TotalBox label={H.spending} t={totals.spending} testID="funds-spending" />
            </View>
          </Card>

          <View style={{ gap: 8 }} accessibilityLabel={H.log}>
            {days.length ? (
              days.map((g) => (
                <View key={g.day} style={{ gap: 8 }}>
                  <Txt
                    tone="muted"
                    bold
                    style={{ fontSize: rem(0.8125), marginTop: 6, paddingHorizontal: 4 }}
                  >
                    {g.label}
                  </Txt>
                  <View
                    style={{
                      borderWidth: 1,
                      borderColor: c.line,
                      borderRadius: 14,
                      backgroundColor: c.surface,
                    }}
                  >
                    {g.rows.map((r, i) => (
                      <View
                        key={r.id}
                        testID={`funds-row-${r.kind}`}
                        style={{
                          flexDirection: 'row',
                          alignItems: 'center',
                          gap: 10,
                          paddingVertical: 10,
                          paddingHorizontal: 12,
                          borderTopWidth: i ? 1 : 0,
                          borderTopColor: c.line,
                        }}
                      >
                        <View
                          style={{
                            minWidth: 36,
                            paddingVertical: 3,
                            paddingHorizontal: 6,
                            borderRadius: 6,
                            alignItems: 'center',
                            backgroundColor: c.surface2,
                          }}
                        >
                          <Txt
                            style={{
                              fontSize: rem(0.6875),
                              fontWeight: '700',
                              color: badge(r.kind),
                            }}
                          >
                            {r.badge}
                          </Txt>
                        </View>
                        <View style={{ flex: 1, minWidth: 0, gap: 2 }}>
                          <Txt numberOfLines={1} style={small}>
                            {r.title}
                          </Txt>
                          <Txt tone="muted" style={{ fontSize: rem(0.75) }}>
                            {r.sub}
                          </Txt>
                        </View>
                        <Txt tone={r.plus ? 'good' : 'ink'} bold num style={small}>
                          {r.amount}
                        </Txt>
                      </View>
                    ))}
                  </View>
                </View>
              ))
            ) : (
              <Card>
                <Txt tone="muted" testID="funds-empty" style={small}>
                  {H.empty}
                </Txt>
              </Card>
            )}
            {res.hasMore ? (
              <Btn block testID="funds-more" disabled={loading} onPress={() => void load(page + 1)}>
                {H.more}
              </Btn>
            ) : null}
            {failed ? (
              <Txt tone="muted" style={small}>
                {H.loadFail}
              </Txt>
            ) : null}
          </View>
        </>
      )}
    </Screen>
  );
}

// apps/web/src/ui/FundsHistory.svelte
<script lang="ts">
  // 구단 자금 내역 — 구단주 화면의 '구단 자금' 칸으로 연다. 지금 자금, 들어온·나간 자금 합(출처별), 그리고 방출·판매·
  // 영입·구단 자금 사용을 한국 시각 날짜로 묶어 최근 순으로 보여 준다(30줄씩 더 보기).
  import Topbar from './Topbar.svelte';
  import BackBar from './BackBar.svelte';
  import { go } from './nav.js';
  import type { FundsHistoryEntry, FundsHistoryResponse } from '@offside/contracts';
  import { fetchFundsHistory, fundsHistoryDays, fundsHistoryTotals } from '@offside/app-core/fundsHistory';
  import { fundsText } from '@offside/app-core/market';
  import { fundsHistoryText as H } from '@offside/app-core/i18n/ko/fundsHistory';
  import { localCareerNames } from '@offside/game/hof-store';

  const local = localCareerNames();
  let res = $state<FundsHistoryResponse | null>(null);
  let items = $state<FundsHistoryEntry[]>([]);
  let page = $state(0);
  let failed = $state(false);
  let loading = $state(false);
  const days = $derived(fundsHistoryDays(items, local));
  const totals = $derived(res ? fundsHistoryTotals(res.totals) : null);

  async function load(next: number) {
    loading = true;
    failed = false;
    const r = await fetchFundsHistory(next);
    loading = false;
    if (!r.ok) return void (failed = true);
    res = r.data;
    items = next === 0 ? r.data.items : [...items, ...r.data.items];
    page = next;
  }
  void load(0);
</script>

<div class="wrap funds-history" data-funds-history>
  <Topbar />
  <header class="settings-head">
    <div class="eyebrow">{H.eyebrow}</div>
    <h1>{H.title}</h1>
  </header>

  {#if failed && !res}
    <section class="card fh-fail">
      <p class="muted">{H.loadFail}</p>
      <button class="btn" data-act="funds-retry" onclick={() => void load(0)}>{H.retry}</button>
    </section>
  {:else if !res || !totals}
    <section class="card"><p class="muted" aria-live="polite">…</p></section>
  {:else}
    <section class="card fh-sum" aria-label={H.balance}>
      <div class="fh-balance">
        <span>{H.balance}</span>
        <b data-funds-balance>{fundsText(res.balance)}</b>
      </div>
      <dl class="fh-totals">
        <div data-funds-income>
          <dt>{H.income}</dt>
          <dd class="fh-plus">{totals.income.total}</dd>
          {#each totals.income.lines as l (l.label)}<span class="muted fs-sm">{l.label} {l.value}</span>{/each}
        </div>
        <div data-funds-spending>
          <dt>{H.spending}</dt>
          <dd>{totals.spending.total}</dd>
          {#each totals.spending.lines as l (l.label)}<span class="muted fs-sm">{l.label} {l.value}</span>{/each}
        </div>
      </dl>
    </section>

    <section class="fh-log" aria-label={H.log}>
      {#each days as g (g.day)}
        <h2 class="fh-day">{g.label}</h2>
        <ul class="fh-rows">
          {#each g.rows as r (r.id)}
            <li data-funds-row={r.kind}>
              <span class="fh-badge fh-badge-{r.kind}">{r.badge}</span>
              <span class="fh-info">
                <span class="fh-title">{r.title}</span>
                <small>{r.sub}</small>
              </span>
              <b class:fh-plus={r.plus}>{r.amount}</b>
            </li>
          {/each}
        </ul>
      {:else}
        <p class="card muted fs-sm" data-funds-empty>{H.empty}</p>
      {/each}
      {#if res.hasMore}
        <button class="btn btn-block" data-act="funds-more" disabled={loading} onclick={() => void load(page + 1)}>{H.more}</button>
      {/if}
      {#if failed}<p class="muted fs-sm">{H.loadFail}</p>{/if}
    </section>
  {/if}

  <BackBar act="owner" fallback={() => go('owner')} />
</div>

<style>
  .funds-history {
    display: flex;
    flex-direction: column;
    gap: 14px;
  }
  .fh-fail {
    display: flex;
    flex-direction: column;
    align-items: flex-start;
    gap: 10px;
  }
  .fh-sum {
    display: flex;
    flex-direction: column;
    gap: 12px;
  }
  .fh-balance {
    display: flex;
    flex-direction: column;
    gap: 2px;
  }
  .fh-balance span {
    font-size: 0.8125rem;
    color: var(--muted);
  }
  .fh-balance b {
    font-family: var(--display);
    font-size: 1.75rem;
    color: var(--accent-text);
    font-variant-numeric: tabular-nums;
  }
  .fh-totals {
    display: grid;
    grid-template-columns: repeat(2, minmax(0, 1fr));
    gap: 8px;
    margin: 0;
  }
  .fh-totals div {
    display: flex;
    flex-direction: column;
    gap: 2px;
    padding: 10px 12px;
    border-radius: 12px;
    background: var(--surface-2);
    min-width: 0;
  }
  .fh-totals dt {
    font-size: 0.75rem;
    color: var(--muted);
  }
  .fh-totals dd {
    margin: 0 0 2px;
    font-family: var(--display);
    font-size: 1.125rem;
    font-weight: 700;
    font-variant-numeric: tabular-nums;
    overflow-wrap: anywhere;
  }
  .fh-log {
    display: flex;
    flex-direction: column;
    gap: 8px;
  }
  .fh-day {
    margin: 6px 0 0;
    font-size: 0.8125rem;
    color: var(--muted);
  }
  .fh-rows {
    list-style: none;
    margin: 0;
    padding: 0;
    border: 1px solid var(--line);
    border-radius: 14px;
    background: var(--surface);
  }
  .fh-rows li {
    display: flex;
    align-items: center;
    gap: 10px;
    padding: 10px 12px;
    border-bottom: 1px solid var(--line);
  }
  .fh-rows li:last-child {
    border-bottom: 0;
  }
  .fh-info {
    flex: 1;
    display: flex;
    flex-direction: column;
    gap: 3px;
    min-width: 0;
  }
  .fh-title {
    overflow: hidden;
    text-overflow: ellipsis;
    white-space: nowrap;
  }
  .fh-info small {
    font-size: 0.75rem;
    color: var(--muted);
  }
  .fh-rows b {
    flex: none;
    font-size: 0.875rem;
    white-space: nowrap;
    font-variant-numeric: tabular-nums;
  }
  .fh-plus {
    color: var(--good);
  }
  /* 이적시장 자금 내역(Market.svelte .mk-badge)과 같은 색 */
  .fh-badge {
    flex: none;
    min-width: 36px;
    padding: 3px 6px;
    border-radius: 6px;
    text-align: center;
    font-size: 0.6875rem;
    font-weight: 700;
  }
  .fh-badge-bought,
  .fh-badge-spent {
    background: color-mix(in srgb, #1f4f8f 14%, var(--surface));
    color: color-mix(in srgb, #1f4f8f 80%, var(--ink));
  }
  .fh-badge-sold {
    background: color-mix(in srgb, var(--accent) 18%, var(--surface));
    color: var(--accent-text);
  }
  .fh-badge-released {
    background: color-mix(in srgb, var(--bad) 12%, var(--surface));
    color: var(--bad);
  }
</style>
