// apps/mobile/src/screens/home/Home.tsx
// 홈(웹 Home.svelte — ui.ts renderHome() 포트): 전광판 · 히어로 · 라이브 현황 · 타일 · 명예의 전당 TOP 3 · 소식 · 푸터.
import { Linking, View } from 'react-native';
import Svg, { Circle, Path } from 'react-native-svg';
import { useSnapshot } from 'valtio';
import { PHASES, LAST_PHASE, posLabel } from '@offside/game/data';
import { ovr } from '@offside/game/attributes';
import { withRo } from '@offside/app-core/format';
import { DC_GALLERY_URL } from '@offside/app-core/links';
import { HallOfFame } from '../../components/HallOfFame';
import { SiteFooter } from '../../components/SiteFooter';
import { adoptCareer, keepOnDevice } from '../../game/host';
import { go, goContinue, goNew } from '../../game/nav';
import { appState } from '../../store';
import { alpha } from '../../theme/colors';
import { num, rem } from '../../theme/type';
import { useColors } from '../../theme/useColors';
import { Btn, Card, PitchCard, Row, Screen, Topbar, Txt } from '../../ui';
import { HomeFirsts } from './HomeFirsts';
import { HomeLive } from './HomeLive';
import { HomeNews } from './HomeNews';
import { HomeTicker } from './HomeTicker';
import { Tile } from './Tile';

export default function Home() {
  const s = useSnapshot(appState);
  const c = useColors();
  const G = s.G && !s.G.retired ? s.G : null;

  return (
    <Screen>
      <Topbar />
      {/* 이적·서버 최초 기록이 흐르는 전광판 */}
      <HomeTicker />
      {G ? (
        // 진행 중인 커리어가 있으면 첫 카드를 '이번 커리어'로 바꿔 이어하기를 가장 먼저 보여 준다.
        <PitchCard>
          <View testID="home-current">
            <Txt v="eyebrow" style={{ color: alpha(c.onPitch, 0.7) }}>
              Current career
            </Txt>
            <View style={{ marginTop: 6, gap: 2 }} accessible accessibilityRole="header">
              <Txt style={{ ...heroSub, color: alpha(c.onPitch, 0.8) }}>이번 커리어는</Txt>
              <Txt style={{ ...heroB, color: c.onPitch }}>
                <Txt style={{ ...heroName, color: c.onPitch }}>{G.name}</Txt> 입니다
              </Txt>
            </View>
            <Txt style={{ ...p, color: alpha(c.onPitch, 0.8) }}>
              {G.club.name} · {G.age}세 · {posLabel(G)}
            </Txt>
            <Txt
              style={[
                num(700),
                {
                  fontSize: rem(0.8125),
                  lineHeight: rem(0.8125) * 1.5,
                  marginTop: 2,
                  color: alpha(c.onPitch, 0.65),
                },
              ]}
            >
              {G.year} 시즌 {PHASES[Math.min(G.phase, LAST_PHASE + 1)]} · OVR {ovr(appState.G!)}
            </Txt>
            {/* 한 줄에 왼쪽 새 커리어, 오른쪽 이어하기(주 버튼이라 더 넓게). */}
            <View style={{ flexDirection: 'row', gap: 8, marginTop: 18 }}>
              <Btn
                testID="new"
                onPress={goNew}
                style={{
                  backgroundColor: 'transparent',
                  borderColor: alpha(c.onPitch, 0.35),
                  paddingHorizontal: 14,
                }}
              >
                <Txt style={btnText(c.onPitch)}>새 커리어 시작</Txt>
              </Btn>
              <Btn
                kind="accent"
                testID="continue"
                onPress={goContinue}
                style={{ flex: 1, minWidth: 0, paddingHorizontal: 14 }}
              >
                <Svg width={18} height={18} viewBox="0 0 24 24">
                  <Circle cx={12} cy={12} r={9} fill="none" stroke={c.accentInk} strokeWidth={2} />
                  <Path d="m10 7.8 6 4.2-6 4.2Z" fill={c.accentInk} />
                </Svg>
                <Txt numberOfLines={1} style={{ ...btnText(c.accentInk), flexShrink: 1 }}>
                  {withRo(G.name)} 계속 →
                </Txt>
              </Btn>
            </View>
          </View>
        </PitchCard>
      ) : (
        <PitchCard>
          <View>
            <Txt v="eyebrow" style={{ color: alpha(c.onPitch, 0.7) }}>
              Kick-off · 0′
            </Txt>
            <Txt
              v="h1"
              accessibilityRole="header"
              style={{
                fontSize: rem(1.875),
                lineHeight: rem(1.875) * 1.25,
                marginTop: 6,
                color: c.onPitch,
              }}
            >
              {'이번 생은 축구다\n나만의 커리어를 시작하세요'}
            </Txt>
            <Txt style={{ ...p, color: alpha(c.onPitch, 0.8) }}>
              고교 3학년의 킥오프부터 은퇴의 종료 휘슬까지. 오프사이드에서 훈련·이적·이벤트 선택으로
              나만의 축구선수 커리어를 만들어 보세요.
            </Txt>
            <Btn kind="accent" block testID="new" onPress={goNew} style={{ marginTop: 18 }}>
              새 커리어 킥오프 →
            </Btn>
          </View>
        </PitchCard>
      )}
      {G && s.ownerConflict ? (
        <View testID="owner-conflict">
          <Card gap={8} style={{ borderWidth: 1, borderColor: alpha(c.warn, 0.45) }}>
            <Txt bold>이 커리어는 다른 계정에 기록돼 있어요</Txt>
            <Txt v="sm" tone="muted">
              로그인한 계정이 바뀌어서 {G.name} 선수의 기록이 서버에 저장되지 않고 있어요. 원래
              계정으로 다시 로그인하면 그대로 이어져요.
            </Txt>
            <Row gap={8}>
              <Btn kind="accent" testID="adopt-career" onPress={adoptCareer}>
                지금 계정으로 이어서 기록
              </Btn>
              <Btn sm testID="keep-on-device" onPress={keepOnDevice}>
                이 기기에만 두기
              </Btn>
            </Row>
          </Card>
        </View>
      ) : null}
      <HomeLive />
      <View style={{ flexDirection: 'row', gap: 10 }}>
        <HomeFirsts />
        <Tile
          testID="dex"
          eyebrow="Events"
          title="확률 이벤트"
          sub="선택지마다 성공 확률 공개 · 확률 도감 보기 →"
          onPress={() => go('dex')}
        />
      </View>
      {/* T-11-009 디시인사이드 마이너 갤러리로 가는 커뮤니티 타일(두 칸 폭). */}
      <Tile
        wide
        testID="dc-gallery"
        eyebrow="Community"
        title="오프사이드 마이너 갤러리 ↗"
        sub="디시인사이드에서 커리어 자랑 · 공략 · 건의 나누기"
        onPress={() => void Linking.openURL(DC_GALLERY_URL)}
      />
      <HallOfFame />
      <HomeNews board="notice" eyebrow="Notice" title="공지사항" />
      <HomeNews board="release" eyebrow="Release notes" title="릴리즈 노트" />
      <SiteFooter />
    </Screen>
  );
}

// 웹 .hero-home p · .hero-current h1 (span · b · strong)
const p = { fontSize: rem(1), lineHeight: rem(1) * 1.55, marginTop: 6, maxWidth: 250 };
const heroSub = {
  fontSize: rem(1.0625),
  lineHeight: rem(1.0625) * 1.25,
  fontWeight: '600' as const,
};
const heroB = { fontSize: rem(1.375), lineHeight: rem(2) * 1.25, fontWeight: '600' as const };
const heroName = { fontSize: rem(2), lineHeight: rem(2) * 1.25, fontWeight: '700' as const };
const btnText = (color: string) => ({
  color,
  fontSize: rem(0.9375),
  fontWeight: '600' as const,
  lineHeight: rem(0.9375) * 1.25,
});

// apps/web/src/ui/Home.svelte
<script lang="ts">
  // ui.ts renderHome() 포트 (156~182줄)
  import { PHASES, LAST_PHASE, posLabel } from '@offside/game/data';
  import { ovr } from '@offside/game/attributes';
  import { appState } from './state.svelte.js';
  import { goNew, goContinue, go, warmGame } from './nav.js';
  import Topbar from './Topbar.svelte';
  import InAppBanner from './InAppBanner.svelte';
  import HallOfFame from './HallOfFame.svelte';
  import HomeNews from './HomeNews.svelte';
  import SiteFooter from './SiteFooter.svelte';
  import HomeFirsts from './firsts/HomeFirsts.svelte';
  import HomeLive from './HomeLive.svelte';
  import HomeTicker from './HomeTicker.svelte';
  import { adoptCareer, keepOnDevice } from './ownerConflict.js';
  import { withRo } from '@offside/app-core/format';
  import { DC_GALLERY_URL } from '@offside/app-core/links';

  const live = $derived(!!appState.G && !appState.G.retired);
</script>

<div class="wrap">
  <Topbar />
  <!-- T-10-115 카톡·인스타 같은 앱 안 브라우저에서만 한 번 보이는 외부 브라우저 안내 -->
  <InAppBanner />
  <!-- T-10-122 이적·서버 최초 기록이 흐르는 전광판 -->
  <HomeTicker />
  {#if live && appState.G}
    {@const G = appState.G}
    <!-- 진행 중인 커리어가 있으면 첫 카드를 '이번 커리어'로 바꿔 이어하기를 가장 먼저 보여 준다. -->
    <section class="hero-home hero-current" data-home-current>
      <div class="chalk"></div>
      <div class="eyebrow">Current career</div>
      <h1><span>이번 커리어는</span><b><strong>{G.name}</strong> 입니다</b></h1>
      <p>{G.club.name} · {G.age}세 · {posLabel(G)}</p>
      <p class="hero-meta num">{G.year} 시즌 {PHASES[Math.min(G.phase, LAST_PHASE + 1)]} · OVR {ovr(G)}</p>
      <!-- T-10-124 한 줄에 왼쪽 새 커리어, 오른쪽 이어하기(주 버튼이라 더 넓게). -->
      <div class="hero-actions">
        <button class="btn hero-new" data-act="new" onclick={goNew} onpointerenter={warmGame} onfocus={warmGame}>새 커리어 시작</button>
        <button class="btn btn-accent" data-act="continue" onclick={goContinue} onpointerenter={warmGame} onfocus={warmGame}>
          <svg class="hero-play" viewBox="0 0 24 24" aria-hidden="true"><circle cx="12" cy="12" r="9" /><path d="m10 7.8 6 4.2-6 4.2Z" /></svg>
          <span>{withRo(G.name)} 계속 →</span>
        </button>
      </div>
    </section>
  {:else}
    <section class="hero-home">
      <div class="chalk"></div>
      <div class="eyebrow">Kick-off · 0′</div>
      <h1>이번 생은 축구다<br />나만의 커리어를 시작하세요</h1>
      <p>고교 3학년의 킥오프부터 은퇴의 종료 휘슬까지. 오프사이드에서 훈련·이적·이벤트 선택으로 나만의 축구선수 커리어를 만들어 보세요.</p>
      <button class="btn btn-accent btn-block" data-act="new" onclick={goNew} onpointerenter={warmGame} onfocus={warmGame}>새 커리어 킥오프 →</button>
    </section>
  {/if}
  {#if live && appState.G && appState.ownerConflict}
    <section class="card owner-conflict" data-owner-conflict>
      <b>이 커리어는 다른 계정에 기록돼 있어요</b>
      <p class="muted">로그인한 계정이 바뀌어서 {appState.G.name} 선수의 기록이 서버에 저장되지 않고 있어요. 원래 계정으로 다시 로그인하면 그대로 이어져요.</p>
      <div class="row" style="gap:8px;flex-wrap:wrap">
        <button class="btn btn-accent" data-act="adopt-career" onclick={adoptCareer}>지금 계정으로 이어서 기록</button>
        <button class="icon-btn" data-act="keep-on-device" onclick={keepOnDevice}>이 기기에만 두기</button>
      </div>
    </section>
  {/if}
  <HomeLive />
  <div class="tiles">
    <HomeFirsts />
    <button class="tile tile-link" data-act="dex" onclick={() => go('dex')}>
      <span class="eyebrow">Events</span><b>확률 이벤트</b><span class="muted fs-sm">선택지마다 성공 확률 공개 · 확률 도감 보기 →</span>
    </button>
    <!-- T-11-009 디시인사이드 마이너 갤러리로 가는 커뮤니티 타일(두 칸 폭). -->
    <a class="tile tile-link tile-wide" data-act="dc-gallery" href={DC_GALLERY_URL} target="_blank" rel="noopener noreferrer">
      <span class="eyebrow">Community</span><b>오프사이드 마이너 갤러리 ↗</b><span class="muted fs-sm">디시인사이드에서 커리어 자랑 · 공략 · 건의 나누기</span>
    </a>
  </div>
  <HallOfFame />
  <HomeNews board="notice" eyebrow="Notice" title="공지사항" />
  <HomeNews board="release" eyebrow="Release notes" title="릴리즈 노트" />
  <SiteFooter />
  <!-- T-11-015 라운지 채팅으로 가는 떠 있는 버튼(하단 메뉴 위). -->
  <button class="chat-fab" data-act="chat" onclick={() => go('chat')}>
    <svg viewBox="0 0 24 24" width="20" height="20" aria-hidden="true"><path d="M4 5.5A2.5 2.5 0 0 1 6.5 3h11A2.5 2.5 0 0 1 20 5.5v8a2.5 2.5 0 0 1-2.5 2.5H10l-4.2 3.6c-.5.4-1.3.1-1.3-.6V16A2.5 2.5 0 0 1 4 13.5z" fill="currentColor"/></svg>
    채팅
  </button>
</div>
