// apps/mobile/src/screens/retired/Legend.tsx
// T-10-005 은퇴 선수 상세(웹 Legend.svelte) — 명예의 전당 · 구단주의 내 선수에서 언제든 다시 들어온다.
import { useEffect, useRef, useState } from 'react';
import { View } from 'react-native';
import Svg, { Path } from 'react-native-svg';
import { useSnapshot } from 'valtio';
import type { LegendView } from '@offside/app-core/state';
import { appState, prefs } from '../../store';
import { alpha } from '../../theme/colors';
import { useColors, useIsDark } from '../../theme/useColors';
import { rem } from '../../theme/type';
import { AdSlot } from '../../components/AdSlot';
import { NameReport } from '../../components/NameReport';
import { BackBar } from '../../ui/ActionBar';
import { Press } from '../../ui/Press';
import { Topbar } from '../../ui/Topbar';
import { Txt } from '../../ui/Txt';
import { CreditScreen, useCredit } from './credit';
import { LegendReport } from './LegendReport';
import { OwnHofCards } from './OwnHofCards';
import { rollCredits } from './roll';
import { ShareBar } from './ShareBar';
import { retiredText as L } from '@offside/app-core/i18n/ko/retired';

export default function Legend() {
  const snap = useSnapshot(appState);
  const { motionOK } = useSnapshot(prefs);
  // 화면은 스냅숏으로 그린다 — 쓰기(이름 공개·대표 칭호)는 own.ts가 원본을 찾아 고친다.
  const v = snap.legend as unknown as LegendView | null;
  return (
    // T-10-128 위쪽 '이전으로' 대신 아래 바: 공유할 수 있는 내 선수는 홈으로 + 공유하기, 그 밖은 '← 이전으로' 하나.
    <CreditScreen
      footer={
        v?.shareId ? (
          <ShareBar id={v.shareId} />
        ) : (
          <BackBar testID="hof-back" fallback={() => (appState.screen = appState.legendBack)} />
        )
      }
      overlay={motionOK && v ? <CareerPlay /> : null}
    >
      <Topbar />
      {v ? (
        <>
          <LegendReport v={v} />
          {v.own?.id ? <OwnHofCards v={v} /> : null}
          {v.reportId ? <NameReport kind="career" id={v.reportId} name={v.name} /> : null}
          <AdSlot place="legend-bottom" />
        </>
      ) : null}
    </CreditScreen>
  );
}

/**
 * T-10-129 커리어 재생: 누르면 크레딧처럼 흘러가고, 다시 누르거나 화면을 만지면 멈춘다. 동작 줄이기면 버튼이 없다.
 * CreditScreen 안에 떠 있어 스크롤 계측기(useCredit)를 받는다.
 */
function CareerPlay() {
  const c = useColors();
  const dark = useIsDark();
  const ctl = useCredit();
  const [rolling, setRolling] = useState(false);
  const stopRoll = useRef<(() => void) | null>(null);
  useEffect(() => () => stopRoll.current?.(), []);
  function toggle() {
    if (stopRoll.current) return stopRoll.current();
    if (!ctl) return;
    setRolling(true);
    stopRoll.current = rollCredits(ctl, () => {
      setRolling(false);
      stopRoll.current = null;
    });
  }
  const fg = rolling ? c.ink : c.accentInk;
  return (
    <Press
      testID="career-play"
      accessibilityLabel={rolling ? L.stop : L.play}
      accessibilityState={{ selected: rolling }}
      onPress={toggle}
      style={{
        flexDirection: 'row',
        alignItems: 'center',
        gap: 6,
        minHeight: 40,
        paddingVertical: 8,
        paddingLeft: 12,
        paddingRight: 16,
        borderRadius: 999,
        borderWidth: 1,
        borderColor: rolling ? c.line : c.accent,
        backgroundColor: rolling ? alpha(c.bg, 0.88) : c.accent,
        shadowColor: '#000',
        shadowOpacity: dark ? 0.5 : 0.35,
        shadowRadius: 9,
        shadowOffset: { width: 0, height: 6 },
        elevation: 6,
      }}
    >
      <View>
        <Svg width={18} height={18} viewBox="0 0 24 24" fill={fg}>
          <Path d={rolling ? 'M8 6h3v12H8zM13 6h3v12h-3z' : 'M8 5.5v13l10.5-6.5z'} />
        </Svg>
      </View>
      <Txt style={{ fontSize: rem(0.875), fontWeight: '700', color: fg }}>
        {rolling ? L.stop : L.play}
      </Txt>
    </Press>
  );
}

// apps/web/src/ui/Legend.svelte
<script lang="ts">
  // T-10-005 은퇴 선수 상세 — 명예의 전당 · 구단주의 내 선수에서 언제든 다시 들어온다.
  import { appState } from './state.svelte.js';
  import Topbar from './Topbar.svelte';
  import LegendReport from './LegendReport.svelte';
  import OwnHofCards from './OwnHofCards.svelte';
  import ShareBar from './ShareBar.svelte';
  import NameReport from './NameReport.svelte';
  import BackBar from './BackBar.svelte';
  import AdSlot from '../ads/AdSlot.svelte';
  import { motionOK } from './motion.js';
  import { rollCredits } from './creditRoll.js';
  import { retiredText as L } from '@offside/app-core/i18n/ko/retired';

  const v = $derived(appState.legend);
  let root: HTMLDivElement;

  // T-10-129 커리어 재생: 누르면 크레딧처럼 흘러가고, 다시 누르거나 화면을 만지면 멈춘다. 감속 모션이면 버튼이 없다.
  let rolling = $state(false);
  let stopRoll: (() => void) | null = null;
  function toggleRoll() {
    if (stopRoll) return stopRoll();
    rolling = true;
    stopRoll = rollCredits(root, () => {
      rolling = false;
      stopRoll = null;
    });
  }
  $effect(() => () => stopRoll?.());
</script>

<div class="wrap" bind:this={root}>
  <Topbar />
  {#if v}
    <LegendReport {v} />
    {#if v.own?.id}<OwnHofCards {v} />{/if}
    {#if v.reportId}<NameReport kind="career" id={v.reportId} name={v.name} />{/if}
    <AdSlot place="legend-bottom" />
  {/if}
  <!-- T-10-128 위쪽 '이전으로' 대신 아래 바: 공유할 수 있는 내 선수는 홈으로 + 공유하기, 그 밖은 '← 이전으로' 하나. -->
  {#if v?.shareId}
    <ShareBar id={v.shareId} />
  {:else}
    <BackBar act="hof-back" fallback={() => (appState.screen = appState.legendBack)} />
  {/if}
  {#if motionOK && v}
    <button class="career-play" class:on={rolling} data-act="career-play" aria-pressed={rolling} onclick={toggleRoll}>
      <svg viewBox="0 0 24 24" aria-hidden="true">
        {#if rolling}<path d="M8 6h3v12H8zM13 6h3v12h-3z" />{:else}<path d="M8 5.5v13l10.5-6.5z" />{/if}
      </svg>
      {rolling ? L.stop : L.play}
    </button>
  {/if}
</div>

<style>
  .career-play {
    position: fixed;
    bottom: calc(var(--bottom-bar-h, 0px) + 12px);
    right: max(var(--pad-r, 16px), calc(50% - 240px + 16px));
    z-index: 6;
    display: inline-flex;
    align-items: center;
    gap: 6px;
    min-height: 40px;
    padding: 8px 16px 8px 12px;
    border-radius: 999px;
    border: 1px solid var(--accent);
    background: var(--accent);
    color: var(--accent-ink);
    font-weight: 700;
    font-size: 0.875rem;
    box-shadow: 0 6px 18px rgb(0 0 0 / 0.35);
  }
  .career-play.on {
    background: color-mix(in srgb, var(--bg) 88%, transparent);
    color: var(--ink);
    border-color: var(--line);
    backdrop-filter: blur(6px);
    -webkit-backdrop-filter: blur(6px);
  }
  .career-play svg {
    width: 18px;
    height: 18px;
    fill: currentColor;
  }
</style>
