// apps/mobile/src/screens/owner/LoginButtons.tsx
import { GoogleLoginButton } from '../../ui/GoogleLoginButton';
// 로그인 버튼 묶음 — 웹은 '구글로 로그인' 하나(구단주 화면·내 팀 안내). 앱은 iOS에서 Sign in with Apple이 가능하면
// 'Apple로 로그인'도 함께 둔다(앱 스토어 심사 지침: 다른 소셜 로그인을 두면 애플도 제공).
import { View } from 'react-native';
import { startAppleLogin, startGoogleLogin, type LoginReturn } from '../../platform/auth';
import { AppleLoginButton, useAppleLogin } from '../../ui/AppleLoginButton';

export function LoginButtons({
  block = true,
  back = null,
  onDone,
}: {
  block?: boolean;
  /** 로그인을 마치고 돌아갈 곳(없으면 구단주 화면). */
  back?: LoginReturn | null;
  /** 로그인 시도가 끝나면(성공·취소 모두) 부른다. */
  onDone?: () => void;
}) {
  const apple = useAppleLogin();
  return (
    <View style={{ gap: 8, alignSelf: block ? 'stretch' : 'flex-start' }}>
      <GoogleLoginButton
        testID="google-login"
        onPress={() => void startGoogleLogin(back).then(onDone)}
        block={block}
      />
      {apple ? (
        <AppleLoginButton
          testID="apple-login"
          onPress={() => void startAppleLogin(back).then(onDone)}
        />
      ) : null}
    </View>
  );
}

// apps/web/src/ui/LoginButtons.svelte
<script lang="ts">
  // 로그인 버튼 묶음 — 구글과 Apple(T-11-202). 앱 screens/owner/LoginButtons.tsx와 같은 자리에 쓴다.
  import GoogleLoginButton from './GoogleLoginButton.svelte';
  import AppleLoginButton from './AppleLoginButton.svelte';
  import { startAppleLogin, startGoogleLogin, type LoginReturn } from './login.js';

  let { back = null, act = 'google-login', block = true }: {
    /** 로그인을 마치고 돌아갈 곳(없으면 구단주 화면). */
    back?: LoginReturn | null;
    /** 구글 버튼의 data-act. Apple 버튼은 'apple-'를 앞에 붙인다. */
    act?: string;
    block?: boolean;
  } = $props();
</script>

<div class="login-btns" class:login-btns-block={block}>
  <GoogleLoginButton {act} {block} onclick={() => startGoogleLogin(back)} />
  <AppleLoginButton act={act.includes('google') ? act.replace('google', 'apple') : `apple-${act}`} {block} onclick={() => startAppleLogin(back)} />
</div>
