// apps/mobile/src/screens/create/NationPicker.tsx
// 국적 고르기(웹 NationPicker.svelte): 한글·초성으로 찾는 목록. 연맹별로 묶어 가나다순, 대한민국은 맨 위.
// 웹은 입력 칸 아래 콤보박스를 펼치지만, 앱은 키보드가 아래 목록을 가리므로 입력 칸을 누르면 아래에서 올라오는
// 창(Modal)에 검색 칸 + 목록을 띄우고 KeyboardAvoidingView로 키보드 위에 맞춘다.
import { useMemo, useState } from 'react';
import {
  KeyboardAvoidingView,
  Modal,
  Platform,
  SectionList,
  TextInput,
  View,
  type SectionListData,
} from 'react-native';
import { useSafeAreaInsets } from 'react-native-safe-area-context';
import { CONFEDS, CONF_ORDER, DEFAULT_NATION, NATIONS } from '@offside/contracts/nations';
import { KR, flagOf, nationOf, type Nation } from '@offside/game/nation';
import { koMatchAt } from '@offside/app-core/koSearch';
import { alpha } from '../../theme/colors';
import { rem } from '../../theme/type';
import { useColors } from '../../theme/useColors';
import { Press, Txt } from '../../ui';

const byKo = new Intl.Collator('ko').compare;
interface Group {
  key: string;
  label: string;
  data: Nation[];
}
const GROUPS: Group[] = [
  { key: 'KR', label: '기본', data: [KR] },
  ...CONF_ORDER.map((conf) => ({
    key: conf,
    label: `${CONFEDS[conf].region} (${conf})`,
    data: NATIONS.filter((n) => n.conf === conf && n.code !== DEFAULT_NATION).sort((a, b) =>
      byKo(a.ko, b.ko),
    ),
  })),
];

export function NationPicker({
  value,
  onChange,
  testID,
}: {
  value: string;
  onChange: (code: string) => void;
  testID?: string;
}) {
  const c = useColors();
  const insets = useSafeAreaInsets();
  const [open, setOpen] = useState(false);
  const [query, setQuery] = useState('');
  const selected = nationOf({ nation: value });

  // 검색 중엔 연맹 묶음 대신 한 목록으로, 이름이 검색어로 시작하는 나라부터.
  const groups = useMemo<Group[]>(() => {
    if (!query) return GROUPS;
    const hits = NATIONS.map((n) => ({ n, at: koMatchAt(n.ko, query) }))
      .filter((h) => h.at >= 0)
      .sort((a, b) => a.at - b.at || byKo(a.n.ko, b.n.ko));
    return hits.length
      ? [{ key: 'hits', label: `검색 결과 ${hits.length}`, data: hits.map((h) => h.n) }]
      : [];
  }, [query]);

  const show = () => {
    setQuery('');
    setOpen(true);
  };
  const hide = () => {
    setOpen(false);
    setQuery('');
  };
  const pick = (n: Nation) => {
    onChange(n.code);
    hide();
  };

  return (
    <>
      <Press
        scale={0.99}
        onPress={show}
        {...(testID ? { testID } : {})}
        accessibilityLabel={`국적 ${selected.ko}`}
        accessibilityHint="누르면 나라를 검색해서 고를 수 있어요"
        accessibilityRole="combobox"
        accessibilityState={{ expanded: open }}
        style={{
          flexDirection: 'row',
          alignItems: 'center',
          gap: 8,
          minHeight: 48,
          paddingHorizontal: 13,
          borderWidth: 1,
          borderColor: c.line,
          borderRadius: 10,
          backgroundColor: c.surface2,
        }}
      >
        <Txt style={{ fontSize: rem(1.125) }} accessibilityElementsHidden>
          {flagOf(selected.code)}
        </Txt>
        <Txt numberOfLines={1} style={{ flex: 1, fontSize: 16 }}>
          {selected.ko}
        </Txt>
        <Txt tone="muted" accessibilityElementsHidden>
          ▾
        </Txt>
      </Press>

      <Modal
        visible={open}
        transparent
        animationType="slide"
        onRequestClose={hide}
        statusBarTranslucent
      >
        <KeyboardAvoidingView
          behavior={Platform.OS === 'ios' ? 'padding' : undefined}
          style={{ flex: 1, justifyContent: 'flex-end', backgroundColor: c.scrim }}
        >
          {/* 바깥을 누르면 닫는다 */}
          <Press onPress={hide} accessibilityLabel="국적 고르기 닫기" style={{ flex: 1 }} scale={1}>
            <View style={{ flex: 1 }} />
          </Press>
          <View
            style={{
              height: '80%',
              backgroundColor: c.surface,
              borderTopLeftRadius: 16,
              borderTopRightRadius: 16,
              paddingTop: 12,
              paddingBottom: insets.bottom,
            }}
          >
            <View
              style={{
                flexDirection: 'row',
                alignItems: 'center',
                gap: 8,
                paddingHorizontal: 12,
                paddingBottom: 8,
              }}
            >
              <TextInput
                {...(testID ? { testID: `${testID}-search` } : {})}
                autoFocus
                autoCorrect={false}
                autoCapitalize="none"
                spellCheck={false}
                returnKeyType="search"
                accessibilityLabel="국적 검색"
                placeholder="나라 이름이나 초성(ㅂㄹㅈ)"
                placeholderTextColor={c.muted}
                value={query}
                onChangeText={setQuery}
                style={{
                  flex: 1,
                  borderWidth: 1,
                  borderColor: c.line,
                  borderRadius: 10,
                  backgroundColor: c.surface2,
                  paddingVertical: 11,
                  paddingHorizontal: 12,
                  fontSize: 16,
                  color: c.ink,
                }}
              />
              <Press
                onPress={hide}
                accessibilityLabel="닫기"
                style={{ minHeight: 44, justifyContent: 'center', paddingHorizontal: 6 }}
              >
                <Txt tone="muted" bold>
                  닫기
                </Txt>
              </Press>
            </View>
            <SectionList<Nation, Group>
              sections={groups}
              keyExtractor={(n) => n.code}
              keyboardShouldPersistTaps="handled"
              stickySectionHeadersEnabled
              initialNumToRender={24}
              contentContainerStyle={{ paddingHorizontal: 8, paddingBottom: 8 }}
              renderSectionHeader={({ section }: { section: SectionListData<Nation, Group> }) => (
                <View
                  style={{
                    paddingTop: 8,
                    paddingBottom: 4,
                    paddingHorizontal: 10,
                    backgroundColor: c.surface,
                  }}
                >
                  <Txt
                    accessibilityRole="header"
                    style={{ color: c.muted, fontSize: rem(0.75), fontWeight: '600' }}
                  >
                    {section.label}
                  </Txt>
                </View>
              )}
              renderItem={({ item: n }) => {
                const on = n.code === value;
                return (
                  <Press
                    scale={0.99}
                    onPress={() => pick(n)}
                    testID={`nation-${n.code}`}
                    accessibilityLabel={n.ko}
                    accessibilityState={{ selected: on }}
                    style={(pressed) => ({
                      flexDirection: 'row',
                      alignItems: 'center',
                      gap: 8,
                      padding: 10,
                      borderRadius: 8,
                      backgroundColor: pressed ? alpha(c.ink, 0.06) : 'transparent',
                    })}
                  >
                    <Txt accessibilityElementsHidden>{flagOf(n.code)}</Txt>
                    <Txt
                      style={{ flex: 1, ...(on ? { fontWeight: '700', color: c.accentText } : {}) }}
                    >
                      {n.ko}
                    </Txt>
                  </Press>
                );
              }}
              ListEmptyComponent={
                <Txt tone="muted" center style={{ paddingVertical: 14, paddingHorizontal: 10 }}>
                  찾는 나라가 없어요
                </Txt>
              }
            />
          </View>
        </KeyboardAvoidingView>
      </Modal>
    </>
  );
}

// apps/web/src/ui/NationPicker.svelte
<script lang="ts">
  // T-10-099 국적 고르기: 한글·초성으로 찾는 콤보박스. 연맹별로 묶어 가나다순, 대한민국은 맨 위.
  import { CONFEDS, CONF_ORDER, DEFAULT_NATION, NATIONS } from '@offside/contracts/nations';
  import { KR, flagOf, nationOf, type Nation } from '../game/nation.js';
  import { koMatchAt } from './koSearch.js';
  import { motionOK } from './motion.js';

  let { id, value = $bindable() }: { id: string; value: string } = $props();

  const byKo = new Intl.Collator('ko').compare;
  const GROUPS = [
    { key: 'KR', label: '기본', list: [KR] },
    ...CONF_ORDER.map((conf) => ({
      key: conf,
      label: `${CONFEDS[conf].region} (${conf})`,
      list: NATIONS.filter((n) => n.conf === conf && n.code !== DEFAULT_NATION).sort((a, b) => byKo(a.ko, b.ko)),
    })),
  ];

  let open = $state(false);
  // null = 아직 안 쳤다(선택된 이름을 보여 주고 전체 목록).
  let query = $state<string | null>(null);
  let active = $state(0);
  let input: HTMLInputElement;
  let root: HTMLDivElement;
  let list = $state<HTMLDivElement>();

  const selected = $derived(nationOf({ nation: value }));
  // 검색 중엔 연맹 묶음 대신 한 목록으로, 이름이 검색어로 시작하는 나라부터.
  const groups = $derived.by(() => {
    if (!query) return GROUPS;
    const hits = NATIONS.map((n) => ({ n, at: koMatchAt(n.ko, query!) }))
      .filter((h) => h.at >= 0)
      .sort((a, b) => a.at - b.at || byKo(a.n.ko, b.n.ko));
    return hits.length ? [{ key: 'hits', label: `검색 결과 ${hits.length}`, list: hits.map((h) => h.n) }] : [];
  });
  const flat = $derived(groups.flatMap((g) => g.list));
  const cur = $derived<Nation | undefined>(flat[active]);
  const optId = (n: Nation) => `${id}-o-${n.code}`;

  function show() {
    if (open) return;
    open = true;
    query = null;
    active = Math.max(0, flat.findIndex((n) => n.code === value));
    input.select();
    // 폰에선 키보드가 올라와 아래 목록을 가리므로 입력 칸을 화면 위쪽으로 올린다(여백은 scroll-margin-top).
    if (matchMedia('(pointer: coarse)').matches) setTimeout(() => root.scrollIntoView({ block: 'start', behavior: motionOK ? 'smooth' : 'auto' }), 300);
  }
  function hide() {
    open = false;
    query = null;
  }
  function pick(n: Nation) {
    value = n.code;
    hide();
    input.blur();
  }
  function onkeydown(e: KeyboardEvent) {
    if (e.key === 'ArrowDown' || e.key === 'ArrowUp') {
      e.preventDefault();
      if (!open) return show();
      const step = e.key === 'ArrowDown' ? 1 : -1;
      active = (active + step + flat.length) % Math.max(1, flat.length);
    } else if (e.key === 'Enter' && open) {
      e.preventDefault();
      if (cur) pick(cur);
    } else if (e.key === 'Escape' && open) {
      e.preventDefault();
      hide();
    }
  }

  // 키보드로 움직인 항목이 목록 밖으로 나가지 않게.
  $effect(() => {
    if (!open || !cur) return;
    list?.querySelector(`#${optId(cur)}`)?.scrollIntoView({ block: 'nearest' });
  });
</script>

<div class="combo" class:open bind:this={root}>
  <span class="combo-flag" aria-hidden="true">{flagOf(selected.code)}</span>
  <input
    {id}
    bind:this={input}
    type="text"
    role="combobox"
    autocomplete="off"
    aria-autocomplete="list"
    aria-expanded={open}
    aria-controls="{id}-list"
    aria-activedescendant={open && cur ? optId(cur) : undefined}
    data-value={value}
    placeholder="나라 이름이나 초성(ㅂㄹㅈ)"
    value={query ?? selected.ko}
    onfocus={show}
    onclick={show}
    oninput={(e) => {
      open = true;
      query = e.currentTarget.value;
      active = 0;
    }}
    {onkeydown}
    onblur={hide}
  />
  <span class="combo-caret" aria-hidden="true">▾</span>
  {#if open}
    <div class="combo-list" id="{id}-list" role="listbox" aria-label="국적" bind:this={list}>
      {#each groups as g (g.key)}
        <div role="group" aria-labelledby="{id}-g-{g.key}">
          <div class="combo-group" id="{id}-g-{g.key}">{g.label}</div>
          {#each g.list as n (n.code)}
            <!-- 목록을 누르는 동안 입력 칸이 초점을 잃지 않게 pointerdown을 막는다. 키보드 선택은 입력 칸이 맡는다. -->
            <!-- svelte-ignore a11y_click_events_have_key_events -->
            <div
              class="combo-opt"
              class:active={cur === n}
              id={optId(n)}
              role="option"
              tabindex="-1"
              aria-selected={n.code === value}
              data-nation={n.code}
              onpointerdown={(e) => e.preventDefault()}
              onclick={() => pick(n)}
            >
              <span aria-hidden="true">{flagOf(n.code)}</span>
              {n.ko}
            </div>
          {/each}
        </div>
      {:else}
        <div class="combo-empty">찾는 나라가 없어요</div>
      {/each}
    </div>
  {/if}
</div>

<style>
  .combo {
    position: relative;
  }
  .combo input {
    padding-inline: 40px 34px;
    text-overflow: ellipsis;
  }
  .combo-flag,
  .combo-caret {
    position: absolute;
    top: 50%;
    transform: translateY(-50%);
    pointer-events: none;
  }
  .combo-flag {
    left: 13px;
    font-size: 1.125rem;
  }
  .combo-caret {
    right: 13px;
    color: var(--muted);
    transition: transform 0.15s;
  }
  .open .combo-caret {
    transform: translateY(-50%) rotate(180deg);
  }
  .combo-list {
    position: absolute;
    z-index: 7;
    top: calc(100% + 6px);
    left: 0;
    right: 0;
    max-height: min(300px, 40vh);
    overflow-y: auto;
    overscroll-behavior: contain;
    background: var(--surface);
    border: 1px solid var(--line);
    border-radius: 12px;
    box-shadow: var(--shadow);
    padding: 4px;
  }
  .combo-group {
    position: sticky;
    top: -4px;
    padding: 8px 10px 4px;
    background: var(--surface);
    color: var(--muted);
    font-size: 0.75rem;
    font-weight: 600;
  }
  .combo-opt {
    display: flex;
    gap: 8px;
    align-items: center;
    padding: 10px;
    border-radius: 8px;
    cursor: pointer;
  }
  .combo-opt.active {
    background: var(--surface-2);
  }
  .combo-opt[aria-selected='true'] {
    font-weight: 700;
    color: var(--accent-text);
  }
  .combo-empty {
    padding: 14px 10px;
    color: var(--muted);
    text-align: center;
  }
</style>
