// apps/mobile/src/screens/hof/RetiredWall.tsx
// T-10-076 기록실 '영구결번' 탭(웹 RetiredWall.svelte) — 서버의 모든 결번을 구단별(결번 많은 구단 먼저) 또는 최신순으로 본다.
// 유니폼은 구단 엠블럼 색(rnStyle), 누르면 그 선수의 은퇴 상세.
import { useEffect, useId, useMemo, useState } from 'react';
import { View } from 'react-native';
import Svg, { Defs, RadialGradient, Rect, Stop } from 'react-native-svg';
import { proxy, useSnapshot } from 'valtio';
import type { RetiredNumbersResponse } from '@offside/contracts';
import { defaultClubName, leagueOfClub } from '@offside/contracts/club-names';
import { getRetiredNumbers } from '@offside/app-core/api/client';
import { anonName } from '@offside/app-core/format';
import { RN_DEFAULT, rnColors } from '@offside/app-core/rnStyle';
import { POS } from '@offside/game/data';
import { loadHOF } from '@offside/game/season';
import { RnShirt } from '../../components/RnJersey';
import { openPublicLegendById } from '../../game/host';
import { alpha } from '../../theme/colors';
import { rem } from '../../theme/type';
import { useColors } from '../../theme/useColors';
import { Card } from '../../ui/Card';
import { ClubMark } from '../../ui/ClubBadge';
import { Press } from '../../ui/Press';
import { Txt } from '../../ui/Txt';
import { SortChips } from '../board/parts';

type Item = RetiredNumbersResponse['items'][number];

// 구단별·최신순 선택은 선수 상세에 다녀와도 그대로 둔다(화면이 다시 그려져도 모듈 값은 남는다).
const view = proxy<{ order: 'club' | 'recent' }>({ order: 'club' });

const leagueOf = (clubId: string) => leagueOfClub(clubId)?.name ?? '';
/** 결번 당시 기록된 이름은 유저가 바꿔 부른 이름일 수 있다 — 모두가 보는 벽에는 게임 기본 이름을 건다. */
const clubName = (it: Item) => defaultClubName(it.clubId) ?? it.club;
const day = (iso: string) => {
  const d = new Date(iso);
  return `${d.getFullYear()}.${d.getMonth() + 1}.${d.getDate()}`;
};

const GAP = 8;
const MIN_TILE = 90;

/** 유니폼 타일 한 장 — 구단 색이 은은히 비치는 바탕(웹 radial-gradient). */
function Tile({
  it,
  withClub,
  mine,
  width,
}: {
  it: Item;
  withClub: boolean;
  mine: boolean;
  width: number;
}) {
  const c = useColors();
  const gid = useId().replace(/[^a-zA-Z0-9]/g, '');
  const base = (rnColors(it.clubId) ?? RN_DEFAULT).base;
  const name = it.name ?? anonName(it.pos, it.number);
  return (
    <Press
      scale={0.985}
      testID={`rn-tile-${it.seq}`}
      onPress={() => void openPublicLegendById(it.careerId)}
      accessibilityLabel={`${name} ${it.number}번 · ${withClub ? clubName(it) : POS[it.pos].label}`}
      style={{
        width,
        alignItems: 'center',
        gap: 2,
        paddingTop: 10,
        paddingBottom: 8,
        paddingHorizontal: 4,
        borderWidth: 1,
        borderColor: c.line,
        borderRadius: 14,
        backgroundColor: c.surface,
        overflow: 'hidden',
      }}
    >
      <Svg
        pointerEvents="none"
        style={{ position: 'absolute', left: 0, right: 0, top: 0, bottom: 0 }}
        width="100%"
        height="100%"
      >
        <Defs>
          <RadialGradient id={gid} cx="50%" cy="30%" rx="90%" ry="60%">
            <Stop offset="0" stopColor={base} stopOpacity={0.22} />
            <Stop offset="1" stopColor={base} stopOpacity={0} />
          </RadialGradient>
        </Defs>
        <Rect width="100%" height="100%" fill={`url(#${gid})`} />
      </Svg>
      <View style={{ marginBottom: 4 }}>
        <RnShirt number={it.number} width={52} clubId={it.clubId} />
      </View>
      <Txt
        bold
        numberOfLines={1}
        style={{ maxWidth: '100%', fontSize: rem(0.875), lineHeight: rem(0.875) * 1.5 }}
      >
        {name}
      </Txt>
      {withClub ? (
        <View style={{ flexDirection: 'row', alignItems: 'center', gap: 4, maxWidth: '100%' }}>
          <ClubMark name={it.club} id={it.clubId} size={14} />
          <Txt tone="muted" numberOfLines={1} style={{ fontSize: rem(0.75), flexShrink: 1 }}>
            {clubName(it)}
          </Txt>
        </View>
      ) : (
        <Txt tone="muted" numberOfLines={1} style={{ fontSize: rem(0.75), maxWidth: '100%' }}>
          {POS[it.pos].label}
        </Txt>
      )}
      <Txt
        tone="muted"
        num={400}
        numberOfLines={1}
        style={{ fontSize: rem(0.75), maxWidth: '100%' }}
      >
        {`${it.seq}번째 · ${day(it.grantedAt)}`}
      </Txt>
      {mine ? (
        <View
          style={{
            position: 'absolute',
            top: 6,
            right: 6,
            paddingHorizontal: 6,
            borderRadius: 999,
            backgroundColor: c.surface2,
            borderWidth: 1,
            borderColor: c.line,
          }}
        >
          <Txt
            style={{
              fontSize: rem(0.625),
              lineHeight: rem(0.625) * 1.6,
              fontWeight: '600',
              color: c.muted,
            }}
          >
            내 선수
          </Txt>
        </View>
      ) : null}
    </Press>
  );
}

/** 웹 grid-template-columns: repeat(auto-fill, minmax(90px, 1fr)). */
function Tiles({
  items,
  withClub,
  myIds,
}: {
  items: Item[];
  withClub: boolean;
  myIds: ReadonlySet<string>;
}) {
  const [w, setW] = useState(0);
  const cols = Math.max(1, Math.floor((w + GAP) / (MIN_TILE + GAP)));
  const tile = (w - GAP * (cols - 1)) / cols;
  return (
    <View
      onLayout={(e) => setW(e.nativeEvent.layout.width)}
      style={{ flexDirection: 'row', flexWrap: 'wrap', gap: GAP, paddingBottom: 10 }}
    >
      {w > 0
        ? items.map((it) => (
            <Tile
              key={it.seq}
              it={it}
              withClub={withClub}
              mine={myIds.has(it.careerId)}
              width={tile}
            />
          ))
        : null}
    </View>
  );
}

export default function RetiredWall() {
  const c = useColors();
  const { order } = useSnapshot(view);
  const [items, setItems] = useState<Item[] | null>(null);
  const [failed, setFailed] = useState(false);
  useEffect(() => {
    let live = true;
    void getRetiredNumbers().then((r) => {
      if (!live) return;
      if (r.ok) setItems(r.data.items);
      else setFailed(true);
    });
    return () => {
      live = false;
    };
  }, []);

  const myIds = useMemo(() => new Set(loadHOF().flatMap((h) => (h.id ? [h.id] : []))), []);
  /** 구단별 — 결번이 많은 구단 먼저, 같으면 먼저 결번을 낸 구단. 구단 안에서는 번호 순. */
  const clubs = useMemo(() => {
    const by: Record<string, Item[]> = {};
    for (const it of items ?? []) (by[it.clubId] ??= []).push(it);
    return Object.values(by)
      .map((list) => list.sort((a, b) => a.number - b.number))
      .sort(
        (a, b) =>
          b.length - a.length ||
          Math.min(...a.map((x) => x.seq)) - Math.min(...b.map((x) => x.seq)),
      );
  }, [items]);
  const recent = useMemo(() => [...(items ?? [])].sort((a, b) => b.seq - a.seq), [items]);

  const empty = (text: string) => (
    <Txt tone="muted" style={{ fontSize: rem(0.875), paddingVertical: 8 }}>
      {text}
    </Txt>
  );
  const summary = (value: string, label: string, small = false) => (
    <View
      style={{
        flex: 1,
        alignItems: 'center',
        gap: 2,
        paddingVertical: 10,
        paddingHorizontal: 6,
        borderRadius: 12,
        backgroundColor: c.surface2,
      }}
    >
      <Txt
        num
        style={{
          fontSize: rem(small ? 0.9375 : 1.25),
          lineHeight: small ? rem(1.75) : rem(1.25) * 1.4,
        }}
      >
        {value}
      </Txt>
      <Txt tone="muted" style={{ fontSize: rem(0.75) }}>
        {label}
      </Txt>
    </View>
  );

  return (
    <Card gap={0}>
      <View testID="rn-wall">
        <Txt v="eyebrow">Retired Numbers</Txt>
        <Txt v="h1" accessibilityRole="header" style={{ marginBottom: 6 }}>
          영구결번
        </Txt>
        <Txt tone="muted" style={{ fontSize: rem(0.8125), marginBottom: 14 }}>
          한 구단에서 오래, 크게 빛난 선수의 등번호는 그 구단에서 다시 쓰지 않습니다. 구단마다 한
          번호에 한 명뿐입니다.
        </Txt>
      </View>

      {items === null && !failed ? (
        <Txt
          tone="muted"
          accessibilityLiveRegion="polite"
          style={{ fontSize: rem(0.875), paddingVertical: 8 }}
        >
          불러오는 중…
        </Txt>
      ) : failed ? (
        empty('영구결번을 불러오지 못했습니다. 잠시 후 다시 시도해 주세요.')
      ) : items?.length ? (
        <>
          <View style={{ flexDirection: 'row', gap: 8, marginBottom: 12 }}>
            {summary(String(items.length), '결번')}
            {summary(String(clubs.length), '구단')}
            {summary(day(recent[0]!.grantedAt), '최근 결번', true)}
          </View>
          <SortChips
            label="정렬"
            testIDPrefix="rn-order"
            value={order}
            onPick={(k) => (view.order = k as 'club' | 'recent')}
            items={[
              { key: 'club', label: '구단별' },
              { key: 'recent', label: '최신순' },
            ]}
          />
          {order === 'club' ? (
            clubs.map((list) => {
              const first = list[0]!;
              return (
                <View
                  key={first.clubId}
                  testID={`rn-club-${first.clubId}`}
                  style={{
                    paddingTop: 14,
                    paddingBottom: 4,
                    borderTopWidth: 1,
                    borderTopColor: c.line,
                  }}
                >
                  <View
                    style={{
                      flexDirection: 'row',
                      alignItems: 'center',
                      gap: 6,
                      marginBottom: 10,
                      minWidth: 0,
                    }}
                  >
                    <ClubMark name={first.club} id={first.clubId} size={22} />
                    <Txt bold numberOfLines={1} style={{ flexShrink: 1 }}>
                      {clubName(first)}
                    </Txt>
                    <Txt tone="muted" style={{ fontSize: rem(0.75) }}>
                      {leagueOf(first.clubId)}
                    </Txt>
                    <View
                      style={{
                        marginLeft: 'auto',
                        paddingVertical: 1,
                        paddingHorizontal: 9,
                        borderRadius: 999,
                        borderWidth: 1,
                        borderColor: c.accent,
                        backgroundColor: alpha(c.accent, 0.16),
                      }}
                    >
                      <Txt
                        num
                        style={{
                          fontSize: rem(0.8125),
                          lineHeight: rem(0.8125) * 1.5,
                          fontWeight: '700',
                        }}
                      >
                        {list.length}
                      </Txt>
                    </View>
                  </View>
                  <Tiles items={list} withClub={false} myIds={myIds} />
                </View>
              );
            })
          ) : (
            <Tiles items={recent} withClub myIds={myIds} />
          )}
        </>
      ) : (
        empty(
          '아직 영구결번이 없습니다. 한 구단의 전설이 되어 첫 번째 결번의 주인공이 되어 보세요.',
        )
      )}
    </Card>
  );
}

// apps/web/src/ui/RetiredWall.svelte
<script lang="ts" module>
  // 구단별·최신순 선택은 선수 상세에 다녀와도 그대로 둔다(화면이 다시 그려져도 모듈 값은 남는다).
  const view = $state<{ order: 'club' | 'recent' }>({ order: 'club' });
</script>

<script lang="ts">
  // T-10-076 기록실 '영구결번' 탭 — 서버의 모든 결번을 구단별(결번 많은 구단 먼저) 또는 최신순으로 본다.
  // 유니폼은 구단 엠블럼 색(rnStyle), 누르면 그 선수의 은퇴 상세.
  import type { RetiredNumbersResponse } from '@offside/contracts';
  import { defaultClubName, LEAGUE_BASE } from '@offside/contracts/club-names';
  import { getRetiredNumbers } from '../api/client.js';
  import { POS } from '../game/data.js';
  import { loadHOF } from '../game/season.js';
  import ClubMark from './ClubMark.svelte';
  import { anonName } from './format.js';
  import { openPublicLegendById } from './legend.js';
  import { RN_SHIRT, RN_TRIM, rnStyle } from './rnStyle.js';

  type Item = RetiredNumbersResponse['items'][number];

  let items = $state<Item[] | null>(null);
  let failed = $state(false);
  void getRetiredNumbers().then((r) => {
    if (r.ok) items = r.data.items;
    else failed = true;
  });

  const myIds = new Set(loadHOF().map((h) => h.id).filter(Boolean));
  const leagueOf = (clubId: string) =>
    LEAGUE_BASE.find((l) => l.id === clubId.slice(0, clubId.lastIndexOf('-')))?.name ?? '';
  /** 결번 당시 기록된 이름은 유저가 바꿔 부른 이름일 수 있다 — 모두가 보는 벽에는 게임 기본 이름을 건다. */
  const clubName = (it: Item) => defaultClubName(it.clubId) ?? it.club;
  const day = (iso: string) => {
    const d = new Date(iso);
    return `${d.getFullYear()}.${d.getMonth() + 1}.${d.getDate()}`;
  };

  /** 구단별 — 결번이 많은 구단 먼저, 같으면 먼저 결번을 낸 구단. 구단 안에서는 번호 순. */
  const clubs = $derived.by(() => {
    const by: Record<string, Item[]> = {};
    for (const it of items ?? []) (by[it.clubId] ??= []).push(it);
    return Object.values(by)
      .map((list) => list.sort((a, b) => a.number - b.number))
      .sort(
        (a, b) =>
          b.length - a.length ||
          Math.min(...a.map((x) => x.seq)) - Math.min(...b.map((x) => x.seq)),
      );
  });
  const recent = $derived([...(items ?? [])].sort((a, b) => b.seq - a.seq));
</script>

{#snippet tile(it: Item, withClub: boolean)}
  <button class="rn-tile" style={rnStyle(it.clubId)} data-rn-tile={it.seq} onclick={() => void openPublicLegendById(it.careerId)}>
    <svg class="rn-jersey rn-tile-shirt" viewBox="0 0 120 124" aria-hidden="true">
      <path class="rn-shirt" d={RN_SHIRT} />
      <path class="rn-trim" d={RN_TRIM} />
      <text class="rn-jersey-num" x="60" y="92">{it.number}</text>
    </svg>
    <b class="rn-tile-name">{it.name ?? anonName(it.pos, it.number)}</b>
    <span class="muted fs-xs">
      {#if withClub}<ClubMark name={it.club} id={it.clubId} size={14} /> {clubName(it)}{:else}{POS[it.pos].label}{/if}
    </span>
    <span class="muted fs-xs num">{it.seq}번째 · {day(it.grantedAt)}</span>
    {#if myIds.has(it.careerId)}<span class="pill rn-tile-mine">내 선수</span>{/if}
  </button>
{/snippet}

<section class="card" data-rn-wall>
  <div class="eyebrow">Retired Numbers</div>
  <h1 style="margin-bottom:6px">영구결번</h1>
  <p class="muted fs-sm rn-wall-lead">한 구단에서 오래, 크게 빛난 선수의 등번호는 그 구단에서 다시 쓰지 않습니다. 구단마다 한 번호에 한 명뿐입니다.</p>

  {#if items === null && !failed}
    <p class="empty">불러오는 중…</p>
  {:else if failed}
    <p class="empty">영구결번을 불러오지 못했습니다. 잠시 후 다시 시도해 주세요.</p>
  {:else if items?.length}
    <div class="rn-wall-sum">
      <div><b class="num">{items.length}</b><small>결번</small></div>
      <div><b class="num">{clubs.length}</b><small>구단</small></div>
      <div><b class="num">{day(recent[0]!.grantedAt)}</b><small>최근 결번</small></div>
    </div>
    <div class="hof-sorts" role="group" aria-label="정렬">
      <button class="hof-sort" aria-pressed={view.order === 'club'} data-rn-order="club" onclick={() => (view.order = 'club')}>구단별</button>
      <button class="hof-sort" aria-pressed={view.order === 'recent'} data-rn-order="recent" onclick={() => (view.order = 'recent')}>최신순</button>
    </div>
    {#if view.order === 'club'}
      {#each clubs as list (list[0]!.clubId)}
        {@const c = list[0]!}
        <div class="rn-club" data-rn-club={c.clubId}>
          <div class="rn-club-head">
            <ClubMark name={c.club} id={c.clubId} size={22} />
            <b>{clubName(c)}</b>
            <span class="muted fs-xs">{leagueOf(c.clubId)}</span>
            <span class="num rn-club-count">{list.length}</span>
          </div>
          <div class="rn-tiles">
            {#each list as it (it.seq)}{@render tile(it, false)}{/each}
          </div>
        </div>
      {/each}
    {:else}
      <div class="rn-tiles">
        {#each recent as it (it.seq)}{@render tile(it, true)}{/each}
      </div>
    {/if}
  {:else}
    <p class="empty">아직 영구결번이 없습니다. 한 구단의 전설이 되어 첫 번째 결번의 주인공이 되어 보세요.</p>
  {/if}
</section>
