// apps/mobile/src/screens/retired/Retired.tsx
// 은퇴 직후 화면(웹 Retired.svelte, ui.ts renderRetired() 포트). 리포트 본문은 LegendReport.
import { useMemo } from 'react';
import { useSnapshot } from 'valtio';
import { viewFromGame } from '../../game/host';
import { goHome, goNew } from '../../game/nav';
import { appState } from '../../store';
import { Btn } from '../../ui/Btn';
import { Topbar } from '../../ui/Topbar';
import { CreditScreen } from './credit';
import { LegendReport } from './LegendReport';
import { OwnHofCards } from './OwnHofCards';
import { ShareBar } from './ShareBar';

export default function Retired() {
  const snap = useSnapshot(appState);
  const hasG = !!snap.G;
  // 스냅숏(snap.G)이 바뀔 때만 다시 만든다 — viewFromGame은 원본 세이브를 읽는다.
  const v = useMemo(() => (hasG ? viewFromGame(appState.G!) : null), [snap.G]);
  if (!v) return null;
  return (
    <CreditScreen footer={v.shareId ? <ShareBar id={v.shareId} /> : null}>
      <Topbar />
      {/* T-10-029: 명예의 전당 공개·다음 버튼은 크레딧 맨 아래에, 공유 버튼은 화면 아래에 고정된다(T-10-067). */}
      <LegendReport
        v={v}
        end={
          <>
            {v.own?.id ? <OwnHofCards v={v} /> : null}
            <Btn kind="primary" block testID="new" onPress={goNew}>
              새 커리어 킥오프 →
            </Btn>
            <Btn block testID="home" onPress={goHome}>
              명예의 전당 보기
            </Btn>
          </>
        }
      />
    </CreditScreen>
  );
}

// apps/web/src/ui/Retired.svelte
<script lang="ts">
  // ui.ts renderRetired() 포트 (398~414줄). 리포트 본문은 LegendReport(T-10-005)로 옮겼다.
  import { appState } from './state.svelte.js';
  import { goHome, goNew } from './nav.js';
  import { viewFromGame } from './legend.js';
  import Topbar from './Topbar.svelte';
  import LegendReport from './LegendReport.svelte';
  import OwnHofCards from './OwnHofCards.svelte';
  import ShareBar from './ShareBar.svelte';

  const v = $derived(viewFromGame(appState.G!));
</script>

<div class="wrap">
  <Topbar />
  <!-- T-10-029: 명예의 전당 공개·다음 버튼은 크레딧 맨 아래에, 공유 버튼은 화면 아래에 고정된다(T-10-067). -->
  <LegendReport {v}>
    {#snippet end()}
      {#if v.own?.id}<OwnHofCards h={v.own} />{/if}
      <button class="btn btn-primary btn-block" data-act="new" onclick={goNew}>새 커리어 킥오프 →</button>
      <button class="btn btn-block" data-act="home" onclick={goHome}>명예의 전당 보기</button>
    {/snippet}
  </LegendReport>
  {#if v.shareId}<ShareBar id={v.shareId} />{/if}
</div>
