// apps/web/src/ui/tabs/CareerTab.svelte
<script lang="ts">
  // ui.ts careerTab() 포트 (371~387줄)
  import type { GameState, LegendSource } from '@offside/game/types';
  import { fmtValue, seasonLabelOf, totals } from '@offside/app-core/format';
  import ClubMark from '../ClubMark.svelte';
  import ValueChart from '../ValueChart.svelte';
  import { careerGoals, GOALS_NOTE } from '@offside/app-core/career-feedback';
  import { peakValue, seasonValue } from '@offside/contracts/market-value';

  // 은퇴 상세(LegendSource)에는 '다음 목표'가 없다 — 진행 중인 커리어(GameState)에서만 계산한다.
  // chart: 몸값 그래프·최고 몸값 줄. 은퇴 크레딧은 자기 '몸값 흐름' 장면이 있어 끈다(T-10-106).
  const { s, chart = true }: { s: LegendSource | GameState; chart?: boolean } = $props();
  const t = $derived(totals(s));
  const rows = $derived(s.career.slice().reverse());
  const miles = $derived((s.miles || []).slice().reverse());
  const next = $derived('attrs' in s && !s.retired ? careerGoals(s) : []);
  const peakV = $derived(chart ? peakValue(s.career) : null);
</script>

<section class="card stack">
  <div><div class="eyebrow">Career</div><h2>통산 기록</h2></div>
  <div class="totals">
    <div><b>{t.p}</b><span>경기</span></div>
    <div><b>{t.g}</b><span>골</span></div>
    {#if s.pos === 'GK' || s.pos === 'DF'}
      <div><b>{t.cs}</b><span>무실점</span></div>
    {:else}
      <div><b>{t.a}</b><span>도움</span></div>
    {/if}
    <div><b>{s.trophies.length + s.awards.length}</b><span>수상</span></div>
  </div>
  {#if peakV}
    <ValueChart rows={s.career} />
    <p class="muted fs-sm" data-peak-value>최고 몸값 <b>{fmtValue(peakV.value)}</b> · {seasonLabelOf(peakV.row)} {peakV.row.club}</p>
  {/if}
</section>
{#if next.length}
  <section class="card stack" data-career-goals>
    <div><div class="eyebrow">Next Goals</div><h2>다음 목표</h2></div>
    <p class="muted fs-sm">{GOALS_NOTE}</p>
    <div class="mile-next">
      {#each next as m, i (m.key)}
        <div class="mile-row">
          <div class="mile-lbl"><b>{m.label}</b><span>{m.have} / {m.target} · 남은 {m.remaining}</span></div>
          <div class="legend-bar" role="progressbar" aria-label={m.label} aria-valuemin={0} aria-valuemax={m.target} aria-valuenow={m.have}><i style="width:{Math.min(100, Math.round((m.have / m.target) * 100))}%;--d:{i * 90}ms"></i></div>
        </div>
      {/each}
    </div>
  </section>
{/if}
<section class="card stack">
  {#if s.career.length}
    <div class="table-wrap">
      <table>
        <thead>
          <tr><th>시즌</th><th>소속</th><th class="n">경기</th><th class="n">골</th><th class="n">도움</th><th class="n">평점</th><th class="n">순위</th><th class="n">OVR</th></tr>
        </thead>
        <tbody>
          {#each rows as r, i (i)}
            {@const sv = seasonValue(r)}
            <tr>
              <td>{r.mil ? r.year : seasonLabelOf(r)} <span class="muted">({r.age})</span>{#if r.ch?.length}<br /><span class="badge-ch">CH×{r.ch.length}</span>{/if}</td>
              <td><ClubMark name={r.club} id={r.clubId} /> {r.club}<div class="muted season-sub">{r.league}{sv ? ' · ' : ''}{#if sv}<span class="season-value" data-season-value>몸값 {fmtValue(sv)}</span>{/if}{r.honors.length ? ` · ` : ''}{#if r.honors.length}<span class="honor">{r.honors.join(', ')}</span>{/if}</div></td>
              <td class="n">{r.apps}</td>
              <td class="n">{r.goals}</td>
              <td class="n">{r.assists}</td>
              <td class="n">{r.rating ? r.rating.toFixed(2) : '-'}</td>
              <td class="n">{r.rank}</td>
              <td class="n">{r.ovr}</td>
            </tr>
          {/each}
        </tbody>
      </table>
    </div>
  {:else}
    <p class="empty">첫 시즌을 마치면 기록이 쌓여요.</p>
  {/if}
  <p class="muted fs-xs">경기·골·도움은 리그·컵·대륙 대회를 합친 공식전 기록이에요. 몸값은 시즌을 마친 때의 리그·OVR·나이로 매긴 이적료 기준 추정치예요.</p>
</section>
<section class="card">
  <div class="eyebrow">Journey</div>
  <h2 style="margin-bottom:4px">커리어 이정표</h2>
  {#if miles.length}
    {#each miles as m, i (i)}
      <div class="trophy"><span class="y">{m.year}</span><div><b>{m.t}</b></div></div>
    {/each}
  {:else}
    <p class="empty">프로 데뷔부터 이정표가 쌓여요.</p>
  {/if}
</section>

// apps/mobile/src/components/CareerTab.tsx
// 커리어 탭(웹 tabs/CareerTab.svelte, ui.ts careerTab 포트): 통산 기록 + 몸값 그래프 · 다음 목표 · 시즌별 기록 표 · 여정.
// 게임 화면의 커리어 탭과 은퇴 리포트 '자세히 보기'가 같이 쓴다.
import { useEffect, useRef, type ReactNode } from 'react';
import { Animated, Easing, ScrollView, View, type TextStyle } from 'react-native';
import { useSnapshot } from 'valtio';
import type { GameState, LegendSource } from '@offside/game/types';
import { fmtValue, seasonLabelOf, totals } from '@offside/app-core/format';
import { careerGoals, GOALS_NOTE } from '@offside/app-core/career-feedback';
import { peakValue, seasonValue } from '@offside/contracts/market-value';
import { prefs } from '../store';
import { alpha } from '../theme/colors';
import { useColors } from '../theme/useColors';
import { DISPLAY, num, rem } from '../theme/type';
import { Card } from '../ui/Card';
import { ClubMark } from '../ui/ClubBadge';
import { Txt } from '../ui/Txt';
import { ValueChart } from './ValueChart';

/** 표 칸 너비(웹 table은 nowrap이라 좁은 화면에선 옆으로 밀어 본다). */
const COL = { season: 100, club: 184, n: 46, rating: 52 };

// 은퇴 상세(LegendSource)에는 '다음 목표'가 없다 — 진행 중인 커리어(GameState)에서만 계산한다.
// chart: 몸값 그래프·최고 몸값 줄. 은퇴 크레딧은 자기 '몸값 흐름' 장면이 있어 끈다(T-10-106).
export function CareerTab({ s, chart = true }: { s: LegendSource | GameState; chart?: boolean }) {
  const c = useColors();
  const t = totals(s);
  const rows = s.career.slice().reverse();
  const miles = (s.miles || []).slice().reverse();
  const next = 'attrs' in s && !s.retired ? careerGoals(s) : [];
  const peakV = chart ? peakValue(s.career) : null;
  const back = s.pos === 'GK' || s.pos === 'DF';
  const totalCells: [number, string][] = [
    [t.p, '경기'],
    [t.g, '골'],
    back ? [t.cs, '무실점'] : [t.a, '도움'],
    [s.trophies.length + s.awards.length, '수상'],
  ];
  return (
    <>
      <Card>
        <View>
          <Txt v="eyebrow">Career</Txt>
          <Txt v="h2" accessibilityRole="header">
            통산 기록
          </Txt>
        </View>
        <View style={{ flexDirection: 'row', gap: 6 }}>
          {totalCells.map(([n, label]) => (
            <View
              key={label}
              style={{
                flex: 1,
                backgroundColor: c.surface2,
                borderRadius: 10,
                padding: 8,
                alignItems: 'center',
              }}
            >
              <Txt
                style={{
                  ...num(700),
                  fontSize: rem(1.625),
                  lineHeight: rem(1.625) * 1.1,
                }}
              >
                {n}
              </Txt>
              <Txt tone="muted" style={{ fontSize: rem(0.6875), lineHeight: rem(0.6875) * 1.5 }}>
                {label}
              </Txt>
            </View>
          ))}
        </View>
        {peakV ? (
          <>
            <ValueChart rows={s.career} />
            <Txt v="sm" tone="muted" testID="peak-value">
              최고 몸값{' '}
              <Txt v="sm" bold>
                {fmtValue(peakV.value)}
              </Txt>{' '}
              · {seasonLabelOf(peakV.row)} {peakV.row.club}
            </Txt>
          </>
        ) : null}
      </Card>
      {next.length ? (
        <Card>
          <View>
            <Txt v="eyebrow">Next Goals</Txt>
            <Txt v="h2" accessibilityRole="header">
              다음 목표
            </Txt>
          </View>
          <Txt v="sm" tone="muted">
            {GOALS_NOTE}
          </Txt>
          <View style={{ gap: 10 }} testID="career-goals">
            {next.map((m, i) => (
              <View key={m.key} style={{ gap: 4 }}>
                <View style={{ gap: 4 }}>
                  <Txt v="sm" style={{ fontWeight: '600' }}>
                    {m.label}
                  </Txt>
                  <Txt v="sm" tone="muted" style={{ fontVariant: ['tabular-nums'] }}>
                    {m.have} / {m.target} · 남은 {m.remaining}
                  </Txt>
                </View>
                <Fill pct={Math.min(100, Math.round((m.have / m.target) * 100))} delay={i * 90} />
              </View>
            ))}
          </View>
        </Card>
      ) : null}
      <Card>
        {s.career.length ? (
          <ScrollView horizontal showsHorizontalScrollIndicator={false} nestedScrollEnabled>
            <View>
              <View style={{ flexDirection: 'row' }}>
                <Th w={COL.season}>시즌</Th>
                <Th w={COL.club}>소속</Th>
                <Th w={COL.n} n>
                  경기
                </Th>
                <Th w={COL.n} n>
                  골
                </Th>
                <Th w={COL.n} n>
                  도움
                </Th>
                <Th w={COL.rating} n>
                  평점
                </Th>
                <Th w={COL.n} n>
                  순위
                </Th>
                <Th w={COL.n} n>
                  OVR
                </Th>
              </View>
              {rows.map((r, i) => {
                const sv = seasonValue(r);
                return (
                  <View key={i} style={{ flexDirection: 'row' }}>
                    <Td w={COL.season}>
                      <Txt style={cell}>
                        {r.mil ? r.year : seasonLabelOf(r)}{' '}
                        <Txt tone="muted" style={cell}>
                          ({r.age})
                        </Txt>
                      </Txt>
                      {r.ch?.length ? (
                        <View
                          style={{
                            alignSelf: 'flex-start',
                            borderRadius: 999,
                            paddingVertical: 2,
                            paddingHorizontal: 6,
                            backgroundColor: alpha(c.accent, 0.22),
                            borderWidth: 1,
                            borderColor: alpha(c.accent, 0.55),
                          }}
                        >
                          <Txt
                            style={{
                              fontSize: rem(0.625),
                              fontWeight: '700',
                              letterSpacing: rem(0.625) * 0.04,
                              color: c.accentText,
                            }}
                          >
                            CH×{r.ch.length}
                          </Txt>
                        </View>
                      ) : null}
                    </Td>
                    <Td w={COL.club}>
                      <View style={{ flexDirection: 'row', alignItems: 'center', gap: 4 }}>
                        <ClubMark name={r.club} id={r.clubId} />
                        <Txt style={[cell, { flexShrink: 1 }]}>{r.club}</Txt>
                      </View>
                      <Txt
                        tone="muted"
                        style={{ fontSize: rem(0.6875), lineHeight: rem(0.6875) * 1.5 }}
                      >
                        {r.league}
                        {sv ? ' · ' : ''}
                        {sv ? (
                          <Txt style={{ fontSize: rem(0.6875), fontWeight: '600' }}>
                            몸값 {fmtValue(sv)}
                          </Txt>
                        ) : null}
                        {r.honors.length ? ' · ' : ''}
                        {r.honors.length ? (
                          <Txt
                            style={{
                              fontSize: rem(0.6875),
                              fontWeight: '600',
                              color: c.accentText,
                            }}
                          >
                            {r.honors.join(', ')}
                          </Txt>
                        ) : null}
                      </Txt>
                    </Td>
                    <Td w={COL.n}>
                      <Txt style={numCell}>{r.apps}</Txt>
                    </Td>
                    <Td w={COL.n}>
                      <Txt style={numCell}>{r.goals}</Txt>
                    </Td>
                    <Td w={COL.n}>
                      <Txt style={numCell}>{r.assists}</Txt>
                    </Td>
                    <Td w={COL.rating}>
                      <Txt style={numCell}>{r.rating ? r.rating.toFixed(2) : '-'}</Txt>
                    </Td>
                    <Td w={COL.n}>
                      <Txt style={numCell}>{r.rank}</Txt>
                    </Td>
                    <Td w={COL.n}>
                      <Txt style={numCell}>{r.ovr}</Txt>
                    </Td>
                  </View>
                );
              })}
            </View>
          </ScrollView>
        ) : (
          <Txt tone="muted" style={{ fontSize: rem(0.875), paddingVertical: 8 }}>
            첫 시즌을 마치면 기록이 쌓여요.
          </Txt>
        )}
        <Txt v="xs" tone="muted">
          경기·골·도움은 리그·컵·대륙 대회를 합친 공식전 기록이에요. 몸값은 시즌을 마친 때의
          리그·OVR·나이로 매긴 이적료 기준 추정치예요.
        </Txt>
      </Card>
      <Card gap={0}>
        <Txt v="eyebrow">Journey</Txt>
        <Txt v="h2" accessibilityRole="header" style={{ marginBottom: 4 }}>
          커리어 이정표
        </Txt>
        {miles.length ? (
          miles.map((m, i) => (
            <View
              key={i}
              style={{
                flexDirection: 'row',
                alignItems: 'center',
                gap: 10,
                paddingVertical: 9,
                borderTopWidth: i ? 1 : 0,
                borderTopColor: c.line,
              }}
            >
              <Txt
                tone="muted"
                style={{
                  width: 44,
                  fontFamily: DISPLAY[600],
                  fontSize: rem(1.125),
                }}
              >
                {m.year}
              </Txt>
              <Txt style={{ flex: 1, fontWeight: '700' }}>{m.t}</Txt>
            </View>
          ))
        ) : (
          <Txt tone="muted" style={{ fontSize: rem(0.875), paddingVertical: 8 }}>
            프로 데뷔부터 이정표가 쌓여요.
          </Txt>
        )}
      </Card>
    </>
  );
}

const cell: TextStyle = { fontSize: rem(0.8125), lineHeight: rem(0.8125) * 1.4 };
const numCell: TextStyle = { ...cell, textAlign: 'right', fontVariant: ['tabular-nums'] };

function Th({ w, n, children }: { w: number; n?: boolean; children: string }) {
  const c = useColors();
  return (
    <View style={{ width: w, padding: 6, borderBottomWidth: 1, borderBottomColor: c.line }}>
      <Txt
        tone="muted"
        style={{
          fontSize: rem(0.75),
          fontWeight: '600',
          textAlign: n ? 'right' : 'left',
        }}
      >
        {children}
      </Txt>
    </View>
  );
}
function Td({ w, children }: { w: number; children: ReactNode }) {
  const c = useColors();
  return (
    <View
      style={{
        width: w,
        paddingVertical: 7,
        paddingHorizontal: 6,
        borderBottomWidth: 1,
        borderBottomColor: c.line,
        gap: 2,
      }}
    >
      {children}
    </View>
  );
}

/** 목표 진행 막대(웹 .legend-bar + fill 0.7s): 처음 그려질 때 왼쪽부터 찬다. */
function Fill({ pct, delay }: { pct: number; delay: number }) {
  const c = useColors();
  const { motionOK } = useSnapshot(prefs);
  const p = useRef(new Animated.Value(motionOK ? 0 : 1)).current;
  useEffect(() => {
    if (!motionOK) return p.setValue(1);
    const a = Animated.timing(p, {
      toValue: 1,
      duration: 700,
      delay,
      easing: Easing.bezier(0.2, 0.8, 0.2, 1),
      useNativeDriver: false,
    });
    a.start();
    return () => a.stop();
  }, [motionOK, delay, p]);
  return (
    <View
      style={{ height: 6, borderRadius: 3, backgroundColor: c.surface2, overflow: 'hidden' }}
      accessibilityRole="progressbar"
      accessibilityValue={{ min: 0, max: 100, now: pct }}
    >
      <Animated.View
        style={{
          height: '100%',
          backgroundColor: c.accent,
          width: p.interpolate({ inputRange: [0, 1], outputRange: ['0%', `${pct}%`] }),
        }}
      />
    </View>
  );
}
