// apps/web/src/ui/team/PlayerCard.svelte
<script lang="ts">
  import { intlLocale } from '@offside/contracts/i18n';
  import { tn } from '@offside/game/i18n/names';
  import { onMount } from 'svelte';
  import type { TeamPlayer } from '@offside/app-core/api/team';
  import { FACE_ABBR, GK_ABBR } from '@offside/game/attributes';
  import type { DetailPos } from '@offside/contracts/positions';
  import { DEFAULT_NATION, NATION_BY_CODE, flagOf } from '@offside/contracts/nations';
  import { cardFootNote, cardSeasonBadge, cardSeasonColor, cardTier, isLegendTier } from '@offside/app-core/format';
  import { teamSeasonLabel } from '@offside/app-core/seasonName';
  import { teamHomeText as L } from '@offside/app-core/i18n/ko/teamHome';

  let { player, name, rating, role, nation, season, compact = false, youth = false, deploymentRating, ratingLabel = L.peakOvr }:
    { player?: TeamPlayer | undefined; name: string; rating: number; role: DetailPos; nation?: string | null | undefined; season?: number | undefined; compact?: boolean; youth?: boolean; deploymentRating?: number | undefined; ratingLabel?: string } = $props();
  // T-11-114 카드 시즌 뱃지(유스 선수·시즌을 모르는 옛 응답은 없다).
  const cardSeason = $derived(youth ? undefined : (season ?? player?.season));
  const country = $derived(!youth ? NATION_BY_CODE.get(nation ?? player?.nation ?? DEFAULT_NATION) : undefined);
  const tier = $derived(youth ? 'youth' : cardTier(player?.legendScore, player?.peak ?? rating));
  const statKeys = $derived(player?.pos === 'GK' ? ['def', 'phy', 'pas', 'pac', 'sho', 'dri'] as const : ['pac', 'sho', 'dri', 'pas', 'def', 'phy'] as const);
  const statLabels = $derived(player?.pos === 'GK' ? GK_ABBR : FACE_ABBR);
  let nameViewport: HTMLElement;
  let viewportWidth = $state(0);
  let nameWidth = $state(0);
  let inView = $state(false);
  const nameOverflow = $derived(Math.max(0, nameWidth - viewportWidth));
  const nameDuration = $derived(Math.max(8, nameOverflow / 12 + 4));
  onMount(() => {
    const observer = new IntersectionObserver(([entry]) => (inView = !!entry?.isIntersecting));
    observer.observe(nameViewport);
    return () => observer.disconnect();
  });
  // 자리 OVR은 최고 OVR과 다를 때(제 자리가 아닐 때)만 — 같으면 같은 숫자가 두 번 보인다.
  const deployed = $derived(deploymentRating !== undefined && deploymentRating !== rating);
</script>

<div class="player-card" class:compact class:youth class:deployed data-tier={tier}>
  <div class="card-face">
    <div class="card-rating" title="{ratingLabel} {rating}"><b>{rating}</b><span>{role}</span></div>
    {#if cardSeason !== undefined}<span class="card-season" data-card-season={cardSeason} style:--season-bg={cardSeasonColor(cardSeason)} title={teamSeasonLabel(cardSeason)}>{cardSeasonBadge(cardSeason)}</span>{/if}
    {#if country}<span class="card-nation" role="img" aria-label={L.nationAria({ name: tn(country.ko) })} title={tn(country.ko)}>{flagOf(country.code)}</span>{/if}
    <div class="card-art" aria-hidden="true">
      <svg viewBox="0 0 100 96"><path d="M30 10 15 17 3 38 20 48 26 36 24 90 76 90 74 36 80 48 97 38 85 17 70 10 62 5Q50 16 38 5Z" /><path class="shirt-trim" d="M38 5Q50 25 62 5M25 73H75M34 12V87M66 12V87" /></svg>
      <span class="shirt-number">{player?.number ?? (youth ? '+' : name.slice(0, 1))}</span>
    </div>
    <strong class="card-name" class:scrolling={nameOverflow > 1} class:in-view={inView} title={name}
      bind:this={nameViewport} bind:clientWidth={viewportWidth} style:--name-offset="-{nameOverflow}px" style:--name-duration="{nameDuration}s">
      <span class="name-track" bind:offsetWidth={nameWidth}>{name}</span>
    </strong>
    {#if deployed && deploymentRating !== undefined}<span class="card-deployment" title={L.posOvr({ n: deploymentRating })}><span>{L.posOvrLabel}</span><b>{deploymentRating}</b></span>{/if}
    {#if !compact}
      <div class="card-divider"></div>
      <div class="card-career"><span title={L.legendScoreTitle}>LS</span><b>{(player?.legendScore ?? 0).toLocaleString(intlLocale())}</b></div>
      <dl class="card-attributes" aria-label={L.attributesAria}>
        {#each statKeys as key (key)}
          <div><dt>{statLabels[key]}</dt><dd>{player?.attrs ? Math.round(player.attrs[key]) : '—'}</dd></div>
        {/each}
      </dl>
      <div class="card-foot">{cardFootNote(player ?? {}) ?? (isLegendTier(tier) ? L.footLegend : L.footMine)}</div>
    {/if}
  </div>
</div>

<style>
  .player-card { --card-base:#e8d5a8; --card-light:#fff2ce; --card-dark:#8a6324; --card-ink:#392b14; --card-line:#b79654; width:100%; padding:2px; background:var(--card-line); clip-path:polygon(0 9%,16% 9%,25% 2%,50% 0,75% 2%,84% 9%,100% 9%,98% 84%,86% 93%,50% 100%,14% 93%,2% 84%); filter:drop-shadow(0 4px 5px #0003); }
  .player-card[data-tier='icon'] { --card-base:#1d2547; --card-light:#4a5a92; --card-dark:#0a0f26; --card-ink:#ffe9b0; --card-line:#e6c369; }
  .player-card[data-tier='legend'] { --card-base:#28382e; --card-light:#51614b; --card-dark:#101e17; --card-ink:#fce7b1; --card-line:#d1ac5f; }
  .player-card[data-tier='elite'] { --card-base:#f1c654; --card-light:#fff4bf; --card-dark:#a36f12; --card-ink:#3b2604; --card-line:#d99a1e; }
  .player-card[data-tier='silver'] { --card-base:#d6dfe0; --card-light:#f8faf6; --card-dark:#83989c; --card-ink:#243339; --card-line:#9fb3b6; }
  .player-card[data-tier='bronze'] { --card-base:#d7a27a; --card-light:#f6d6bb; --card-dark:#7d4a29; --card-ink:#3a1f0e; --card-line:#a86e45; }
  .player-card[data-tier='youth'] { --card-base:#d5e4d8; --card-light:#eaf3e9; --card-dark:#9bae9b; --card-ink:#365342; --card-line:#8cab97; opacity:.82; }
  .card-face { position:relative; overflow:hidden; min-height:183px; padding:28px 10px 20px; clip-path:inherit; background:linear-gradient(135deg,transparent 34%,#ffffff25 34.5%,transparent 35%,transparent 62%,#ffffff1c 62.5%,transparent 63%),radial-gradient(ellipse at 80% 10%,var(--card-light),transparent 70%),linear-gradient(165deg,var(--card-base),var(--card-dark)); color:var(--card-ink); }
  .card-rating { position:absolute; top:28px; left:11px; display:flex; flex-direction:column; align-items:center; z-index:1; }
  .card-rating b { font-family:var(--display); font-size:2.3rem; font-weight:800; line-height:.9; }
  .card-rating span { font-family:var(--display); font-size:.82rem; font-weight:700; line-height:1; margin-top:4px; }
  .card-nation {position:absolute;top:82px;left:11px;z-index:1;width:36px;text-align:center;font-family:system-ui,sans-serif;font-size:18px;line-height:18px;}
  /* T-11-114 시즌 뱃지(색은 cardSeasonColor). */
  .card-season {position:absolute;top:9px;left:50%;transform:translateX(-50%);z-index:1;padding:2px 5px 1px;border-radius:3px;background:var(--season-bg);color:#fff;font:800 9px/1.1 system-ui,sans-serif;letter-spacing:.06em;box-shadow:0 0 0 1px #ffffff55 inset;}
  .compact .card-season {top:4px;padding:1px 3px 0;font-size:7px;}
  .card-deployment {display:flex;flex-direction:column;align-items:center;font-size:8px;line-height:10px;}
  .card-deployment b {font-family:var(--display);font-size:12px;line-height:13px;}
  .card-art { position:relative; height:72px; margin-left:26px; }
  .card-art svg { width:100%; height:100%; fill:var(--card-dark); stroke:var(--card-ink); stroke-opacity:.4; stroke-width:1.4; }
  .card-art .shirt-trim { fill:none; stroke:var(--card-light); stroke-width:2; stroke-opacity:.65; }
  .shirt-number { position:absolute; inset:25% 0 0; display:flex; align-items:center; justify-content:center; font-family:var(--display); font-size:1.8rem; font-weight:700; }
  .card-name { display:block; margin-top:4px; text-align:center; font-size:.88rem; white-space:nowrap; overflow:hidden; line-height:1.6; }
  .name-track {display:inline-block;width:max-content;vertical-align:top;}
  .card-name.scrolling {text-align:left;}
  .card-name.scrolling .name-track {animation:card-name-scroll var(--name-duration) linear infinite;}
  .card-name:not(.in-view) .name-track,
  .player-card:hover .name-track,
  .player-card:active .name-track,
  :global(button:focus-visible) .name-track {animation-play-state:paused;}
  @keyframes card-name-scroll {0%,15% {transform:translateX(0);} 85%,100% {transform:translateX(var(--name-offset));}}
  @media(prefers-reduced-motion:reduce) {
    .card-name.scrolling {overflow-x:auto;scrollbar-width:none;}
    .card-name.scrolling .name-track {animation:none;}
    .card-name::-webkit-scrollbar {display:none;}
  }
  .card-divider { height:1px; background:var(--card-ink); opacity:.25; margin:4px 0 6px; }
  .card-career { display:flex;justify-content:center;align-items:baseline;gap:4px;font-size:.72rem; }
  .card-career b { font-family:var(--display); font-size:1.15rem; }
  .card-attributes {display:grid;grid-template-columns:repeat(3,minmax(0,1fr));gap:6px 4px;margin:8px 0 0;text-align:center;}
  .card-attributes dt {font-size:10px;line-height:1.3;font-weight:600;}
  .card-attributes dd {margin:0;font-family:var(--display);font-size:1.25rem;line-height:1.1;font-weight:700;}
  .card-foot { font-size:.6rem; text-align:center; margin-top:7px; opacity:.8; }
  .compact .card-face { min-height:0; height:100px; padding:11px 4px 13px; }
  .compact .card-rating { top:14px; left:7px; }
  .compact .card-rating b { font-size:1.6rem; }
  .compact .card-rating span { font-size:.62rem; margin-top:2px; }
  .compact .card-nation {top:13px;left:auto;right:5px;width:16px;font-size:12px;line-height:14px;}
  .compact .card-art { height:48px; margin:10px 0 0 17px; }
  .compact .shirt-number { font-size:1.15rem; }
  .compact .card-name { font-size:11px; margin-top:3px; }
  .compact.deployed .card-art {height:36px;}
  @media(max-width:440px) { .compact .card-face { height:88px; padding:8px 3px 10px; } .compact .card-rating { left:5px;top:11px; } .compact .card-season {top:2px;} .compact .card-rating b { font-size:1.3rem; } .compact .card-art { height:34px;margin-top:8px; } .compact .shirt-number {font-size:1rem;} .compact.deployed .card-art {height:24px;} }
</style>

// apps/mobile/src/components/PlayerCard.tsx
import { useEffect, useId, useRef, useState } from 'react';
import { Animated, Easing, Text, View } from 'react-native';
import Svg, { Defs, LinearGradient, Path, Stop, Text as SvgText } from 'react-native-svg';
import { useSnapshot } from 'valtio';
import { prefs } from '../store';
import { DISPLAY } from '../theme/type';
import { RN_SHIRT, RN_TRIM } from '@offside/app-core/rnStyle';
import { FACE_ABBR, GK_ABBR } from '@offside/game/attributes';
import type { TeamPlayer } from '@offside/app-core/api/team';
import { DEFAULT_NATION, NATION_BY_CODE, flagOf } from '@offside/contracts/nations';
import { teamHomeText as L } from '@offside/app-core/i18n/ko/teamHome';
import { cardFootNote, cardSeasonBadge, cardSeasonColor, cardTier } from '@offside/app-core/format';
import { intlLocale } from '@offside/app-core/i18n/core';
import { tn } from '@offside/game/i18n/names';
import { teamSeasonLabel } from '@offside/app-core/seasonName';

/** Only overflowing names move; reduced motion keeps the full name accessible. */
function CardName({
  name,
  color,
  animate,
  compact,
}: {
  name: string;
  color: string;
  animate: boolean;
  compact: boolean;
}) {
  const { motionOK } = useSnapshot(prefs);
  const [width, setWidth] = useState(0);
  const [textWidth, setTextWidth] = useState(0);
  const offset = useRef(new Animated.Value(0)).current;
  useEffect(() => {
    offset.setValue(0);
    const distance = textWidth - width;
    if (distance <= 1 || !motionOK || !animate || !width) return;
    const loop = Animated.loop(
      Animated.sequence([
        Animated.delay(2000),
        Animated.timing(offset, {
          toValue: -distance,
          duration: Math.max(4500, distance * 100),
          easing: Easing.linear,
          useNativeDriver: true,
        }),
        Animated.delay(2000),
        Animated.timing(offset, { toValue: 0, duration: 0, useNativeDriver: true }),
      ]),
    );
    loop.start();
    return () => loop.stop();
  }, [textWidth, width, name, motionOK, animate, offset]);
  const style = {
    fontSize: compact ? 10.5 : 12,
    lineHeight: compact ? 16 : 19,
    fontWeight: '700' as const,
    color,
    includeFontPadding: false,
  };
  return (
    <View
      onLayout={(e) => setWidth(e.nativeEvent.layout.width)}
      style={{
        width: '100%',
        height: compact ? 18 : 23,
        overflow: 'hidden',
        justifyContent: 'center',
      }}
    >
      <Text
        accessible={false}
        maxFontSizeMultiplier={1.2}
        onTextLayout={(e) => setTextWidth(e.nativeEvent.lines[0]?.width ?? 0)}
        style={[style, { position: 'absolute', width: 2000, opacity: 0 }]}
      >
        {name}
      </Text>
      <Animated.Text
        accessibilityLabel={name}
        maxFontSizeMultiplier={1.2}
        numberOfLines={1}
        adjustsFontSizeToFit={!animate || !motionOK}
        minimumFontScale={0.5}
        style={[
          style,
          {
            width: animate && motionOK ? Math.max(width, textWidth) : width,
            textAlign: animate && motionOK && textWidth > width ? 'left' : 'center',
            transform: [{ translateX: offset }],
          },
        ]}
      >
        {name}
      </Animated.Text>
    </View>
  );
}

/** Collectible-card materials stay readable against both app themes and the pitch. */
export const CARD_TONES = {
  bronze: {
    light: '#f6dcc6',
    base: '#dcab84',
    shade: '#b97e55',
    line: '#8f5a35',
    ink: '#3a1f0e',
    shirt: '#6b3d20',
    shirtInk: '#f6dcc6',
  },
  silver: {
    light: '#f5f8fa',
    base: '#d8e2e6',
    shade: '#b2c3cd',
    line: '#839ba9',
    ink: '#223743',
    shirt: '#365464',
    shirtInk: '#f5f8fa',
  },
  gold: {
    light: '#fff2cd',
    base: '#ead096',
    shade: '#c29b50',
    line: '#a97b2f',
    ink: '#46320f',
    shirt: '#705025',
    shirtInk: '#fff2cd',
  },
  elite: {
    light: '#fff4c4',
    base: '#f2c95c',
    shade: '#d39a26',
    line: '#a8700f',
    ink: '#3b2604',
    shirt: '#7a5008',
    shirtInk: '#fff4c4',
  },
  legend: {
    light: '#3c5448',
    base: '#1d3529',
    shade: '#10271c',
    line: '#d7b56b',
    ink: '#ffedbd',
    shirt: '#d7b56b',
    shirtInk: '#10271c',
  },
  icon: {
    light: '#4a5a92',
    base: '#1d2547',
    shade: '#0f1633',
    line: '#e6c369',
    ink: '#ffe9b0',
    shirt: '#e6c369',
    shirtInk: '#0f1633',
  },
  youth: {
    light: '#edf5ed',
    base: '#d4e5d5',
    shade: '#acc8b2',
    line: '#78987f',
    ink: '#284b35',
    shirt: '#375e42',
    shirtInk: '#edf5ed',
  },
} as const;

function CardShirt({
  number,
  youth,
  width,
  tone,
}: {
  number: number | null | undefined;
  youth: boolean;
  width: number;
  tone: (typeof CARD_TONES)[keyof typeof CARD_TONES];
}) {
  return (
    <Svg
      width={width}
      height={(width * 124) / 120}
      viewBox="0 0 120 124"
      accessibilityElementsHidden
      importantForAccessibility="no-hide-descendants"
    >
      <Path d={RN_SHIRT} fill={tone.shirt} stroke={tone.ink} strokeOpacity={0.4} strokeWidth={2} />
      <Path d={RN_TRIM} fill="none" stroke={tone.light} strokeWidth={4} />
      <SvgText
        x={60}
        y={92}
        textAnchor="middle"
        fontFamily={DISPLAY[700]}
        fontSize={46}
        fill={tone.shirtInk}
      >
        {number ?? (youth ? '+' : '')}
      </SvgText>
    </Svg>
  );
}

export type PlayerCardData = {
  name: string;
  nation?: string | null;
  rating: number;
  peak?: number;
  number?: number | null;
  legendScore?: number | null;
  attrs?: TeamPlayer['attrs'];
  attrsEstimated?: boolean;
  /** T-11-080 카드 기준가(만 원). */
  cardValue?: number | null | undefined;
  pos?: TeamPlayer['pos'];
  /** T-11-114 카드 시즌(0 = 프리시즌) — 뱃지. 모르면 없다. */
  season?: number | undefined;
  youth: boolean;
};

/** T-11-114 카드 시즌 뱃지(웹 PlayerCard .card-season). */
function SeasonBadge({ season, compact }: { season: number; compact: boolean }) {
  return (
    <View
      accessibilityLabel={teamSeasonLabel(season)}
      style={{
        position: 'absolute',
        top: 26,
        right: compact ? 4 : 11,
        paddingHorizontal: compact ? 3 : 5,
        paddingVertical: 1,
        borderRadius: 3,
        backgroundColor: cardSeasonColor(season),
        borderWidth: 0.5,
        borderColor: '#ffffff55',
      }}
    >
      <Text
        maxFontSizeMultiplier={1.1}
        style={{
          color: '#fff',
          fontSize: compact ? 7 : 9,
          lineHeight: compact ? 9 : 11,
          fontWeight: '800',
          letterSpacing: 0.5,
          includeFontPadding: false,
        }}
      >
        {cardSeasonBadge(season)}
      </Text>
    </View>
  );
}

const CARD_STATS = {
  field: ['pac', 'sho', 'dri', 'pas', 'def', 'phy'],
  GK: ['def', 'phy', 'pas', 'pac', 'sho', 'dri'],
} as const;

function CardAttributes({ cell, color }: { cell: PlayerCardData; color: string }) {
  const order = CARD_STATS[cell.pos === 'GK' ? 'GK' : 'field'];
  const labels = cell.pos === 'GK' ? GK_ABBR : FACE_ABBR;
  const foot = cardFootNote(cell);
  return (
    <View style={{ width: '100%', marginTop: 8 }}>
      <View style={{ flexDirection: 'row', flexWrap: 'wrap', rowGap: 4 }}>
        {order.map((key) => (
          <View key={key} style={{ width: '33.333%', height: 34, alignItems: 'center' }}>
            <Text
              maxFontSizeMultiplier={1.15}
              style={{
                color,
                fontSize: 10,
                lineHeight: 12,
                fontWeight: '600',
                includeFontPadding: false,
              }}
            >
              {labels[key]}
            </Text>
            <Text
              numberOfLines={1}
              adjustsFontSizeToFit
              maxFontSizeMultiplier={1.1}
              style={{
                color,
                fontFamily: DISPLAY[700],
                fontSize: 19,
                lineHeight: 22,
                includeFontPadding: false,
              }}
            >
              {cell.attrs ? Math.round(cell.attrs[key]) : '—'}
            </Text>
          </View>
        ))}
      </View>
      {foot ? (
        <Text
          maxFontSizeMultiplier={1.15}
          style={{ color, fontSize: 10, lineHeight: 14, textAlign: 'center', marginTop: 4 }}
        >
          {foot}
        </Text>
      ) : null}
    </View>
  );
}

export function PlayerCard({
  cell,
  code,
  compact = false,
  animate = true,
}: {
  cell: PlayerCardData;
  code: string;
  compact?: boolean;
  animate?: boolean;
}) {
  const country = !cell.youth ? NATION_BY_CODE.get(cell.nation ?? DEFAULT_NATION) : undefined;
  const tone =
    CARD_TONES[cell.youth ? 'youth' : cardTier(cell.legendScore, cell.peak ?? cell.rating)];
  const uid = useId().replace(/[^a-zA-Z0-9]/g, '');
  const [cardWidth, setCardWidth] = useState(compact ? 62 : 100);
  const shirtWidth = compact ? 25 : Math.min(43, Math.max(24, cardWidth - 56));
  // 자리 OVR은 최고 OVR과 다를 때(제 자리가 아닐 때)만 — 같으면 같은 숫자가 두 번 보인다(웹 PlayerCard).
  const deployed = cell.peak !== undefined && cell.peak !== cell.rating;
  const height = compact ? 88 : 242 + (deployed ? 31 : 0);
  const shield = 'M2 14H17L25 5L50 1L75 5L83 14H98L97 149L88 161L50 173L12 161L3 149Z';
  return (
    <View
      onLayout={(e) => setCardWidth(e.nativeEvent.layout.width)}
      style={{
        width: '100%',
        height,
        paddingHorizontal: compact ? 5 : 8,
        paddingTop: compact ? 8 : 22,
        alignItems: 'center',
      }}
    >
      <Svg
        width={cardWidth}
        height={height}
        viewBox="0 0 100 174"
        preserveAspectRatio="none"
        style={{ position: 'absolute', left: 0, top: 0 }}
        pointerEvents="none"
        accessibilityElementsHidden
        importantForAccessibility="no-hide-descendants"
      >
        <Defs>
          <LinearGradient id={`${uid}face`} x1="0" y1="0" x2="1" y2="1">
            <Stop offset="0" stopColor={tone.light} />
            <Stop offset="0.5" stopColor={tone.base} />
            <Stop offset="1" stopColor={tone.shade} />
          </LinearGradient>
        </Defs>
        <Path d={shield} fill={`url(#${uid}face)`} stroke={tone.line} strokeWidth="1.5" />
        <Path
          d="M7 21H20L28 12L50 8L72 12L80 21H93M8 147L16 157L50 166L84 157L92 147"
          fill="none"
          stroke={tone.light}
          strokeOpacity={0.7}
          strokeWidth={1}
        />
        <Path
          d="M43 26L91 44M41 33L90 51M40 40L89 58"
          fill="none"
          stroke={tone.line}
          strokeOpacity={0.18}
          strokeWidth={1}
        />
      </Svg>
      <View
        style={{
          flexDirection: 'row',
          width: '100%',
          height: compact ? 34 : 72,
          alignItems: 'flex-start',
          justifyContent: 'space-between',
        }}
      >
        <View style={{ alignItems: 'center', width: compact ? 25 : 36 }}>
          <Text
            numberOfLines={1}
            adjustsFontSizeToFit={!compact}
            minimumFontScale={0.8}
            maxFontSizeMultiplier={1.1}
            style={{
              fontFamily: DISPLAY[800],
              fontSize: compact ? ((cell.peak ?? cell.rating) >= 100 ? 17 : 22) : 32,
              lineHeight: compact ? 24 : 39,
              width: '100%',
              textAlign: 'center',
              color: tone.ink,
              includeFontPadding: false,
            }}
          >
            {cell.peak ?? cell.rating}
          </Text>
          <Text
            numberOfLines={1}
            maxFontSizeMultiplier={1.1}
            style={{
              fontFamily: DISPLAY[700],
              fontSize: compact ? 9 : 12,
              lineHeight: compact ? 10 : 15,
              color: tone.ink,
              includeFontPadding: false,
            }}
          >
            {code}
          </Text>
          {!compact && country ? (
            <Text
              accessibilityLabel={L.nationAria({ name: tn(country.ko) })}
              maxFontSizeMultiplier={1.1}
              style={{ fontSize: 18, lineHeight: 18, marginTop: 2, includeFontPadding: false }}
            >
              {flagOf(country.code)}
            </Text>
          ) : null}
        </View>
        <View
          style={{
            marginTop: compact ? 4 : 9,
            alignItems: 'center',
            flex: compact ? undefined : 1,
            minWidth: 0,
          }}
        >
          <CardShirt number={cell.number} youth={cell.youth} width={shirtWidth} tone={tone} />
          {!compact && cell.legendScore != null ? (
            <Text
              numberOfLines={1}
              adjustsFontSizeToFit
              minimumFontScale={0.7}
              maxFontSizeMultiplier={1.15}
              style={{
                width: '100%',
                textAlign: 'center',
                color: tone.ink,
                fontSize: 9,
                lineHeight: 13,
                marginTop: 3,
                includeFontPadding: false,
              }}
            >
              LS{' '}
              <Text style={{ fontFamily: DISPLAY[700], fontSize: 11 }}>
                {cell.legendScore.toLocaleString(intlLocale())}
              </Text>
            </Text>
          ) : null}
        </View>
      </View>
      {compact && country ? (
        <Text
          accessibilityLabel={L.nationAria({ name: tn(country.ko) })}
          maxFontSizeMultiplier={1.1}
          style={{
            position: 'absolute',
            top: 11,
            right: 5,
            fontSize: 11,
            lineHeight: 13,
            includeFontPadding: false,
          }}
        >
          {flagOf(country.code)}
        </Text>
      ) : null}
      {!cell.youth && cell.season !== undefined ? (
        <SeasonBadge season={cell.season} compact={compact} />
      ) : null}
      <View
        style={{
          width: '100%',
          marginTop: compact ? 1 : 3,
          paddingHorizontal: 1,
          borderTopWidth: 0.5,
          borderBottomWidth: 0.5,
          borderColor: tone.line,
        }}
      >
        <CardName name={cell.name} color={tone.ink} animate={animate} compact={compact} />
      </View>
      {deployed ? (
        <View style={{ alignItems: 'center', marginTop: 2 }}>
          <Text
            maxFontSizeMultiplier={1.1}
            style={{
              color: tone.ink,
              fontSize: compact ? 7.5 : 10,
              lineHeight: compact ? 9 : 12,
              includeFontPadding: false,
            }}
          >
            {L.posOvrLabel}
          </Text>
          <Text
            maxFontSizeMultiplier={1.1}
            style={{
              color: tone.ink,
              fontFamily: DISPLAY[700],
              fontSize: compact ? 12 : 14,
              lineHeight: compact ? 12 : 17,
              includeFontPadding: false,
            }}
          >
            {cell.rating}
          </Text>
        </View>
      ) : null}
      {!compact ? <CardAttributes cell={cell} color={tone.ink} /> : null}
    </View>
  );
}
