// apps/web/src/ui/SiteFooter.svelte
<script lang="ts">
  import { DC_GALLERY_URL } from '@offside/app-core/links';
  import { shellText as L } from '@offside/app-core/i18n/ko/shell';
</script>

<!-- 문의·SNS 링크 푸터 — 홈과 설정 화면 맨 아래에 같은 모양으로 둔다. -->
<footer class="site-foot">
  <p>{L.footContact} <a href="mailto:contact@offside-lab.com">contact@offside-lab.com</a></p>
  <p>
    Instagram <a href="https://www.instagram.com/offside.lab.kr/" target="_blank" rel="noopener noreferrer">@offside.lab.kr</a>
    · Threads <a href="https://www.threads.com/@offside.lab.kr" target="_blank" rel="noopener noreferrer">@offside.lab.kr</a>
  </p>
  <p>{L.footCommunity} <a href={DC_GALLERY_URL} target="_blank" rel="noopener noreferrer">{L.footGallery}</a></p>
</footer>

// apps/mobile/src/components/SiteFooter.tsx
// 문의·SNS 링크 푸터(웹 SiteFooter.svelte) — 홈과 설정 화면 맨 아래.
import { Linking, View } from 'react-native';
import { DC_GALLERY_URL } from '@offside/app-core/links';
import { rem } from '../theme/type';
import { Txt } from '../ui/Txt';
import { shellText as L } from '@offside/app-core/i18n/ko/shell';

function Link({ href, children }: { href: string; children: string }) {
  return (
    <Txt
      accessibilityRole="link"
      tone="accent"
      onPress={() => void Linking.openURL(href)}
      style={{ fontSize: rem(0.75), fontWeight: '600' }}
    >
      {children}
    </Txt>
  );
}

export function SiteFooter() {
  return (
    <View style={{ alignItems: 'center', gap: 4, paddingTop: 8, paddingBottom: 20 }}>
      <Txt tone="muted" style={{ fontSize: rem(0.75) }}>
        {L.footContact} <Link href="mailto:contact@offside-lab.com">contact@offside-lab.com</Link>
      </Txt>
      <Txt tone="muted" style={{ fontSize: rem(0.75) }}>
        Instagram <Link href="https://www.instagram.com/offside.lab.kr/">@offside.lab.kr</Link> ·
        Threads <Link href="https://www.threads.com/@offside.lab.kr">@offside.lab.kr</Link>
      </Txt>
      <Txt tone="muted" style={{ fontSize: rem(0.75) }}>
        {L.footCommunity} <Link href={DC_GALLERY_URL}>{L.footGallery}</Link>
      </Txt>
    </View>
  );
}
