// apps/web/src/ui/team/TeamSynergy.svelte
<script lang="ts">
  // T-11-105 팀 시너지 — 규칙 전부를 적용 중 → 효과 없음 → 미적용 순으로 보인다. 켜진 시너지는 누르면 그라운드에서 그 선수들을 잇는다.
  import { DUO_LINE_CAP, DUO_TOTAL_CAP, synergyPower, type TeamSynergy } from '@offside/contracts/owner-team';
  import { synergyRows, synergyNote } from '@offside/app-core/teamOwner';
  import { teamSynergyText as L } from '@offside/app-core/i18n/ko/teamSynergy';

  let { synergy, season, focus = $bindable(null) }: { synergy: TeamSynergy; season: number; focus?: string | null } = $props();
  const power = $derived(synergyPower(synergy));
  const rows = $derived(synergyRows(synergy));
  const anyOn = $derived(rows.some((r) => r.state !== 'off'));
  const stateText = { applied: L.chipApplied, noEffect: L.chipNoEffect, off: L.chipOff };
</script>

{#snippet body(r: (typeof rows)[number])}
  <span class="mark" aria-hidden="true">{#if r.state === 'applied'}<svg viewBox="0 0 12 12"><path d="M2.5 6.2 5 8.6 9.6 3.6" /></svg>{/if}</span>
  <span class="text"><b>{r.name}</b><span class="desc">{r.desc}</span></span>
  <span class="side"><small>{r.effect}</small><em class="state">{focus === r.id ? L.chipViewing : stateText[r.state]}</em></span>
{/snippet}

<section class="syn" data-team-synergy aria-label={L.title}>
  <header>
    <h3>{L.title}{#if power > 0}<b>+{power}</b>{/if}</h3>
    <span class="note">{synergyNote(season)}</span>
  </header>
  <p class="muted hint">{anyOn ? L.chipHint : L.empty}</p>
  <ul class="rows">
    {#each rows as r (r.id)}
      <li>
        {#if r.state === 'off'}
          <div class="row" data-synergy={r.id} data-state={r.state}>{@render body(r)}</div>
        {:else}
          <button class="row" class:dashed={r.badge} data-synergy={r.id} data-state={r.state} aria-pressed={focus === r.id}
            onclick={() => (focus = focus === r.id ? null : r.id)}>{@render body(r)}</button>
        {/if}
      </li>
    {/each}
  </ul>
  <p class="muted cap">{L.capNote({ line: DUO_LINE_CAP, total: DUO_TOTAL_CAP })}</p>
</section>

<style>
  .syn {padding:12px 14px;border-bottom:1px solid var(--line);display:grid;gap:8px;}
  header {display:flex;align-items:baseline;justify-content:space-between;gap:8px;flex-wrap:wrap;}
  h3 {margin:0;font-size:15px;display:flex;gap:6px;align-items:baseline;}
  h3 b {color:var(--accent-text);font-family:var(--display);}
  .note {font-size:12px;color:var(--muted);}
  .hint, .cap {margin:0;font-size:11px;}
  .rows {list-style:none;margin:0;padding:0;display:grid;gap:6px;}
  .row {width:100%;display:grid;grid-template-columns:16px minmax(0,1fr) auto;gap:8px;align-items:center;text-align:left;padding:8px 10px;border-radius:10px;border:1px solid var(--line);background:var(--surface-2);color:inherit;font:inherit;}
  button.row {cursor:pointer;}
  .mark {width:16px;height:16px;border-radius:50%;display:grid;place-items:center;border:1px solid var(--line);}
  .mark svg {width:11px;height:11px;fill:none;stroke:var(--accent-ink);stroke-width:2.2;stroke-linecap:round;stroke-linejoin:round;}
  .text {display:grid;gap:1px;min-width:0;}
  .text b {font-size:13px;}
  .desc {font-size:11px;color:var(--muted);}
  .side {display:grid;justify-items:end;gap:3px;}
  .side small {font-size:11px;color:var(--muted);white-space:nowrap;}
  .state {font-style:normal;font-size:10px;font-weight:700;padding:1px 7px;border-radius:999px;border:1px solid var(--line);color:var(--muted);white-space:nowrap;}
  /* 적용 중은 모두 같은 모습. 누른 줄은 고른 것처럼 보이지 않게 배경만 바꾸고 '보는 중'을 단다. */
  .row[data-state='applied'] {border-color:color-mix(in srgb,var(--accent),transparent 55%);}
  .row[data-state='applied'] .mark {background:var(--accent);border-color:var(--accent);}
  .row[data-state='applied'] .side small {color:var(--accent-text);}
  .row[data-state='applied'] .state {border-color:color-mix(in srgb,var(--accent),transparent 50%);color:var(--accent-text);}
  .row[aria-pressed='true'] {background:color-mix(in srgb,var(--accent),var(--surface-2) 82%);}
  .row[aria-pressed='true'] .state {border-color:var(--accent);background:var(--accent);color:var(--accent-ink);}
  .row.dashed {border-style:dashed;}
  .row[data-state='off'] {background:transparent;opacity:.62;}
  .row[data-state='off'] .mark {border-style:dashed;}
  @media(max-width:440px) { .row {grid-template-columns:16px minmax(0,1fr);} .side {grid-column:2;justify-items:start;grid-auto-flow:column;justify-content:start;align-items:center;gap:6px;} }
</style>

// apps/mobile/src/components/TeamSynergy.tsx
// T-11-105 팀 시너지 — 규칙 전부를 적용 중 → 효과 없음 → 미적용 순으로 보인다(웹 team/TeamSynergy.svelte와 같은 내용).
// 켜진 시너지는 누르면 그라운드에서 그 선수들을 잇는다. 누르는 것과 상관없이 켜진 것은 모두 적용된다.
import { View } from 'react-native';
import {
  DUO_LINE_CAP,
  DUO_TOTAL_CAP,
  synergyPower,
  type TeamSynergy as Synergy,
} from '@offside/contracts/owner-team';
import { synergyRows, synergyNote, type SynergyRow } from '@offside/app-core/teamOwner';
import { teamSynergyText as L } from '@offside/app-core/i18n/ko/teamSynergy';
import { useColors } from '../theme/useColors';
import { Press } from '../ui/Press';
import { Txt } from '../ui/Txt';

export function TeamSynergy({
  synergy,
  season,
  focus,
  setFocus,
}: {
  synergy: Synergy;
  season: number;
  focus: string | null;
  setFocus: (id: string | null) => void;
}) {
  const c = useColors();
  const power = synergyPower(synergy);
  const rows = synergyRows(synergy);
  const anyOn = rows.some((r) => r.state !== 'off');
  const stateText = { applied: L.chipApplied, noEffect: L.chipNoEffect, off: L.chipOff };
  const row = (r: SynergyRow) => {
    const viewing = focus === r.id;
    const applied = r.state === 'applied';
    const state = viewing ? L.chipViewing : stateText[r.state];
    const body = (
      <>
        <View
          style={{
            width: 16,
            height: 16,
            borderRadius: 8,
            alignItems: 'center',
            justifyContent: 'center',
            borderWidth: 1,
            borderStyle: r.state === 'off' ? 'dashed' : 'solid',
            borderColor: applied ? c.accent : c.line,
            backgroundColor: applied ? c.accent : 'transparent',
          }}
        >
          {applied ? (
            <Txt bold style={{ fontSize: 10, lineHeight: 12, color: c.accentInk }}>
              ✓
            </Txt>
          ) : null}
        </View>
        <View style={{ flex: 1, gap: 1 }}>
          <Txt v="sm" bold>
            {r.name}
          </Txt>
          <Txt v="xs" tone="muted">
            {r.desc}
          </Txt>
        </View>
        <View style={{ alignItems: 'flex-end', gap: 3, maxWidth: '42%' }}>
          <Txt v="xs" tone={applied ? 'accent' : 'muted'} style={{ textAlign: 'right' }}>
            {r.effect}
          </Txt>
          <View
            style={{
              paddingHorizontal: 7,
              paddingVertical: 1,
              borderRadius: 999,
              borderWidth: 1,
              borderColor: viewing ? c.accent : applied ? `${c.accent}80` : c.line,
              backgroundColor: viewing ? c.accent : 'transparent',
            }}
          >
            <Txt
              bold
              style={{
                fontSize: 10,
                lineHeight: 13,
                color: viewing ? c.accentInk : applied ? c.accentText : c.muted,
              }}
            >
              {state}
            </Txt>
          </View>
        </View>
      </>
    );
    const style = {
      flexDirection: 'row' as const,
      alignItems: 'center' as const,
      gap: 8,
      paddingVertical: 8,
      paddingHorizontal: 10,
      borderRadius: 10,
      borderWidth: 1,
      borderStyle: r.badge ? ('dashed' as const) : ('solid' as const),
      // 적용 중은 모두 같은 모습 — 누른 줄은 고른 것처럼 보이지 않게 배경만 바꾸고 '보는 중'을 단다.
      borderColor: applied ? `${c.accent}80` : c.line,
      backgroundColor: viewing ? `${c.accent}2e` : r.state === 'off' ? 'transparent' : c.surface2,
      opacity: r.state === 'off' ? 0.62 : 1,
    };
    return r.state === 'off' ? (
      <View key={r.id} testID={`synergy-${r.id}`} style={style}>
        {body}
      </View>
    ) : (
      <Press
        key={r.id}
        testID={`synergy-${r.id}`}
        accessibilityLabel={`${r.name} · ${r.effect} · ${state}`}
        accessibilityState={{ selected: viewing }}
        onPress={() => setFocus(viewing ? null : r.id)}
        style={style}
      >
        {body}
      </Press>
    );
  };
  return (
    <View testID="team-synergy" style={{ gap: 8 }}>
      <View
        style={{
          flexDirection: 'row',
          justifyContent: 'space-between',
          alignItems: 'baseline',
          flexWrap: 'wrap',
          gap: 6,
        }}
      >
        <Txt v="h3">
          {L.title}
          {power > 0 ? <Txt v="h3" tone="accent">{` +${power}`}</Txt> : null}
        </Txt>
        <Txt v="xs" tone="muted">
          {synergyNote(season)}
        </Txt>
      </View>
      <Txt v="xs" tone="muted">
        {anyOn ? L.chipHint : L.empty}
      </Txt>
      <View style={{ gap: 6 }}>{rows.map(row)}</View>
      <Txt v="xs" tone="muted">
        {L.capNote({ line: DUO_LINE_CAP, total: DUO_TOTAL_CAP })}
      </Txt>
    </View>
  );
}
