// apps/web/src/ui/cup/CupBracket.svelte
<script lang="ts">
  import { tick } from 'svelte';
  import type { CupMatch, CupTeam } from '@offside/app-core/api/cup';
  import { BRACKET as B, cupBracket, type BracketNode } from '@offside/app-core/cupBracket';
  import { cupText as L } from '@offside/app-core/i18n/ko/cup';
  import { roundLabel, whenText } from './cupView';
  import TeamLogo from '../team/TeamLogo.svelte';
  let { matches, teams, mineId, now, onselect }: { matches: readonly CupMatch[]; teams: ReadonlyMap<string, CupTeam>; mineId: string | null; now: number; onselect: (m: CupMatch) => void } = $props();
  let viewport: HTMLDivElement;
  let active = $state(0);
  const tree = $derived(cupBracket(matches, active));
  let viewWidth = $state(0);
  let offset = $derived(Math.min(active * B.column, Math.max(0, tree.width + 24 - viewWidth)));
  let drag: { x: number; offset: number } | null = null;
  let dragged = false;
  function pan(event: PointerEvent) {
    if (!drag) return;
    const distance = event.clientX - drag.x;
    if (Math.abs(distance) > 6) { dragged = true; viewport.setPointerCapture(event.pointerId); }
    if (dragged) offset = Math.max(0, Math.min(Math.max(0, tree.width + 24 - viewWidth), drag.offset - distance));
  }
  const own = $derived(tree.nodes.findLast(n => mineId && (n.homeTeamId === mineId || n.awayTeamId === mineId)));
  async function jump(column: number, node?: BracketNode) {
    active = Math.max(0, Math.min(tree.rounds.length - 1, column));
    await tick();
    offset = Math.min(active * B.column, Math.max(0, tree.width + 24 - viewWidth));
    const target = node ? tree.nodes.find(n => n.round === node.round && n.slot === node.slot) : null;
    viewport.scrollTo({ top: target ? Math.max(0, target.y - B.header) : 0, behavior: 'instant' });
  }

</script>
<div class="bracket-controls">
  <nav aria-label={L.secBracket}>
    {#each tree.rounds as r, i (r)}<button class:chosen={active === i} aria-pressed={active === i} onclick={() => jump(i)}>{roundLabel(r)}</button>{/each}
  </nav>
</div>
<div class="bracket-help">
  <p class="muted fs-xs">{L.bracketHint}</p>
  {#if own}<button class="mine-jump" onclick={() => jump(tree.rounds.indexOf(own!.round), own)}>{L.bracketMine}<span aria-hidden="true">↗</span></button>{/if}
</div>
<!-- svelte-ignore a11y_no_noninteractive_tabindex, a11y_no_noninteractive_element_interactions (The scrollable bracket supports pointer panning and arrow keys; buttons provide equivalent navigation.) -->
<div class="bracket-viewport" bind:this={viewport} tabindex="0" role="region" aria-label={L.bracketView} data-bracket-viewport bind:clientWidth={viewWidth}
  onpointerdown={e => { drag = { x:e.clientX, offset }; dragged=false; }} onpointermove={pan} onpointerup={() => drag=null} onpointercancel={() => drag=null}
  onclickcapture={e => { if (dragged) { e.preventDefault(); e.stopPropagation(); dragged=false; } }}
  onkeydown={e => { if(e.target === viewport && (e.key === 'ArrowLeft' || e.key === 'ArrowRight')) { e.preventDefault(); void jump(active + (e.key === 'ArrowRight' ? 1 : -1)); } }} style:height="{tree.viewportHeight}px">
  <div class="bracket-pan" style:width="{tree.width + 24}px" style:height="{tree.height + 24}px">
  <div class="bracket-canvas" style:width="{tree.width}px" style:height="{tree.height}px" style:transform="translateX(-{offset}px)">
    <svg width={tree.width} height={tree.height} aria-hidden="true">{#each tree.paths as d, i (i)}<path {d} style={`d:path("${d}")`} />{/each}</svg>
    {#each tree.rounds as r, i (r)}<h3 class="round-heading" style:left="{i * B.column}px">{roundLabel(r)}</h3>{/each}
    {#each tree.nodes as n (`${n.round}:${n.slot}`)}
      {@const m = n.match}
      {@const mine = !!mineId && (n.homeTeamId === mineId || n.awayTeamId === mineId)}
      <button class="bracket-match" class:compact={n.compact} class:mine disabled={!m} style:left="{n.x}px" style:top="{n.y}px" style:width="{B.cardWidth}px" style:height="{n.height}px" onclick={() => m && onselect(m)} aria-label={`${roundLabel(n.round)} · ${teams.get(n.homeTeamId ?? '')?.name ?? L.tbd} · ${teams.get(n.awayTeamId ?? '')?.name ?? L.tbd}`} data-bracket-match={m?.id}>
        <span class="match-state" class:finished={m?.played}>{m ? m.played ? L.matchFinished : Date.parse(m.at) <= now ? L.matchProcessing : L.matchScheduled : L.bracketPending}{#if mine}<b>{L.mineTag}</b>{/if}</span>
        {#each [n.homeTeamId, n.awayTeamId] as id, side (side)}
          <span class="team-row" class:winner={!!id && m?.winnerTeamId === id} class:own={!!id && id === mineId}>
            <TeamLogo logo={id ? teams.get(id)?.logo : null} name={id ? teams.get(id)?.name ?? L.tbd : L.tbd} size={20} decorative />
            <span class="team-name">{id ? teams.get(id)?.name ?? L.tbd : L.tbd}</span>
            <b>{m?.played ? side === 0 ? m.homeGoals : m.awayGoals : '–'}</b>
          </span>
        {/each}
        <small>{m?.pens ? L.pens(m.pens) : m ? whenText(m.at) : roundLabel(n.round)}</small>
      </button>
    {/each}
  </div>
  </div>
</div>
<style>
  .bracket-controls {min-width:0;}
  nav {display:flex;gap:6px;overflow-x:auto;padding:2px 0 6px;scrollbar-width:thin;}
  nav button {flex:1 0 auto;min-height:44px;padding:6px 10px;border:1px solid var(--line);border-radius:999px;background:transparent;color:var(--muted);font:inherit;font-size:.8125rem;white-space:nowrap;cursor:pointer;}
  nav button.chosen {border-color:var(--accent);background:color-mix(in srgb,var(--accent) 12%,var(--surface));color:var(--accent-text);font-weight:700;}
  .bracket-help {display:flex;align-items:center;gap:12px;}
  .bracket-help p {flex:1;min-width:0;margin:0;line-height:1.5;}
  .mine-jump {flex:none;display:flex;align-items:center;gap:4px;min-height:44px;padding:6px 0;border:0;background:transparent;color:var(--accent-text);font:inherit;font-size:.8125rem;font-weight:600;cursor:pointer;}
  .bracket-viewport {max-width:100%;height:640px;max-height:65vh;overflow-y:auto;overflow-x:hidden;touch-action:pan-y;transition:height .4s ease;overscroll-behavior:contain;border:1px solid var(--line);border-radius:12px;background:var(--bg);}
  .bracket-pan {position:relative;max-width:100%;transition:height .4s ease;}
  .bracket-canvas {position:relative;margin:12px;transition:transform .4s ease,height .4s ease;}
  svg {position:absolute;inset:0;pointer-events:none;}
  path {fill:none;stroke:var(--muted);stroke-width:1.5;opacity:.65;transition:d .4s ease;}
  .round-heading {position:absolute;top:0;margin:0;font-size:14px;}
  .bracket-match {position:absolute;display:flex;flex-direction:column;justify-content:center;gap:4px;padding:8px 10px;border:1px solid var(--line);border-radius:10px;background:var(--surface);color:var(--ink);font:inherit;text-align:left;cursor:pointer;transition:top .4s ease,height .4s ease;}
  .bracket-match:disabled {opacity:1;cursor:default;border-style:dashed;}
  .bracket-match.mine {border:2px solid var(--accent);}
  .bracket-match:hover:not(:disabled) {border-color:var(--accent);}
  .match-state {display:flex;justify-content:space-between;font-size:11px;color:white;background:#1d4ed8;border-radius:4px;padding:1px 4px;}
  .match-state.finished {background:var(--pitch);color:var(--on-pitch);}
  .match-state b {color:inherit;}
  .own {color:var(--accent-text);}
  .bracket-match:disabled .match-state {color:var(--muted);background:transparent;}
  .team-row {display:flex;align-items:center;gap:6px;min-width:0;font-size:13px;}
  .team-name {flex:1;overflow:hidden;text-overflow:ellipsis;white-space:nowrap;}
  .winner {font-weight:700;}
  small {font-size:10px;color:var(--muted);white-space:nowrap;}
  .compact .match-state,.compact small {display:none;}
  .compact {gap:2px;padding-block:4px;}
  @media (prefers-reduced-motion:reduce) { .bracket-viewport,.bracket-pan,.bracket-canvas,.bracket-match,path {transition:none;} }
  button:focus-visible,.bracket-viewport:focus-visible {outline:2px solid var(--accent);outline-offset:2px;}
</style>

// apps/mobile/src/screens/owner/CupBracket.tsx
import { alpha } from '../../theme/colors';
import { useSnapshot } from 'valtio';
import { prefs } from '../../store';
import { useEffect, useRef, useState } from 'react';
import { LayoutAnimation, ScrollView, View, useWindowDimensions } from 'react-native';
import Svg, { Path } from 'react-native-svg';
import { BRACKET as B, cupBracket, type BracketNode } from '@offside/app-core/cupBracket';
import type { CupMatch, CupResponse } from '@offside/app-core/api/cup';
import { cupText as L } from '@offside/app-core/i18n/ko/cup';
import { TeamLogo } from '../../components/TeamLogo';
import { useColors } from '../../theme/useColors';
import { Press, Txt } from '../../ui';
import { dayTimeText, roundLabel } from './cupText';

export default function CupBracket({
  cup,
  mineId,
  now,
  onselect,
}: {
  cup: CupResponse;
  mineId: string | null;
  now: number;
  onselect: (m: CupMatch) => void;
}) {
  const c = useColors();
  const window = useWindowDimensions();
  const { motionOK } = useSnapshot(prefs);
  const horizontal = useRef<ScrollView>(null);
  const vertical = useRef<ScrollView>(null);
  const [active, setActive] = useState(0);
  const tree = cupBracket(cup.matches, active);
  const pending = useRef<{ column: number; node?: BracketNode } | null>(null);
  const own = tree.nodes.findLast(
    (n) => mineId && (n.homeTeamId === mineId || n.awayTeamId === mineId),
  );
  function jump(column: number, node?: BracketNode) {
    const target = Math.max(0, Math.min(tree.rounds.length - 1, column));
    if (motionOK)
      LayoutAnimation.configureNext({ duration: 400, update: { type: 'easeInEaseOut' } });
    pending.current = { column: target, ...(node ? { node } : {}) };
    if (target === active) movePending();
    else setActive(target);
  }
  function movePending() {
    const target = pending.current;
    if (!target) return;
    pending.current = null;
    const node = target.node
      ? tree.nodes.find((n) => n.round === target.node!.round && n.slot === target.node!.slot)
      : null;
    horizontal.current?.scrollTo({ x: target.column * B.column, animated: motionOK });
    vertical.current?.scrollTo({
      y: node ? Math.max(0, node.y - B.header) : 0,
      animated: motionOK,
    });
  }
  useEffect(() => {
    movePending();
  }, [active]);
  return (
    <View style={{ gap: 8 }}>
      <ScrollView
        horizontal
        showsHorizontalScrollIndicator={false}
        contentContainerStyle={{ gap: 6, flexGrow: 1, paddingVertical: 2 }}
      >
        {tree.rounds.map((r, i) => (
          <Press
            key={r}
            accessibilityState={{ selected: i === active }}
            onPress={() => jump(i)}
            style={{
              flexGrow: 1,
              minHeight: 44,
              paddingHorizontal: 10,
              alignItems: 'center',
              justifyContent: 'center',
              borderRadius: 24,
              borderWidth: 1,
              borderColor: i === active ? c.accent : c.line,
              backgroundColor: i === active ? alpha(c.accent, 0.12) : 'transparent',
            }}
          >
            <Txt v="sm" bold={i === active} tone={i === active ? 'accent' : 'muted'}>
              {roundLabel(r)}
            </Txt>
          </Press>
        ))}
      </ScrollView>
      <View style={{ flexDirection: 'row', alignItems: 'center', gap: 12 }}>
        <Txt v="xs" tone="muted" style={{ flex: 1 }}>
          {L.bracketHint}
        </Txt>
        {own ? (
          <Press
            onPress={() => jump(tree.rounds.indexOf(own.round), own)}
            style={{
              minHeight: 44,
              justifyContent: 'center',
              flexDirection: 'row',
              alignItems: 'center',
              gap: 4,
            }}
          >
            <Txt v="sm" tone="accent" bold>
              {L.bracketMine}
            </Txt>
            <Txt v="sm" tone="accent" accessible={false}>
              ↗
            </Txt>
          </Press>
        ) : null}
      </View>
      <ScrollView
        horizontal
        ref={horizontal}
        nestedScrollEnabled
        style={{
          height: Math.min(window.height * 0.65, tree.viewportHeight),
          borderWidth: 1,
          borderColor: c.line,
          borderRadius: 12,
        }}
      >
        <ScrollView
          ref={vertical}
          nestedScrollEnabled
          style={{
            width: tree.width + 24,
            height: Math.min(window.height * 0.65, tree.viewportHeight),
          }}
        >
          <View style={{ width: tree.width, height: tree.height, margin: 12 }}>
            {tree.connectors.map((line, i) => (
              <Svg
                key={i}
                pointerEvents="none"
                accessible={false}
                width={line.width}
                height={line.height}
                viewBox={`${line.x} ${line.y} ${line.width} ${line.height}`}
                style={{ position: 'absolute', left: line.x, top: line.y }}
              >
                <Path d={line.path} fill="none" stroke={c.muted} strokeWidth={1.5} />
              </Svg>
            ))}
            {tree.rounds.map((r, i) => (
              <Txt key={r} bold style={{ position: 'absolute', left: i * B.column, top: 0 }}>
                {roundLabel(r)}
              </Txt>
            ))}
            {tree.nodes.map((n) => {
              const m = n.match;
              const mine = !!mineId && (n.homeTeamId === mineId || n.awayTeamId === mineId);
              const status = m
                ? m.played
                  ? L.matchFinished
                  : Date.parse(m.at) <= now
                    ? L.matchProcessing
                    : L.matchScheduled
                : L.bracketPending;
              return (
                <Press
                  key={`${n.round}:${n.slot}`}
                  disabled={!m}
                  onPress={() => m && onselect(m)}
                  accessibilityLabel={`${roundLabel(n.round)} · ${cup.teams.find((t) => t.teamId === n.homeTeamId)?.name ?? L.tbd} · ${cup.teams.find((t) => t.teamId === n.awayTeamId)?.name ?? L.tbd} · ${status}`}
                  style={{
                    position: 'absolute',
                    left: n.x,
                    top: n.y,
                    width: B.cardWidth,
                    height: n.height,
                    padding: n.compact ? 4 : 8,
                    gap: n.compact ? 2 : 4,
                    borderRadius: 10,
                    borderWidth: mine ? 2 : 1,
                    borderColor: mine ? c.accent : c.line,
                    backgroundColor: c.surface,
                  }}
                >
                  {!n.compact ? (
                    <View style={{ flexDirection: 'row', justifyContent: 'space-between' }}>
                      <Txt v="xs" tone={m?.played ? 'good' : 'muted'}>
                        {status}
                      </Txt>
                      {mine ? (
                        <Txt v="xs" tone="accent">
                          {L.mineTag}
                        </Txt>
                      ) : null}
                    </View>
                  ) : null}
                  {[n.homeTeamId, n.awayTeamId].map((id, side) => {
                    const t = cup.teams.find((t) => t.teamId === id);
                    return (
                      <View
                        key={side}
                        style={{ flexDirection: 'row', alignItems: 'center', gap: 6 }}
                      >
                        <TeamLogo logo={t?.logo} name={t?.name ?? L.tbd} size={20} decorative />
                        <Txt
                          v="sm"
                          numberOfLines={1}
                          bold={!!id && m?.winnerTeamId === id}
                          tone={id && id === mineId ? 'accent' : 'ink'}
                          style={{ flex: 1 }}
                        >
                          {t?.name ?? L.tbd}
                        </Txt>
                        <Txt v="sm" bold>
                          {m?.played ? String(side === 0 ? m.homeGoals : m.awayGoals) : '–'}
                        </Txt>
                      </View>
                    );
                  })}
                  {!n.compact ? (
                    <Txt v="xs" tone="muted" numberOfLines={1}>
                      {m?.pens ? L.pens(m.pens) : m ? dayTimeText(m.at) : roundLabel(n.round)}
                    </Txt>
                  ) : null}
                </Press>
              );
            })}
          </View>
        </ScrollView>
      </ScrollView>
    </View>
  );
}
