// apps/web/src/ui/owner/OwnerHonors.svelte
<script lang="ts">
  import Topbar from '../Topbar.svelte';
  import BackBar from '../BackBar.svelte';
  import { go } from '../nav.js';
  import OwnerHall from './OwnerHall.svelte';
</script>

<div class="wrap" data-owner-honors-screen>
  <Topbar />
  <OwnerHall />
</div>
<BackBar act="honors-back" fallback={() => go('owner')} atBottom={false} />

// apps/mobile/src/screens/owner/OwnerHonors.tsx
import { Screen, Topbar, BackBar } from '../../ui';
import { go } from '../../game/nav';
import { OwnerHall } from './OwnerHall';

export default function OwnerHonors() {
  return (
    <Screen>
      <Topbar />
      <OwnerHall />
      <BackBar testID="honors-back" fallback={() => go('owner')} />
    </Screen>
  );
}
