// apps/web/src/ui/owner/OwnerHall.svelte
<script lang="ts">
  // T-11-150 명예관 — 구단주 화면에서 받은 칭호 가운데 대표 칭호를 고른다(자동 · 칭호 하나 · 달지 않기). 고른 칭호는 랭킹 ·
  // 팀 프로필 · 댓글 · 채팅 닉네임 옆에 붙는다. 불러오지 못하면 카드를 숨긴다.
  import { onMount } from 'svelte';
  import {
    fetchOwnerTitles,
    putOwnerTitle,
    type OwnerTitlesResponse,
  } from '@offside/app-core/api/ownerProfile';
  import { TITLE_NONE, titleLabel } from '@offside/app-core/ownerTitle';
  import { ownerProfileText as L } from '@offside/app-core/i18n/ko/ownerProfile';
  import TitleBadge from '../cup/TitleBadge.svelte';
  import { toast } from '../helpers.js';
  import { appState, hofStart } from '../state.svelte.js';
  import { go } from '../nav.js';

  let hall = $state<OwnerTitlesResponse | null>(null);
  let saving = $state(false);
  /** 고른 칸 — null = 자동, TITLE_NONE = 달지 않기, 그 밖은 칭호 id. */
  const picked = $derived(hall ? (hall.pinned ? (hall.title ?? TITLE_NONE) : null) : null);

  onMount(() => {
    void fetchOwnerTitles().then((r) => {
      if (r.ok) hall = r.data;
    });
  });

  async function pick(title: string | null) {
    if (!hall || saving || title === picked) return;
    saving = true;
    const r = await putOwnerTitle(title);
    saving = false;
    if (!r.ok) return toast(r.error.message);
    hall = { ...hall, title: r.data.title, pinned: r.data.pinned };
    toast(L.saved);
  }

  function openProfile(teamId: string) {
    appState.hof = { ...hofStart(), tab: 'teams', team: teamId, owner: true };
    go('hof');
  }
</script>

{#if hall}
  <section class="card stack" style="gap:12px" aria-label={L.hallTitle} data-owner-hall>
    <div>
      <small class="eyebrow">Hall of honors</small>
      <h2>{L.hallTitle}</h2>
      <p class="muted fs-sm">{hall.titles.length ? L.hallLead : L.hallEmpty}</p>
    </div>
    {#if hall.titles.length}
      <div class="oh-current">
        <span class="muted fs-sm">{L.current}</span>
        {#if hall.title}<TitleBadge title={hall.title} />{:else}<b>{L.currentNone}</b>{/if}
      </div>
      <div class="oh-picks" role="group" aria-label={L.current}>
        <button class="opt" aria-label={`${L.pickAuto} · ${L.pickAutoNote}`} aria-pressed={picked === null} disabled={saving} onclick={() => pick(null)} data-title-pick="auto">
          <b>{L.pickAuto}</b><small class="muted">{L.pickAutoNote}</small>
        </button>
        {#each hall.titles as t (t)}
          <button class="opt" aria-pressed={picked === t} aria-label={titleLabel(t)} disabled={saving} onclick={() => pick(t)} data-title-pick={t}>
            <TitleBadge title={t} />
          </button>
        {/each}
        <button class="opt" aria-label={L.pickNone} aria-pressed={picked === TITLE_NONE} disabled={saving} onclick={() => pick(TITLE_NONE)} data-title-pick="none">
          <b>{L.pickNone}</b>
        </button>
      </div>
    {/if}
    {#if hall.teamId}
      {@const teamId = hall.teamId}
      <button class="btn btn-block" data-act="my-owner-profile" onclick={() => openProfile(teamId)}>{L.viewProfile}</button>
    {/if}
  </section>
{/if}

<style>
  .oh-current {display:flex; align-items:center; gap:8px; flex-wrap:wrap;}
  .oh-picks {display:flex; flex-wrap:wrap; gap:8px;}
</style>

// apps/mobile/src/screens/owner/OwnerHall.tsx
// T-11-150 명예관(웹 ui/owner/OwnerHall.svelte) — 구단주 화면에서 받은 칭호 가운데 대표 칭호를 고른다(자동 · 칭호 하나 ·
// 달지 않기). 고른 칭호는 랭킹 · 팀 프로필 · 댓글 · 채팅 닉네임 옆에 붙는다. 불러오지 못하면 카드를 숨긴다.
import { useEffect, useState, type ReactNode } from 'react';
import { View } from 'react-native';
import {
  fetchOwnerTitles,
  putOwnerTitle,
  type OwnerTitlesResponse,
} from '@offside/app-core/api/ownerProfile';
import { ownerProfileText as L } from '@offside/app-core/i18n/ko/ownerProfile';
import { TITLE_NONE, titleLabel } from '@offside/app-core/ownerTitle';
import { hofStart } from '@offside/app-core/state';
import { TitleBadge } from '../../components/TitleBadge';
import { toast } from '../../game/host';
import { go } from '../../game/nav';
import { appState } from '../../store';
import { rem } from '../../theme/type';
import { Btn } from '../../ui/Btn';
import { Card } from '../../ui/Card';
import { Opt } from '../../ui/bits';
import { Txt } from '../../ui/Txt';

export function OwnerHall() {
  const [hall, setHall] = useState<OwnerTitlesResponse | null>(null);
  const [saving, setSaving] = useState(false);
  useEffect(() => {
    let live = true;
    void fetchOwnerTitles().then((r) => {
      if (live && r.ok) setHall(r.data);
    });
    return () => {
      live = false;
    };
  }, []);
  if (!hall) return null;
  /** 고른 칸 — null = 자동, TITLE_NONE = 달지 않기, 그 밖은 칭호 id. */
  const picked = hall.pinned ? (hall.title ?? TITLE_NONE) : null;

  async function pick(title: string | null) {
    if (!hall || saving || title === picked) return;
    setSaving(true);
    const r = await putOwnerTitle(title);
    setSaving(false);
    if (!r.ok) return toast(r.error.message);
    setHall({ ...hall, title: r.data.title, pinned: r.data.pinned });
    toast(L.saved);
  }

  const option = (key: string, title: string | null, label: string, body: ReactNode) => (
    <Opt
      key={key}
      testID={`title-pick-${key}`}
      selected={picked === title}
      disabled={saving}
      accessibilityLabel={label}
      onPress={() => void pick(title)}
    >
      {body}
    </Opt>
  );

  const teamId = hall.teamId;
  return (
    <Card gap={12} testID="owner-hall">
      <View style={{ gap: 2 }}>
        <Txt v="eyebrow">Hall of honors</Txt>
        <Txt v="h2" accessibilityRole="header">
          {L.hallTitle}
        </Txt>
        <Txt tone="muted" style={{ fontSize: rem(0.875) }}>
          {hall.titles.length ? L.hallLead : L.hallEmpty}
        </Txt>
      </View>
      {hall.titles.length ? (
        <>
          <View style={{ flexDirection: 'row', alignItems: 'center', gap: 8, flexWrap: 'wrap' }}>
            <Txt tone="muted" style={{ fontSize: rem(0.875) }}>
              {L.current}
            </Txt>
            {hall.title ? <TitleBadge title={hall.title} /> : <Txt bold>{L.currentNone}</Txt>}
          </View>
          <View
            accessibilityRole="none"
            accessibilityLabel={L.current}
            style={{ flexDirection: 'row', flexWrap: 'wrap', gap: 8 }}
          >
            {option(
              'auto',
              null,
              `${L.pickAuto} · ${L.pickAutoNote}`,
              <>
                <Txt bold>{L.pickAuto}</Txt>
                <Txt tone="muted" style={{ fontSize: rem(0.6875) }}>
                  {L.pickAutoNote}
                </Txt>
              </>,
            )}
            {hall.titles.map((t) => option(t, t, titleLabel(t) ?? t, <TitleBadge title={t} />))}
            {option('none', TITLE_NONE, L.pickNone, <Txt bold>{L.pickNone}</Txt>)}
          </View>
        </>
      ) : null}
      {teamId ? (
        <Btn
          block
          testID="my-owner-profile"
          onPress={() => {
            appState.hof = { ...hofStart(), tab: 'teams', team: teamId, owner: true };
            go('hof');
          }}
        >
          {L.viewProfile}
        </Btn>
      ) : null}
    </Card>
  );
}
