// apps/web/src/ui/team/TeamResult.svelte
<script lang="ts">
  // 경기 결과(중계가 끝난 뒤) — 스코어 · 득점 · 레이팅 변화.
  import type { OwnerTeam, TeamMatch } from '@offside/app-core/api/team';
  import { kstMonthDayTime } from '@offside/app-core/boardText';
  import { OUTCOME_TITLE, outcomeOf as outcome } from '@offside/app-core/teamOwner';
  import { recordText, signedNum } from '@offside/app-core/teamText';
  import TeamLogo from './TeamLogo.svelte';

  let {
    m,
    team,
    eventName,
    matchesLeft,
    ontoTeam,
    onreplay,
    onagain,
    onhistory,
  }: {
    m: TeamMatch;
    team: OwnerTeam | null;
    eventName: (id: string | null, fallback: string) => string;
    matchesLeft: number;
    ontoTeam: () => void;
    onreplay: () => void;
    onagain: () => void;
    onhistory?: (() => void) | undefined;
  } = $props();

  const gain = $derived(m[m.mine].ratingChange);
</script>

<section class="card stack tm-result" style="gap:14px" data-team-result>
  <div>
    <div class="eyebrow">Full time</div>
    <h1>{OUTCOME_TITLE[outcome(m)]}</h1>
  </div>
  <div class="tm-score">
    <div class="tm-side" class:mine={m.mine === 'home'}>
      <TeamLogo logo={m.home.logo} name={m.home.name} size={40} decorative />
      <b>{m.home.name}</b><small class="muted">{m.home.owner} · OVR {m.home.ovr}</small>
    </div>
    <div class="tm-goals"><b>{m.home.goals}</b><span aria-hidden="true">:</span><b>{m.away.goals}</b></div>
    <div class="tm-side away" class:mine={m.mine === 'away'}>
      <TeamLogo logo={m.away.logo} name={m.away.name} size={40} decorative />
      <b>{m.away.name}</b><small class="muted">{m.away.owner} · OVR {m.away.ovr}</small>
    </div>
  </div>
  {#if m.events.length}
    <ol class="tm-events">
      {#each m.events as e, k (k)}
        <li class:away={e.side === 'away'}>
          <span class="tm-min">{e.minute}'</span>
          <span>
            <b>{eventName(e.scorerId, e.scorer)}</b>
            {#if e.assist}<small class="muted">도움 {eventName(e.assistId, e.assist)}</small>{/if}
          </span>
        </li>
      {/each}
    </ol>
  {:else}
    <p class="muted">골 없이 비겼어요.</p>
  {/if}
  <p class="muted fs-sm">{kstMonthDayTime(m.createdAt)}{team && m.mine === 'home' ? ` · 내 팀 ${recordText(team.record)}` : ''}</p>
  {#if gain != null}
    <p class="fs-sm" data-rating-change>내 팀 레이팅 <b>{signedNum(gain)}</b></p>
  {/if}
  <div class="tm-actions">
    {#if onhistory}<button class="btn" onclick={onhistory} data-act="team-result-history">기록으로 돌아가기</button>{:else}<button class="btn" onclick={ontoTeam}>편성으로</button>{/if}
    <button class="btn" onclick={onreplay} data-act="team-replay">중계 다시 보기</button>
    <button class="btn btn-primary" onclick={onagain} disabled={matchesLeft === 0}>다시 경기하기</button>
  </div>
</section>

<style>
  .tm-actions {
    display: grid;
    grid-template-columns: 1fr 1fr;
    gap: 8px;
  }
  .tm-score {
    display: grid;
    grid-template-columns: 1fr auto 1fr;
    align-items: center;
    gap: 10px;
  }
  .tm-side {
    display: flex;
    flex-direction: column;
    gap: 2px;
    min-width: 0;
    overflow-wrap: anywhere;
  }
  .tm-side.away {
    text-align: right;
    align-items: flex-end;
  }
  .tm-side.mine b {
    color: var(--accent-text);
  }
  .tm-goals {
    display: flex;
    gap: 8px;
    font-family: var(--display);
    font-size: 2.5rem;
    font-weight: 700;
    line-height: 1;
  }
  .tm-events {
    list-style: none;
    margin: 0;
    padding: 0;
    display: flex;
    flex-direction: column;
    gap: 8px;
  }
  .tm-events li {
    display: flex;
    gap: 10px;
    align-items: baseline;
  }
  .tm-events li.away {
    flex-direction: row-reverse;
    text-align: right;
  }
  .tm-events li > span:last-child {
    display: flex;
    flex-direction: column;
  }
  .tm-min {
    flex: none;
    font-family: var(--display);
    font-weight: 700;
    color: var(--muted);
    min-width: 2.2em;
  }
</style>

// apps/mobile/src/screens/owner/TeamResult.tsx
// 경기 결과(웹 team/Team.svelte 의 view === 'result', 중계가 끝난 뒤) — 스코어 · 득점 · 레이팅 변화.
import { View } from 'react-native';
import { TeamLogo } from '../../components/TeamLogo';
import type { OwnerTeam, TeamMatch } from '@offside/app-core/api/team';
import { kstMonthDayTime } from '@offside/app-core/boardText';
import { OUTCOME_TITLE, outcomeOf } from '@offside/app-core/teamOwner';
import { recordText, signedNum } from '@offside/app-core/teamText';
import { DISPLAY, rem } from '../../theme/type';
import { Btn, Card, Txt } from '../../ui';
import { Grid2 } from './TeamParts';

export function TeamResult({
  m,
  team,
  eventName,
  matchesLeft,
  toTeam,
  replay,
  again,
  backLabel = '내 팀',
}: {
  m: TeamMatch;
  team: OwnerTeam | null;
  eventName: (id: string | null, fallback: string) => string;
  matchesLeft: number;
  toTeam: () => void;
  replay: () => void;
  again: () => void;
  backLabel?: string;
}) {
  const gain = m[m.mine].ratingChange;
  const side = (s: TeamMatch['home'], away: boolean, mine: boolean) => (
    <View style={{ flex: 1, minWidth: 0, gap: 2, alignItems: away ? 'flex-end' : 'flex-start' }}>
      <TeamLogo logo={s.logo} name={s.name} size={40} decorative />
      <Txt bold tone={mine ? 'accent' : 'ink'} style={{ textAlign: away ? 'right' : 'left' }}>
        {s.name}
      </Txt>
      <Txt tone="muted" v="xs" style={{ textAlign: away ? 'right' : 'left' }}>
        {`${s.owner} · OVR ${s.ovr}`}
      </Txt>
    </View>
  );
  const goalStyle = {
    fontFamily: DISPLAY[700],
    fontSize: rem(2.5),
    lineHeight: rem(2.5),
  } as const;
  return (
    <Card gap={14}>
      <View testID="team-result">
        <Txt v="eyebrow">Full time</Txt>
        <Txt v="h1" accessibilityRole="header">
          {OUTCOME_TITLE[outcomeOf(m)]}
        </Txt>
      </View>
      <View style={{ flexDirection: 'row', alignItems: 'center', gap: 10 }}>
        {side(m.home, false, m.mine === 'home')}
        <View
          accessible
          accessibilityLabel={`${m.home.goals} 대 ${m.away.goals}`}
          style={{ flexDirection: 'row', gap: 8 }}
        >
          <Txt style={goalStyle}>{m.home.goals}</Txt>
          <Txt accessible={false} style={goalStyle}>
            :
          </Txt>
          <Txt style={goalStyle}>{m.away.goals}</Txt>
        </View>
        {side(m.away, true, m.mine === 'away')}
      </View>
      {m.events.length ? (
        <View style={{ gap: 8 }}>
          {m.events.map((e, k) => (
            <View
              key={k}
              style={{
                flexDirection: e.side === 'away' ? 'row-reverse' : 'row',
                gap: 10,
                alignItems: 'baseline',
              }}
            >
              <Txt
                tone="muted"
                style={{
                  minWidth: rem(1) * 2.2,
                  fontFamily: DISPLAY[700],
                  textAlign: e.side === 'away' ? 'right' : 'left',
                }}
              >{`${e.minute}'`}</Txt>
              <View style={{ alignItems: e.side === 'away' ? 'flex-end' : 'flex-start' }}>
                <Txt bold>{eventName(e.scorerId, e.scorer)}</Txt>
                {e.assist ? (
                  <Txt tone="muted" v="xs">{`도움 ${eventName(e.assistId, e.assist)}`}</Txt>
                ) : null}
              </View>
            </View>
          ))}
        </View>
      ) : (
        <Txt tone="muted">골 없이 비겼어요.</Txt>
      )}
      <Txt tone="muted" v="sm">
        {`${kstMonthDayTime(m.createdAt)}${team && m.mine === 'home' ? ` · 내 팀 ${recordText(team.record)}` : ''}`}
      </Txt>
      {gain != null ? (
        <Txt v="sm" testID="rating-change">
          {'내 팀 레이팅 '}
          <Txt v="sm" bold>
            {signedNum(gain)}
          </Txt>
        </Txt>
      ) : null}
      <Grid2>
        <Btn block onPress={toTeam} testID="team-result-team">
          {backLabel}
        </Btn>
        <Btn block onPress={replay} testID="team-replay">
          중계 다시 보기
        </Btn>
        <Btn block kind="primary" onPress={again} disabled={matchesLeft === 0} testID="team-again">
          다시 경기하기
        </Btn>
      </Grid2>
    </Card>
  );
}
