// apps/web/src/ui/team/TeamPicker.svelte
<script lang="ts">
  // T-10-117 선수 고르기 시트 — 고른 자리에 넣을 은퇴 선수. 정렬 셋 · 유스 선수(자리 비우기).
  import { DETAIL_LABEL, YOUTH_NAME, YOUTH_OVR, type DetailPos } from '@offside/contracts/owner-team';
  import type { TeamPlayer } from '@offside/app-core/api/team';
  import { PICK_SORTS, attrLine, pct, type PickCandidate, type PickSort } from '@offside/app-core/teamOwner';
  import { POS_LABEL } from '@offside/game/pos-label';

  let {
    picking,
    slotCodes,
    slots,
    sort = $bindable(),
    candidates,
    nameOf,
    onassign,
    onclose,
  }: {
    /** 고르는 자리의 순서(null이면 닫힘). */
    picking: number | null;
    slotCodes: readonly DetailPos[];
    slots: (string | null)[];
    sort: PickSort;
    candidates: PickCandidate[];
    nameOf: (p: TeamPlayer) => string;
    /** 고른 선수를 넣는다(null이면 유스 선수). */
    onassign: (id: string | null) => void;
    onclose: () => void;
  } = $props();
</script>

{#if picking !== null}
  {@const slot = slotCodes[picking]!}
  <button class="tm-scrim" aria-label="닫기" onclick={onclose}></button>
  <div class="tm-sheet" role="dialog" aria-modal="true" aria-label="{DETAIL_LABEL[slot]} 자리 선수 고르기">
    <div class="tm-sheet-head">
      <div>
        <div class="eyebrow">{slot}</div>
        <h2>{DETAIL_LABEL[slot]}</h2>
      </div>
      <button class="icon-btn" onclick={onclose}>닫기</button>
    </div>
    <div class="seg three tm-sort" role="group" aria-label="정렬">
      {#each PICK_SORTS as [k, label] (k)}
        <button class="opt" aria-pressed={sort === k} onclick={() => (sort = k)} data-pick-sort={k}>{label}</button>
      {/each}
    </div>
    <div class="tm-list">
      <button class="tm-pick" aria-pressed={slots[picking] === null} onclick={() => onassign(null)} data-pick="youth">
        <b class="tm-pick-ovr">{YOUTH_OVR}</b>
        <span class="tm-opp-info"><span>{YOUTH_NAME}</span><small class="muted">자리를 비워 두면 유스 선수가 뛰어요</small></span>
      </button>
      {#each candidates as c (c.p.careerId)}
        <button class="tm-pick" aria-pressed={slots[picking] === c.p.careerId} onclick={() => onassign(c.p.careerId)} data-pick={c.p.careerId}>
          <b class="tm-pick-ovr">{c.rating}</b>
          <span class="tm-opp-info">
            <span>{nameOf(c.p)}</span>
            <small class="muted">{c.p.dpos ? DETAIL_LABEL[c.p.dpos] : POS_LABEL[c.p.pos]} · 최고 {c.p.peak} · 적합 {pct(c.fit)}{c.at >= 0 && c.at !== picking ? ` · ${slotCodes[c.at]} 자리에서 바꿈` : ''}</small>
            {#if attrLine(c.p)}<small class="muted tm-attrs">{attrLine(c.p)}</small>{/if}
          </span>
        </button>
      {:else}
        <p class="muted">넣을 수 있는 은퇴 선수가 없어요.</p>
      {/each}
    </div>
  </div>
{/if}

<style>
  .tm-sort {
    margin-bottom: 6px;
  }
  .tm-attrs {
    font-size: 0.6875rem;
  }
  .tm-pick {
    display: flex;
    align-items: center;
    gap: 10px;
    padding: 10px 0;
    border-top: 1px solid var(--line);
    width: 100%;
    background: none;
    border-inline: 0;
    border-bottom: 0;
    color: inherit;
    font: inherit;
    text-align: left;
    cursor: pointer;
    min-height: 52px;
  }
  .tm-pick[aria-pressed='true'] {
    background: var(--surface-2);
  }
  .tm-opp-info {
    display: flex;
    flex-direction: column;
    gap: 2px;
    flex: 1;
    min-width: 0;
    overflow-wrap: anywhere;
  }
  .tm-pick-ovr {
    flex: none;
    min-width: 2.2em;
    font-family: var(--display);
    font-size: 1.375rem;
    font-weight: 700;
    text-align: center;
    color: var(--accent-text);
  }
  .tm-scrim {
    position: fixed;
    inset: 0;
    z-index: 60;
    border: 0;
    padding: 0;
    background: rgba(0, 0, 0, 0.45);
  }
  .tm-sheet {
    position: fixed;
    z-index: 61;
    left: 50%;
    bottom: 0;
    transform: translateX(-50%);
    width: min(100%, 560px);
    max-height: 78vh;
    display: flex;
    flex-direction: column;
    padding: 16px 16px calc(12px + var(--safe-b));
    border-radius: 18px 18px 0 0;
    background: var(--surface);
    color: var(--ink);
    box-shadow: var(--shadow);
  }
  .tm-sheet-head {
    display: flex;
    justify-content: space-between;
    align-items: flex-start;
    gap: 12px;
    padding-bottom: 8px;
  }
  .tm-list {
    overflow-y: auto;
    overscroll-behavior: contain;
  }
</style>

// apps/mobile/src/screens/owner/TeamPicker.tsx
// 선수 고르기 시트(웹 team/Team.svelte 의 .tm-sheet) — 고른 자리에 넣을 은퇴 선수. 정렬 셋 · 유스 선수(자리 비우기).
import { Modal, Pressable, ScrollView, View } from 'react-native';
import { useSafeAreaInsets } from 'react-native-safe-area-context';
import { useSnapshot } from 'valtio';
import { DETAIL_LABEL, YOUTH_NAME, YOUTH_OVR, type DetailPos } from '@offside/contracts/owner-team';
import type { TeamPlayer } from '@offside/app-core/api/team';
import {
  PICK_SORTS,
  attrLine,
  pct,
  type PickCandidate,
  type PickSort,
} from '@offside/app-core/teamOwner';
import { POS_LABEL } from '@offside/game/pos-label';
import { prefs } from '../../store';
import { useColors } from '../../theme/useColors';
import { DISPLAY, rem } from '../../theme/type';
import { Btn, Press, Txt } from '../../ui';
import { Seg, SegBtn } from './TeamParts';

export function TeamPicker({
  slot,
  slotCodes,
  current,
  sort,
  setSort,
  candidates,
  nameOf,
  onAssign,
  onClose,
}: {
  /** 고르는 자리(포메이션 자리 코드). null이면 닫힘. */
  slot: DetailPos | null;
  slotCodes: readonly DetailPos[];
  /** 그 자리에 지금 편성된 선수(빈 자리면 null). */
  current: string | null;
  sort: PickSort;
  setSort: (s: PickSort) => void;
  candidates: PickCandidate[];
  nameOf: (p: TeamPlayer) => string;
  onAssign: (id: string | null) => void;
  onClose: () => void;
}) {
  const c = useColors();
  const insets = useSafeAreaInsets();
  const { motionOK } = useSnapshot(prefs);
  const row = (selected: boolean) =>
    ({
      flexDirection: 'row',
      alignItems: 'center',
      gap: 10,
      paddingVertical: 10,
      borderTopWidth: 1,
      borderTopColor: c.line,
      minHeight: 52,
      backgroundColor: selected ? c.surface2 : 'transparent',
    }) as const;
  const ovr = {
    minWidth: rem(1.375) * 1.6,
    fontFamily: DISPLAY[700],
    fontSize: rem(1.375),
    textAlign: 'center',
  } as const;
  return (
    <Modal
      visible={slot !== null}
      transparent
      animationType={motionOK ? 'slide' : 'none'}
      statusBarTranslucent
      onRequestClose={onClose}
    >
      <View style={{ flex: 1, justifyContent: 'flex-end' }}>
        <Pressable
          accessibilityLabel="닫기"
          onPress={onClose}
          style={{
            position: 'absolute',
            top: 0,
            left: 0,
            right: 0,
            bottom: 0,
            backgroundColor: 'rgba(0,0,0,0.45)',
          }}
        />
        {slot ? (
          <View
            accessibilityViewIsModal
            accessibilityLabel={`${DETAIL_LABEL[slot]} 자리 선수 고르기`}
            style={{
              maxHeight: '78%',
              paddingTop: 16,
              paddingHorizontal: 16,
              paddingBottom: 12 + insets.bottom,
              borderTopLeftRadius: 18,
              borderTopRightRadius: 18,
              backgroundColor: c.surface,
            }}
          >
            <View
              style={{
                flexDirection: 'row',
                justifyContent: 'space-between',
                alignItems: 'flex-start',
                gap: 12,
                paddingBottom: 8,
              }}
            >
              <View>
                <Txt v="eyebrow">{slot}</Txt>
                <Txt v="h2" accessibilityRole="header">
                  {DETAIL_LABEL[slot]}
                </Txt>
              </View>
              <Btn sm onPress={onClose} testID="pick-close">
                닫기
              </Btn>
            </View>
            <View style={{ marginBottom: 6 }}>
              <Seg label="정렬">
                {PICK_SORTS.map(([k, label]) => (
                  <SegBtn
                    key={k}
                    selected={sort === k}
                    onPress={() => setSort(k)}
                    testID={`pick-sort-${k}`}
                  >
                    <Txt style={{ fontWeight: '600' }}>{label}</Txt>
                  </SegBtn>
                ))}
              </Seg>
            </View>
            <ScrollView nestedScrollEnabled>
              <Press
                testID="pick-youth"
                scale={0.985}
                accessibilityState={{ selected: current === null }}
                onPress={() => onAssign(null)}
                style={row(current === null)}
              >
                <Txt tone="accent" style={ovr}>
                  {YOUTH_OVR}
                </Txt>
                <View style={{ flex: 1, minWidth: 0, gap: 2 }}>
                  <Txt>{YOUTH_NAME}</Txt>
                  <Txt tone="muted" v="xs">
                    자리를 비워 두면 유스 선수가 뛰어요
                  </Txt>
                </View>
              </Press>
              {candidates.length ? (
                candidates.map((cd) => {
                  const line = attrLine(cd.p);
                  const picked = current === cd.p.careerId;
                  return (
                    <Press
                      key={cd.p.careerId}
                      testID={`pick-${cd.p.careerId}`}
                      scale={0.985}
                      accessibilityState={{ selected: picked }}
                      onPress={() => onAssign(cd.p.careerId)}
                      style={row(picked)}
                    >
                      <Txt tone="accent" style={ovr}>
                        {cd.rating}
                      </Txt>
                      <View style={{ flex: 1, minWidth: 0, gap: 2 }}>
                        <Txt>{nameOf(cd.p)}</Txt>
                        <Txt tone="muted" v="xs">
                          {`${cd.p.dpos ? DETAIL_LABEL[cd.p.dpos] : POS_LABEL[cd.p.pos]} · 최고 ${cd.p.peak} · 적합 ${pct(cd.fit)}${cd.at >= 0 && slotCodes[cd.at] && current !== cd.p.careerId ? ` · ${slotCodes[cd.at]} 자리에서 바꿈` : ''}`}
                        </Txt>
                        {line ? (
                          <Txt tone="muted" style={{ fontSize: rem(0.6875) }}>
                            {line}
                          </Txt>
                        ) : null}
                      </View>
                    </Press>
                  );
                })
              ) : (
                <Txt tone="muted">넣을 수 있는 은퇴 선수가 없어요.</Txt>
              )}
            </ScrollView>
          </View>
        ) : null}
      </View>
    </Modal>
  );
}
