// apps/web/src/ui/team/Team.svelte
<script lang="ts">
  // T-10-092 구단주 팀 — 시즌마다 그 시즌에 뛰고 은퇴한 내 선수로 11명을 꾸려(빈 자리는 유스 선수가 채운다) 같은 시즌
  // 다른 구단주의 팀과 겨룬다. 지난 시즌 팀은 보기만 한다. 구단주 화면에서 처음 열 때 불러오는 지연 청크다. 경기 결과는
  // 서버가 정한다(웹은 보여 주기만).
  import { onDestroy, onMount, untrack } from 'svelte';
  import {
    FORMATIONS,
    LINEUP_SIZE,
    MANAGER_NAME_MAX,
    MANAGER_NAME_MIN,
    TEAM_NAME_MAX,
    TEAM_NAME_MIN,
    YOUTH_NAME,
    YOUTH_OVR,
    presetLayout,
    slotRating,
    teamOvr,
    type AchCategory,
    type FormationId,
    type TeamPosition,
  } from '@offside/contracts/owner-team';
  import {
    fetchClubAchievements,
    fetchOpponents,
    fetchOwnerTeam,
    fetchTeamMatches,
    playMatch,
    saveOwnerTeam,
    type ClubAchievementsResponse,
    type OwnerTeam,
    type OwnerTeamResponse,
    type TeamMatch,
    type TeamOpponent,
    type TeamPlayer,
  } from '@offside/app-core/api/team';
  import { localCareerNames } from '@offside/game/season';
  import type { TeamLogo } from '@offside/contracts/team-logo';
  import TeamLogoEditor from './TeamLogoEditor.svelte';
  import { go } from '../nav.js';
  import { anonName } from '@offside/game/pos-label';
  import { toast } from '../helpers.js';
  import { dur } from '../motion.js';
  import { startGoogleLogin } from '../login.js';
  import LoadState, { type LoadStatus } from '../LoadState.svelte';
  import { appState, hofStart, type TeamView } from '../state.svelte.js';
  import Topbar from '../Topbar.svelte';
  import BackBar from '../BackBar.svelte';
  import TeamAchievements from './TeamAchievements.svelte';
  import TeamHead from './TeamHead.svelte';
  import TeamHistory from './TeamHistory.svelte';
  import TeamLineup from './TeamLineup.svelte';
  import TeamLive from './TeamLive.svelte';
  import TeamNav from './TeamNav.svelte';
  import TeamOpponents from './TeamOpponents.svelte';
  import TeamResult from './TeamResult.svelte';
  import TeamFriends from './TeamFriends.svelte';
  import { friendsUi } from '../friendInvite.svelte.js';
  import { achNudge } from '../achNudge.js';
  import { WILDCARD_FULL_TEXT, assignSlot, autoFillSlots, draftLines, isPreseasonLegacy, matchHintOf, overWildcards, slotsSynergy, teamEditableIn } from '@offside/app-core/teamOwner';
  import { accountCache } from '../account-state.svelte.js';
  import { readTeamDraft, teamDraftBase, writeTeamDraft, type TeamDraft } from './teamDraft.js';

  let status = $state<LoadStatus>('loading');
  let needLogin = $state(false);
  let team = $state<OwnerTeam | null>(null);
  let players = $state<TeamPlayer[]>([]);
  let matchesLeft = $state(0);
  let perDay = $state(0);
  /** 보고 있는 시즌 · 지금 고치고 겨루는 시즌(휴식기면 null) · 고를 수 있는 시즌. */
  let season = $state(0);
  let current = $state<number | null>(null);
  let seasons = $state<OwnerTeamResponse['seasons']>([]);
  let lastManager = $state<string | null>(null);
  // T-11-113 개막 뒤에도 프리시즌 팀은 친선전용으로 고칠 수 있다.
  const editable = $derived(teamEditableIn(season, current));
  const seasonName = $derived(seasons.find((o) => o.id === season)?.name ?? '');

  // 편집 초안 — 저장하기 전까지 이 기기에만 있다.
  let name = $state('');
  let manager = $state('');
  let logo = $state<TeamLogo | null>(null);
  let editingLogo = $state(false);
  let formation = $state<FormationId>('4-3-3');
  let layout = $state<TeamPosition[] | null>(null);
  let slots = $state<(string | null)[]>(Array(LINEUP_SIZE).fill(null));
  let saving = $state(false);
  /** 팀이 있으면 이름 칸은 '이름 바꾸기'를 눌렀을 때만 펼친다. */
  let renaming = $state(false);
  let draftKey = $state<string | null>(null);
  let pendingDraft = $state<TeamDraft | null>(null);
  let restoredDraft = $state(false);
  let loadSequence = 0;

  let opponents = $state<TeamOpponent[]>([]);
  let oppStatus = $state<LoadStatus>('loading');
  let playing = $state(false);
  let result = $state<TeamMatch | null>(null);
  let resultOrigin = $state<'opponents' | 'history'>('opponents');
  /** 방금 치른 경기(또는 '다시 보기')를 문자중계로 보여 주는 중(T-10-097). */
  let live = $state(false);
  /** T-11-098 오늘 남은 친선전(친선전 결과 화면의 '다시 경기하기'). */
  let friendlyLeft = $state(0);
  // T-10-130 팀 안의 화면은 appState.teamView — 뒤로 가기로 오간다. 결과는 이 화면에만 있어 다시 들어왔을 때(앞으로 가기)
  // 없으면 팀을 보여 준다.
  const view = $derived(appState.teamView === 'result' && !result ? 'team' : appState.teamView);
  const show = (v: TeamView) => (appState.teamView = v);
  let history = $state<TeamMatch[]>([]);
  let histStatus = $state<LoadStatus>('loading');
  let ach = $state<ClubAchievementsResponse | null>(null);
  let achStatus = $state<LoadStatus>('loading');
  /** T-11-028 업적 화면에서 보고 있는 분류(선수·팀·구단주·감독). */
  let achCat = $state<AchCategory>('player');
  /** T-11-034 지난번 업적 탭을 본 뒤 새로 오른 업적(NEW). */
  let achNewIds = $state<ReadonlySet<string>>(new Set());

  // 서버에는 비공개 이름이 없다 — 이 기기에서 은퇴한 선수는 이 기기에 남은 이름을 쓴다.
  const localNames = localCareerNames();
  const byId = $derived(new Map(players.map((p) => [p.careerId, p])));
  const nameOf = (p: TeamPlayer) =>
    localNames.get(p.careerId) ?? p.publicName ?? anonName(p.pos, p.number);
  const eventName = (id: string | null, fallback: string) => (id && localNames.get(id)) || fallback;

  const slotCodes = $derived(layout?.map((p) => p.slot) ?? FORMATIONS[formation]);
  const ratings: (number | null)[] = $derived(
    slotCodes.map((slot, i) => {
      const id = slots[i];
      const p = id ? byId.get(id) : undefined;
      return p ? slotRating(slot, p) : null;
    }),
  );
  const ovr = $derived(teamOvr(ratings));
  // T-11-105 선발 시너지 — 늘 보여 주고, 반영 시즌부터 줄 힘에도 더한다.
  const synergy = $derived(slotsSynergy(layout ?? presetLayout(formation), slots, byId));
  // 공격·중원·수비·골키퍼 힘 — 자리별 실력에 포메이션의 줄 무게를 더한 값(서버 경기 계산과 같은 규칙).
  const lines = $derived(draftLines(slotCodes, ratings, synergy, season));
  const filled = $derived(slots.filter((s) => s !== null).length);
  const dirty = $derived(
    !team ||
      name.trim() !== team.name ||
      manager.trim() !== team.manager ||
      JSON.stringify(logo) !== JSON.stringify(team.logo ?? null) ||
      formation !== team.formation ||
      JSON.stringify(layout) !== JSON.stringify(team.layout ?? null) ||
      slots.some((id, i) => id !== (team?.slots[i]?.careerId ?? null)),
  );
  const between = (v: string, min: number, max: number) => v.trim().length >= min && v.trim().length <= max;
  const nameOk = $derived(
    between(name, TEAM_NAME_MIN, TEAM_NAME_MAX) && between(manager, MANAGER_NAME_MIN, MANAGER_NAME_MAX),
  );
  const cells = $derived(
    slots.map((id, i) => {
      const p = id ? byId.get(id) : undefined;
      return { rating: ratings[i] ?? YOUTH_OVR, name: p ? nameOf(p) : YOUTH_NAME, youth: !p, player: p };
    }),
  );
  const matchHint = $derived(matchHintOf(team, dirty, matchesLeft, season, current));

  const draftValue = () => ({ name, manager, logo, formation, layout, slots });
  function preserveDraft() {
    if (status !== 'ready' || !editable || !draftKey || pendingDraft) return;
    const hasChanges = team ? dirty : !!name || !!logo || !!layout || slots.some(Boolean) || formation !== '4-3-3' || manager !== (lastManager ?? '');
    writeTeamDraft(draftKey, hasChanges ? { base: teamDraftBase(team), value: draftValue() } : null);
  }
  $effect(preserveDraft);
  onDestroy(preserveDraft);

  function restoreDraft(draft: TeamDraft) {
    ({ name, manager, formation, slots } = draft.value);
    logo = draft.value.logo ?? null;
    layout = draft.value.layout ?? null;
    renaming = !!team && (name !== team.name || manager !== team.manager);
    pendingDraft = null;
    restoredDraft = true;
  }
  function discardDraft() {
    if (draftKey) writeTeamDraft(draftKey, null);
    pendingDraft = null;
    restoredDraft = false;
    applyTeam(team);
    renaming = false;
  }

  function applyTeam(t: OwnerTeam | null) {
    team = t;
    name = t?.name ?? '';
    manager = t?.manager || lastManager || '';
    logo = t?.logo ?? null;
    editingLogo = false;
    formation = t?.formation ?? '4-3-3';
    layout = t?.layout?.map((p) => ({ ...p })) ?? null;
    slots = t ? t.slots.map((s) => s.careerId) : Array(LINEUP_SIZE).fill(null);
  }

  async function load(want?: number) {
    preserveDraft();
    const sequence = ++loadSequence;
    status = 'loading';
    const r = await fetchOwnerTeam(want);
    if (sequence !== loadSequence) return;
    if (!r.ok) {
      needLogin = r.error.reason === 'GOOGLE_LOGIN_REQUIRED' || r.error.code === 'PROFILE_REQUIRED';
      status = needLogin ? 'ready' : 'error';
      return;
    }
    ({ season, current, seasons, lastManager, players, matchesLeft } = r.data);
    perDay = r.data.matchesPerDay;
    needLogin = false;
    applyTeam(r.data.team);
    const account = accountCache.value;
    draftKey = team?.id ?? (account && account !== 'error' ? `${account.id}:${season}` : null);
    pendingDraft = null;
    restoredDraft = false;
    const draft = editable && draftKey ? readTeamDraft(draftKey) : null;
    if (draft) {
      if (draft.base === teamDraftBase(team)) restoreDraft(draft);
      else pendingDraft = draft;
    }
    status = 'ready';
  }
  /** 시즌을 바꿔 본다(지난 시즌 팀은 보기만). */
  function pickSeason(id: number) {
    show('team');
    void load(id);
  }
  /** T-11-028 기록실 구단주 랭킹. */
  function openAchRanking() {
    appState.hof = { ...hofStart(), tab: 'ach' };
    go('hof');
  }
  onMount(() => void load());

  // ───────── 편성 ─────────
  /** 라커룸에서 넣거나, 이미 선발인 선수의 두 자리를 바꾼다. T-11-114 지난 시즌 선수는 와일드카드 상한까지만. */
  function assign(index: number, id: string | null) {
    if (overWildcards(slots, index, id, byId, season)) return toast(WILDCARD_FULL_TEXT);
    slots = assignSlot(slots, index, id);
  }

  /** 자리마다 가장 잘 맞는 선수부터 채운다(유스 선수보다 나을 때만). */
  function autoFill() {
    slots = autoFillSlots(slotCodes, players, season);
  }

  async function save(): Promise<boolean> {
    if (saving || !nameOk || !editable || pendingDraft) return false;
    const key = draftKey;
    const sequence = loadSequence;
    const submitted = JSON.parse(JSON.stringify(draftValue())) as ReturnType<typeof draftValue>;
    saving = true;
    const r = await saveOwnerTeam({
      ...submitted, name: submitted.name.trim(), manager: submitted.manager.trim(),
      ...(isPreseasonLegacy(season, current) ? { season: 0 } : {}),
    });
    saving = false;
    if (!r.ok) { toast(r.error.message); return false; }
    if (sequence !== loadSequence) { if (key) writeTeamDraft(key, null); return false; }
    const created = !team;
    const unchanged = JSON.stringify(submitted) === JSON.stringify(draftValue());
    if (!unchanged) {
      team = r.data.team;
      preserveDraft();
      toast('저장했어요. 그 뒤에 바꾼 내용은 아직 저장 전이에요.');
      return false;
    }
    if (key) writeTeamDraft(key, null);
    applyTeam(r.data.team);
    draftKey = r.data.team.id;
    pendingDraft = null;
    restoredDraft = false;
    renaming = false;
    toast(created ? '팀을 만들었어요' : '변경 사항을 저장했어요');
    return true;
  }

  async function saveAndFindOpponents() {
    if (!await save()) return;
    if (appState.screen === 'team' && view === 'opponents' && !matchHint) await loadOpponents();
  }

  // ───────── 경기 ─────────
  async function loadOpponents() {
    oppStatus = 'loading';
    const r = await fetchOpponents();
    if (!r.ok) {
      oppStatus = 'error';
      return;
    }
    opponents = r.data.items;
    oppStatus = 'ready';
  }

  async function challenge(o: TeamOpponent) {
    if (playing) return;
    playing = true;
    const r = await playMatch(o.teamId);
    playing = false;
    if (!r.ok) {
      if (r.error.reason === 'TEAM_MATCH_DAILY_LIMIT') matchesLeft = 0;
      if (r.error.reason === 'TEAM_OPPONENT_DAILY_LIMIT')
        opponents = opponents.filter((x) => x.teamId !== o.teamId);
      return toast(r.error.message);
    }
    result = r.data.match;
    resultOrigin = 'opponents';
    live = true;
    matchesLeft = r.data.matchesLeft;
    if (team) {
      team.record = r.data.record;
      team.rating = r.data.rating;
    }
    show('result');
    window.scrollTo(0, 0);
  }

  // T-11-098 친선전 결과(방금 치른 경기는 중계부터, 최근 친선전은 결과부터). 결과에서 돌아가면 '경기' 탭의 친구 쪽이다.
  function openFriendly(m: TeamMatch, left: number, fresh: boolean) {
    result = m;
    resultOrigin = 'opponents';
    live = fresh;
    friendlyLeft = left;
    show('result');
    window.scrollTo(0, 0);
  }

  // ───────── 시즌 업적 ─────────
  async function loadAchievements(want = season) {
    achStatus = 'loading';
    const r = await fetchClubAchievements(want);
    if (!r.ok) {
      achStatus = 'error';
      return;
    }
    ach = r.data;
    // T-11-034 가장 최근 시즌을 열면 본 것으로 적고, 지난번 뒤로 새로 오른 업적에 NEW를 붙여 그 분류·단계를 펼친다.
    const latest = Math.max(r.data.season, ...r.data.seasons.map((o) => o.id));
    achNewIds = r.data.season === latest ? achNudge.viewed(r.data) : new Set();
    const first = r.data.groups.find((g) => g.items.some((i) => achNewIds.has(i.id)));
    if (first) achCat = first.category;
    achStatus = 'ready';
  }

  async function loadHistory() {
    histStatus = 'loading';
    const r = await fetchTeamMatches(season);
    if (!r.ok) {
      histStatus = 'error';
      return;
    }
    history = r.data.items;
    histStatus = 'ready';
  }

  // 화면마다 불러올 내용. 다른 화면에서 들어오면(뒤로·앞으로 가기 포함) 아래 $effect가, 이미 그 화면이면 open이 다시 불러온다.
  const LOAD = {
    opponents: () => (matchHint || friendsUi.mode === 'friends' ? undefined : loadOpponents()),
    achievements: () => loadAchievements(),
    history: loadHistory,
  };
  function open(v: keyof typeof LOAD) {
    if (appState.teamView === v) void LOAD[v]();
    else show(v);
  }
  $effect(() => {
    const v = appState.teamView;
    if (status !== 'ready' || needLogin) return;
    if (v in LOAD) untrack(() => void LOAD[v as keyof typeof LOAD]());
  });
  const navOn = $derived(view === 'result' ? resultOrigin : view);
  /** 탭을 바꾸면 맨 위에서 시작하고, 보고 있는 탭을 다시 누르면 맨 위로 부드럽게 올린다(게임 화면 탭과 같다). */
  function switchView(v: TeamView) {
    if (view === v) return window.scrollTo({ top: 0, behavior: dur(1) ? 'smooth' : 'instant' });
    show(v);
    window.scrollTo({ top: 0, behavior: 'instant' });
  }
</script>

<div class="wrap" class:has-tabbar={!needLogin} class:lineup-editor={view === 'team' && !needLogin}>
  <Topbar />

  <LoadState {status} failText="팀을 불러오지 못했어요." retry={load}>
    {#if needLogin}
      <section class="card stack" style="gap:10px">
        <div class="eyebrow">My team</div>
        <h1>내 팀</h1>
        <p class="muted">로그인한 구단주만 은퇴한 선수로 팀을 꾸릴 수 있어요.</p>
        <button class="btn btn-primary self-start" onclick={() => void startGoogleLogin(null)}>구글로 로그인</button>
      </section>
    {:else if view === 'achievements'}
      <TeamAchievements {ach} status={achStatus} newIds={achNewIds} bind:cat={achCat} load={(s) => void loadAchievements(s)} onrank={openAchRanking} />
    {:else if view === 'team'}
      {#if pendingDraft}
        <section class="card draft-notice" role="status">
          <p>저장된 팀이 바뀌었어요. 이전에 수정하던 초안도 남아 있어요.</p>
          <div><button class="btn btn-sm" onclick={() => pendingDraft && restoreDraft(pendingDraft)} data-act="team-draft-restore">초안 불러오기</button><button class="btn btn-sm" onclick={discardDraft}>저장된 팀 유지</button></div>
        </section>
      {:else if restoredDraft && dirty}
        <section class="card draft-notice" role="status"><p>이 탭에서 수정하던 내용을 불러왔어요. 아직 저장 전이에요.</p><button class="btn btn-sm" onclick={discardDraft} data-act="team-draft-discard">저장된 팀으로</button></section>
      {/if}
      <TeamHead
        {team}
        {logo}
        onlogo={() => (editingLogo = true)}
        {seasonName}
        {editable}
        {dirty}
        {ovr}
        {matchesLeft}
        {perDay}
        {seasons}
        {season}
        {current}
        bind:name
        bind:manager
        bind:renaming
        onseason={pickSeason}
      />
      {#if editingLogo && editable}<TeamLogoEditor {logo} name={name.trim() || '내 팀'} onapply={(value) => { logo = value; editingLogo = false; }} onclose={() => (editingLogo = false)} />{/if}
      <TeamLineup
        {team}
        teamLogo={logo}
        teamName={name.trim()}
        managerName={manager.trim()}
        {editable}
        bind:formation
        bind:layout
        {slots}
        {nameOf}
        {lines}
        {synergy}
        {season}
        {cells}
        {players}
        {seasonName}
        {filled}
        {saving}
        nameOk={nameOk && !pendingDraft}
        {dirty}
        onassign={assign}
        onauto={autoFill}
        onsave={save}
      />
    {:else if view === 'opponents'}
      <div class="seg two tm-mode" role="group" aria-label="경기 종류">
        <button class="hof-sort" aria-pressed={friendsUi.mode === 'ranked'} data-match-mode="ranked" onclick={() => { if (friendsUi.mode === 'ranked') return; friendsUi.mode = 'ranked'; if (!matchHint && oppStatus !== 'ready') void loadOpponents(); }}>랭크 경기</button>
        <button class="hof-sort" aria-pressed={friendsUi.mode === 'friends'} data-match-mode="friends" onclick={() => (friendsUi.mode = 'friends')}>친구</button>
      </div>
      {#if friendsUi.mode === 'friends'}
        <TeamFriends onplayed={(m, left) => openFriendly(m, left, true)} onopen={(m, left) => openFriendly(m, left, false)} onpreseason={() => pickSeason(0)} />
      {:else}
      <TeamOpponents
        ovr={team?.ovr ?? ovr}
        {matchesLeft}
        {perDay}
        {opponents}
        status={oppStatus}
        {playing}
        hint={matchHint}
        onreload={() => void loadOpponents()}
        onchallenge={(o) => void challenge(o)}
        onmore={() => open('opponents')}
        ontoTeam={editable ? () => switchView('team') : undefined}
        onsave={season === current && dirty && filled > 0 && matchesLeft > 0 ? () => void saveAndFindOpponents() : undefined}
        {saving}
        saveDisabled={!nameOk || !!pendingDraft}
      />
      {/if}
    {:else if view === 'result' && result}
      {#if live}
        {#key result.id}
          <TeamLive match={result} name={eventName} onend={() => ((live = false), window.scrollTo(0, 0))} />
        {/key}
      {:else}
        <TeamResult
          m={result}
          {team}
          {eventName}
          matchesLeft={result.friendly ? friendlyLeft : matchesLeft}
          ontoTeam={() => switchView('team')}
          onreplay={() => (live = true)}
          onagain={() => open('opponents')}
          onhistory={resultOrigin === 'history' ? () => switchView('history') : undefined}
        />
      {/if}
    {:else if view === 'history'}
      <TeamHistory
        {history}
        status={histStatus}
        onreload={() => void loadHistory()}
        onopen={(m) => { result = m; resultOrigin = 'history'; live = false; switchView('result'); }}
      />
    {/if}
  </LoadState>
  {#if needLogin}<BackBar act="team-back" fallback={() => (appState.screen = 'owner')} />{/if}
</div>

{#if !needLogin}
  <TeamNav {navOn} onswitch={switchView} />
{/if}

<style>
  .lineup-editor { max-width: 880px; }
  .tm-mode { margin-bottom: 12px; }
  .draft-notice {display:flex;align-items:center;justify-content:space-between;flex-wrap:wrap;gap:10px;padding:12px 16px;}
  .draft-notice p {margin:0;font-size:13px;flex:1 1 200px;}
  .draft-notice > div {display:flex;flex-wrap:wrap;gap:8px;}
  .draft-notice .btn {min-height:44px;}
</style>

// apps/mobile/src/screens/owner/Team.tsx
// T-10-092 구단주 팀(웹 team/Team.svelte) — 시즌마다 그 시즌에 뛰고 은퇴한 내 선수로 11명을 꾸려(빈 자리는 유스 선수가
// 채운다) 같은 시즌 다른 구단주의 팀과 겨룬다. 지난 시즌 팀은 보기만 한다. 경기 결과는 서버가 정한다(앱은 보여 주기만).
// 편성·후보·업적 표기 같은 순수 계산은 웹과 같은 @offside/app-core/teamOwner.
import { useEffect, useMemo, useRef, useState } from 'react';
import { View } from 'react-native';
import { useSnapshot } from 'valtio';
import {
  FORMATION_IDS,
  presetLayout,
  type TeamPosition,
  LINEUP_SIZE,
  MANAGER_NAME_MAX,
  MANAGER_NAME_MIN,
  TEAM_NAME_MAX,
  TEAM_NAME_MIN,
  YOUTH_NAME,
  YOUTH_OVR,
  lineStrength,
  slotRating,
  teamOvr,
  type FormationId,
} from '@offside/contracts/owner-team';
import {
  fetchClubAchievements,
  fetchOpponents,
  fetchOwnerTeam,
  fetchTeamMatches,
  playMatch,
  saveOwnerTeam,
  type ClubAchievementsResponse,
  type OwnerTeam,
  type OwnerTeamResponse,
  type TeamMatch,
  type TeamOpponent,
  type TeamPlayer,
} from '@offside/app-core/api/team';
import { type TeamView } from '@offside/app-core/state';
import { recordText, num } from '@offside/app-core/teamText';
import { autoFillSlots, matchHintOf } from '@offside/app-core/teamOwner';
import { anonName } from '@offside/game/pos-label';
import { localCareerNames } from '@offside/game/season';
import { LoadState, type LoadStatus } from '../../components/LoadState';
import { TeamLines } from '../../components/TeamPitch';
import { toast } from '../../game/host';
import { go } from '../../game/nav';
import { achNudge } from '../../game/achNudge';
import { accountCache, appState, prefs } from '../../store';
import { notificationDestination } from '../../platform/notificationDestination';
import { useColors } from '../../theme/useColors';
import { BackBar, Btn, Card, Screen, Topbar, Txt, scrollTo } from '../../ui';
import { BarBelow } from '../../ui/Screen';
import { TabBar, type TabItem } from '../../ui/TabBar';
import type { TabIconName } from '../../ui/TabIcon';
import { Field, SelectField, TextField } from '../settings/parts';
import { LoginButtons } from './LoginButtons';
import { TeamAchievements } from './TeamAchievements';
import { TeamFriends, OppSwitch, useFriends, type OppTab } from './TeamFriends';
import { TeamHistory } from './TeamHistory';
import { TeamLive } from './TeamLive';
import { TeamOpponents } from './TeamOpponents';
import { OvrBadge } from './TeamParts';
import { TeamLineup } from './TeamLineup';
import { TeamLogo } from '../../components/TeamLogo';
import { TeamLogoEditor } from './TeamLogoEditor';
import { TeamShare, type TeamShareData } from './TeamShare';
import { TeamDialog } from '../../components/TeamDialog';
import type { TeamLogo as Logo } from '@offside/contracts/team-logo';
import type { PutOwnerTeamBody } from '@offside/contracts';
import { readTeamDraft, writeTeamDraft, teamDraftBase, type TeamDraft } from './teamDraft';
import { RecordsChips as SortChips } from '../hof/RecordsControls';
import { TeamResult } from './TeamResult';

const between = (v: string, min: number, max: number) =>
  v.trim().length >= min && v.trim().length <= max;

// T-11-026 내 팀 하단 메뉴 — 편성 · 경기 · (가운데) 구단주 · 업적 · 기록. 경기 결과는 '경기' 탭 안이다.
const NAV: [TeamView, string, TabIconName][] = [
  ['team', '편성', 'lineup'],
  ['opponents', '경기', 'season'],
  ['achievements', '업적', 'trophy'],
  ['history', '경기 기록', 'career'],
];

export default function Team() {
  const c = useColors();
  const { teamView, achNew } = useSnapshot(appState);
  const [status, setStatus] = useState<LoadStatus>('loading');
  const [needLogin, setNeedLogin] = useState(false);
  const [team, setTeam] = useState<OwnerTeam | null>(null);
  const [players, setPlayers] = useState<TeamPlayer[]>([]);
  const [matchesLeft, setMatchesLeft] = useState(0);
  const [perDay, setPerDay] = useState(0);
  /** 보고 있는 시즌 · 지금 고치고 겨루는 시즌(휴식기면 null) · 고를 수 있는 시즌. */
  const [season, setSeason] = useState(0);
  const [current, setCurrent] = useState<number | null>(null);
  const [seasons, setSeasons] = useState<OwnerTeamResponse['seasons']>([]);
  const [lastManager, setLastManager] = useState<string | null>(null);
  const editable = season === current;
  const seasonName = seasons.find((o) => o.id === season)?.name ?? '';

  // 편집 초안 — 저장하기 전까지 이 기기에만 있다.
  const [name, setName] = useState('');
  const [manager, setManager] = useState('');
  const [formation, setFormation] = useState<FormationId>('4-3-3');
  const [slots, setSlots] = useState<(string | null)[]>(Array(LINEUP_SIZE).fill(null));
  const [saving, setSaving] = useState(false);
  /** 팀이 있으면 이름 칸은 '이름 바꾸기'를 눌렀을 때만 펼친다. */
  const [renaming, setRenaming] = useState(false);
  const [layout, setLayout] = useState<TeamPosition[] | null>(null);
  const [logo, setLogo] = useState<Logo | null>(null);
  const [editingLogo, setEditingLogo] = useState(false);
  const [menu, setMenu] = useState(false);
  const [selected, setSelected] = useState<string | null>(null);
  const [dragging, setDragging] = useState(false);
  const [share, setShare] = useState<TeamShareData | null>(null);
  const jump = useRef<(() => void) | null>(null);
  const [draftKey, setDraftKey] = useState<string | null>(null);
  const [pendingDraft, setPendingDraft] = useState<TeamDraft | null>(null);
  const [restored, setRestored] = useState(false);
  const loadSequence = useRef(0);
  const savingRef = useRef(false);
  const draftNow = useRef<PutOwnerTeamBody | null>(null);

  /** T-11-098 '경기' 탭의 두 칸(랭크 경기 · 친구). 친구 칸은 처음 열 때만 불러온다. */
  const destination = useSnapshot(notificationDestination);
  const [oppTab, setOppTab] = useState<OppTab>(destination.friends ? 'friends' : 'ranked');
  const friends = useFriends();
  useEffect(() => {
    if (status !== 'ready' || needLogin) return;
    if (destination.friends) {
      setOppTab('friends');
      notificationDestination.friends = false;
      friends.reload();
    }
    if (destination.history) {
      notificationDestination.history = false;
      void loadHistory();
    }
  }, [destination.friends, destination.history, status, needLogin]);
  const oppLoaded = useRef(false);
  const [opponents, setOpponents] = useState<TeamOpponent[]>([]);
  const [oppStatus, setOppStatus] = useState<LoadStatus>('loading');
  const [playing, setPlaying] = useState(false);
  const [result, setResult] = useState<TeamMatch | null>(null);
  /** 방금 치른 경기(또는 '다시 보기')를 문자중계로 보여 주는 중(T-10-097). */
  const [live, setLive] = useState(false);
  const [resultOrigin, setResultOrigin] = useState<'opponents' | 'history'>('opponents');
  const [history, setHistory] = useState<TeamMatch[]>([]);
  const [histStatus, setHistStatus] = useState<LoadStatus>('loading');
  const [ach, setAch] = useState<ClubAchievementsResponse | null>(null);
  const [achStatus, setAchStatus] = useState<LoadStatus>('loading');
  /** T-11-034 지난번 업적 탭을 본 뒤 새로 오른 업적(NEW). */
  const [achNewIds, setAchNewIds] = useState<ReadonlySet<string>>(new Set());

  // T-10-130 팀 안의 화면은 appState.teamView — 뒤로 가기로 오간다. 결과는 이 화면에만 있어 다시 들어왔을 때(앞으로
  // 가기) 없으면 팀을 보여 준다.
  const view: TeamView = teamView === 'result' && !result ? 'team' : teamView;
  const show = (v: TeamView) => {
    appState.teamView = v;
  };

  // 서버에는 비공개 이름이 없다 — 이 기기에서 은퇴한 선수는 이 기기에 남은 이름을 쓴다.
  const localNames = useMemo(() => localCareerNames(), []);
  const byId = new Map(players.map((p) => [p.careerId, p]));
  const nameOf = (p: TeamPlayer) =>
    localNames.get(p.careerId) ?? p.publicName ?? anonName(p.pos, p.number);
  const eventName = (id: string | null, fallback: string) => (id && localNames.get(id)) || fallback;

  const positions = layout ?? presetLayout(formation);
  const slotCodes = positions.map((p) => p.slot);
  const ratings: (number | null)[] = slotCodes.map((slot, i) => {
    const id = slots[i];
    const p = id ? byId.get(id) : undefined;
    return p ? slotRating(slot, p) : null;
  });
  const ovr = teamOvr(ratings);
  // 공격·중원·수비·골키퍼 힘 — 자리별 실력에 포메이션의 줄 무게를 더한 값(서버 경기 계산과 같은 규칙).
  const lines = lineStrength(slotCodes, ratings);
  const filled = slots.filter((s) => s !== null).length;
  const dirty =
    !team ||
    name.trim() !== team.name ||
    manager.trim() !== team.manager ||
    JSON.stringify(logo) !== JSON.stringify(team.logo ?? null) ||
    JSON.stringify(layout) !== JSON.stringify(team.layout ?? null) ||
    formation !== team.formation ||
    slots.some((id, i) => id !== (team.slots[i]?.careerId ?? null));
  const nameOk =
    between(name, TEAM_NAME_MIN, TEAM_NAME_MAX) &&
    between(manager, MANAGER_NAME_MIN, MANAGER_NAME_MAX);
  const cells = slots.map((id, i) => {
    const p = id ? byId.get(id) : undefined;
    return {
      rating: ratings[i] ?? YOUTH_OVR,
      name: p ? nameOf(p) : YOUTH_NAME,
      youth: !p,
      ...(p
        ? { peak: p.peak, number: p.number, legendScore: p.legendScore, nation: p.nation }
        : {}),
    };
  });
  const matchHint = matchHintOf(team, dirty, matchesLeft, season, current);
  const draftValue: PutOwnerTeamBody = { name, manager, logo, formation, slots, layout };
  draftNow.current = draftValue;
  useEffect(() => {
    if (status !== 'ready' || !editable || !draftKey || pendingDraft) return;
    writeTeamDraft(draftKey, dirty ? { base: teamDraftBase(team), value: draftValue } : null);
  }, [
    name,
    manager,
    logo,
    formation,
    slots,
    layout,
    status,
    editable,
    draftKey,
    pendingDraft,
    team,
  ]);
  function applyDraft(value: PutOwnerTeamBody) {
    setName(value.name);
    setManager(value.manager);
    setLogo(value.logo ?? null);
    setFormation(value.formation);
    setSlots([...value.slots]);
    setLayout(value.layout ? [...value.layout] : null);
    setRestored(true);
  }

  function applyTeam(t: OwnerTeam | null, lm: string | null = lastManager) {
    setTeam(t);
    setName(t?.name ?? '');
    setManager(t?.manager || lm || '');
    setFormation(t?.formation ?? '4-3-3');
    setLayout(t?.layout ? [...t.layout] : null);
    setLogo(t?.logo ?? null);
    setSelected(null);
    setSlots(t ? t.slots.map((s) => s.careerId) : Array(LINEUP_SIZE).fill(null));
  }

  async function load(want?: number) {
    const sequence = ++loadSequence.current;
    setDraftKey(null);
    setPendingDraft(null);
    setRestored(false);
    setStatus('loading');
    const r = await fetchOwnerTeam(want);
    if (sequence !== loadSequence.current) return;
    if (!r.ok) {
      const login =
        r.error.reason === 'GOOGLE_LOGIN_REQUIRED' || r.error.code === 'PROFILE_REQUIRED';
      setNeedLogin(login);
      setStatus(login ? 'ready' : 'error');
      return;
    }
    const d = r.data;
    setSeason(d.season);
    setCurrent(d.current);
    setSeasons(d.seasons);
    setLastManager(d.lastManager);
    setPlayers(d.players);
    setMatchesLeft(d.matchesLeft);
    setPerDay(d.matchesPerDay);
    setNeedLogin(false);
    applyTeam(d.team, d.lastManager);
    const profile = accountCache.value;
    const key =
      d.team?.id ??
      (profile && typeof profile === 'object' ? `new:${profile.id}:${d.season}` : null);
    if (d.season === d.current && key) {
      const draft = readTeamDraft(key);
      setDraftKey(key);
      if (draft) {
        if (draft.base === teamDraftBase(d.team)) applyDraft(draft.value);
        else setPendingDraft(draft);
      }
    }
    setStatus('ready');
  }
  /** 시즌을 바꿔 본다(지난 시즌 팀은 보기만). */
  function pickSeason(id: number) {
    show('team');
    void load(id);
  }
  useEffect(() => {
    void load();
    // 처음 한 번만.
  }, []);

  // ───────── 편성 ─────────
  async function save(): Promise<boolean> {
    if (savingRef.current || !nameOk) return false;
    savingRef.current = true;
    setSaving(true);
    const snapshot = JSON.stringify(draftNow.current);
    const body = { ...draftValue, name: name.trim(), manager: manager.trim() };
    try {
      const r = await saveOwnerTeam(body);
      if (!r.ok) {
        toast(r.error.message);
        return false;
      }
      const unchanged = JSON.stringify(draftNow.current) === snapshot;
      const created = !team;
      if (unchanged) {
        applyTeam(r.data.team);
        setRenaming(false);
        setRestored(false);
      } else setTeam(r.data.team);
      if (draftKey)
        writeTeamDraft(
          draftKey,
          unchanged ? null : { base: teamDraftBase(r.data.team), value: draftNow.current! },
        );
      setDraftKey(r.data.team.id);
      toast(created ? '팀을 만들었어요' : '편성을 저장했어요');
      return unchanged;
    } finally {
      savingRef.current = false;
      setSaving(false);
    }
  }
  async function saveAndFind() {
    if (await save()) await loadOpponents();
  }

  // ───────── 경기 ─────────
  async function loadOpponents() {
    oppLoaded.current = true;
    setOppStatus('loading');
    const r = await fetchOpponents();
    if (!r.ok) return setOppStatus('error');
    setOpponents(r.data.items);
    setOppStatus('ready');
  }

  async function challenge(o: TeamOpponent) {
    if (playing) return;
    setPlaying(true);
    const r = await playMatch(o.teamId);
    setPlaying(false);
    if (!r.ok) {
      if (r.error.reason === 'TEAM_MATCH_DAILY_LIMIT') setMatchesLeft(0);
      if (r.error.reason === 'TEAM_OPPONENT_DAILY_LIMIT')
        setOpponents((list) => list.filter((x) => x.teamId !== o.teamId));
      return toast(r.error.message);
    }
    setResultOrigin('opponents');
    setResult(r.data.match);
    setLive(true);
    setMatchesLeft(r.data.matchesLeft);
    setTeam((t) => (t ? { ...t, record: r.data.record, rating: r.data.rating } : t));
    show('result');
    scrollTo(0);
  }

  /** 친구 칸에서 친선전을 치렀거나(중계부터) 최근 친선전을 열 때(결과부터). 친선전은 레이팅·전적을 건드리지 않는다. */
  function showFriendly(m: TeamMatch, withLive: boolean) {
    setResultOrigin('opponents');
    setResult(m);
    setLive(withLive);
    show('result');
    scrollTo(0);
  }
  function pickOppTab(t: OppTab) {
    setOppTab(t);
    if (t === 'friends') friends.ensure();
    else if (!oppLoaded.current && !matchHint) void loadOpponents();
  }

  // ───────── 시즌 업적 ─────────
  async function loadAchievements(want = season) {
    setAchStatus('loading');
    const r = await fetchClubAchievements(want);
    if (!r.ok) return setAchStatus('error');
    setAch(r.data);
    // T-11-034 가장 최근 시즌을 열면 본 것으로 적고, 지난번 뒤로 새로 오른 업적에 NEW를 붙인다(웹 Team.svelte).
    const latest = Math.max(r.data.season, ...r.data.seasons.map((o) => o.id));
    setAchNewIds(r.data.season === latest ? achNudge.viewed(r.data) : new Set());
    setAchStatus('ready');
  }

  async function loadHistory() {
    setHistStatus('loading');
    const r = await fetchTeamMatches(season);
    if (!r.ok) return setHistStatus('error');
    setHistory(r.data.items);
    setHistStatus('ready');
  }

  // 화면마다 불러올 내용. 다른 화면에서 들어오면(뒤로·앞으로 가기 포함) 아래 effect가, 이미 그 화면이면 open이 다시 불러온다.
  const LOAD = {
    opponents: () =>
      destination.friends || oppTab === 'friends'
        ? friends.ensure()
        : matchHint
          ? undefined
          : loadOpponents(),
    achievements: () => loadAchievements(),
    history: loadHistory,
  };
  function open(v: keyof typeof LOAD) {
    if (appState.teamView === v) void LOAD[v]();
    else show(v);
  }
  useEffect(() => {
    if (status !== 'ready' || needLogin) return;
    if (destination.friends || destination.history) return;
    if (teamView === 'opponents') void LOAD.opponents();
    else if (teamView === 'achievements') void loadAchievements();
    else if (teamView === 'history') void loadHistory();
    // 화면·상태가 바뀔 때만(시즌 등 다른 값 변화로는 다시 부르지 않는다).
  }, [teamView, status, needLogin]);

  /** 탭을 바꾸면 맨 위에서 시작하고, 보고 있는 탭을 다시 누르면 맨 위로 부드럽게 올린다(게임 화면 탭과 같다). */
  function switchView(v: TeamView) {
    if (view === v) return scrollTo(0, prefs.motionOK);
    show(v);
    scrollTo(0);
  }
  const navOn = view === 'result' ? resultOrigin : view;
  const navItems: TabItem[] = NAV.map(([k, label, icon]) => ({
    key: icon,
    label,
    active: navOn === k,
    onPress: () => switchView(k),
    testID: `team-tab-${k}`,
    ...(k === 'achievements' ? { dot: achNew } : {}),
  }));
  navItems.splice(2, 0, {
    key: 'owner',
    label: '구단주',
    active: false,
    onPress: () => go('owner'),
    testID: 'team-back',
  });

  let body;
  if (needLogin) {
    body = (
      <Card gap={10}>
        <Txt v="eyebrow">My team</Txt>
        <Txt v="h1" accessibilityRole="header">
          내 팀
        </Txt>
        <Txt tone="muted">로그인한 구단주만 은퇴한 선수로 팀을 꾸릴 수 있어요.</Txt>
        <LoginButtons block={false} />
      </Card>
    );
  } else if (view === 'achievements') {
    body = (
      <TeamAchievements
        ach={ach}
        status={achStatus}
        newIds={achNewIds}
        load={(s) => void loadAchievements(s)}
      />
    );
  } else if (view === 'team') {
    body = (
      <>
        <Card gap={10}>
          {seasons.length > 1 ? (
            <SelectField
              label="시즌"
              testID="team-season"
              value={season}
              options={seasons.map((o) => ({
                value: o.id,
                label: `${o.name}${o.id === current ? ' (지금)' : ''}`,
              }))}
              onChange={pickSeason}
            />
          ) : (
            <Txt v="eyebrow">{`My team · ${seasonName}`}</Txt>
          )}
          <View style={{ flexDirection: 'row', gap: 10, alignItems: 'center' }}>
            <TeamLogo name={name || team?.name || 'FC'} logo={logo} />
            <View style={{ flex: 1, minWidth: 0 }}>
              <Txt v="h2" accessibilityRole="header">
                {name || team?.name || (editable ? '팀 만들기' : '팀 없음')}
              </Txt>
              <Txt
                v="sm"
                tone="muted"
              >{`${manager || team?.manager || '나의'} 감독${dirty && team ? ' · 저장 전' : ''}`}</Txt>
            </View>
            <OvrBadge ovr={ovr} />
          </View>
          {team ? (
            <Txt
              v="sm"
              tone="muted"
              testID="team-record"
            >{`${recordText(team.record)} · 레이팅 ${num(team.rating)} · ${editable ? `오늘 ${matchesLeft}/${perDay}경기` : '지난 시즌'}`}</Txt>
          ) : (
            <Txt v="sm" tone="muted">
              빈 자리는 유스 선수(OVR {YOUTH_OVR})가 채워요. 한 명만 넣어도 경기할 수 있어요.
            </Txt>
          )}
          {editable ? (
            <Btn sm kind="ghost" testID="team-more" onPress={() => setMenu(true)}>
              더보기
            </Btn>
          ) : (
            <Txt v="sm" tone="muted" testID="team-readonly">
              지난 시즌 팀이라 보기만 할 수 있어요.
            </Txt>
          )}
          {editable && (!team || renaming) ? (
            <View style={{ gap: 10 }}>
              <Field label="팀 이름">
                <TextField
                  value={name}
                  onChangeText={setName}
                  maxLength={TEAM_NAME_MAX}
                  testID="team-name"
                  accessibilityLabel="팀 이름"
                />
              </Field>
              <Field label="감독 이름">
                <TextField
                  value={manager}
                  onChangeText={setManager}
                  maxLength={MANAGER_NAME_MAX}
                  testID="team-manager"
                  accessibilityLabel="감독 이름"
                />
              </Field>
            </View>
          ) : null}
        </Card>
        {pendingDraft ? (
          <Card>
            <Txt v="sm">저장된 팀이 바뀌었어요. 이 기기에 남아 있는 편성을 불러올까요?</Txt>
            <Btn
              onPress={() => {
                applyDraft(pendingDraft.value);
                setPendingDraft(null);
              }}
            >
              이 기기 편성 불러오기
            </Btn>
            <Btn
              kind="ghost"
              onPress={() => {
                if (draftKey) writeTeamDraft(draftKey, null);
                setPendingDraft(null);
              }}
            >
              저장된 팀 유지
            </Btn>
          </Card>
        ) : restored ? (
          <Card>
            <Txt v="sm">저장 전 편성을 복원했어요. 편성 저장을 누르면 팀에 반영돼요.</Txt>
            <Btn
              sm
              kind="ghost"
              onPress={() => {
                applyTeam(team);
                setRestored(false);
                if (draftKey) writeTeamDraft(draftKey, null);
              }}
            >
              저장된 팀으로 되돌리기
            </Btn>
          </Card>
        ) : null}
        {editable || team ? (
          <>
            <Card gap={8}>
              <View
                style={{
                  flexDirection: 'row',
                  justifyContent: 'space-between',
                  alignItems: 'center',
                }}
              >
                <Txt v="h2">그라운드</Txt>
                <Txt v="sm" tone="muted">{`선발 ${filled} · 유스 ${LINEUP_SIZE - filled}`}</Txt>
              </View>
              {editable ? (
                <SortChips
                  label="포메이션 기본 배치"
                  value={layout ? 'custom' : formation}
                  items={FORMATION_IDS.map((key) => ({ key, label: key }))}
                  onPick={(key) => {
                    setFormation(key as FormationId);
                    setLayout(null);
                  }}
                  testIDPrefix="formation"
                />
              ) : null}
              <TeamLines lines={lines} />
              <View style={{ flexDirection: 'row', gap: 8 }}>
                {editable ? (
                  <Btn
                    sm
                    testID="team-auto"
                    disabled={!players.length}
                    style={{ flex: 1 }}
                    onPress={() => setSlots(autoFillSlots(slotCodes, players))}
                  >
                    자동 배치
                  </Btn>
                ) : null}
                <Btn
                  sm
                  testID="team-share"
                  style={{ flex: 1 }}
                  onPress={() =>
                    setShare({
                      name: name || team?.name || '나의 팀',
                      manager,
                      logo,
                      formation,
                      layout: positions,
                      cells,
                      ovr,
                      lines,
                      draft: dirty,
                      season: seasonName,
                    })
                  }
                >
                  이미지 공유
                </Btn>
              </View>
              {editable ? (
                <Txt v="xs" tone="muted">
                  선수 카드를 길게 눌러 옮겨요.
                </Txt>
              ) : null}
            </Card>
            <TeamLineup
              formation={formation}
              layout={positions}
              slots={slots}
              cells={cells}
              players={players}
              editable={editable}
              nameOf={nameOf}
              selected={selected}
              select={setSelected}
              dragging={setDragging}
              jumpRef={jump}
              change={(nextSlots, nextLayout) => {
                setSlots(nextSlots);
                setLayout(nextLayout);
              }}
            />
          </>
        ) : null}
      </>
    );
  } else if (view === 'opponents') {
    body = (
      <>
        <OppSwitch value={oppTab} onPick={pickOppTab} />
        {oppTab === 'friends' ? (
          <TeamFriends
            friends={friends}
            onPlayed={(m) => showFriendly(m, true)}
            onOpen={(m) => showFriendly(m, false)}
          />
        ) : (
          <TeamOpponents
            ovr={team?.ovr ?? ovr}
            matchesLeft={matchesLeft}
            perDay={perDay}
            opponents={opponents}
            status={oppStatus}
            playing={playing}
            reload={() => void loadOpponents()}
            challenge={(o) => void challenge(o)}
            hint={matchHint}
            toTeam={editable ? () => switchView('team') : undefined}
            saveAndFind={editable && dirty && team ? () => void saveAndFind() : undefined}
            saving={saving}
            canSave={nameOk}
          />
        )}
      </>
    );
  } else if (view === 'result' && result) {
    body = live ? (
      <TeamLive
        key={result.id}
        match={result}
        name={eventName}
        onend={() => {
          setLive(false);
          scrollTo(0);
        }}
      />
    ) : (
      <TeamResult
        m={result}
        team={team}
        eventName={eventName}
        matchesLeft={matchesLeft}
        toTeam={() => show(resultOrigin === 'history' ? 'history' : 'team')}
        backLabel={resultOrigin === 'history' ? '기록으로 돌아가기' : '편성으로'}
        replay={() => setLive(true)}
        again={() => {
          if (result.friendly) {
            setOppTab('friends');
            show('opponents');
            scrollTo(0);
          } else {
            setOppTab('ranked');
            open('opponents');
          }
        }}
      />
    );
  } else if (view === 'history') {
    body = (
      <TeamHistory
        history={history}
        status={histStatus}
        reload={() => void loadHistory()}
        open={(m) => {
          setResultOrigin('history');
          setResult(m);
          setLive(false);
          show('result');
        }}
      />
    );
  }

  return (
    <>
      <BarBelow.Provider value={!needLogin}>
        <View style={{ flex: 1, backgroundColor: c.bg }}>
          <Screen
            scrollEnabled={!dragging}
            footer={
              needLogin ? (
                <BackBar fallback={() => (appState.screen = 'owner')} testID="team-back" />
              ) : view === 'team' && editable && (selected || dirty) ? (
                <View
                  style={{
                    paddingHorizontal: 16,
                    paddingVertical: 8,
                    gap: 6,
                    borderTopWidth: 1,
                    borderColor: c.line,
                    backgroundColor: c.surface,
                  }}
                >
                  {selected ? (
                    <View style={{ flexDirection: 'row', alignItems: 'center', gap: 6 }}>
                      <Txt v="sm" numberOfLines={1} style={{ flex: 1 }}>
                        {players.find((p) => p.careerId === selected)
                          ? nameOf(players.find((p) => p.careerId === selected)!)
                          : '선수 선택'}
                      </Txt>
                      <Btn sm onPress={() => jump.current?.()}>
                        그라운드로
                      </Btn>
                      <Btn sm kind="ghost" onPress={() => setSelected(null)}>
                        취소
                      </Btn>
                    </View>
                  ) : null}
                  {dirty ? (
                    <Btn
                      kind="primary"
                      block
                      testID="team-save"
                      disabled={saving || !nameOk || !!pendingDraft}
                      onPress={() => void save()}
                    >
                      {saving ? '저장 중…' : team ? '편성 저장' : '팀 만들기'}
                    </Btn>
                  ) : null}
                </View>
              ) : undefined
            }
          >
            <Topbar />
            <LoadState status={status} failText="팀을 불러오지 못했어요." retry={() => void load()}>
              {body}
            </LoadState>
          </Screen>
          {needLogin ? null : <TabBar label="내 팀 메뉴" items={navItems} sub="team" />}
        </View>
      </BarBelow.Provider>
      {menu ? (
        <TeamDialog title="내 팀 설정" close={() => setMenu(false)}>
          <Btn
            testID="team-logo-edit"
            onPress={() => {
              setMenu(false);
              setEditingLogo(true);
            }}
          >
            로고 설정
          </Btn>
          <Btn
            testID="team-rename"
            onPress={() => {
              setMenu(false);
              setRenaming(true);
              scrollTo(0);
            }}
          >
            이름 바꾸기
          </Btn>
        </TeamDialog>
      ) : null}
      {editingLogo ? (
        <TeamLogoEditor
          name={name}
          logo={logo}
          apply={setLogo}
          close={() => setEditingLogo(false)}
        />
      ) : null}
      {share ? <TeamShare data={share} close={() => setShare(null)} /> : null}
    </>
  );
}
