// apps/web/src/ui/NewsBanner.svelte
<script lang="ts">
  // T-10-058: 새 공지사항·릴리즈 노트 알림(news.svelte.ts). 새 버전 배너가 떠 있으면 그쪽을 먼저 보이고,
  // 소식 화면을 보고 있을 때는 띄우지 않는다. T-10-108 이미 본 글이 고쳐져도 같은 자리에 알린다.
  import { fly } from 'svelte/transition';
  import { newsState, dismissNews } from './news.svelte.js';
  import { updateState } from './update.svelte.js';
  import { appState } from './state.svelte.js';
  import { openBoard } from './nav.js';
  import { dur } from './motion.js';
  import { shellText as L } from '@offside/app-core/i18n/ko/shell';

  const post = $derived(newsState.post);
  const headline = $derived(
    newsState.count > 1
      ? L.newsCount({ n: newsState.count })
      : newsState.edited
        ? post?.board === 'release'
          ? L.newsReleaseEdited
          : L.newsNoticeEdited
        : post?.board === 'release'
          ? L.newsReleaseNew
          : L.newsNoticeNew,
  );
  function open() {
    if (!post) return;
    const { board, id } = post;
    dismissNews();
    openBoard(board, id);
  }
</script>

{#if post && !updateState.ready && appState.screen !== 'board'}
  <aside class="update-banner news-banner" aria-label={L.newsAlert} data-news-banner={post.board} transition:fly={{ y: -16, duration: dur(200) }}>
    <span class="news-text"><b>{headline}</b><small>{post.title}</small></span>
    <button class="btn btn-accent btn-sm" data-act="news-open" onclick={open}>{L.newsView}</button>
    <button class="news-close" aria-label={L.bannerClose} data-act="news-close" onclick={dismissNews}>✕</button>
  </aside>
{/if}

// apps/mobile/src/banners/NewsBanner.tsx
// 새 공지사항·릴리즈 노트 알림(웹 NewsBanner.svelte, news.svelte.ts). 소식 화면을 보고 있을 때는 띄우지 않는다.
// 이미 본 글이 고쳐져도 같은 자리에 알린다. 다른 배너와의 순서는 useTopBanner.
import { useState } from 'react';
import { useSnapshot } from 'valtio';
import type { PostSummary } from '@offside/app-core/api/boards';
import { dismissNews } from '../game/host';
import { openBoard } from '../game/nav';
import { newsState } from '../store';
import { Btn } from '../ui';
import { BannerClose, BannerText, TopBanner } from './TopBanner';
import { useFly } from './useFly';
import { useTopBanner } from './useTopBanner';
import { shellText as L } from '@offside/app-core/i18n/ko/shell';

export function NewsBanner() {
  const news = useSnapshot(newsState);
  const { mounted, style } = useFly(useTopBanner() === 'news', 200);
  // 사라지는 동안에도 글자가 남도록 마지막 글을 붙들어 둔다.
  const [last, setLast] = useState<{
    post: PostSummary;
    count: number;
    edited: boolean;
  } | null>(null);
  if (
    news.post &&
    (!last ||
      last.post.id !== news.post.id ||
      last.count !== news.count ||
      last.edited !== news.edited)
  )
    setLast({ post: { ...news.post }, count: news.count, edited: news.edited });
  const cur = news.post ? { post: news.post, count: news.count, edited: news.edited } : last;
  if (!mounted || !cur) return null;
  const { post, count, edited } = cur;
  const headline =
    count > 1
      ? L.newsCount({ n: count })
      : edited
        ? post.board === 'release'
          ? L.newsReleaseEdited
          : L.newsNoticeEdited
        : post.board === 'release'
          ? L.newsReleaseNew
          : L.newsNoticeNew;
  const open = () => {
    const { board, id } = post;
    dismissNews();
    openBoard(board, id);
  };

  return (
    <TopBanner testID={`news-banner-${post.board}`} label={L.newsAlert} style={style}>
      <BannerText title={headline} body={post.title} bodyLines={1} />
      <Btn kind="accent" sm testID="news-open" onPress={open}>
        {L.newsView}
      </Btn>
      <BannerClose testID="news-close" onPress={dismissNews} />
    </TopBanner>
  );
}
