// apps/mobile/src/sheets/Achieve.tsx
// T-11-034 업적 달성 알림 본문(웹 sheets/Achieve.svelte) — 등급 엠블럼(올랐으면 크게, 이전 → 지금), 새 업적과 얻은 점수,
// 지금 점수·다음 등급까지.
import { View } from 'react-native';
import { useSnapshot } from 'valtio';
import type { SheetView } from '@offside/app-core/sheets';
import { sheetAchieveText as L } from '@offside/app-core/i18n/ko/sheetAchieve';
import { num as n } from '@offside/app-core/teamText';
import { useColors } from '../theme/useColors';
import { rem } from '../theme/type';
import { GradeEmblem } from '../ui/GradeEmblem';
import { Txt } from '../ui/Txt';
import { Pop } from './anim';

export function Achieve({ v }: { v: Extract<SheetView, { kind: 'achieve' }> }) {
  const s = useSnapshot(v);
  const c = useColors();
  return (
    <>
      <Txt v="eyebrow">{s.eyebrow}</Txt>
      <View
        testID="ach-sheet"
        style={{ alignItems: 'center', gap: 6, marginTop: 4, marginBottom: 10 }}
      >
        <Pop ms={500}>
          <GradeEmblem id={s.grade.id} size={s.from ? 96 : 64} />
        </Pop>
        <Txt v="h2" accessibilityRole="header" style={{ textAlign: 'center' }}>
          {s.title}
        </Txt>
        {s.from ? (
          <View
            accessible
            accessibilityLabel={L.fromTo({ from: s.from.name, to: s.grade.name })}
            style={{ flexDirection: 'row', alignItems: 'center', gap: 4 }}
          >
            <GradeEmblem id={s.from.id} size={20} />
            <Txt tone="muted" style={{ fontSize: rem(0.875) }}>
              {s.from.name}
            </Txt>
            <Txt tone="muted" style={{ fontSize: rem(0.875), marginHorizontal: 4 }}>
              →
            </Txt>
            <GradeEmblem id={s.grade.id} size={20} />
            <Txt style={{ fontSize: rem(0.875), fontWeight: '700' }}>{s.grade.name}</Txt>
          </View>
        ) : null}
      </View>
      <View style={{ gap: 6 }}>
        {s.items.map((it, i) => (
          <View
            key={i}
            style={{
              flexDirection: 'row',
              justifyContent: 'space-between',
              gap: 12,
              paddingVertical: 8,
              paddingHorizontal: 12,
              borderRadius: 10,
              backgroundColor: c.surface2,
            }}
          >
            <Txt style={{ flexShrink: 1, fontSize: rem(0.875) }}>{it.label}</Txt>
            <Txt style={{ fontSize: rem(0.875), fontWeight: '700' }}>+{n(it.gained)}</Txt>
          </View>
        ))}
        {s.more > 0 ? (
          <View
            style={{
              paddingVertical: 8,
              paddingHorizontal: 12,
              borderRadius: 10,
              backgroundColor: c.surface2,
            }}
          >
            <Txt tone="muted" style={{ fontSize: rem(0.875) }}>
              {L.more({ n: s.more })}
            </Txt>
          </View>
        ) : null}
      </View>
      <Txt tone="muted" style={{ fontSize: rem(0.8125), textAlign: 'center', marginTop: 8 }}>
        <Txt style={{ fontSize: rem(0.8125), fontWeight: '700' }}>
          {L.gainedPts({ n: n(s.gained) })}
        </Txt>
        {` · ${L.nowPts({ n: n(s.score) })}${s.next ? ` · ${s.next}` : ''}`}
      </Txt>
    </>
  );
}

// apps/web/src/ui/sheets/Achieve.svelte
<script lang="ts">
  // T-11-034 업적 달성 알림 본문 — 등급 엠블럼(올랐으면 크게, 이전 → 지금), 새 업적과 얻은 점수, 지금 점수·다음 등급까지.
  import type { SheetView } from '@offside/app-core/sheets';
  import { num as n } from '@offside/app-core/teamText';
  import GradeEmblem from '../team/GradeEmblem.svelte';
  import { sheetAchieveText as L } from '@offside/app-core/i18n/ko/sheetAchieve';

  let { v }: { v: Extract<SheetView, { kind: 'achieve' }> } = $props();
</script>

<div class="eyebrow">{v.eyebrow}</div>
<div class="ach-up" class:grade={!!v.from} data-ach-sheet>
  <span class="ach-up-emblem"><GradeEmblem id={v.grade.id} size={v.from ? 96 : 64} /></span>
  <h2>{v.title}</h2>
  {#if v.from}
    <p class="ach-up-from" aria-label={L.fromTo({ from: v.from.name, to: v.grade.name })}>
      <GradeEmblem id={v.from.id} size={20} />{v.from.name}<span aria-hidden="true">→</span><GradeEmblem id={v.grade.id} size={20} /><b>{v.grade.name}</b>
    </p>
  {/if}
</div>
<ul class="ach-up-list">
  {#each v.items as it, i (i)}
    <li><span>{it.label}</span><b class="num">+{n(it.gained)}</b></li>
  {/each}
  {#if v.more > 0}<li class="muted"><span>{L.more({ n: v.more })}</span></li>{/if}
</ul>
<p class="muted fs-sm ach-up-sum">
  <b class="num">{L.gainedPts({ n: n(v.gained) })}</b> · {L.nowPts({ n: n(v.score) })}{v.next ? ` · ${v.next}` : ''}
</p>

<style>
  .ach-up {
    display: flex;
    flex-direction: column;
    align-items: center;
    gap: 6px;
    text-align: center;
    margin: 4px 0 10px;
  }
  .ach-up h2 {
    margin: 0;
  }
  .ach-up-emblem {
    display: block;
    animation: ach-pop 0.5s cubic-bezier(0.2, 1.4, 0.4, 1) both;
  }
  .ach-up.grade .ach-up-emblem {
    filter: drop-shadow(0 6px 16px color-mix(in srgb, var(--accent) 35%, transparent));
  }
  @keyframes ach-pop {
    from {
      transform: scale(0.6);
      opacity: 0;
    }
  }
  .ach-up-from {
    display: flex;
    align-items: center;
    gap: 4px;
    margin: 0;
    font-size: 0.875rem;
    color: var(--muted);
  }
  .ach-up-from span {
    margin: 0 4px;
  }
  .ach-up-from b {
    color: var(--ink);
  }
  .ach-up-list {
    list-style: none;
    margin: 0;
    padding: 0;
    display: grid;
    gap: 6px;
  }
  .ach-up-list li {
    display: flex;
    justify-content: space-between;
    gap: 12px;
    padding: 8px 12px;
    border-radius: 10px;
    background: var(--surface-2);
    font-size: 0.875rem;
  }
  .ach-up-sum {
    margin: 8px 0 0;
    text-align: center;
  }
  @media (prefers-reduced-motion: reduce) {
    .ach-up-emblem {
      animation: none;
    }
  }
</style>
