// apps/mobile/src/sheets/Block.tsx
// 경기 중계 시트(웹 sheets/Block.svelte, T-10-028): 구간 경기가 한 경기씩 올라오며 승무패·출전 기록이 쌓인다.
// 진행·줄 추가는 sheet-controller가 뷰를 고치며 하고, 여기서는 읽어 그린다.
import { useEffect, useRef } from 'react';
import { Animated, Easing, View } from 'react-native';
import { useSnapshot } from 'valtio';
import type { SheetView } from '@offside/app-core/sheets';
import { sheetCoreText } from '@offside/app-core/i18n/ko/sheetCore';
import { prefs } from '../store';
import { useColors } from '../theme/useColors';
import { DISPLAY, fitLine, rem } from '../theme/type';
import { Txt } from '../ui/Txt';
import { Enter } from './anim';
import { ProgBar, SkipLink, StatGrid } from './parts';
import { TickerLine } from './TickerLine';

/** 값이 바뀔 때마다 커졌다 돌아오는 숫자(웹 tally b.bump: 40%에서 1.25배 + 금색). 0·'-'은 그대로. */
function Bump({ value }: { value: number | string }) {
  const c = useColors();
  const { motionOK } = useSnapshot(prefs);
  const bump = value !== 0 && value !== '-' && motionOK;
  const t = useRef(new Animated.Value(bump ? 0 : 1)).current;
  useEffect(() => {
    if (!bump) return;
    t.setValue(0);
    const a = Animated.timing(t, {
      toValue: 1,
      duration: 300,
      easing: Easing.out(Easing.ease),
      useNativeDriver: false,
    });
    a.start();
    return () => a.stop();
  }, [value, bump, t]);
  return (
    <Animated.Text
      style={[
        fitLine({
          fontFamily: DISPLAY[700],
          fontSize: rem(1.5),
          lineHeight: rem(1.5) * 1.1,
          fontVariant: ['tabular-nums'],
        }),
        {
          color: t.interpolate({ inputRange: [0, 0.4, 1], outputRange: [c.ink, c.accent, c.ink] }),
          transform: [
            { scale: t.interpolate({ inputRange: [0, 0.4, 1], outputRange: [1, 1.25, 1] }) },
          ],
        },
      ]}
    >
      {value}
    </Animated.Text>
  );
}

export function Block({ v }: { v: Extract<SheetView, { kind: 'block' }> }) {
  const s = useSnapshot(v);
  const c = useColors();
  const tally = [
    { key: 'apps', k: s.tally.apps, l: sheetCoreText.tallyApps },
    { key: 'g', k: s.tally.g, l: sheetCoreText.tallyGoals },
    {
      key: 'a',
      k: s.back ? s.tally.cs : s.tally.a,
      l: s.back ? sheetCoreText.tallyCleanSheets : sheetCoreText.tallyAssists,
    },
    { key: 'rating', k: s.tally.rating, l: sheetCoreText.tallyRating },
  ];
  return (
    <>
      <Txt v="eyebrow">{s.eyebrow}</Txt>
      <Txt v="h2" accessibilityRole="header">
        {s.title}
      </Txt>
      <ProgBar progress={s.progress} fill={s.fill} />
      <View style={{ flexDirection: 'row', justifyContent: 'space-between', marginTop: -6 }}>
        <Txt tone="muted" style={{ fontSize: rem(0.75), fontVariant: ['tabular-nums'] }}>
          {s.round}
        </Txt>
        <Txt
          tone="muted"
          testID="block-wdl"
          style={{ fontSize: rem(0.75), fontVariant: ['tabular-nums'] }}
        >
          {sheetCoreText.wdl(s.wdl)}
        </Txt>
      </View>
      <StatGrid items={tally.map((t) => ({ key: t.key, l: t.l, v: <Bump value={t.k} /> }))} />
      {/* 새 경기 줄이 위에 붙고, 지난 줄은 muted로 누른다. */}
      <View style={{ minHeight: 124, gap: 4 }}>
        {s.ticker.map((m, i) => (
          <Enter key={m.key} kind="translateY" from={-6} ms={250}>
            <TickerLine m={m} muted={i > 0} bold={i === 0} />
          </Enter>
        ))}
      </View>
      <View style={{ gap: 6 }}>
        {s.extras.map((x, i) => (
          <Txt
            key={i}
            tone={x.done ? 'muted' : 'ink'}
            style={{ fontSize: rem(0.875), lineHeight: rem(0.875) * 1.55 }}
          >
            {x.done ? (
              <Txt style={{ color: c.good }}>{'✓ '}</Txt>
            ) : (
              <Txt style={{ color: c.accent }}>{'▸ '}</Txt>
            )}
            {x.text}
          </Txt>
        ))}
      </View>
      {s.skip ? <SkipLink onPress={() => v.skip?.()} /> : null}
    </>
  );
}

// apps/web/src/ui/sheets/Block.svelte
<script lang="ts">
  // T-10-028 경기 중계 시트 — 구간 경기가 한 경기씩 올라오며 승무패·출전 기록이 쌓인다.
  import TickerLine from './TickerLine.svelte';
  import type { SheetView } from '@offside/app-core/sheets';
  import { sheetCoreText } from '@offside/app-core/i18n/ko/sheetCore';
  let { v }: { v: Extract<SheetView, { kind: 'block' }> } = $props();
  const tally = $derived([
    { k: v.tally.apps, l: sheetCoreText.tallyApps },
    { k: v.tally.g, l: sheetCoreText.tallyGoals },
    { k: v.back ? v.tally.cs : v.tally.a, l: v.back ? sheetCoreText.tallyCleanSheets : sheetCoreText.tallyAssists },
    { k: v.tally.rating, l: sheetCoreText.tallyRating },
  ]);
</script>

<div class="eyebrow">{v.eyebrow}</div>
<h2>{v.title}</h2>
<div class="prog"><i style:width="{v.progress * 100}%" style:transition-duration="{v.fill}ms"></i></div>
<div class="prog-meta"><span>{v.round}</span><span data-block-wdl>{sheetCoreText.wdl(v.wdl)}</span></div>
<div class="tally">
  {#each tally as t (t.l)}
    <!-- 값이 바뀔 때마다 {#key}로 <b>를 새로 그려 bump 애니메이션을 다시 건다. -->
    <div>{#key t.k}<b class:bump={t.k !== 0 && t.k !== '-'}>{t.k}</b>{/key}<span>{t.l}</span></div>
  {/each}
</div>
<div class="ticker live">
  {#each v.ticker as m (m.key)}
    <TickerLine {m} />
  {/each}
</div>
<div class="steps">
  {#each v.extras as x, i (i)}
    <div class:on={!x.done} class:done={x.done}>{x.text}</div>
  {/each}
</div>
{#if v.skip}
  <button class="link-btn skip" id="an-skip" onclick={v.skip}>{sheetCoreText.skip}</button>
{/if}
