// apps/mobile/src/sheets/Contract.tsx
// 계약서 사인 시트(웹 sheets/Contract.svelte, T-11-039): 이적시장에서 고른 구단과의 계약. 손가락으로 사인하거나
// '이름 사인 사용'으로 선수 이름을 흘려 쓴 사인을 넣으면 확정 버튼이 켜진다. 누르면 도장이 찍히고 onSign. 사인은 화면
// 연출이라 저장하지 않는다.
// 웹은 canvas에 그렸지만 앱은 획마다 점을 모아 react-native-svg Path로 그린다. 터치는 패드 위에 덮은 투명 View 하나가
// PanResponder로 잡는다(DragShot과 같다 — 터치 대상이 늘 그 View라 locationX/Y가 패드 기준으로 일정하고, 바깥 스크롤이
// 제스처를 가져가지 못한다).
import { useCallback, useEffect, useId, useMemo, useRef, useState } from 'react';
import { Easing, PanResponder, StyleSheet, View, type GestureResponderEvent } from 'react-native';
import Svg, { ClipPath, Defs, G, Path, Rect, Text as SvgText } from 'react-native-svg';
import { useSnapshot } from 'valtio';
import type { SheetView } from '@offside/app-core/sheets';
import { prefs } from '../store';
import { useColors } from '../theme/useColors';
import { DISPLAY, rem } from '../theme/type';
import { Btn } from '../ui/Btn';
import { ClubBadge } from '../ui/ClubBadge';
import { Press } from '../ui/Press';
import { Txt } from '../ui/Txt';
import { Enter } from './anim';

/** 이만큼(px) 그어야 사인으로 친다 — 점 하나 찍고 넘어가지 않게. */
const MIN_INK = 40;
const STAMP_MS = 650;
const REVEAL_MS = 600;
/** 웹 stamp 키프레임의 cubic-bezier(0.2, 1.6, 0.4, 1). */
const STAMP_EASE = Easing.bezier(0.2, 1.6, 0.4, 1);

interface Pt {
  x: number;
  y: number;
}

/** 점들을 이어 부드러운 곡선 path로 — 웹처럼 두 점의 가운데를 끝점으로, 앞 점을 제어점으로 하는 2차 곡선. */
function strokePath(pts: Pt[]): string {
  const f = pts[0];
  if (!f) return '';
  if (pts.length === 1) return `M${f.x},${f.y}l0.01,0`;
  let d = `M${f.x},${f.y}`;
  for (let i = 1; i < pts.length; i++) {
    const a = pts[i - 1]!,
      b = pts[i]!;
    d += `Q${a.x},${a.y} ${(a.x + b.x) / 2},${(a.y + b.y) / 2}`;
  }
  const l = pts[pts.length - 1]!;
  return `${d}L${l.x},${l.y}`;
}

/** 굵은 이탤릭 글자 폭 어림(RN엔 measureText가 없다) — 한글·한자는 글자 크기만큼, 그 밖은 0.58배. */
function textWidth(text: string, size: number): number {
  let w = 0;
  for (const ch of text) w += ch === ' ' ? 0.3 : ch.charCodeAt(0) >= 0x2e80 ? 1 : 0.58;
  return w * size;
}

export function Contract({ v }: { v: Extract<SheetView, { kind: 'contract' }> }) {
  const s = useSnapshot(v);
  const c = useColors();
  const { motionOK } = useSnapshot(prefs);
  const clip = useId();

  const [done, setDone] = useState<string[]>([]);
  const [cur, setCur] = useState('');
  const [ink, setInk] = useState(0);
  const [named, setNamed] = useState(false);
  const [reveal, setReveal] = useState(1);
  const [sealed, setSealed] = useState(false);
  const [size, setSize] = useState({ w: 0, h: 150 });
  const ready = named || ink >= MIN_INK;

  // 터치 핸들러는 한 번만 만들어 쓰므로 최신 값은 ref로 읽는다.
  const pts = useRef<Pt[]>([]);
  const sealedRef = useRef(false);
  const namedRef = useRef(false);
  const raf = useRef(0);
  const motionRef = useRef(motionOK);
  useEffect(() => {
    motionRef.current = motionOK;
  }, [motionOK]);
  useEffect(() => () => cancelAnimationFrame(raf.current), []);

  const clear = useCallback(() => {
    cancelAnimationFrame(raf.current);
    pts.current = [];
    namedRef.current = false;
    setDone([]);
    setCur('');
    setInk(0);
    setNamed(false);
    setReveal(1);
  }, []);

  const pan = useMemo(() => {
    const at = (e: GestureResponderEvent): Pt => ({
      x: Math.round(e.nativeEvent.locationX * 10) / 10,
      y: Math.round(e.nativeEvent.locationY * 10) / 10,
    });
    const end = () => {
      const p = pts.current;
      if (!p.length) return;
      const d = strokePath(p);
      pts.current = [];
      setDone((a) => [...a, d]);
      setCur('');
    };
    return PanResponder.create({
      onStartShouldSetPanResponder: () => !sealedRef.current,
      // 그리는 동안 바깥 스크롤(시트)이 터치를 가져가지 않게 한다.
      onPanResponderTerminationRequest: () => false,
      onPanResponderGrant: (e) => {
        if (namedRef.current) clear();
        pts.current = [at(e)];
        setCur(strokePath(pts.current));
      },
      onPanResponderMove: (e) => {
        const p = at(e);
        const last = pts.current[pts.current.length - 1];
        if (!last) return;
        const d = Math.hypot(p.x - last.x, p.y - last.y);
        if (d < 1) return;
        pts.current.push(p);
        setInk((n) => n + d);
        setCur(strokePath(pts.current));
      },
      onPanResponderRelease: end,
      onPanResponderTerminate: end,
    });
  }, [clear]);

  const { w: W, h: H } = size;
  // 이름 사인 글자 크기: 높이의 42%에서 시작해 폭 70%를 넘으면 줄인다.
  const sign = useMemo(() => {
    let fs = H * 0.42;
    const tw = textWidth(s.name, fs);
    if (tw > W * 0.7) fs *= (W * 0.7) / tw;
    const half = Math.min(W * 0.42, textWidth(s.name, fs) / 2 + fs * 0.9);
    const flourish =
      `M${-half},${fs * 0.32}` +
      `C${-half * 0.3},${fs * 0.12} ${half * 0.4},${fs * 0.5} ${half},${fs * 0.05}` +
      `Q${half * 0.8},${fs * 0.6} ${half * 0.55},${fs * 0.3}`;
    return { fs, flourish };
  }, [s.name, W, H]);

  /** 선수 이름을 기울여 흘려 쓰고 밑줄 꼬리를 붙인다. 동작 줄이기가 아니면 왼쪽부터 써 나간다. */
  function nameSign() {
    if (sealedRef.current || W === 0) return;
    clear();
    namedRef.current = true;
    setNamed(true);
    if (!motionRef.current) return;
    setReveal(0);
    const t0 = performance.now();
    const step = () => {
      const t = Math.min(1, (performance.now() - t0) / REVEAL_MS);
      setReveal(1 - Math.pow(1 - t, 2));
      if (t < 1) raf.current = requestAnimationFrame(step);
    };
    raf.current = requestAnimationFrame(step);
  }

  function seal() {
    if (!ready || sealedRef.current) return;
    sealedRef.current = true;
    cancelAnimationFrame(raf.current);
    setReveal(1);
    setSealed(true);
    setTimeout(() => v.onSign(), motionRef.current ? STAMP_MS : 0);
  }

  return (
    <View style={{ gap: 12 }}>
      <Txt v="eyebrow">{s.eyebrow}</Txt>
      <Txt v="h2" accessibilityRole="header" style={{ paddingRight: 40 }}>
        {s.title}
      </Txt>
      {/* 제목 줄 오른쪽 위 × — 이적시장으로 돌아간다. */}
      <Press
        testID="sign-close"
        accessibilityLabel="계약서 닫기"
        disabled={sealed}
        onPress={() => v.onClose()}
        style={{
          position: 'absolute',
          top: -6,
          right: -4,
          width: 40,
          height: 40,
          borderRadius: 20,
          backgroundColor: c.surface2,
          alignItems: 'center',
          justifyContent: 'center',
          opacity: sealed ? 0.45 : 1,
        }}
      >
        <Txt tone="muted" style={{ fontSize: rem(1.375), lineHeight: rem(1.375) }}>
          ×
        </Txt>
      </Press>
      <Txt tone="muted" style={{ marginTop: -4, fontSize: rem(0.9375) }}>
        {s.text}
      </Txt>
      <View
        style={{
          flexDirection: 'row',
          alignItems: 'center',
          gap: 12,
          paddingVertical: 10,
          paddingHorizontal: 12,
          borderRadius: 12,
          backgroundColor: c.surface2,
        }}
      >
        <ClubBadge club={s.club} size={34} />
        <View style={{ flex: 1, flexDirection: 'row', flexWrap: 'wrap', rowGap: 4, columnGap: 16 }}>
          {s.terms.map((t) => (
            <View key={t.label}>
              <Txt tone="muted" style={{ fontSize: rem(0.6875), lineHeight: rem(0.6875) * 1.4 }}>
                {t.label}
              </Txt>
              <Txt bold style={{ fontSize: rem(0.875), lineHeight: rem(0.875) * 1.4 }}>
                {t.value}
              </Txt>
            </View>
          ))}
        </View>
      </View>
      <View
        accessibilityLabel="선수 사인 입력 영역"
        onLayout={(e) => {
          const { width, height } = e.nativeEvent.layout;
          // 폭이 바뀌면(회전 등) 그린 사인이 어긋나므로 처음부터 다시 받는다(웹 ResizeObserver).
          if (size.w && Math.round(size.w) !== Math.round(width)) clear();
          setSize({ w: width, h: height });
        }}
        style={{
          height: 150,
          borderWidth: 1.5,
          borderStyle: 'dashed',
          borderColor: c.line,
          borderRadius: 14,
          backgroundColor: c.surface,
          overflow: 'hidden',
        }}
      >
        <Svg width="100%" height="100%" pointerEvents="none">
          {done.map((d, i) => (
            <Path
              key={i}
              d={d}
              fill="none"
              stroke={c.ink}
              strokeWidth={2.6}
              strokeLinecap="round"
              strokeLinejoin="round"
            />
          ))}
          {cur ? (
            <Path
              d={cur}
              fill="none"
              stroke={c.ink}
              strokeWidth={2.6}
              strokeLinecap="round"
              strokeLinejoin="round"
            />
          ) : null}
          {named && W > 0 ? (
            <>
              <Defs>
                <ClipPath id={clip}>
                  <Rect x={0} y={0} width={W * reveal} height={H} />
                </ClipPath>
              </Defs>
              <G clipPath={`url(#${clip})`}>
                <G transform={`translate(${W / 2} ${H * 0.56}) matrix(1 -0.06 -0.28 1 0 0)`}>
                  <SvgText
                    x={0}
                    y={0}
                    textAnchor="middle"
                    fontSize={sign.fs}
                    fontWeight="500"
                    fontStyle="italic"
                    fill={c.ink}
                  >
                    {s.name}
                  </SvgText>
                  <Path
                    d={sign.flourish}
                    fill="none"
                    stroke={c.ink}
                    strokeWidth={2.2}
                    strokeLinecap="round"
                  />
                </G>
              </G>
            </>
          ) : null}
        </Svg>
        {ink > 0 || named ? null : (
          <View
            pointerEvents="none"
            style={[StyleSheet.absoluteFill, { alignItems: 'center', justifyContent: 'center' }]}
          >
            <Txt tone="muted" style={{ fontSize: rem(0.9375) }}>
              이곳에 사인해 주세요
            </Txt>
          </View>
        )}
        {/* 서명란 밑줄과 × 표시(종이 계약서처럼). */}
        <View
          pointerEvents="none"
          style={{
            position: 'absolute',
            left: 18,
            right: 18,
            bottom: 30,
            borderBottomWidth: 1,
            borderBottomColor: c.line,
          }}
        >
          <Txt
            tone="muted"
            style={{
              position: 'absolute',
              left: 0,
              bottom: 2,
              fontSize: rem(0.875),
              lineHeight: rem(0.875),
            }}
          >
            ×
          </Txt>
        </View>
        {sealed ? (
          <View
            pointerEvents="none"
            style={{ position: 'absolute', right: 14, top: 12, transform: [{ rotate: '-14deg' }] }}
          >
            <Enter kind="scale" from={1.8} ms={280} ease={STAMP_EASE}>
              <Stamp name={s.club.name} />
            </Enter>
          </View>
        ) : null}
        <View style={StyleSheet.absoluteFill} {...pan.panHandlers} />
      </View>
      <Txt
        tone="muted"
        center
        style={{ marginTop: -6, fontSize: rem(0.75), lineHeight: rem(0.75) * 1.5 }}
      >
        게임 속 선수의 가상 사인입니다
      </Txt>
      <View style={{ flexDirection: 'row', gap: 8 }}>
        <Btn sm testID="sign-clear" disabled={sealed} onPress={clear} style={{ flex: 1 }}>
          다시 쓰기
        </Btn>
        <Btn sm testID="sign-name" disabled={sealed} onPress={nameSign} style={{ flex: 1 }}>
          이름 사인 사용
        </Btn>
      </View>
      <Btn kind="primary" block testID="sign-ok" disabled={!ready || sealed} onPress={seal}>
        {`${s.cta} →`}
      </Btn>
    </View>
  );
}

/** 'SIGNED' 도장 — 웹 .stamp의 이중 테두리 원(double border)을 안팎 두 겹 원으로 그린다. */
function Stamp({ name }: { name: string }) {
  const c = useColors();
  return (
    <View
      style={{
        width: 86,
        height: 86,
        borderRadius: 43,
        borderWidth: 1.5,
        borderColor: c.bad,
        alignItems: 'center',
        justifyContent: 'center',
      }}
    >
      <View
        style={{
          width: 78,
          height: 78,
          borderRadius: 39,
          borderWidth: 1.5,
          borderColor: c.bad,
          alignItems: 'center',
          justifyContent: 'center',
        }}
      >
        <Txt
          style={{
            fontFamily: DISPLAY[700],
            fontSize: rem(1.25),
            lineHeight: rem(1.25),
            letterSpacing: rem(1.25) * 0.06,
            color: c.bad,
          }}
        >
          SIGNED
        </Txt>
        <Txt
          numberOfLines={1}
          style={{
            maxWidth: 62,
            marginTop: 3,
            fontSize: rem(0.5625),
            lineHeight: rem(0.5625) * 1.3,
            fontWeight: '700',
            color: c.bad,
          }}
        >
          {name}
        </Txt>
      </View>
    </View>
  );
}

// apps/web/src/ui/sheets/Contract.svelte
<script lang="ts">
  // T-11-039 계약서 사인 — 이적시장에서 고른 구단과의 계약. 손가락·마우스로 사인하거나 '이름 사인 사용'으로 선수 이름을
  // 흘려 쓴 사인을 넣으면 확정 버튼이 켜진다. 누르면 도장이 찍히고 onSign. 사인은 화면 연출이라 저장하지 않는다.
  import { onMount } from 'svelte';
  import ClubBadge from '../ClubBadge.svelte';
  import { motionOK } from '../motion.js';
  import type { SheetView } from '@offside/app-core/sheets';

  let { v }: { v: Extract<SheetView, { kind: 'contract' }> } = $props();

  /** 이만큼(px) 그어야 사인으로 친다 — 점 하나 찍고 넘어가지 않게. */
  const MIN_INK = 40;
  const STAMP_MS = 650;

  let canvas = $state<HTMLCanvasElement | null>(null);
  let ink = $state(0);
  let named = $state(false);
  let sealed = $state(false);
  const ready = $derived(named || ink >= MIN_INK);

  let ctx: CanvasRenderingContext2D | null = null;
  let dpr = 1;
  let raf = 0;
  let last: { x: number; y: number; t: number; w: number } | null = null;
  let mid: { x: number; y: number } | null = null;

  const inkColor = () => getComputedStyle(canvas!).color;

  function fit() {
    if (!canvas) return;
    dpr = Math.min(3, devicePixelRatio || 1);
    canvas.width = Math.round(canvas.clientWidth * dpr);
    canvas.height = Math.round(canvas.clientHeight * dpr);
    ctx = canvas.getContext('2d');
    ctx?.setTransform(dpr, 0, 0, dpr, 0, 0);
  }
  onMount(() => {
    fit();
    // 폭이 바뀌면(회전 등) 캔버스를 다시 맞춘다 — 그린 사인은 지워지므로 처음부터 다시 받는다.
    const ro = new ResizeObserver(() => {
      if (canvas && Math.round(canvas.clientWidth * dpr) !== canvas.width) clear();
    });
    if (canvas) ro.observe(canvas);
    return () => {
      ro.disconnect();
      cancelAnimationFrame(raf);
    };
  });

  function clear() {
    cancelAnimationFrame(raf);
    fit();
    ink = 0;
    named = false;
    last = mid = null;
  }

  const at = (e: PointerEvent) => {
    const r = canvas!.getBoundingClientRect();
    return { x: e.clientX - r.left, y: e.clientY - r.top, t: e.timeStamp };
  };
  function down(e: PointerEvent) {
    if (sealed || !ctx) return;
    if (named) clear();
    canvas!.setPointerCapture(e.pointerId);
    const p = at(e);
    last = { ...p, w: 2.6 };
    mid = p;
    ctx.fillStyle = inkColor();
    ctx.beginPath();
    ctx.arc(p.x, p.y, 1.3, 0, Math.PI * 2);
    ctx.fill();
  }
  // 빠르게 그을수록 가늘어지는 펜 — 두 점의 가운데를 이어 부드러운 곡선으로 그린다.
  function move(e: PointerEvent) {
    if (!last || !ctx || !mid) return;
    for (const ev of e.getCoalescedEvents?.() ?? [e]) {
      const p = at(ev);
      const d = Math.hypot(p.x - last.x, p.y - last.y);
      if (d < 1) continue;
      const speed = d / Math.max(1, p.t - last.t);
      const w: number = last.w * 0.7 + Math.min(3.4, Math.max(1.2, 3.6 - speed * 1.1)) * 0.3;
      const m = { x: (last.x + p.x) / 2, y: (last.y + p.y) / 2 };
      ctx.strokeStyle = inkColor();
      ctx.lineWidth = w;
      ctx.lineCap = ctx.lineJoin = 'round';
      ctx.beginPath();
      ctx.moveTo(mid.x, mid.y);
      ctx.quadraticCurveTo(last.x, last.y, m.x, m.y);
      ctx.stroke();
      ink += d;
      last = { ...p, w };
      mid = m;
    }
  }
  const up = () => (last = mid = null);

  /** 선수 이름을 기울여 흘려 쓰고 밑줄 꼬리를 붙인다. 감속 모션이 아니면 왼쪽부터 써 나간다. */
  function nameSign() {
    if (sealed || !canvas) return;
    clear();
    const c = ctx!;
    const W = canvas.clientWidth,
      H = canvas.clientHeight;
    const font = getComputedStyle(canvas).fontFamily;
    let size = H * 0.42;
    c.font = `italic 500 ${size}px ${font}`;
    const tw = c.measureText(v.name).width;
    if (tw > W * 0.7) size *= (W * 0.7) / tw;
    const draw = (reveal: number) => {
      c.save();
      c.setTransform(dpr, 0, 0, dpr, 0, 0);
      c.clearRect(0, 0, W, H);
      c.beginPath();
      c.rect(0, 0, W * reveal, H);
      c.clip();
      c.fillStyle = c.strokeStyle = inkColor();
      c.translate(W / 2, H * 0.56);
      c.transform(1, -0.06, -0.28, 1, 0, 0);
      c.font = `italic 500 ${size}px ${font}`;
      c.textAlign = 'center';
      c.textBaseline = 'alphabetic';
      c.fillText(v.name, 0, 0);
      const half = Math.min(W * 0.42, c.measureText(v.name).width / 2 + size * 0.9);
      c.lineWidth = 2.2;
      c.lineCap = 'round';
      c.beginPath();
      c.moveTo(-half, size * 0.32);
      c.bezierCurveTo(-half * 0.3, size * 0.12, half * 0.4, size * 0.5, half, size * 0.05);
      c.quadraticCurveTo(half * 0.8, size * 0.6, half * 0.55, size * 0.3);
      c.stroke();
      c.restore();
    };
    named = true;
    if (!motionOK) return draw(1);
    const t0 = performance.now();
    const step = (now: number) => {
      const t = Math.min(1, (now - t0) / 600);
      draw(1 - Math.pow(1 - t, 2));
      if (t < 1) raf = requestAnimationFrame(step);
    };
    raf = requestAnimationFrame(step);
  }

  function sign() {
    if (!ready || sealed) return;
    sealed = true;
    setTimeout(v.onSign, motionOK ? STAMP_MS : 0);
  }
</script>

<div class="contract">
  <button class="contract-x" aria-label="계약서 닫기" data-sign="close" disabled={sealed} onclick={v.onClose}>×</button>
  <div class="eyebrow">{v.eyebrow}</div>
  <h2>{v.title}</h2>
  <p class="contract-text">{v.text}</p>
  <div class="contract-club">
    <ClubBadge club={v.club} size={34} />
    <dl>
      {#each v.terms as t (t.label)}
        <div><dt>{t.label}</dt><dd>{t.value}</dd></div>
      {/each}
    </dl>
  </div>
  <div class="sign-pad" class:inked={ink > 0 || named}>
    <canvas
      bind:this={canvas}
      aria-label="선수 사인 입력 영역"
      onpointerdown={down}
      onpointermove={move}
      onpointerup={up}
      onpointercancel={up}
      ontouchstart={(e) => e.stopPropagation()}
    ></canvas>
    <span class="sign-hint" aria-hidden="true">이곳에 사인해 주세요</span>
    <i aria-hidden="true"></i>
    {#if sealed}
      <div class="stamp" aria-hidden="true"><b>SIGNED</b><span>{v.club.name}</span></div>
    {/if}
  </div>
  <p class="sign-note">게임 속 선수의 가상 사인입니다</p>
  <div class="sign-tools">
    <button class="btn btn-sm" data-sign="clear" disabled={sealed} onclick={clear}>다시 쓰기</button>
    <button class="btn btn-sm" data-sign="name" disabled={sealed} onclick={nameSign}>이름 사인 사용</button>
  </div>
  <button class="btn btn-primary btn-block" data-sign="ok" disabled={!ready || sealed} onclick={sign}>
    {v.cta} <span aria-hidden="true">→</span>
  </button>
</div>

<style>
  .contract {
    position: relative;
    display: flex;
    flex-direction: column;
    gap: 12px;
  }
  .contract h2 {
    padding-right: 40px;
    word-break: keep-all;
  }
  .contract-x {
    position: absolute;
    top: -6px;
    right: -4px;
    width: 40px;
    height: 40px;
    border-radius: 999px;
    border: 0;
    background: var(--surface-2);
    color: var(--muted);
    font-size: 1.375rem;
    line-height: 1;
  }
  .contract-text {
    margin: -4px 0 0;
    color: var(--muted);
    font-size: 0.9375rem;
  }
  .contract-club {
    display: flex;
    align-items: center;
    gap: 12px;
    padding: 10px 12px;
    border-radius: 12px;
    background: var(--surface-2);
  }
  .contract-club dl {
    flex: 1;
    display: flex;
    flex-wrap: wrap;
    gap: 4px 16px;
    margin: 0;
  }
  .contract-club dt {
    font-size: 0.6875rem;
    color: var(--muted);
  }
  .contract-club dd {
    margin: 0;
    font-size: 0.875rem;
    font-weight: 700;
  }
  .sign-pad {
    position: relative;
    height: 150px;
    border: 1.5px dashed var(--line);
    border-radius: 14px;
    background: var(--surface);
    overflow: hidden;
  }
  .sign-pad canvas {
    position: absolute;
    inset: 0;
    width: 100%;
    height: 100%;
    touch-action: none;
    cursor: crosshair;
    color: var(--ink);
    font-family: var(--body);
  }
  .sign-hint {
    position: absolute;
    inset: 0;
    display: grid;
    place-items: center;
    color: var(--muted);
    font-size: 0.9375rem;
    pointer-events: none;
  }
  .sign-pad.inked .sign-hint {
    display: none;
  }
  /* 서명란 밑줄과 × 표시(종이 계약서처럼). */
  .sign-pad i {
    position: absolute;
    left: 18px;
    right: 18px;
    bottom: 30px;
    border-bottom: 1px solid var(--line);
    pointer-events: none;
  }
  .sign-pad i::before {
    content: '×';
    position: absolute;
    left: 0;
    bottom: 2px;
    color: var(--muted);
    font-size: 0.875rem;
    font-style: normal;
  }
  .stamp {
    position: absolute;
    right: 14px;
    top: 12px;
    display: grid;
    place-items: center;
    width: 86px;
    height: 86px;
    border-radius: 50%;
    border: 3px double var(--bad);
    color: var(--bad);
    transform: rotate(-14deg);
    text-align: center;
    pointer-events: none;
    animation: stamp 0.28s cubic-bezier(0.2, 1.6, 0.4, 1) both;
  }
  .stamp b {
    font-family: var(--display);
    font-size: 1.25rem;
    letter-spacing: 0.06em;
    line-height: 1;
    align-self: end;
  }
  .stamp span {
    align-self: start;
    max-width: 70px;
    font-size: 0.5625rem;
    font-weight: 700;
    overflow: hidden;
    white-space: nowrap;
    text-overflow: ellipsis;
  }
  @keyframes stamp {
    from {
      transform: rotate(-14deg) scale(1.8);
    }
  }
  @media (prefers-reduced-motion: reduce) {
    .stamp {
      animation: none;
    }
  }
  .sign-note {
    margin: -6px 0 0;
    text-align: center;
    font-size: 0.75rem;
    color: var(--muted);
  }
  .sign-tools {
    display: grid;
    grid-template-columns: 1fr 1fr;
    gap: 8px;
  }
</style>
