// apps/mobile/src/sheets/Notice.tsx
// 안내 시트 본문(웹 sheets/Notice.svelte): 눈썹 · 제목 · 큰 결과 · 단계 목록 · 문단 · 확인 칸.
import { useState } from 'react';
import { Switch, View } from 'react-native';
import { useSnapshot } from 'valtio';
import type { SheetView } from '@offside/app-core/sheets';
import { useColors } from '../theme/useColors';
import { DISPLAY, rem } from '../theme/type';
import { Txt } from '../ui/Txt';

export function Notice({ v }: { v: Extract<SheetView, { kind: 'notice' }> }) {
  const s = useSnapshot(v);
  const c = useColors();
  const [checked, setChecked] = useState(false);
  return (
    <>
      <Txt v="eyebrow">{s.eyebrow}</Txt>
      {s.title ? (
        <Txt v="h2" accessibilityRole="header">
          {s.title}
        </Txt>
      ) : null}
      {s.big ? (
        <Txt
          style={{
            fontFamily: DISPLAY[700],
            fontSize: rem(2.5),
            lineHeight: rem(2.5),
            color: s.big.ok ? c.good : c.bad,
          }}
        >
          {s.big.text}
        </Txt>
      ) : null}
      {s.steps ? (
        <View style={{ gap: 4 }}>
          {s.steps.map((t, i) => (
            <Txt key={i}>{`${i + 1}. ${t}`}</Txt>
          ))}
        </View>
      ) : null}
      {s.text ? <Txt tone={s.muted ? 'muted' : 'ink'}>{s.text}</Txt> : null}
      {s.check ? (
        <View style={{ flexDirection: 'row', alignItems: 'center', gap: 10 }}>
          <Switch
            value={checked}
            onValueChange={(on) => {
              setChecked(on);
              v.check?.onChange(on);
            }}
            accessibilityLabel={s.check.label}
          />
          <Txt style={{ flex: 1 }}>{s.check.label}</Txt>
        </View>
      ) : null}
    </>
  );
}

// apps/web/src/ui/sheets/Notice.svelte
<script lang="ts">
  import type { SheetView } from '@offside/app-core/sheets';
  let { v }: { v: Extract<SheetView, { kind: 'notice' }> } = $props();
</script>

<div class="eyebrow">{v.eyebrow}</div>
{#if v.title}<h2>{v.title}</h2>{/if}
{#if v.big}<div class="result-big {v.big.ok ? 'ok' : 'ng'}">{v.big.text}</div>{/if}
{#if v.steps}<ol class="notice-steps">{#each v.steps as s, i (i)}<li>{s}</li>{/each}</ol>{/if}
{#if v.text}<p class:muted={v.muted}>{v.text}</p>{/if}
{#if v.check}
  {@const check = v.check}
  <label class="notice-check"><input type="checkbox" data-sheet-check onchange={(e) => check.onChange(e.currentTarget.checked)} /> {check.label}</label>
{/if}
