// apps/web/src/ui/tabs/SeasonTab.svelte
<script lang="ts" module>
  /** 마지막으로 안내 스크롤을 돈 리포트 — 탭을 오가며 다시 마운트돼도 같은 리포트로 또 돌지 않는다. */
  let touredKey = 0;
</script>

<script lang="ts">
  // ui.ts seasonTab()/compsCard()/storiesCard()/meter() 포트 (224~259줄, 340~345줄, 671~684줄)
  // T-11-024 순서: 방금 끝난 구간 리포트 → 다음 구간 준비(컨디션·훈련·자기 투자) → 시즌 현황(진행 막대·누적 기록·
  // 순위표·대회) → 스토리 → 최근 소식 → 버튼. 버튼은 고정 바 없이 탭 맨 아래 한 자리에 둔다 — 이벤트·시즌 결산이 대기 중이면
  // 그걸 열고, 아니면 구간을 진행한다. 결과와 훈련 선택을 지나야 누를 수 있다. 리포트와 겹치는 숫자·소식은 다시 그리지 않는다.
  import { PHASES, LAST_PHASE } from '@offside/game/data';
  import { roundRange, leagueOf, blockMatches, TRAININGS, trainingLabel, trainingCard, trainingHelp, INVESTS, investCard, investHelp, investDef, fmtMoney, STORIES, turnNo } from '@offside/game/engine';
  import { eventById } from '@offside/game/events-data';
  import type { GameState } from '@offside/game/types';
  import { save } from '../helpers.js';
  import { seasonLabel } from '@offside/app-core/career';
  import { appState } from '../state.svelte.js';
  import { advance, nextPending } from '../actions.js';
  import { buzz, dur } from '../motion.js';
  import PhaseReport from './PhaseReport.svelte';
  import LeagueTable from './LeagueTable.svelte';

  const { s }: { s: GameState } = $props();

  const S = $derived(s.season);
  const avg = $derived(S.apps ? (S.ratingSum / S.apps).toFixed(2) : '-');
  const phase = $derived(Math.min(s.phase, LAST_PHASE));
  const label = $derived(phase === 0 ? '프리시즌' : `${PHASES[phase]} · ${roundRange(s, phase)}`);
  const lastCol = $derived((s.pos === 'GK' || s.pos === 'DF' ? ['무실점', S.cs] : ['도움', S.assists]) as [string, number]);
  const comps = $derived(s.season.comps || []);
  const activeStories = $derived(Object.entries(s.story || {}).filter(([, v]) => !v.done));
  const t = $derived(turnNo(s));
  const picked = $derived(TRAININGS.find((x) => x.id === s.training));
  const invest = $derived(investDef(s));
  const report = $derived(appState.report && appState.report.year === s.year ? appState.report : null);
  // 리포트가 개막 후 첫 구간이면 시즌 누적 = 구간 기록이라 누적 칸을 숨긴다. 개막 전(0경기)에도 숨긴다.
  const showTotals = $derived(S.played > 0 && !(report?.block && S.played === report.games.length));
  const left = $derived(leagueOf(s.leagueId).matches - S.played);
  const btnLabel = $derived(phase === 0 ? '프리시즌 훈련 진행' : `훈련 후 ${phase >= LAST_PHASE ? left : Math.min(blockMatches(s), left)}경기 진행`);
  // 최근 소식: 리포트에 이미 나온 구간 기록은 빼고 5줄만, '더 보기'로 14줄까지.
  const FEED_SHORT = 5;
  const FEED_LONG = 14;
  let feedAll = $state(false);
  const feed = $derived.by(() => {
    const hide = report ? `${report.year} ${PHASES[report.ph]}` : null;
    return s.log.filter((l) => l.t !== hide).slice(0, FEED_LONG);
  });

  const pendingLabel = $derived(s.pending?.type === 'event' ? '⚡ 이벤트 확인' : '시즌 결산 보기');

  // T-11-024 결과 안내 스크롤: 중계 시트를 닫고 새 리포트가 뜨면, 리포트를 읽을 시간을 준 뒤 아래 카드들을 차례로
  // 화면 위쪽에 맞춰 부드럽게 내려가며 잠깐씩 강조하고, 맨 아래 버튼에서 멈춘다. 훈련·자기 투자 카드에서는 시간 대신
  // 사용자가 하나를 고를 때까지 기다렸다가(고른 카드가 톡 튄다) 넘어가고, 순위표에서는 내 팀 순위 변동을 움직여 보여 준다.
  // 기다리는 카드 밖의 단계에서 사용자가 손대면(휠·터치·클릭·키) 바로 그만둔다. 감속 모션·업무 모드에서는 돌지 않는다.
  type Gate = 'train' | 'invest';
  const TOUR: [string, number | Gate][] = [
    ['[data-report]', 2600],
    ['[data-prep]', 'train'],
    ['[data-invest-card]', 'invest'],
    ['[data-season-status]', 1600],
    ['[data-stories]', 1000],
    ['[data-feed]', 1000],
    ['.advance-go', 1400],
  ];
  const PICK_MS = 650;
  const RANK_DELAY = 500;
  const RANK_MS = 1000;
  let tourWait = $state<Gate | null>(null);
  let onPick: ((g: Gate, btn: HTMLElement) => void) | null = null;
  let table = $state<ReturnType<typeof LeagueTable>>();
  $effect(() => {
    const k = report?.key;
    if (!k || k === touredKey) return;
    touredKey = k;
    if (!dur(1)) return;
    return tour();
  });

  function tour(): () => void {
    const timers: number[] = [];
    const later = (fn: () => void, ms: number) => void timers.push(window.setTimeout(fn, ms));
    let lit: HTMLElement | null = null;
    const light = (el: HTMLElement | null) => {
      if (lit) delete lit.dataset.tourSpot;
      lit = el;
      if (el) el.dataset.tourSpot = '';
    };
    const evs = ['wheel', 'touchstart', 'pointerdown', 'keydown'] as const;
    // 고르기를 기다리는 동안에는 스크롤·탭으로 카드를 살펴볼 수 있어야 하니 멈추지 않는다.
    const onUser = () => void (tourWait || stop());
    const stop = () => {
      timers.forEach(clearTimeout);
      light(null);
      tourWait = null;
      onPick = null;
      for (const e of evs) removeEventListener(e, onUser, true);
    };
    for (const e of evs) addEventListener(e, onUser, { capture: true, passive: true });
    const steps = TOUR.map(([sel, wait]) => [document.querySelector<HTMLElement>(sel), wait] as const).filter(([el]) => el);
    const go = (i: number) => {
      if (i >= steps.length) return stop();
      const [el, wait] = steps[i]!;
      if (i) {
        const last = i === steps.length - 1;
        const head = document.querySelector<HTMLElement>('.topbar')?.offsetHeight ?? 0;
        const box = el!.getBoundingClientRect();
        let y = last ? document.documentElement.scrollHeight : box.top + scrollY - head - 12;
        // 고르기를 기다리는 카드가 화면보다 길면 선택지·설명이 있는 아래쪽이 보이게 바닥에 맞춘다.
        if (typeof wait !== 'number') {
          const foot = document.querySelector<HTMLElement>('.tabs')?.offsetHeight ?? 0;
          y = Math.max(y, box.bottom + scrollY - (innerHeight - foot - 12));
        }
        scrollTo({ top: Math.max(0, y), behavior: 'smooth' });
        if (last) el!.querySelector('button')?.focus({ preventScroll: true });
      }
      light(el);
      if (typeof wait !== 'number') {
        tourWait = wait;
        onPick = (g, btn) => {
          if (g !== wait) return;
          tourWait = null;
          onPick = null;
          btn.dataset.picked = '';
          later(() => {
            delete btn.dataset.picked;
            go(i + 1);
          }, PICK_MS);
        };
        return;
      }
      let ms = wait;
      if (el!.hasAttribute('data-season-status') && report && report.rank.before !== report.rank.after) {
        later(() => table?.playRank(report.rank.before), RANK_DELAY);
        ms += RANK_MS;
      }
      later(() => go(i + 1), ms);
    };
    go(0);
    return stop;
  }

  function onAdvance() {
    buzz();
    void advance();
  }

  function onPending() {
    buzz();
    nextPending();
  }

  function meterCls(v: number, badAt: number, warnAt: number): string {
    return v < badAt ? 'bad' : v < warnAt ? 'warn' : '';
  }

  function setTraining(id: string, btn: HTMLElement) {
    s.training = id;
    save();
    onPick?.('train', btn);
  }

  function setInvest(id: string, btn: HTMLElement) {
    s.invest = id;
    save();
    onPick?.('invest', btn);
  }

  function waitText(k: string): string {
    const c = (s.chains || []).find((x) => {
      const e = eventById(x.id);
      return e && e.story === k;
    });
    if (!c) return '';
    return c.at <= t ? '곧 이어짐' : `약 ${c.at - t}구간 후`;
  }
</script>

{#if report}
  {#key report.key}
    <PhaseReport r={report} />
  {/key}
{/if}

<!-- 훈련·자기 투자 카드 공통 내용. T-11-024 카드에는 무엇이 오르는지(첫 효과)와 눈여겨볼 한 가지(주력·비용 등)만 두고,
     컨디션 소모 같은 나머지 효과와 자세한 설명은 고른 카드의 설명 칸에서만 보여 준다. -->
{#snippet optBody(label: string, c: { effect: string[]; tag: string })}
  <b>{label}</b><small>{c.effect[0]}</small>{#if c.tag}<small class="train-tag">{c.tag}</small>{/if}
{/snippet}
{#snippet helpBody(title: string, c: { effect: string[] }, body: string)}
  <b>{title} <span class="muted">· {c.effect.join(' · ')}</span></b>
  <p>{body}</p>
{/snippet}

<section class="card stack" data-prep>
  <div><div class="eyebrow">Next · {label}</div><h2>다음 구간 준비</h2></div>
  <div class="meters">
    <div class="meter"><span>컨디션</span><div class="bar"><i class={meterCls(s.cond, 40, 65)} style="width:{Math.round(s.cond)}%"></i></div><span class="v">{Math.round(s.cond)}</span></div>
    <div class="meter"><span>사기</span><div class="bar"><i class={meterCls(s.morale, 40, 60)} style="width:{Math.round(s.morale)}%"></i></div><span class="v">{Math.round(s.morale)}</span></div>
    <div class="meter"><span>인기</span><div class="bar"><i class="acc" style="width:{Math.min(100, Math.round(s.fame))}%"></i></div><span class="v">{Math.round(s.fame)}</span></div>
  </div>
  <h3 class="sub-title">훈련 방향</h3>
  {#if tourWait === 'train'}<p class="tour-hint" aria-live="polite">이번 구간 훈련을 고르면 다음으로 넘어가요</p>{/if}
  <div class="train">
    {#each TRAININGS as tr (tr.id)}
      {@const c = trainingCard(s, tr)}
      <button class="opt" data-train={tr.id} aria-pressed={s.training === tr.id} onclick={(e) => setTraining(tr.id, e.currentTarget)}>
        {@render optBody(trainingLabel(s, tr), c)}
      </button>
    {/each}
  </div>
  {#if picked}
    <div class="train-help" data-train-help aria-live="polite">
      {@render helpBody(trainingLabel(s, picked), trainingCard(s, picked), trainingHelp(s, picked))}
    </div>
  {/if}
</section>

<section class="card stack" data-invest-card>
  <div class="row" style="justify-content:space-between">
    <div><div class="eyebrow">Invest</div><h2>자기 투자</h2></div>
    <span class="pill" data-invest-money>보유 {fmtMoney(s.money)}원</span>
  </div>
  {#if tourWait === 'invest'}<p class="tour-hint" aria-live="polite">투자를 고르면 넘어가요 · 아끼려면 투자 안 함</p>{/if}
  <div class="train">
    {#each INVESTS as d (d.id)}
      {@const c = investCard(s, d)}
      <button class="opt" data-invest={d.id} aria-pressed={invest.id === d.id} disabled={!c.affordable} onclick={(e) => setInvest(d.id, e.currentTarget)}>
        {@render optBody(d.label, c)}
      </button>
    {/each}
  </div>
  <div class="train-help" data-invest-help aria-live="polite">
    {@render helpBody(invest.label, investCard(s, invest), investHelp(s, invest))}
  </div>
</section>

<section class="card stack" data-season-status>
  <div>
    <div class="eyebrow">{seasonLabel(s)} Season</div>
    <h2>{label}</h2>
    <div class="track">
      {#each [0, 1, 2] as i (i)}
        <div class={i < phase ? 'done' : i === phase ? 'now' : ''}></div>
      {/each}
    </div>
    <div class="track-lbl">
      {#each ['프리시즌', '전반기', '후반기'] as tl (tl)}
        <span>{tl}</span>
      {/each}
    </div>
  </div>
  {#if showTotals}
    <p class="muted fs-sm" data-season-totals>시즌 누적 · {S.w}승 {S.d}무 {S.l}패 · 출전 {S.apps} · {S.goals}골 · {lastCol[0]} {lastCol[1]} · 평점 {avg}</p>
  {/if}
  <LeagueTable {s} bind:this={table} />
  {#if comps.length}
    <div>
      <h3 class="sub-title" style="margin-bottom:2px">이번 시즌 대회</h3>
      {#each comps as c (c.name)}
        <div class="story-row">
          <b>{c.name}</b>
          <span class="muted">{c.stage || (c.type === 'super' ? '개막 전 단판' : '1구간 시작')}{c.alive && c.stage ? ' · 진행 중' : ''}</span>
          <span class="muted">{c.apps}경기 {c.g}골</span>
        </div>
      {/each}
    </div>
  {/if}
</section>

{#if activeStories.length}
  <section class="card" data-stories>
    <div class="eyebrow">Storylines</div>
    <h2 style="margin-bottom:6px">진행 중인 스토리</h2>
    {#each activeStories as [k, v] (k)}
      <div class="story-row">
        <b>{STORIES[k]!.name}</b>
        <span class="dots">
          {#each Array.from({ length: STORIES[k]!.total }) as _, i (i)}
            <i class={i < v.stage ? 'on' : ''}></i>
          {/each}
        </span>
        <span class="muted">{waitText(k)}</span>
      </div>
    {/each}
  </section>
{/if}

{#if feed.length}
  <section class="card" data-feed>
    <div class="eyebrow">Timeline</div>
    <h2 style="margin-bottom:6px">최근 소식</h2>
    <div class="feed">
      {#each feedAll ? feed : feed.slice(0, FEED_SHORT) as l, i (i)}
        <div><time>{l.t}</time><span class={l.kind}>{l.text}</span></div>
      {/each}
    </div>
    {#if feed.length > FEED_SHORT}
      <button class="icon-btn" style="margin-top:8px" data-act="feed-more" aria-expanded={feedAll} onclick={() => (feedAll = !feedAll)}>{feedAll ? '접기' : '더 보기'}</button>
    {/if}
  </section>
{/if}

<div class="advance-go">
  {#if s.pending}
    <button class="btn btn-block btn-accent" data-act="resume" onclick={onPending}>{pendingLabel} →</button>
  {:else}
    <p class="muted fs-sm">훈련 <b>{picked ? trainingLabel(s, picked) : '-'}</b> · 자기 투자 <b>{invest.label}</b></p>
    <button class="btn btn-block btn-primary" data-act="advance" onclick={onAdvance}>{btnLabel} →</button>
  {/if}
</div>

// apps/mobile/src/screens/game/SeasonTab.tsx
// 시즌 탭(웹 tabs/SeasonTab.svelte, T-11-025): 구간 리포트 → 다음 구간 준비(컨디션·훈련·자기 투자) → 시즌 현황(진행 막대·
// 누적 기록·순위표·대회) → 스토리 → 최근 소식 → 버튼. 버튼은 고정 바 없이 탭 맨 아래 한 자리에 둔다 — 이벤트·시즌 결산이
// 대기 중이면 그걸 열고, 아니면 구간을 진행한다. 리포트와 겹치는 숫자·소식은 다시 그리지 않는다.
// 새 리포트가 뜨면 아래 카드들을 차례로 비추며 내려가는 결과 안내가 돈다(useResultTour).
import { useEffect, useMemo, useRef, useState, type ReactNode } from 'react';
import { Animated, View } from 'react-native';
import { useSafeAreaInsets } from 'react-native-safe-area-context';
import { useSnapshot } from 'valtio';
import { PHASES, LAST_PHASE } from '@offside/game/data';
import {
  roundRange,
  leagueOf,
  blockMatches,
  logLabel,
  TRAININGS,
  trainingLabel,
  trainingCard,
  trainingHelp,
  INVESTS,
  investCard,
  investHelp,
  investDef,
  fmtMoney,
  STORIES,
  turnNo,
} from '@offside/game/engine';
import { eventById } from '@offside/game/events-data';
import type { GameState } from '@offside/game/types';
import { seasonLabel } from '@offside/app-core/career';
import {
  RESULT_TOUR,
  TOUR_PICK_MS,
  TOUR_RANK_DELAY,
  TOUR_RANK_MS,
  type TourGate,
  type TourSpot,
} from '@offside/app-core/resultTour';
import type { PhaseReport as PhaseReportData } from '@offside/app-core/sheets';
import { advance, buzz, nextPending, save } from '../../game/host';
import { useTween } from '../../sheets/useTween';
import { appState, prefs } from '../../store';
import { alpha } from '../../theme/colors';
import { useColors } from '../../theme/useColors';
import { DISPLAY, rem } from '../../theme/type';
import { Card } from '../../ui/Card';
import { Opt, Pill } from '../../ui/bits';
import { Btn } from '../../ui/Btn';
import { scrollTo, scrollToEnd, scrollY, viewH } from '../../ui/scroll';
import { Txt } from '../../ui/Txt';
import { LeagueTable, SubTitle, type RankPlay } from './LeagueTable';
import { PhaseReport } from './PhaseReport';

function meterTone(v: number, badAt: number, warnAt: number): 'bad' | 'warn' | 'good' {
  return v < badAt ? 'bad' : v < warnAt ? 'warn' : 'good';
}

/** 컨디션·사기·인기 막대(웹 .meter: 이름 54 · 막대 · 값 34). 값이 바뀌면 막대가 0.4초 동안 따라간다. */
function Meter({
  label,
  value,
  tone,
}: {
  label: string;
  value: number;
  tone: 'good' | 'warn' | 'bad' | 'acc';
}) {
  const c = useColors();
  const pct = Math.min(100, Math.round(value));
  const [w] = useTween([pct], 400);
  const fill = tone === 'acc' ? c.accent : c[tone];
  return (
    <View
      accessible
      accessibilityLabel={`${label} ${Math.round(value)}`}
      style={{ flexDirection: 'row', alignItems: 'center', gap: 10 }}
    >
      <Txt style={{ width: 54, fontSize: rem(0.8125) }}>{label}</Txt>
      <View
        style={{
          flex: 1,
          height: 8,
          backgroundColor: c.surface2,
          borderRadius: 4,
          overflow: 'hidden',
          borderWidth: 1,
          borderColor: c.line,
        }}
      >
        <View style={{ width: `${w}%`, height: '100%', borderRadius: 4, backgroundColor: fill }} />
      </View>
      <Txt style={{ width: 34, textAlign: 'right', fontFamily: DISPLAY[600], fontSize: rem(1) }}>
        {Math.round(value)}
      </Txt>
    </View>
  );
}

/** 이름 · (점/문구) · (문구) 한 줄(웹 .story-row: 위에 구분선). */
function StoryRow({ children }: { children: ReactNode }) {
  const c = useColors();
  return (
    <View
      style={{
        flexDirection: 'row',
        alignItems: 'center',
        gap: 12,
        paddingVertical: 9,
        borderTopWidth: 1,
        borderTopColor: c.line,
      }}
    >
      {children}
    </View>
  );
}
const RowMuted = ({ children }: { children: ReactNode }) => (
  <Txt
    tone="muted"
    style={{ fontSize: rem(0.75), minWidth: 64, textAlign: 'right', flexShrink: 1 }}
  >
    {children}
  </Txt>
);

// T-11-025 결과 안내(웹 SeasonTab tour): 중계 시트를 닫고 새 리포트가 뜨면, 리포트를 읽을 시간을 준 뒤 아래 카드들을
// 차례로 화면 위쪽에 맞춰 부드럽게 내려가며 잠깐씩 테두리를 두르고, 맨 아래 버튼에서 멈춘다. 훈련·자기 투자 카드에서는
// 사용자가 하나를 고를 때까지 기다렸다가(고른 카드가 톡 튄다) 넘어가고, 시즌 현황에서는 순위표의 내 팀 순위 변동을
// 움직여 보여 준다. 기다리는 카드 밖의 단계에서 화면을 만지면 바로 그만둔다. 동작 줄이기면 돌지 않는다.
/** 안내를 이미 돈 리포트 — 탭을 오가며 다시 마운트돼도 한 리포트에 한 번만. */
let touredKey = 0;

interface Tour {
  /** 화면을 만졌다(고르기를 기다리는 중이 아니면 그만둔다). */
  touch: () => void;
  pick: (g: TourGate) => void;
}

function useResultTour(report: PhaseReportData | null) {
  const { motionOK } = useSnapshot(prefs);
  const insets = useSafeAreaInsets();
  const views = useRef<Partial<Record<TourSpot, View | null>>>({});
  const tour = useRef<Tour | null>(null);
  const [spot, setSpot] = useState<TourSpot | null>(null);
  const [wait, setWait] = useState<TourGate | null>(null);
  const [rankPlay, setRankPlay] = useState<RankPlay | null>(null);

  useEffect(() => {
    const k = report?.key;
    if (!report || !k || k === touredKey) return;
    touredKey = k;
    if (!motionOK) return;
    const timers: ReturnType<typeof setTimeout>[] = [];
    const later = (fn: () => void, ms: number) => void timers.push(setTimeout(fn, ms));
    let waiting: TourGate | null = null;
    let alive = true;
    const stop = () => {
      alive = false;
      timers.forEach(clearTimeout);
      waiting = null;
      tour.current = null;
      setSpot(null);
      setWait(null);
    };
    const steps = RESULT_TOUR.filter(([k]) => views.current[k]);
    const go = (i: number) => {
      if (i >= steps.length) return stop();
      const [k, w] = steps[i]!;
      const gate = typeof w !== 'number';
      if (k === 'go') scrollToEnd(true);
      else if (i)
        views.current[k]?.measureInWindow((_x, y, _w, h) => {
          if (!alive) return;
          let to = scrollY() + y - insets.top - 12;
          // 고르기를 기다리는 카드가 화면보다 길면 선택지·설명이 있는 아래쪽이 보이게 바닥에 맞춘다.
          if (gate) to = Math.max(to, scrollY() + y + h - (viewH() - 12));
          scrollTo(Math.max(0, to), true);
        });
      setSpot(k);
      if (gate) {
        waiting = w;
        setWait(w);
        return;
      }
      let ms = w;
      const { before, after } = report.rank;
      if (k === 'status' && before != null && before !== after) {
        later(() => setRankPlay({ before, key: report.key }), TOUR_RANK_DELAY);
        ms += TOUR_RANK_MS;
      }
      later(() => go(i + 1), ms);
    };
    tour.current = {
      touch: () => void (waiting || stop()),
      pick: (g) => {
        if (g !== waiting) return;
        waiting = null;
        setWait(null);
        const i = steps.findIndex(([k]) => k === (g === 'train' ? 'prep' : 'invest'));
        later(() => go(i + 1), TOUR_PICK_MS);
      },
    };
    go(0);
    return stop;
    // 새 리포트(key)마다 한 번만 돈다.
  }, [report?.key]);

  /** Spotlight에 넘길 등록 함수 — 안내가 스크롤해 갈 카드 자리를 재 둔다. */
  const reg = (id: TourSpot) => (v: View | null) => void (views.current[id] = v);
  return { spot, wait, rankPlay, tour, reg };
}

/** 안내가 비추는 카드 감싸개 — 자리를 등록하고, 지금 비추는 카드면 바깥에 강조 테두리를 두른다(웹 [data-tour-spot]). */
function Spotlight({
  reg,
  on,
  children,
}: {
  reg: (v: View | null) => void;
  on: boolean;
  children: ReactNode;
}) {
  const c = useColors();
  return (
    <View
      ref={reg}
      collapsable={false}
      style={{
        margin: -5,
        padding: 3,
        borderWidth: 2,
        borderRadius: 21,
        borderColor: on ? c.accent : 'transparent',
      }}
    >
      {children}
    </View>
  );
}

/** 고르기를 기다리는 카드의 안내 줄(웹 .tour-hint). */
function TourHint({ children }: { children: string }) {
  const c = useColors();
  return (
    <View
      accessibilityLiveRegion="polite"
      style={{
        paddingVertical: 6,
        paddingHorizontal: 10,
        borderRadius: 10,
        backgroundColor: alpha(c.accent, 0.14),
      }}
    >
      <Txt style={{ fontSize: rem(0.8125), fontWeight: '700', color: c.accentText }}>
        {children}
      </Txt>
    </View>
  );
}

/** 고른 선택지가 톡 튄다(웹 .opt[data-picked] — 0.96배로 눌렸다가 1.03배로 튀고 제자리로). */
function PickPop({ on, children }: { on: boolean; children: ReactNode }) {
  const v = useRef(new Animated.Value(1)).current;
  useEffect(() => {
    if (!on) return;
    const a = Animated.sequence([
      Animated.timing(v, { toValue: 0.96, duration: 180, useNativeDriver: true }),
      Animated.timing(v, { toValue: 1.03, duration: 180, useNativeDriver: true }),
      Animated.timing(v, { toValue: 1, duration: 240, useNativeDriver: true }),
    ]);
    a.start();
    return () => a.stop();
  }, [on, v]);
  return <Animated.View style={{ flex: 1, transform: [{ scale: v }] }}>{children}</Animated.View>;
}

interface Choice {
  id: string;
  label: string;
  effect: string[];
  tag: string;
  selected: boolean;
  disabled?: boolean;
  onPress: () => void;
}

/** 훈련·자기 투자 선택지(웹 .train grid 3열) — 3개씩 끊어 줄로 그리고, 모자란 칸은 빈 칸으로 폭을 맞춘다.
 * T-11-025 카드에는 무엇이 오르는지(첫 효과)와 눈여겨볼 한 가지(주력·비용 등)만 두고, 나머지 효과는 고른 카드의 설명 칸에서. */
function ChoiceGrid({
  testPrefix,
  items,
  popped,
}: {
  testPrefix: string;
  items: Choice[];
  /** 방금 고른 선택지(안내가 고르기를 기다리던 중에 고른 것만) — 톡 튀는 효과를 준다. */
  popped?: string | null;
}) {
  const c = useColors();
  const rows: Choice[][] = [];
  for (let i = 0; i < items.length; i += 3) rows.push(items.slice(i, i + 3));
  return (
    <View style={{ gap: 8 }}>
      {rows.map((row, ri) => (
        <View key={ri} style={{ flexDirection: 'row', gap: 8 }}>
          {row.map((it) => (
            <View key={it.id} testID={`${testPrefix}-${it.id}`} style={{ flex: 1 }}>
              <PickPop on={popped === it.id}>
                <Opt
                  selected={it.selected}
                  disabled={it.disabled}
                  onPress={it.onPress}
                  style={{
                    flex: 1,
                    paddingVertical: it.selected ? 7.5 : 9,
                    paddingHorizontal: it.selected ? 8.5 : 10,
                  }}
                >
                  <Txt style={{ fontSize: rem(0.875), fontWeight: '700' }}>{it.label}</Txt>
                  <Txt tone="muted" style={{ fontSize: rem(0.75), lineHeight: rem(0.75) * 1.35 }}>
                    {it.effect[0]}
                  </Txt>
                  {it.tag ? (
                    <Txt
                      style={{
                        fontSize: rem(0.75),
                        lineHeight: rem(0.75) * 1.35,
                        fontWeight: '600',
                        color: c.accentText,
                      }}
                    >
                      {it.tag}
                    </Txt>
                  ) : null}
                </Opt>
              </PickPop>
            </View>
          ))}
          {Array.from({ length: 3 - row.length }).map((_, i) => (
            <View key={`pad-${i}`} style={{ flex: 1 }} />
          ))}
        </View>
      ))}
    </View>
  );
}

/** 고른 선택지의 자세한 설명(웹 .train-help) — 제목 옆에 효과 전체를 붙인다. */
function HelpBox({
  testID,
  title,
  effect,
  body,
}: {
  testID: string;
  title: string;
  effect: string[];
  body: string;
}) {
  const c = useColors();
  return (
    <View
      testID={testID}
      accessibilityLiveRegion="polite"
      style={{
        gap: 4,
        paddingVertical: 10,
        paddingHorizontal: 12,
        borderRadius: 10,
        backgroundColor: c.surface2,
      }}
    >
      <Txt style={{ fontSize: rem(0.8125), lineHeight: rem(0.8125) * 1.5, fontWeight: '700' }}>
        {title}
        <Txt tone="muted" style={{ fontSize: rem(0.8125), fontWeight: '700' }}>
          {` · ${effect.join(' · ')}`}
        </Txt>
      </Txt>
      <Txt style={{ fontSize: rem(0.8125), lineHeight: rem(0.8125) * 1.5 }}>{body}</Txt>
    </View>
  );
}

const FEED_SHORT = 5;
const FEED_LONG = 14;

export function SeasonTab({ s }: { s: GameState }) {
  const c = useColors();
  const { report: rep } = useSnapshot(appState);
  const report = rep && rep.year === s.year ? (rep as PhaseReportData) : null;
  const [feedAll, setFeedAll] = useState(false);
  const S = s.season;
  const avg = S.apps ? (S.ratingSum / S.apps).toFixed(2) : '-';
  const phase = Math.min(s.phase, LAST_PHASE);
  const label = phase === 0 ? '프리시즌' : `${PHASES[phase]} · ${roundRange(s, phase)}`;
  const back = s.pos === 'GK' || s.pos === 'DF';
  const lastCol = (back ? ['무실점', S.cs] : ['도움', S.assists]) as [string, number];
  const comps = s.season.comps || [];
  const activeStories = Object.entries(s.story || {}).filter(([, v]) => !v.done);
  const t = turnNo(s);
  const picked = TRAININGS.find((x) => x.id === s.training);
  const invest = investDef(s);
  // 리포트가 개막 후 첫 구간이면 시즌 누적 = 구간 기록이라 누적 칸을 숨긴다. 개막 전(0경기)에도 숨긴다.
  const showTotals = S.played > 0 && !(report?.block && S.played === report.games.length);
  const left = leagueOf(s.leagueId).matches - S.played;
  const btnLabel =
    phase === 0
      ? '프리시즌 훈련 진행'
      : `훈련 후 ${phase >= LAST_PHASE ? left : Math.min(blockMatches(s), left)}경기 진행`;
  // 최근 소식: 리포트에 이미 나온 구간 기록은 빼고 5줄만, '더 보기'로 14줄까지.
  const hide = report ? logLabel(report.year, report.ph) : null;
  const feed = s.log.filter((l) => l.t !== hide).slice(0, FEED_LONG);
  // 안내가 단계마다 탭을 다시 그리므로 선택지 카드 계산은 게임 상태가 바뀔 때만 한다(설명 칸도 같은 값을 쓴다).
  const trainCards = useMemo(
    () => new Map(TRAININGS.map((tr) => [tr.id, trainingCard(s, tr)])),
    [s],
  );
  const investCards = useMemo(() => new Map(INVESTS.map((d) => [d.id, investCard(s, d)])), [s]);
  const { spot, wait, rankPlay, tour, reg } = useResultTour(report);
  const [popped, setPopped] = useState<{ g: TourGate; id: string } | null>(null);

  function pick(g: TourGate, id: string) {
    if (wait === g) {
      setPopped({ g, id });
      setTimeout(() => setPopped(null), TOUR_PICK_MS);
    }
    tour.current?.pick(g);
  }

  function setTraining(id: string) {
    appState.G!.training = id;
    save();
    pick('train', id);
  }

  function setInvest(id: string) {
    appState.G!.invest = id;
    save();
    pick('invest', id);
  }

  const pendingLabel = s.pending?.type === 'event' ? '⚡ 이벤트 확인' : '시즌 결산 보기';

  function onAdvance() {
    buzz();
    void advance();
  }

  function onPending() {
    buzz();
    nextPending();
  }

  function waitText(k: string): string {
    const ch = (s.chains || []).find((x) => {
      const e = eventById(x.id);
      return e && e.story === k;
    });
    if (!ch) return '';
    return ch.at <= t ? '곧 이어짐' : `약 ${ch.at - t}구간 후`;
  }

  return (
    <View style={{ gap: 14 }} onTouchStart={() => tour.current?.touch()}>
      {report ? (
        <Spotlight reg={reg('report')} on={spot === 'report'}>
          <PhaseReport key={report.key} r={report} />
        </Spotlight>
      ) : null}

      <Spotlight reg={reg('prep')} on={spot === 'prep'}>
        <Card gap={10}>
          <View>
            <Txt v="eyebrow">{`Next · ${label}`}</Txt>
            <Txt v="h2" accessibilityRole="header">
              다음 구간 준비
            </Txt>
          </View>
          <View style={{ gap: 9 }}>
            <Meter label="컨디션" value={s.cond} tone={meterTone(s.cond, 40, 65)} />
            <Meter label="사기" value={s.morale} tone={meterTone(s.morale, 40, 60)} />
            <Meter label="인기" value={s.fame} tone="acc" />
          </View>
          <SubTitle>훈련 방향</SubTitle>
          {wait === 'train' ? <TourHint>이번 구간 훈련을 고르면 다음으로 넘어가요</TourHint> : null}
          <ChoiceGrid
            testPrefix="train"
            popped={popped?.g === 'train' ? popped.id : null}
            items={TRAININGS.map((tr) => {
              const cd = trainCards.get(tr.id)!;
              return {
                id: tr.id,
                label: trainingLabel(s, tr),
                effect: cd.effect,
                tag: cd.tag,
                selected: s.training === tr.id,
                onPress: () => setTraining(tr.id),
              };
            })}
          />
          {picked ? (
            <HelpBox
              testID="train-help"
              title={trainingLabel(s, picked)}
              effect={trainCards.get(picked.id)!.effect}
              body={trainingHelp(s, picked)}
            />
          ) : null}
        </Card>
      </Spotlight>

      <Spotlight reg={reg('invest')} on={spot === 'invest'}>
        <Card gap={10}>
          <View
            style={{
              flexDirection: 'row',
              justifyContent: 'space-between',
              alignItems: 'center',
              gap: 10,
            }}
          >
            <View style={{ flex: 1 }}>
              <Txt v="eyebrow">Invest</Txt>
              <Txt v="h2" accessibilityRole="header">
                자기 투자
              </Txt>
            </View>
            <Pill>{`보유 ${fmtMoney(s.money)}원`}</Pill>
          </View>
          {wait === 'invest' ? (
            <TourHint>투자를 고르면 넘어가요 · 아끼려면 투자 안 함</TourHint>
          ) : null}
          <ChoiceGrid
            testPrefix="invest"
            popped={popped?.g === 'invest' ? popped.id : null}
            items={INVESTS.map((d) => {
              const cd = investCards.get(d.id)!;
              return {
                id: d.id,
                label: d.label,
                effect: cd.effect,
                tag: cd.tag,
                selected: invest.id === d.id,
                disabled: !cd.affordable,
                onPress: () => setInvest(d.id),
              };
            })}
          />
          <HelpBox
            testID="invest-help"
            title={invest.label}
            effect={investCards.get(invest.id)!.effect}
            body={investHelp(s, invest)}
          />
        </Card>
      </Spotlight>

      <Spotlight reg={reg('status')} on={spot === 'status'}>
        <Card gap={14}>
          <View>
            <Txt v="eyebrow">{`${seasonLabel(s)} Season`}</Txt>
            <Txt v="h2" accessibilityRole="header">
              {label}
            </Txt>
            <View style={{ flexDirection: 'row', gap: 4, marginTop: 10 }}>
              {[0, 1, 2].map((i) => (
                <View
                  key={i}
                  style={{
                    flex: 1,
                    height: 6,
                    borderRadius: 3,
                    backgroundColor: i < phase ? c.pitch2 : i === phase ? c.accent : c.line,
                  }}
                />
              ))}
            </View>
            <View style={{ flexDirection: 'row', gap: 4, marginTop: 4 }}>
              {['프리시즌', '전반기', '후반기'].map((tl) => (
                <Txt key={tl} tone="muted" center style={{ flex: 1, fontSize: rem(0.6875) }}>
                  {tl}
                </Txt>
              ))}
            </View>
          </View>
          {showTotals ? (
            <Txt testID="season-totals" tone="muted" style={{ fontSize: rem(0.8125) }}>
              {`시즌 누적 · ${S.w}승 ${S.d}무 ${S.l}패 · 출전 ${S.apps} · ${S.goals}골 · ${lastCol[0]} ${lastCol[1]} · 평점 ${avg}`}
            </Txt>
          ) : null}
          <LeagueTable s={s} play={rankPlay} />
          {comps.length ? (
            <View>
              <SubTitle>이번 시즌 대회</SubTitle>
              {comps.map((cp) => (
                <StoryRow key={cp.name}>
                  <Txt style={{ flex: 1, fontSize: rem(0.875), fontWeight: '700' }}>{cp.name}</Txt>
                  <RowMuted>
                    {`${cp.stage || (cp.type === 'super' ? '개막 전 단판' : '1구간 시작')}${cp.alive && cp.stage ? ' · 진행 중' : ''}`}
                  </RowMuted>
                  <RowMuted>{`${cp.apps}경기 ${cp.g}골`}</RowMuted>
                </StoryRow>
              ))}
            </View>
          ) : null}
        </Card>
      </Spotlight>

      {activeStories.length ? (
        <Spotlight reg={reg('stories')} on={spot === 'stories'}>
          <Card gap={0}>
            <Txt v="eyebrow">Storylines</Txt>
            <Txt v="h2" accessibilityRole="header" style={{ marginBottom: 6 }}>
              진행 중인 스토리
            </Txt>
            {activeStories.map(([k, v]) => (
              <StoryRow key={k}>
                <Txt style={{ flex: 1, fontSize: rem(0.875), fontWeight: '700' }}>
                  {STORIES[k]!.name}
                </Txt>
                <View style={{ flexDirection: 'row', gap: 4 }}>
                  {Array.from({ length: STORIES[k]!.total }).map((_, i) => (
                    <View
                      key={i}
                      style={{
                        width: 18,
                        height: 6,
                        borderRadius: 3,
                        backgroundColor: i < v.stage ? c.accent : c.line,
                      }}
                    />
                  ))}
                </View>
                <RowMuted>{waitText(k)}</RowMuted>
              </StoryRow>
            ))}
          </Card>
        </Spotlight>
      ) : null}

      {feed.length ? (
        <Spotlight reg={reg('feed')} on={spot === 'feed'}>
          <Card gap={0}>
            <Txt v="eyebrow">Timeline</Txt>
            <Txt v="h2" accessibilityRole="header" style={{ marginBottom: 6 }}>
              최근 소식
            </Txt>
            <View>
              {(feedAll ? feed : feed.slice(0, FEED_SHORT)).map((l, i) => (
                <View
                  key={i}
                  style={{
                    flexDirection: 'row',
                    gap: 8,
                    paddingVertical: 8,
                    borderTopWidth: i ? 1 : 0,
                    borderTopColor: c.line,
                  }}
                >
                  <Txt
                    tone="muted"
                    style={{
                      width: 76,
                      fontFamily: DISPLAY[400],
                      fontSize: rem(0.75),
                      letterSpacing: rem(0.75) * 0.03,
                    }}
                  >
                    {l.t}
                  </Txt>
                  <Txt
                    style={{
                      flex: 1,
                      fontSize: rem(0.8125),
                      lineHeight: rem(0.8125) * 1.5,
                      fontWeight: l.kind === 'big' ? '600' : '400',
                      color: l.kind === 'good' ? c.good : l.kind === 'bad' ? c.bad : c.ink,
                    }}
                  >
                    {l.text}
                  </Txt>
                </View>
              ))}
            </View>
            {feed.length > FEED_SHORT ? (
              <Btn
                sm
                testID="feed-more"
                accessibilityLabel={feedAll ? '최근 소식 접기' : '최근 소식 더 보기'}
                onPress={() => setFeedAll(!feedAll)}
                style={{ alignSelf: 'flex-start', marginTop: 8 }}
              >
                {feedAll ? '접기' : '더 보기'}
              </Btn>
            ) : null}
          </Card>
        </Spotlight>
      ) : null}
      <Spotlight reg={reg('go')} on={spot === 'go'}>
        <View style={{ gap: 8 }}>
          {s.pending ? (
            <Btn block kind="accent" testID="resume" onPress={onPending}>
              {`${pendingLabel} →`}
            </Btn>
          ) : (
            <>
              <Txt tone="muted" center style={{ fontSize: rem(0.8125) }}>
                {'훈련 '}
                <Txt style={{ fontSize: rem(0.8125), fontWeight: '700' }}>
                  {picked ? trainingLabel(s, picked) : '-'}
                </Txt>
                {' · 자기 투자 '}
                <Txt style={{ fontSize: rem(0.8125), fontWeight: '700' }}>{invest.label}</Txt>
              </Txt>
              <Btn block kind="primary" testID="advance" onPress={onAdvance}>
                {`${btnLabel} →`}
              </Btn>
            </>
          )}
        </View>
      </Spotlight>
    </View>
  );
}
