// apps/web/src/ui/sheets/Chips.svelte
<script lang="ts">
  import { fmtMoney } from '@offside/game/engine';
  import type { Chip } from '../sheetState.svelte.js';

  // split(T-11-200 구간 리포트): 오른 것과 내린 것을 한 줄씩 나눠 그린다.
  let { chips, pop = false, split = false }: { chips: Chip[]; pop?: boolean; split?: boolean } = $props();
  const val = (c: Chip) => c.text || (c.money ? (c.d > 0 ? '+' : '') + fmtMoney(c.d) : (c.d > 0 ? '+' : '') + c.d);
  const down = (c: Chip) => c.bad || c.d < 0;
  const rows = $derived(split ? [chips.filter((c) => !down(c)), chips.filter(down)].filter((r) => r.length) : [chips]);
</script>

{#if chips.length}
  {#each rows as row, ri (ri)}
    <div class="chips">
      {#each row as c, i (i)}
        <span class="chip {down(c) ? 'down' : 'up'}" class:pop style="--d:{(ri ? rows[0]!.length : 0) * 70 + i * 70}ms">{c.label} {val(c)}</span>
      {/each}
    </div>
  {/each}
{/if}

// apps/mobile/src/sheets/Chips.tsx
// 능력치·자금 변화 칩 줄(웹 sheets/Chips.svelte). split이면 오른 것·내린 것을 두 줄로. pop이면 칩마다 70ms 간격으로 튀어 오른다(delay: 구간 리포트가 늦춰 준다).
import { View } from 'react-native';
import { fmtMoney } from '@offside/game/engine';
import type { Chip as ChipData } from '@offside/app-core/sheets';
import { Chip } from '../ui/bits';
import { Pop } from './anim';

const val = (c: ChipData) =>
  c.text || (c.money ? (c.d > 0 ? '+' : '') + fmtMoney(c.d) : (c.d > 0 ? '+' : '') + c.d);

export function Chips({
  chips,
  pop = false,
  delay = 0,
  split = false,
}: {
  chips: readonly ChipData[];
  pop?: boolean;
  delay?: number;
  /** T-11-200 구간 리포트: 오른 것과 내린 것을 한 줄씩 나눠 그린다. */
  split?: boolean;
}) {
  if (!chips.length) return null;
  const down = (c: ChipData) => c.bad || c.d < 0;
  const rows = split
    ? [chips.filter((c) => !down(c)), chips.filter(down)].filter((r) => r.length)
    : [chips];
  return (
    <View style={{ gap: 6 }}>
      {rows.map((row, ri) => (
        <View key={ri} style={{ flexDirection: 'row', flexWrap: 'wrap', gap: 6 }}>
          {row.map((c, i) => {
            const chip = <Chip text={`${c.label} ${val(c)}`} dir={down(c) ? 'down' : 'up'} />;
            const at = (ri ? rows[0]!.length : 0) + i;
            return pop ? (
              <Pop key={i} delay={delay + at * 70}>
                {chip}
              </Pop>
            ) : (
              <View key={i}>{chip}</View>
            );
          })}
        </View>
      ))}
    </View>
  );
}
